### ISSUE TITLE
Upgrade guide?

### ISSUE THREAD

**Issue by plweil** [vuelidate/vuelidate#1000]
**Is your feature request related to a problem? Please describe.**
I'm migrating a project from Vue 2 (using Vuelidate 1x) to Vue 3. Perhaps I missing it, but I don't see a clear upgrade guide for moving from Vuelidate 1 to 2. Let's say that I stick with the Options API for the time being. Will my Vuelidate 1 code just "work", or do I have to make changes?

**Describe the solution you'd like**
A  brief list of any breaking changes (if any), steps to take to upgrade to Vuelidate 2.

**Comment by dobromir-hristov** [comment]
Hey there, sorry for the late reply.

Most of what you have in vuelidate 0.x will work in 2.x. There are small exceptions like using $each, or the mixin.

You can still use the options API, you just need a one line of setup.

I will see to write a guide, when I have time.

**Comment by dargmuesli** [comment]
Here it is: https://vuelidate-next.netlify.app/migration_guide.html
I think this issue can be closed.
