### ISSUE TITLE
[HELP NEEDED] Unable to use via CDN

### ISSUE THREAD

**Issue by angelhdzmultimedia** [vuelidate/vuelidate#1001]
### Make sure that you are familiar with documentation before submitting an issue.

  https://vuelidate-next.netlify.com/

**Describe the bug**
I'm trying Vuelidate on CDN. validators 0.7.7 via CDN works, but no Vuelidate Core.
I get `'CollectFlag' before initialization vuelidate` error when calling useVuelidate() inside setup.

So I upgraded both to latest version available:

2.0.0-alpha.26 https://www.jsdelivr.com/package/npm/@vuelidate/validators
2.0.0-alpha.34 https://www.jsdelivr.com/package/npm/@vuelidate/core

Now  there's no window.validators or window.useVuelidate.

Any light will be appreciated.

**Reproduction URL**
https://codepen.io/angelhdzmultimedia/pen/abVNBee

**To Reproduce**

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dobromir-hristov** [comment]
It does not support cdn use yet. I will try to get something going this weekend

**Comment by jebaexpert** [comment]
can you please let me know if the CDN version is available now

**Comment by angelhdzmultimedia** [comment]
Thanks for replying.

I don't know what happened to my reproduction URL https://codepen.io/angelhdzmultimedia/pen/abVNBee
but it's missing all Vuelidate implementation.

Can you please provide me the links and the imports? Thanks!

**Comment by jebaexpert** [comment]
It will be very helpful if we get iife export for vuelidate core and validators.

https://stackoverflow.com/questions/70633687/vuelidate-in-vue-property-v-was-accessed-during-render-but-is-not-defined-on

**Comment by dobromir-hristov** [comment]
Just added support for this. Very sorry about all the delays. I am adding some basic docs for users, going to give it a test and will release today.
