### ISSUE TITLE
Validating Collections - Adding/Removing Child Instances Breaks Vuelidate

### ISSUE THREAD

**Issue by shasderias** [vuelidate/vuelidate#1009]
**Describe the bug**
When using the nested validation technique described here:

https://vuelidate-next.netlify.app/advanced_usage.html#nested-validations

After calling $validate on the parent Vuelidate instance, removing or adding Vuelidate instances in child components breaks Vuelidate.

**Reproduction URL**
https://codesandbox.io/s/sad-nobel-nlgbhs?file=/src/components/Comp.vue

(if you see a "cannot use import" error, click the refresh button in the embedded browser window)

**To Reproduce**
1. Click "Add" twice
2. Click "Validate"
3. Clear textbox 1
4. Vuelidate works fine here. If either textbox 0 or 1 are blank, Vuelidate complains about the failing validation. Fixing the validation error causes the failing validation to pass.
5. Click "Add"
6. Clear textbox 2
7. Note that parent Vuelidate instance breaks here for textbox 2. Validation errors in the component holding textbox 2 are not propagated up to the parent.

Removing an item from the collection can also break Vuelidate:
1. Click "Add" thrice
2. Clear textbox 1
3. Click "Validate"
4. Delete textbox 1
5. Note that parent Vuelidate instance still reports a "ghost" validation error.

**Comment by shasderias** [comment]
After some poking around Vuelidate's source code, assigning each child component a random ID and using that as the key in v-for results in the "right" component being unmounted allowing this line at index.js:109 to do its work:

```
onBeforeUnmount(() => removeValidationResultsFromParent.forEach((f) => f($registerAs)))
```

**Comment by dobromir-hristov** [comment]
Hello, i will try to look into it this weekend.

Thanks allot

**Comment by shasderias** [comment]
I think the problem here is:
- $validate() only calls $touch() if the dirty flag is not set (core.js:481)
- the above logic is based on the assumption that: as $touch() operates recursively, if the dirty flag is set on the root instance, it will also be set on all child instances
- adding a child instance after calling $validate() breaks the above assumption - after adding a child instance, $touch() should be called even if the dirty flag is set on the root instance

If I am correct, the obvious fix would be to remove the `if (!$dirty.value)` check. But I'm not sure what else that might break.

The workaround is to call $reset() before calling $validate(), if removing the check is not feasible and the current behavior is correct, perhaps this should be documented?

Hope this helps.

**Comment by awacode21** [comment]
I think i am dealing with the same issue. I also created a very basic reproduction:
https://stackblitz.com/edit/vitejs-vite-rwwprn

I have a toggle which adds or removes additional required fields. When toggling them in before the form gets the first time validated and then click submit to validate, they get validated. But after the first time the form is validated, when then removing them and adding again and finally click submit, they are not recognized by the validate function. First i thought they somehow loose their validation scope, but that is not the case. It really is related to the $dirty flag not set.

i was able to proove that by adding v$.value.$touch in front of calling the $validate function:
```
v$.value.$touch();
const isFormValid = await v$.value.$validate();

```
See on this reproduction: https://stackblitz.com/edit/vitejs-vite-dammwd

calling the touch before calling validate workaround the issue.
But when i have a look at the documentation: https://vuelidate-next.netlify.app/guide.html#validating-forms-before-submitting

i understand it that way that it really should be done by the $validate function. so my fix is only a temporarily fix which i will remove once this bug gets fixed.

**Comment by dobromir-hristov** [comment]
Please try v alpha.38

**Comment by awacode21** [comment]
@dobromir-hristov i can confirm the issue is fixed with v alpha.38. Thank you very much!

**Comment by awacode21** [comment]
@dobromir-hristov when building the project i get typescript linting issues with the vuelidate package. There seems to be something wrong with the type definition of ValidationArgs.

<img width="891" alt="Bildschirmfoto 2022-03-30 um 09 47 12" src="https://user-images.githubusercontent.com/30939926/160779584-afe970f7-6975-42a9-9c06-4852e668e96c.png">
