### ISSUE TITLE
Vuelidate next docs is unreachable

### ISSUE THREAD

**Issue by metalsadman** [vuelidate/vuelidate#1011]
### Make sure that you are familiar with documentation before submitting an issue.

  https://vuelidate-next.netlify.com/

**Describe the bug**

**Reproduction URL**
Please use one of the two following codesandbox templates, to provide a reproduction of your problem

[Vuelidate 2 - Composition API + Vue 3](https://codesandbox.io/s/vuelidate-2-composition-api-vue-3-7wf99)
[Vuelidate 2 - Options API + Vue 3](https://codesandbox.io/s/vuelidate-2-options-api-vue-3-5ux4j)

Issues without a working fiddle are generally much harder to solve and usually take much more time to actually do it.

**To Reproduce**

**Expected behavior**

**Screenshots**
![Screen Shot 2022-03-11 at 1 35 18 PM](https://user-images.githubusercontent.com/31038838/157808670-d406d67c-b33a-43c5-b5f9-415612dac609.png)

**Additional context**

**Comment by dobromir-hristov** [comment]
It's vuelidate-next.netlify.app

**Comment by metalsadman** [comment]
@dobromir-hristov it is what i'm trying to browse, you can see it in the screenshot.

**Comment by dobromir-hristov** [comment]
Very strange, works great here...

**Comment by metalsadman** [comment]
it's ok, changed my computer's dns settings, and it's loading fine now. thanks.
