### ISSUE TITLE
Is there documentation to use sameAs in rules

### ISSUE THREAD

**Issue by harm-meijer** [vuelidate/vuelidate#1014]
I can see how sameAs is used in option api but I am using a different way:

    const rules = {
      newPassword,
      confirmPassword: {
        required,
        sameAsPassword: sameAs(newPassword.$model),
      },
    };

Should I just try all infinite combinations to see what works or is it possible to document how to do this?

**Comment by dobromir-hristov** [comment]
Make rules a function, then you have access to this.whatever

**Comment by harm-meijer** [comment]
@dobromir-hristov Thank you for your reply, I tried the following:
```
function Rules() {
  this.newPassword = { required };
  this.confirmPassword = {
    required,
    sameAsPassword: sameAs(this.newPassword),
  };
}
```

And in setup:
```
    const rules = new Rules();
    const v = useVuelidate(rules, form);
```

It still fails on the sameAs check

**Comment by dobromir-hristov** [comment]
Oh hehe. If you are using composition API, just pass the data. If its a reference or computed from a reactive.

**Comment by harm-meijer** [comment]
@dobromir-hristov I still don't understand where the other value is supposed to come from. Tried the following:

```
function Rules(form) {
  this.newPassword = { required };
  this.confirmPassword = {
    required,
    sameAsPassword: sameAs(form.value.newPassword),
  };
}
```

And in setup:

```
    const form = ref({});
    const rules = new Rules(form);
    const v = useVuelidate(rules, form);
```

But sameAs still fails

**Comment by harm-meijer** [comment]
@dobromir-hristov I solved in with the following code:

```
function Rules(form) {
  const sameAs = (value) =>
    value === form.value.newPassword;
  this.newPassword = { required };
  this.confirmPassword = {
    required,
    sameAsPassword: sameAs,
  };
}
```

Did not use sameAs from `@vuelidate/validators`
