### ISSUE TITLE
$externalResults does not work if rules are empty for specific field

### ISSUE THREAD

**Issue by weeuwee** [vuelidate/vuelidate#1015]
**Describe the bug**
validation message returned from server and appending to $externalResults will only be shown if there is a client side rule attached to the field/variable.

**To Reproduce**
Take the example from the doc

```js
// inside setup
const state = reactive({ foo: '', bar: '' });
const $externalResults = ref({}) // works with reactive({}) too.

const rules = { foo: { someValidation }, bar: {} }
const v = useVuelidate(rules, state, { $externalResults })

// validate method
async function validate () {
  // check if everything is valid
  if (!await v.value.$validate()) return
  await doAsyncStuff()
  // do server validation, and assume we have these errors
  const errors = {
    // foo: 'error', is also supported
    foo: ['Error one', 'Error Two'],
    bar: ['Error one']
  }
  // add the errors into the external results object
  $externalResults.value = errors
  // if using a `reactive` object instead,
  // Object.assign($externalResults, errors)
}

return { v, validate }
```

v.foo.$error will be true and there will be value in v.foo.$externalResults. Nothing will be shown on v.bar.$externalResults.

**Expected behavior**
External results should be supported by fields without an active client side rule

**Comment by dobromir-hristov** [comment]
Hey there. I just tried this out and this is expected. We skip empty objects, because they are usually branches, that hold other state. Once we extract all validators, we end up with an empty object :) 

Can you add just a boolean validator in that empty object, it should work fine.

```js
const rules = { foo: { someValidation }, bar: { true: () => true } }
```

**Comment by Migushthe2nd** [comment]
I couldn't find a mention of this in the documentation, which caused me to get stuck on this for many hours. Would appreciate it you could make sure others don't waste their time!

**Comment by dobromir-hristov** [comment]
A PR with doc improvements are very much welcome :)
