### ISSUE TITLE
document error: v$.$error not working instead v$.value.$error working.

### ISSUE THREAD

**Issue by rajeshtva** [vuelidate/vuelidate#1016]
**Describe the bug**
this is actually in documentation. first i didn't find any example clearly mentioning how to use v$ object as referenced in following code snippet. then which is mentioned in document didn't work properly. `v$.$error` prints `undefined` but `v$.value.$error` prints `true` or `false`. which is desired

```javascript
const form = reactive({
  name: "",
  email: "",
  password: "",
  referral_code: "",
  password_confirmation: "",
  agreeWithPrivacyPolicy: "",
});


const rules = {
  name: { required, $lazy: true },
  email: { required, email, $lazy: true },
  password: {
    required,
    minLength: minLength(8),
    $lazy: true,
  },
  password_confirmation: {
    required,
    sameAsPassword: sameAs(toRef(form, "password")),
    minLength: minLength(8),
    $lazy: true,
  },
};
const v$ = useVuelidate(rules, form, { $lazy: true });

console.log(v$.$error) // undefined

console.log(v$.value.$error) // true/false
```

**Reproduction URL**
i don't think it is needed. but please mention if it is needed as it is just documentation correction.
Issues without a working fiddle are generally much harder to solve and usually take much more time to actually do it.

**Expected behavior**
I just wanted to inform & see if documented behaviour was expected or this observed one.

**Comment by dobromir-hristov** [comment]
Hey there. `useVuelidate` returns a ref, so you are correct, you do need to use `.value`. In most cases, users have been using it in the Options API, so its not a problem there.

A PR would be very welcome to improve the docs :)
