### ISSUE TITLE
Using dynamic values results in TypeScript errors inside VS Code

### ISSUE THREAD

**Issue by stigvanbrabant** [vuelidate/vuelidate#1017]
**Describe the bug**
When using a dynamic nested state for validation, TypeScript throws errors inside VS Code.

**To Reproduce**
1. Setup nuxt project with Typescript
2. Create validation with nested state

**Expected behavior**
No TS error should be thrown

**Screenshots**
<img width="1209" alt="image" src="https://user-images.githubusercontent.com/14889538/159721820-e6525b25-c403-492e-8b3e-dbb2e3e0b23d.png">
**Additional context**
Using version ```2.0.0-alpha.34```

I'm not very experienced with Typescript so chances are that i'm overlooking something, but i can't find any way to resolve this.

**Comment by dobromir-hristov** [comment]
I think you have to guard first if showPasswordChange.value is true, because TS cannot be sure you if it is, at the time you are reaching into that to check :D

**Comment by stigvanbrabant** [comment]
@dobromir-hristov Could you maybe provide an example? I can't get it to work.

**Comment by dobromir-hristov** [comment]
I am not great with TS either. But I assume you should just do an if Check before you try and reach into the property.

**Comment by stigvanbrabant** [comment]
@dobromir-hristov 
<img width="646" alt="image" src="https://user-images.githubusercontent.com/14889538/160627005-16f3cd7d-bc00-453f-aa0d-e19ea2a79564.png">
This is not fixing it. Could you reopen this issue please? As it is not resolved.

**Comment by A-Ghorab** [comment]
i can help with this one @dobromir-hristov,

Let me redo this example on my side and maybe think of a solution for it 😃

**Comment by A-Ghorab** [comment]
@stigvanbrabant i don't think typescript can understand that easily 

so why don't you use requiredIf instead of required

```ts
const formValidators = computed(() => ({
firstName: {required},
password: {
   current: {required: requiredIf(showPasswordChange.value)}
//or  current: showPasswordChange.value ? {required} : {}
}
}));
```

this will register password fields and typescript can check them but only validate if it's enabled

**Comment by stigvanbrabant** [comment]
@A-Ghorab Ah didn't know about that one, that does the trick! Thank you so much!

**Comment by cibilex** [comment]
I think this error is normal for this situation because you use a optional variable.I think you can use these ways to solve this problem 👍 

1.  `if` control
2. requiredIf control
3. helpers.req(val)
