### ISSUE TITLE
Feature request: Keep track of properties not in rules for a kind of 'dirty' check

### ISSUE THREAD

**Issue by Jogai** [vuelidate/vuelidate#1019]
**Is your feature request related to a problem? Please describe.**
When using a form its nice to be able to check for a dirty state. I pulled in Vuelidate to do this for me but it only marks my object dirty if the properties that are mutated are present in the rules.

**Describe the solution you'd like**
When using Vuelidate for an object I want to use the dirtycheck for properties that don't have validation rules.

**Describe alternatives you've considered**
Alternatively I'm considering adding a validator that's always valid just to have the property in the rules.

**Additional context**
Using Vuelidate next the autoDirty option sounded like the option I needed, but thats not the case. If setting the validation to dirty has too much implications another property could be made next to 'dirty', maybe call it 'wet'. Than an object could be wet as well as dirty :wink: 

```
const v = useVuelidate(
	{
		someProperty: { required, $lazy: true }
	} as any,
	myObject, //{ someProperty, otherProperty } editing otherProperty does not trigger the dirty state.
	{ $autoDirty: true }
);

**Comment by dobromir-hristov** [comment]
I am afraid that wont be possible.

We build the validation tree based on the rules, not on the state. Both can change, but it made no sense to keep state for something that may not have validation rules.

Your alternative is good. You can even have an empty object I think and not pass any validators.
