### ISSUE TITLE
useVuelidate produces error with almost all input

### ISSUE THREAD

**Issue by Fuzzyma** [vuelidate/vuelidate#1025]
**Describe the bug**
`useVuelidate` produces typescript error with any input

**Reproduction**

I tried to create a reproduction but it "just works" in the codesandbox. That's why I added an image of the simplest example from my machine and the error. 

I am using latest vite with latest vuelidate and latest vue and typescript. My volar version is v0.33.10 (which is the latest as well)

![grafik](https://user-images.githubusercontent.com/3540542/160437859-912eddbe-0862-4e4f-8875-17bf86f24af3.png)

The only way I get typescript to shut up is if I don't pass a state at all but that's obviously not a solution

**Comment by dobromir-hristov** [comment]
We are having some TS issues ATM, trying to resolve them atm.

**Comment by dobromir-hristov** [comment]
Can you try again with the latest version?

**Comment by Fuzzyma** [comment]
Works like a charm! Thank you very much :)
