### ISSUE TITLE
Vuelidate typescript definition error crashes the project build

### ISSUE THREAD

**Issue by awacode21** [vuelidate/vuelidate#1027]
**Describe the bug**
When running my project build which also executes `vue-tsc --noEmit` (typescript linting), the build is not able to succeed because i get some typescript errors on vuelidates' type definition file.

**Expected behavior**
Build runs without errors, because there should be no typescript issues on vuelidate definition files.

**Screenshots**
<img width="885" alt="Bildschirmfoto 2022-03-30 um 17 39 44" src="https://user-images.githubusercontent.com/30939926/160875072-07f82210-88f2-4fd0-8c8d-b23bbf259a38.png">
<img width="751" alt="Bildschirmfoto 2022-03-30 um 17 41 18" src="https://user-images.githubusercontent.com/30939926/160875386-0f1235a1-b609-45f3-a8a9-8e4aea6bb046.png">

**Additional context**
It was still working with those version:
<img width="394" alt="Bildschirmfoto 2022-03-30 um 17 42 54" src="https://user-images.githubusercontent.com/30939926/160876055-3f692f13-f1d2-47ee-b850-1a3c0d2eda25.png">

But then i updated to this version:
<img width="400" alt="Bildschirmfoto 2022-03-30 um 17 45 24" src="https://user-images.githubusercontent.com/30939926/160876247-6834650c-37fa-4a62-b91b-d05e518e1fd7.png">

and now i have this problem. To be honest i really don't understand the issue that well. If it would be an issue on my code i would have expected a message related to my code that i am using wrong typing, but this error directly seems to be related to vueldates type definition. That's why i think it is a bug in vuelidate.

**Comment by dobromir-hristov** [comment]
Try v 40, I released it today. It should fix the issue. Sorry for the headache

**Comment by awacode21** [comment]
@dobromir-hristov v40 fixes the issue. Thank you very much.
