### ISSUE TITLE
Using vuelidate with a single value instead of an object raises TypeScript error

### ISSUE THREAD

**Issue by danielwaltz** [vuelidate/vuelidate#1028]
I noticed some strange behavior with types on the latest version. I discovered when using an object for validation, the new types are actually very helpful and caught a couple issues in my rule definitions, for example mistakes like this are causing a type error because the rule name didn't match the field name.

```ts
const form = reactive({
  name: '',
  email: '',
});

const rules = computed(() => ({
  name: { required },
  emailAddress: { required }, // Notice the rule name doesn't match
}));

const v$ = useVuelidate(rules, form, { $autoDirty: true }); // Surfaces a type error 🎉 
```

However, anywhere I had used vuelidate for a _single value_ and not an object, I am getting unexpected type errors.

```ts
const name = ref('');

const rules = computed(() => ({ required }));

const v$ = useVuelidate(rules, name, { $autoDirty: true }); // Error...?
```

I know this works at runtime and is just a type error, so I ended up suppressing it until it's fixed by using a `@ts-expect-error` comment like this:

```ts
// @ts-expect-error vuelidate supports single value validations
const v$ = useVuelidate(rules, name, { $autoDirty: true });
```

Not sure if this is expected behavior or not, but figured I'd share my findings in case others are running into it too!

**Comment by dobromir-hristov** [comment]
Unfortunately it should always have an object as state, and an object with the same structure for the rules.

What you are using, passing a single value is probably a glitch in the matrix, but deff not intended lol

**Comment by danielwaltz** [comment]
Funky... I think I'm pretty good at finding these glitches. 😆 It's a wonder why it's been working so well for me all this time (and continues to work despite the type error).

Do you think it might be beneficial to officially support a single value in this way, or is it uncommon enough to simply not allow it?

**Comment by dobromir-hristov** [comment]
Sorry, but I dont plan to support that case "officially' :D

**Comment by danielwaltz** [comment]
No worries, totally understandable! Appreciate the response and appreciate your work!
