### ISSUE TITLE
MessageProps interface – bad format code

### ISSUE THREAD

**Issue by idcom-jakub-soboczynski** [vuelidate/vuelidate#1031]
Hi!

there are code formatting errors in `index.d.ts` in the `MessageProps` interface definition. There are commas at the end of the line instead of semicolons.

https://github.com/vuelidate/vuelidate/blob/2c3e82f29e3e1e1781bda3abf50ea6e355525cf9/packages/validators/index.d.ts#L75

```typescript
export interface MessageProps {
  $model: string;
  $property: string;
  $params: object;
  $validator: string;
  $pending: boolean,
  $invalid: boolean,
  $response: unknown,
  $propertyPath: string,
}
```

**Comment by dobromir-hristov** [comment]
Closed in 8502d1af2fdbc41404aa11b11e0ff1c556882e01
