### ISSUE TITLE
Instructions for i18n are unclear

### ISSUE THREAD

**Issue by dvincitravis** [vuelidate/vuelidate#1036]
I'm struggling to get i18n working.

I'm using the exact code shown [in the docs](https://vuelidate-next.netlify.app/advanced_usage.html#i18n-support).

I get:

```
Compiled with problems:

ERROR in ./src/utils/i18n-validators.js 4:0-30

Module not found: Error: Can't resolve '@/i18n' in '/Users/dvincitravis/Desktop/vuesandbox/src/utils'
```

I don't really understand what this line is supposed to be importing, or from where:

    import { i18n } from "@/i18n"

Do I need to create a /src/i18n directory in my project? If so, what should I put there?

I have vue-i18n 9.1.9 installed. It works great elsewhere in my app. I just can't get it working with Vuelidate.

**Comment by dobromir-hristov** [comment]
Just use your i18n instance.  I assumed most ppl export it from that folder.

**Comment by dvincitravis** [comment]
I got it working. Two things were confusing me:

1. It was unclear to me what the /src/i18n directory was supposed to be. ([The instructions for setting up vue-i18n 9](https://vue-i18n.intlify.dev/guide/) tell you to define the i18n instance in main.js. It totally makes sense to put the i18n config in its own file – but I'm new to Vue, Vuelidate, _and_ vue-i18n. So things that are clear to more experienced Vue developers aren't necessarily clear to me.)

2. I didn't realize that importing from `'@/i18n'` would resolve to `'@/i18n/index.js'`.

Thanks. Seems like a nice package, by the way!

**Comment by CyntaxDotDev** [comment]
@dvincitravis I'm right there with you. Can you share an example of how you got this to work? :)

**Comment by emman-ok** [comment]
Anybody has an idea how this work. Am struggling to understand their documentation on this i18n support.

**Comment by dobromir-hristov** [comment]
What part are you struggling with?

The library does not ship with translated messages, you would have to do it, using your library of choice.

The docs show how to so that with vue-i18n.

**Comment by phprad** [comment]
Thank you, I have figured it out. Works well with Vue-i18n.

**Comment by labbedaine** [comment]
> Thank you, I have figured it out. Works well with Vue-i18n.

@phprad Can you share how you did it?  Thanks!
