### ISSUE TITLE
need better default message text

### ISSUE THREAD

**Issue by plweil** [vuelidate/vuelidate#1040]
I really appreciate the ability to customize error messages with `helpers.withMessage()`, but if you are going to supply some basic default messages (also a very good idea), they really ought to be a bit more meaningful and read well. In particular, I'm thinking of messages regarding `minLength()` and `maxLength()` such as

>  This field should be at least 4 long

Of course one can probably guess what this means from the context, but it reads very poorly. It would read much better if it said:

> This field must be at least 3 **characters** long

As things stand now, I'm going to have to add a custom message for every field using these validators, which seems silly.

**Comment by dobromir-hristov** [comment]
Hey there. You are absolutely right, feel free to create a PR.

This is just an oversight
