### ISSUE TITLE
Vuelidate on nested property potentially undefined when property exists

### ISSUE THREAD

**Issue by VividLemon** [vuelidate/vuelidate#1043]
Vuelidate 0.7.7
On Nuxt 2.15.8
**Describe the bug**
A nested property, such as 
```
data () {
  return {
    form: { foo: ""  }, 
    bar: ""
  }
}
```
If you check the possibilities (mainly with typescript) the value "foo" can be undefined. I thought this may have just been on purpose, but when I noticed that example property "bar" is not possibly undefined, it raised some flags.

**Reproduction URL**
Please use the following codesandbox template, to provide a reproduction of your problem

[Vuelidate Template](https://codesandbox.io/s/vuelidate-0x-template-rxbkz)
I attempted to make a sandbox, but it doesn't really work well without having typescript to view the error message. 

Issues without a working fiddle are generally much harder to solve and usually take much more time to actually do it.

**To Reproduce**
Simply copy the above code example, then check the types. You will see that nested properties, can possibly be undefined, whereas others are not
**Expected behavior**
The value is not undefined, it should not be possibly undefined.

**Screenshots**
![image](https://user-images.githubusercontent.com/31498096/163916237-19985d4f-4dbf-43ec-b4e8-cf8f95dbe02f.png)
![image](https://user-images.githubusercontent.com/31498096/163916291-63418c41-5e4e-4016-88fc-8965b2f12728.png)

**Additional context**

**Comment by dobromir-hristov** [comment]
Sorry I cannot help much without a minimal working example.

From the looks if things, you did not have `email` defined on your `form` TS definition initially. 
You also have not shown your validation rules, so I cannot tell for sure whats going on.

**Comment by dobromir-hristov** [comment]
I will close this for now, if you havent resolved it, we can reopen.
