### ISSUE TITLE
Nuxt2 + nuxt-i18n + translated messages ?

### ISSUE THREAD

**Issue by CaptainFalcon92** [vuelidate/vuelidate#1044]
Hello.

I can't find a way to use translated validators and messages with nuxt-i18n module.
Does anyone had found a ways to access $t instance injected by the nuxt plugin ?

Documentation at https://vuelidate-next.netlify.app/advanced_usage.html#i18n-support is confusing and pretty much unusable for me. 😞 

Thank you in advance

**Comment by FelixGraf** [comment]
I was able to get it working with `nuxt-i18n` using the [`useContext nuxt composable`](https://composition-api.nuxtjs.org/api/usecontext/). The `useContext` composable returns the `i18n` instance you can use to pass it to the `createI18nMessage` function.

```ts
import * as validators from '@vuelidate/validators';
import { useContext } from '@nuxtjs/composition-api';

export const useValidators = () => {
    const { i18n } = useContext();

    const withI18nMessage = validators.createI18nMessage({ t: i18n.t.bind(i18n) });

    const required = withI18nMessage(validators.required);

    return {
        required,
    };
};
```

In your component, just call the `useValidators` composable like the following:

```ts
setup() {
  const { required } = useValidators();

  const validationRules = {
    title: { required }
  }

  const v$ = useVuelidate(validationRules, formValue)
}
```

@CaptainFalcon92

**Comment by CaptainFalcon92** [comment]
Very interesting.
I though `useContext` was not available outside of Nuxt3. But apparently you're right ! It's also in @nuxtjs/composition-api.
I'm trying this immediately ! Thanks a lot for reminding me. If it works for me too i close the issue. 🙏

**Comment by CaptainFalcon92** [comment]
It works. Thanks again for reminding me about `useContext` and this solution.
