### ISSUE TITLE
$error state true when $pending true

### ISSUE THREAD

**Issue by philBrown** [vuelidate/vuelidate#1046]
**Describe the bug**

The [documentation for `$error`](https://vuelidate-next.netlify.app/api/state.html#error) states...

> Equivalent to `this.$dirty && !this.$pending && this.$invalid`.

However in testing it's clear that `$error` can be `true` while `$pending` is also `true`.

While async validators are executing, the `$error` state reports incorrectly.

**Reproduction URL**

I've set up a CodeSandbox example with watchers on `$error`, `$errors` and `$pending` here ~ https://codesandbox.io/s/nostalgic-feistel-dd80ii?file=/src/App.vue

You can see from the logs that the logic is not correct

> ```
> 1650509056935 "$pending:" true
> 1650509056937 "$error:" true
> 1650509056937 "$errors.length:" 0
> 1650509057937 "$error:" false
> 1650509057937 "$pending:" false
> ```

**To Reproduce**

Configure an async validator and use something like this to throw some errors
```html
<p v-if="v$.field.$error">{{ v$.field.$errors[0].$message }}</p>
```

**Expected behavior**

`$error` should be `false` if `$pending` is `true` based on the documentation.

**Additional context**

Originally from StackOverflow here ~ https://stackoverflow.com/q/71940268/283366

**Comment by dobromir-hristov** [comment]
Hey there, sorry for the late reply.

This was changed in #914

Please check the issue and PR and let me know what you think. We cant fix it for all cases I am afraid :/
