### ISSUE TITLE
Failed to resolve entry for package "@vuelidate/components".

### ISSUE THREAD

**Issue by darthf1** [vuelidate/vuelidate#1047]
### Make sure that you are familiar with documentation before submitting an issue.

  https://vuelidate-next.netlify.com/

**Describe the bug**
I'm currently on Vue 2 + Nuxt 2 + Composition API and I'm trying to migrate to Nuxt Bridge. During build, I get an error related to this package:

```
Failed to resolve entry for package "@vuelidate/components". The package may have incorrect main/module/exports specified in its package.json: Failed to resolve entry for package "@vuelidate/components". The package may have incorrect main/module/exports specified in its package.json.
```

I'm not sure this is an issue in this repository, which just happens to surface with Nuxt Bridge, or this is an issue with Nuxt Bridge.

**Screenshots**
![image](https://user-images.githubusercontent.com/17253332/165043353-2447a055-c0e5-4920-a657-908d60c6c487.png)

**Depdendencies**
```json
{
  dependencies: {
    "@vuelidate/components": "1.1.20",
    "@vuelidate/core": "2.0.0-alpha.40",
    "@vuelidate/validators": "2.0.0-alpha.28"
  }
}

**Comment by dobromir-hristov** [comment]
Most probably bad package.json indeed.

Will check out

**Comment by dobromir-hristov** [comment]
Try with v1.1.21

**Comment by darthf1** [comment]
> Try with v1.1.21

Thanks! I'm on holiday now, I can try next week.
