### ISSUE TITLE
Misleading variable name in the migration guide

### ISSUE THREAD

**Issue by domoratskii** [vuelidate/vuelidate#1048]
**Describe the bug**

The migration guide uses the variable name `v$`. This is misleading because the `0.x` version used `$v`. After the migration, I couldn't figure out why the errors occurred for a long time.

```js
 setup () {
    return { v$: useVuelidate() }
  },
```

https://vuelidate-next.netlify.app/migration_guide.html

**Expected behavior**
You can add a new paragraph to the migration about renaming the variable, but do it explicitly.

**Comment by dobromir-hristov** [comment]
Unfortunately, Vue 3 does not allow the use of variable, starting with `$`. That is why we had to change it to either `v` or `v$`.

**Comment by domoratskii** [comment]
> Unfortunately, Vue 3 does not allow the use of variable, starting with `$`. That is why we had to change it to either `v` or `v$`.

I'm not arguing with that. It's not obvious during the migration if you don't know about it.  Sentence in the migration guide - also rename `$v` to `v$` would not be redundant.

**Comment by dobromir-hristov** [comment]
Oh I see what you mean. Make it explicit with a warning for Vue 2 users? Yep will do!

**Comment by domoratskii** [comment]
> Oh I see what you mean. Make it explicit with a warning for Vue 2 users? Yep will do!

Thank you! This will be helpful.

**Comment by dobromir-hristov** [comment]
WDYT? Is this enough in the migration guide?

![image](https://user-images.githubusercontent.com/9863944/166137800-6aa45915-4ddc-46bf-9f93-e597762b5c0c.png)
