### ISSUE TITLE
Question: Is the Validation Group feature removed from 2.x?

### ISSUE THREAD

**Issue by kashiif** [vuelidate/vuelidate#1051]
I could not find the documentation for validation groups features on vuelidate-next. This documentation [exists for 0.x version](https://vuelidate.js.org/#sub-validation-groups). There is no mention in the [migration guide](https://vuelidate-next.netlify.app/migration_guide.html) as well.

**Comment by dobromir-hristov** [comment]
Yes you are correct, it is removed. This was one of the things we had dropped, along with `$each` and `$iter`.

Unfortunately it is not so easy to recreate that functionality now. Can you give me an example what you want to do with it, and maybe I can suggest a workaround?

**Comment by dobromir-hristov** [comment]
Been trying to think of a way to get groups back, but its tricky. We dont have access to the entire validation state, until its done building itself, so its not as easy as one might think to build a computed from for a group of items.

**Comment by kashiif** [comment]
Thanks for the input. We found a simple solution using computed property that looks into `$error` and `$invalid` of all the properties that were in the group.

May be the migration guide needs to mention the removal of `group`.
