### ISSUE TITLE
Url to accept protocol option

### ISSUE THREAD

**Issue by VividLemon** [vuelidate/vuelidate#1053]
**Is your feature request related to a problem? Please describe.**
The ability to only allow certain protocols -- http/https/ftp, etc. Would be a nice feature to add. In my use case, vuelidate validates the url, but on my server I have it disallowing ftp urls. Making this would solve the inconsistencies of client side allowing ftp protocol, while disallowing it on server. 

**Describe the solution you'd like**
URL could contain an optional parameter for specific protocols, say if you wanted to mandate the url is only of https. 

**Describe alternatives you've considered**
The only option out of the box given to us is to use a custom validator with a custom regular expression.

**Additional context**
This is to bring vuelidate validation a little bit closer to validator.js

**Comment by dobromir-hristov** [comment]
Hey there.

The url validator is not exposed as a function atm, so adding options would be a breaking change, which I would like to avoid.

We use this regex directly atm - https://gist.github.com/dperini/729294, wrapping it in the `regex` helper. 

Its not ideal, but you can deff wrap it yourself and remove the `ftp` part :))
