### ISSUE TITLE
Error with optionnal form field

### ISSUE THREAD

**Issue by NicolasMelin** [vuelidate/vuelidate#1058]
Hello, I have upgraded my @vuelidate/core to 2.0.0-alpha.41 (last used version for me was 2.0.0-alpha.34). And with this version I have now some bugs with optionnal field on my form.

For a very basic example, we will say that I have a user form with only a fiel password. And I want that my password field can be empty (so optionnal) and if the user valid with an empty field, the API will be update nothing. But, if the user insert a new password in the field, I want to check some rules with vualidate.

So, I have this code :

```javascript
interface UserEditionInterface {
    password?: string;
}

function passwordValidation(value: string) { ... }

const stateEdition : Ref<UserEditionInterface> = ref({});
const rulesEdition = {
    password: {
        password: helpers.withMessage(t('error.invalidPassword'), passwordValidation),
    },
};
const v$Edition = useVuelidate(rulesEdition, stateEdition);
```

And with this code, I have this error : 
```Property 'password' is optional in type 'UserEditionInterface' but required in type '{ password: any; }'.```.

Thanks by advance for your help and your support.

Best regards.

**Comment by dobromir-hristov** [comment]
Not sure, but I think the rule you defined is deff not optional. This is an issue with your types, not the library itself.

**Comment by NicolasMelin** [comment]
Thank's for your speed response. When you said " I think the rule you defined is deff not optional", you talk about my rulesEdition variable ?

**Comment by dobromir-hristov** [comment]
Sorry for the very late reply,

Well, the way it is defined now, the `password` field has one rule, called `password`, which maps to the `passwordValidation` function. Nothing tells the types that is an optional field, so because your `UserEditionInterface` may or may not have a `password` field at all, Vuelidate throws a fuss.

Let me know if that makes sense.
