### ISSUE TITLE
Access $index in helpers.forEach

### ISSUE THREAD

**Issue by dack94** [vuelidate/vuelidate#1059]
Hi, i don't think if this is a bug but i'd like to know if it's possible to achieve what i'm trying to do.

I'm using the forEach helper (i need it cause i'm validating an array of objects). The validation works very well but i need to have access to the current index in the forEach  method.

```
$each: helpers.forEach({
                    minutes_from: {
                        required,
                        isDuplicate(minutes_from) {
                             // I'd like to use the $index from the foreEach in here, is it possible ? 
                       }
                   }
 },
```

I don't want to use the findIndex() function cause i need the exact line (working with a big table)
and i need to check the previous and the next objects in the array

 Any ideas ?
 
 Thanks!

**Comment by dobromir-hristov** [comment]
Let me know if this would work for you - #1065

**Comment by dack94** [comment]
That's perfect!
Thanks a lot 🙂

**Comment by Dara-baptiste** [comment]
yes but how does we do  that?
