### ISSUE TITLE
Custom validator error when other accessing component 

### ISSUE THREAD

**Issue by huypxgear** [vuelidate/vuelidate#1060]
**Describe the bug**
I am not quite sure if it is a bug or not. I have created a custom validator and want to access other properties in the Vue instance. it is working correctly when using the function context. When using the arrow function I cannot access any other properties. According to the document both functions are equivalent

**Reproduction URL**
https://codesandbox.io/s/vuelidate-custom-validator-test-98uyib

**To Reproduce**
1. Type anything on the input box
2. Alert display

**Expected behavior**
Access other properties through vm

**Comment by dobromir-hristov** [comment]
If not mistaking, second param is the parent object of the validated property. Third param should be the VM.

Can you try that?

**Comment by huypxgear** [comment]
@dobromir-hristov 
I tried but it show undefined

![image](https://user-images.githubusercontent.com/45187933/169280112-47d92f6b-7f6c-4403-a8ad-ffc8ff866a27.png)

**Comment by dobromir-hristov** [comment]
Sorry, this is vuelidate 0.x.

I don't think we pass VM as a param there, only bind it to the function. Since arrow functions cannot rebind this context, you are forced to use a normal function.

**Comment by huypxgear** [comment]
oh okay. thanks
