### ISSUE TITLE
Type Narrowing - like Zod

### ISSUE THREAD

**Issue by stefnotch** [vuelidate/vuelidate#1061]
**Is your feature request related to a problem? Please describe.**
One case that is hard to type-safely handle with vuelidate at the moment is the following:

Assuming I have a dropdown where the default value is *nothing is selected*. Then the code could look like as follows.
```ts
const state = reactive<{country: string | null}>({country:null});
const rules = {
  country: { required },
};
```

And after calling the validation function, I can assume that a country has indeed been selected
```ts
const isFormCorrect = await v$.value.$validate();
if(!isFormCorrect) return;

let selectedCountry: string = state.country; // this fails, the type of country is still   string | null
```

**Describe the solution you'd like**
I would love it if vuelidate could do [type narrowing](https://www.typescriptlang.org/docs/handbook/2/narrowing.html)

**Describe alternatives you've considered**
The alternatives that I'm considering at the moment are throwing typesafety out of the window by manually casting it to the correct type (error prone and extra code) or writing my own validation library that uses https://github.com/colinhacks/zod under the hood (a significant amount of effort).

**Comment by dobromir-hristov** [comment]
Sorry but Vuelidate was written in JS with TS types contributed by users. So this would not come anytime soon, unless we rewrite the library again, which I dont have time for atm.
