### ISSUE TITLE
Question: How to use with a (nested) dynamic collection?

### ISSUE THREAD

**Issue by rezaffm** [vuelidate/vuelidate#1063]
Hi,

Thanks for Vuelidate, I more or less use it all the time. I am still on vue-2 but will migrate soon to vue-3.

Now, I came across an issue I just can't figure out (tough I looked at some examples I could find in this repo).

So basically, I have an object "review-score" that could have several children. Therefore, you have the following hierarchy (just 1 deep):

```javascript
review-score
  review-score
  review-score
review-score
review-score
review-score
  review-score
```

(it is dynamic, so you can even just have one or two review-scores and no nesting at all....)

and so on. For the moment, I have a classic parent-child component structure, where children review-scores are recursively rendered. 

What I do is to validate each review-score for itself. The validation is fairly easy, all that is required is to provide a "name" and that's all.

If a name is given and the data was changed/adjusted, it fires automatically a PUT Request that it send to the server.

I came now across the issue that I might want to create/update all the reviews and then submit (validate) the data.

And this is precisely where I am stuck now.

If I understood correctly I need to dynamically add the validation rules based on the current review scores. Or? Something like, if there are any scores then for $each a name is required and in case there are children for $each a name is required as well?

Or I keep the structure as it is, but somehow I need to tell $v.$invalid that the data is not correct once one of the review scores is invalid. I found an example where $v is passed as prop and then touched in the component - however, as I don't know how to create the validation object, I have no idea how to do that.

My apologies, but I am really lost on this one. And help or even a simple example would be appreciated.

**Comment by dobromir-hristov** [comment]
I am sorry but I dont understand your question. A very simple code example of what you are trying to do would help allot. Just keep things as simple as you can.

**Comment by rezaffm** [comment]
Hi, no worries, I will give it a try ...

So, this is the mentioned ReviewScore Component that looks like this (shortened):

```vue
<template>
  <b-form @submit.prevent="submit">
    <b-form-row class="d-flex align-items-center">
      <b-col lg="3">
        <b-form-group id="criteria" label="Criteria" label-for="criteria">
          <b-form-input
            name="criteria-input"
            :value="form.criteria"
            @input="setCriteria"
            :state="validateState('criteria')"
          ></b-form-input>
        </b-form-group>
      </b-col>
    </b-form-row>
    <!-- recursive call -->
    <template v-if="reviewScore.children">
      <review-score
        v-for="child in reviewScore.children"
        :review-score="child"
      ></review-score>
    </template>
  </b-form>
</template>

<script>

  export default {
    name: 'review-score',
    mixins: [validationMixin],
    props: {
      reviewScore: {
        type: Object,
        required: true
      }
    },
    data() {
      return {
        form: {
          criteria: '',
        }
      }
    },
    validations: {
      form: {
        criteria: { required },
      }
    },
    methods: {
      validateState(name) {
        const { $dirty, $error, $pending } = this.$v.form[name];
        if ($pending) return;
        return $dirty ? !$error : null;
      }
      setCriteria(criteria) {
        this.form.criteria = criteria
        this.$v.form.criteria.$touch()
        if (!this.$v.$invalid) {
          this.handleUpdate(this.reviewScore, this.form)
        }
      }
    }
  }
</script>
```
The component itself is called in the parent component like:

```vue
<template>
  <review-score v-for="score in scores" />
</template>
    ---

<script>
    data() {
      return {
        // could be also just a flat array where no score has any children at all.
         scores: [
           { id: 1, criteria: "Service", children: [] },
           { id: 2, criteria: "Usability", children: [] },
           { id: 3, criteria: "Features", children: [
             { id: 4, criteria: "Some Feature", children: [] },
             { id: 5, criteria: "Another Feature", children: [] } 
           ] },
         ] 
      }
    },
</script>
```

In this context, the validation happens in each component itself and is then send directly to the API (Database accordingly).

My question now is, how could I achieve the validation in the parent component when I click on a "Save" button I would call **this.$v.$touch()** which then validates all the review scores and its children?

In case all scores are valid, this.$v.$invalid becomes false and lets the request go through to the database.

I know there is the $each option for validations, but wouldn't I need kind of a "$each" in an $each"? So, basically, the validation must be recursive as well (depending upon the scores that exist), yes?

Thanks for having a look at all, btw.

**Comment by dobromir-hristov** [comment]
Aha I see what you mean, you are using vuelidate 0.x. Old vuelidate did not have a concept of child component validations, all rules had to be stored in the parent. This is quite tricky, because you have to somehow check each nested component's state, or store all of them somewhere... reactive..

In Vuelidate 2.x this is taken care for you, so the parent can call `$validate` and all of the children will validate.

**Comment by rezaffm** [comment]
Oh okay, yeah, I see.

True, I am lagging a bit behind :-) need to update to vue 3 (and also to vuetify then, as I am coming from boostrap-vue) right now. Cool to hear that this is considered in Vuelidate 2.x (great work!).

Just by chance, you don't have somewhere some sample code or a sandbox showing how this could be achieved?

**Comment by dobromir-hristov** [comment]
Vuelidate 2 supports Vue 2 :)
