### ISSUE TITLE
v$ in collector component contains "_vuelidate_15" object?

### ISSUE THREAD

**Issue by plweil** [vuelidate/vuelidate#1064]
Not sure whether this is a bug or an indicator that something else is wrong in my code. I have a parent collector component that is collecting results from a child form component. The collected child information is contained by an object named `_vuelidate_15`. Is this expected (as opposed to `form`)?

![Screen Shot 2022-05-26 at 6 05 27 PM](https://user-images.githubusercontent.com/1033771/170594007-4b7a1593-0b3d-4296-9f24-fcc0ad89c234.png)

**Comment by plweil** [comment]
Never mind. I just figured out how to use `$registerAs` and `$getResultsForChild`. Although I'm not clear as to what the advantage is in using a computed property like this (in Vue 2):

`return this.v$.$getResultsForChild("child1")`

versus using the v$ data object directly (both of these are in the parent component. It would be helpful to include some examples of using $registerAs` and `$getResultsForChild()` in the docs -- for slow people like me  ;-)

Also (maybe because I am kinda slow sometimes) while reading the docs, sometimes the distinction gets blurred between what applies to composition API versus options API, or both. For that reason, I really appreciate it when there are clearly demarcated sections devoted to each API. I guess that's one of the downsides (challenges) of having two different APIs, whether you're developing or writing documentation.

**Comment by dobromir-hristov** [comment]
Hey there. You can indeed use the property directly. We did not used to expose them, so the helper was added.

Maybe use the method, because if we move things internally you wont get a random error, as its not an official way to reach for things.
