### ISSUE TITLE
Nested validation doesn't seems to work when the child is a dynamic component

### ISSUE THREAD

**Issue by kaskatiyski** [vuelidate/vuelidate#1068]
I am not sure if this is a bug or how it's supposed to work, but if I use a dynamic component `<component :is="..." />`, when I trigger the validation from the parent, it's not taking into consideration the validations in the dynamic component. Any ideas?

**Comment by dobromir-hristov** [comment]
Can you make a small repro somewhere? It deff shouldn't happen but who knows

**Comment by kaskatiyski** [comment]
Strangely enough I tried in codesandbox and it worked, then when I returned in my project it was working there as well. Guess I changed something without realizing but couldn't find out what it was..
