### ISSUE TITLE
Validating collection of primitive types

### ISSUE THREAD

**Issue by DamianGlowala** [vuelidate/vuelidate#1069]
I'd like to validate a simple array of strings to make sure none of them is empty:

```
const rules = {
    questions: {
        $each: helpers.forEach({
            required
        })
    }
};
```
```
const state = ref({
    questions: ["", "abc", ""]
});
```

However, the validation is applied to each of the individual characters of the string. Isn't there a space for improvement to differentiate between the arrays/objects vs primitive types? Currently, there seems to be no way to validate an array of strings, which is really frustrating. If there is a straightforward one, I'd appreciate an example.

![image](https://user-images.githubusercontent.com/48835293/172456549-0fd8657c-83ef-46b2-80d1-77b4d10a31e7.png)

**Comment by dobromir-hristov** [comment]
You should just create a custom validator, that runs a validator with Array.every for example.

We don't have a helper for that, and the forEach helper is for an array of objects actually.

**Comment by DamianGlowala** [comment]
Thank you for the pointer! I am currently exploring how to apply custom validator to the array of strings, so that I still can display messages for each field separately (rather than one generic message saying that some elements do not conform to the requirements). Would you have any advice in this matter? `Array.every` sounds like a one error for all...

**Comment by dobromir-hristov** [comment]
Uf.... That's tougher. What would you do? Show the error under the input maybe?

That could be done, if you return an object with $invalid key in it, and maybe the keys which are invalid. Then you can access anything extra from that object using the $response object on the validator instance.

It's not complicated, but it's extra boilerplate that could be improved for sure.

I can play with something tomorrow.

**Comment by DamianGlowala** [comment]
I got it working! Didn't even know that's possible but yeah, works well:

```
const rules = computed(() => ({
    questions: state.value.questions.reduce(
        (total, _currentQuestion, index) => {
            total = Object.assign(total, {
                [index]: {
                    required
                }
            });

            return total;
        },
        {}
    )
}));
```

Thank you for the above answers, appreciate your time. Shall I close this issue or there might be a more elegant solution out there worth exploring? ;)
