### ISSUE TITLE
`$autoDirty` only works on the first of two fields.

### ISSUE THREAD

**Issue by mayakokits** [vuelidate/vuelidate#1073]
I have two fields bound to properties of a reactive object, and I’m setting up the Vuelidate instance with `$autoDirty: true`. Nevertheless, I can change the value of the second field, even delete it (with the validation fireing!) and `v$.$dirty` won’t become `true`. Only when I change the value of the first field, it becomes `true`. 

**Reproduction URL**
https://codesandbox.io/s/flamboyant-jasper-wjr7vx?file=/src/App.vue

**To Reproduce**
1. Type into the second input
2. Delete the content of the second input -> Validation says it's required!
3. `v$.$dirty` is still `false`
4. Type into the first input
6. `v$.$dirty` is finally `true`

**Expected behavior**
`v$.$dirty` should be `true` with the first change to the second input.

**Comment by dobromir-hristov** [comment]
I think $anyDirty would be true in that case, can you try?

**Comment by mayakokits** [comment]
Hey, thanks for the quick reply!

Yes, `$anyDirty` does it. Just looked it up in the API docs.
Now I get the difference between them, but it seems a bit counterintuitive to me, and I didn’t come across it when browsing through the guide. Maybe it should be mentioned at least in the section about [data nesting](https://vuelidate-next.netlify.app/examples.html#data-nesting)?

~~Still, it seems inconsistent to me that `$dirty` becomes `true` when I change the first field. After all, it’s on the same level in the data hierarchy, and I didn’t mutate the parent object (`name` in my example).~~ edit: my fault, the behavior is as described in the API docs. `$dirty` is only true after all children have been touched.

**Comment by mayakokits** [comment]
For me, it would be more intuitive if `$dirty` was `true` if any child has been touched. Then there could be an `$allDirty` flag to indicate that all children have been touched, but I can’t come up with a use case for that atm. Although there probably are some :upside_down_face:
