### ISSUE TITLE
Please update vue-demi dependency to 0.13.x for Vue 2.7 support

### ISSUE THREAD

**Issue by maximas31** [vuelidate/vuelidate#1079]
Vue 2.7 have composition API integrated in the package, but vuelidate require @vue/composition-api, now i need to keep both for properly work and have some side effects from that.

**Comment by dobromir-hristov** [comment]
Can you create a PR? I am not going to be available next few days, so if you can test it and make sure it works i can merge it asap and release.

**Comment by maximas31** [comment]
I tried but it fail tests, my skills is not enough to fix that.

**Comment by Warhead5555** [comment]
The following error occurs when adding vuelidate to a fresh Vue 2.7 project.

```
Compiled with problems:X

ERROR in ./node_modules/vue-demi/lib/index.mjs 2:0-81

Module not found: Error: Can't resolve '@vue/composition-api/dist/vue-composition-api.mjs' in 'D:\Development\Vue\vue-app27\node_modules\vue-demi\lib'
```

Package.json snippet:
+-- vue@2.7.2
+-- @vuelidate/core@2.0.0-alpha.42
+-- @vuelidate/validators@2.0.0-alpha.30

**Comment by maximas31** [comment]
> The following error occurs when adding vuelidate to a fresh Vue 2.7 project.
> 
> ```
> Compiled with problems:X
> 
> ERROR in ./node_modules/vue-demi/lib/index.mjs 2:0-81
> 
> Module not found: Error: Can't resolve '@vue/composition-api/dist/vue-composition-api.mjs' in 'D:\Development\Vue\vue-app27\node_modules\vue-demi\lib'
> ```
> 
> Package.json snippet: +-- vue@2.7.2 +-- @vuelidate/core@2.0.0-alpha.42 +-- @vuelidate/validators@2.0.0-alpha.30

You can fix this temporarily by overriding dependency with this rule in your package.json file, but again, you need to have installed @vue/composition-api because Vuelidate currently can't use composition-api from Vue 2.7 itself.

`  "overrides": {
    "vue-demi": "npm:vue-demi@^0.13.1"
  }`

**Comment by yk1711** [comment]
For anyone interested, here's a commit from my fork that worked for me: https://github.com/yk1711/vuelidate/commit/3512086a324d4e4bf800b8f7fb5f68ed88da76fe
It doesn't require to have `@vue/composition-api` in your node_modules anymore.

I didn't create a PR, because the tests fail and it doesn't seem to be trivial to understand what's going on. 

It seems to be connected to `vue-test-utils`-specific issues related to 2.7 changes, because in the real application all my use cases work as expected with this code.

**Comment by dobromir-hristov** [comment]
Hey my friend. 

Open the PR, we can fix the errors :) your fork looks OK

**Comment by renatodeleao** [comment]
For ppl using classic `yarn`, update your `package.json` then `yarn install`

```json
  "resolutions": {
    "@vuelidate/core/**/vue-demi": "^0.13.2",
    "@vuelidate/validators/**/vue-demi": "^0.13.2",
  }
```

>You can fix this temporarily by overriding dependency with this rule in your package.json file, but again, you need to have installed @vue/composition-api because Vuelidate currently can't use composition-api from Vue 2.7 itself.

I had no issues removing `@vue/composition-api` plugin, since with the correct `vue-demi` version we get the forwarding right.

**Comment by Florent-Bouisset** [comment]
Hello :) just made a PR, let me know if it looks good for you

**Comment by rdominl2003** [comment]
Hey guys! I've tried both suggestions and seems that vuelidate can't notice data changes in the fields's $model property.
Even when you can change the value, the field does not get the $model property updated with the value and this cause the required validators keeps saying that the field is required.  Here I drop the field structure.
```
{
  "$dirty": false,
  "$path": "",
  "$model": {
    "date": "07/02/2022",
  },
  "$error": false,
  "$errors": [
    {
      "$propertyPath": "1.date",
      "$property": "date",
      "$validator": "required",
      "$uid": "date-required",
      "$message": "Date is required",
      "$params": {
        "type": "required"
      },
      "$response": false,
      "$pending": false
    }
  ],
  "$invalid": true,
  "$anyDirty": true,
  "$pending": false,
  "$silentErrors": [
    {
      "$propertyPath": "date",
      "$property": "date",
      "$validator": "required",
      "$uid": "date-required",
      "$message": "Date is required",
      "$params": {
        "type": "required"
      },
      "$response": false,
      "$pending": false
    },
  ],
  "date": {
    "$dirty": true,
    "$path": "date",
    "required": {
      "$message": "Date is required",
      "$params": {
        "type": "required"
      },
      "$pending": false,
      "$invalid": true,
      "$response": false
    },
    "$externalResults": [],
    "$invalid": true,
    "$pending": false,
    "$error": true,
    "$silentErrors": [
      {
        "$propertyPath": "date",
        "$property": "date",
        "$validator": "required",
        "$uid": "date-required",
        "$message": "Date is required",
        "$params": {
          "type": "required"
        },
        "$response": false,
        "$pending": false
      }
    ],
    "$errors": [
      {
        "$propertyPath": "date",
        "$property": "date",
        "$validator": "required",
        "$uid": "date-required",
        "$message": "Date is required",
        "$params": {
          "type": "required"
        },
        "$response": false,
        "$pending": false
      }
    ],
    "$model": "",
    "$anyDirty": true
  }
}
```

**Comment by dobromir-hristov** [comment]
I have been very busy, but I will look into it today.

**Comment by elzodxon** [comment]
<img width="1262" alt="Screenshot 2023-02-07 at 12 33 58" src="https://user-images.githubusercontent.com/52325239/217181215-4ff1fa27-e86a-4fae-a1d3-37ebe456f137.png">

Hi, I am having this issue. I am using Nuxt 3. Vuelidate version is 2.0.0
