### ISSUE TITLE
Trouble with validating nested component

### ISSUE THREAD

**Issue by twei55** [vuelidate/vuelidate#1081]
I have an issue with [nested validations](https://vuelidate-next.netlify.app/advanced_usage.html#nested-validations) which is a bit related to what is described here https://github.com/vuelidate/vuelidate/issues/1062. The documentation is lacking some details here.

My code with a nested component currently looks like this (example). My goal is to have multiple persons on a project, project has a name, each person has a first and last name, all fields are required. Once successfully validated, I want to send the form data to a REST API to create the project.

Validations on the nested component do not work, neither on form submit nor on change events in the input field.

I use vuelidate 2.0.0-alpha.42.

(BTW: I use Nuxt3 but this should not matter I guess).

```
# pages/new.vue

<template>
   <v-form @submit.prevent="submit">
      <ProjectFormFields ref="formRef" />
      <v-btn type="submit">Create project</v-btn>
    </v-form>
</template>

<script>
import ProjectFormFields from '@/components/ProjectFormFields.vue'

export default {
  methods: {
    async submit(event) {
      const formRef = this.$refs.formRef
      const result = await formRef.v.$validate()

      if (!result) {
        return
      }
      else {
        fetch('http://my/api/projects', {
          method: 'POST',
          headers: {
            'Content-Type': 'application/json',
          },
          body: JSON.stringify(formRef.form),
        })
      }
    }  
  }
}
</script>
```

```
# components/ProjectFormFields.vue

<template>
  <v-text-field v-model="form.name" label="Project Name" />
  <div class="input-errors" v-for="error of v.form.name.$errors" :key="error.$uid">
    <div class="error-msg">{{ error.$message }}</div>
  </div>
  <PersonFields v-for="(person, index) in form.persons" :index="index" />
  <v-btn @click.prevent="addPerson">Add person</v-btn>
</template>

<script>
import useVuelidate from '@vuelidate/core'
import { required } from '@vuelidate/validators'
import PersonFields from '@/components/PersonFields.vue'

export default {
  components: { PersonFields },
  setup() {
    const v = useVuelidate({ $scope: false })
    return { v }
  },
  data() {
    return {
      form: {
        name: ''
        persons: [{ first_name: '', last_name: '' }]
      }
    }
  },
  methods: {
    addPerson() {
      this.form.persons.push({
        first_name: '',
        last_name: ''
      })
    }
  },
  validations() {
    return {
      form: {
        name: { required }
      }
    }
  }
}
</script>
```

```
# components/PersonFields.vue

<template>
  <v-text-field v-model="first_name" label="First Name" @input="updateFirstName" />
  <div class="input-errors" v-for="error of v.first_name.$errors" :key="error.$uid">
    <div class="error-msg">{{ error.$message }}</div>
  </div>
  <v-text-field v-model="last_name" label="Last name" @input="updateLastName" />
  <div class="input-errors" v-for="error of v.last_name.$errors" :key="error.$uid">
    <div class="error-msg">{{ error.$message }}</div>
  </div>
</template>

<script>
import { useVuelidate } from '@vuelidate/core'
import { required } from '@vuelidate/validators'

export default {
  setup() {
    const v = useVuelidate()
    return { v }
  },
  data() {
    return {
      first_name: '',
      last_name: ''
    }
  },
  props: {
    index: Number
  },
  methods: {
     updateFirstName(event) {
        this.$parent.persons[this.index].first_name = event.target.value
     },
     updateLastName(event) {
        this.$parent.persons[this.index].last_name = event.target.value
     },
  },
  validations() {
    return {
      first_name: { required },
      last_name: { required }
    }
  }
}
</script>
```

Thanks in advance for any advise :)

**Comment by twei55** [comment]
UPDATE:

I solved the issue by adding a ref to each child component and calling `$validate` on each of them.

```
...
<PersonFields v-for="(person, index) in form.persons" :index="index" :ref="'person' + index" />
...
```

```
async submit(event) {
      const formRef = this.$refs.formRef
      let childResult

      // Validate all child components
      Object.keys(formRef.$refs).forEach((key) => {
        if (formRef.$refs[key][0].v) {
          formRef.$refs[key][0].v.$validate().then((result) => {
            childResult = result
          })
        }
      })

      // Validate parent component
      const parentResult = await formRef.v.$validate()

      if (!parentResult || !childResult) {
        return
      }
      else {
         // Submit form data
      }
}
```

Not sure if this is the way, it should be implemented. As far as I understand the documentation, validating nested components should happen automatically:

> When using useVuelidate, Vuelidate will collect all validation $errors and $silentErrors from all nested components. No need to pass any props or listen to any events.

**Comment by dobromir-hristov** [comment]
Calling validate on the parent should validate the children too.

**Comment by twei55** [comment]
But in my case it doesn't :(

**Comment by dobromir-hristov** [comment]
hey I just had time to look at your code, and I saw you have defined `$scope : false` in `ProjectFormFields.vue`.

That will tell the `ProjectFormFields.vue` component to not collect Validation instances from children

**Comment by twei55** [comment]
Awesome, thanks for taking the time to go through the code. That was my issue 🤦, now the validation works like a charm. The behaviour is also [documented](https://vuelidate-next.netlify.app/advanced_usage.html#scope-property), but I wasn't aware of this.

**Comment by jorinho** [comment]
Just wanted to add a (edge) usecase where the validation chain is lost between children and parent, as it took me several hours to figure it out :dizzy_face:

If your parent component is inside a "portal" (from the "vue-portal" library) :door: in order to be displayed somewhere else than where it was defined -> This will confuse vuelidate and the children validations won't bubble up to the parent component anymore.

I couldn't find a clean solution to mitigate this and had to play without portal :shrug:
