### ISSUE TITLE
How to pass a computed property to a custom validator?

### ISSUE THREAD

**Issue by iandevlin** [vuelidate/vuelidate#1087]
I am trying to pass a computed propery to a custom validator but an error is being thrown in the console indicating that it is undefined.
`TypeError: Cannot read properties of undefined (reading 'surname')`

The documentation mentions that this is possible, and yet only uses overly simplified examples of how to use custom validators, and none of which show how to pass a computed property.

I'm fully aware that I may simply be doing something stupid, so any help appreciated!

e.g.

following from what the docs show,

if my computed property is called `surname`,

```
const isValidName = name => helpers.withParams(
    { value: name },
    (value) => {
       // do something to validate the name
       return ...;
    }
);

validations: {
   internalValue: {
      required,
         isValid: isValidName(this.surname)
      }
}
```

**Comment by dobromir-hristov** [comment]
Make validations a function retuning an object with validators. That should work.

**Comment by iandevlin** [comment]
> Make validations a function retuning an object with validators. That should work.

OMG, I'm as blind as a bat, that's even in the examples, I just overlooked it, I knew I was doing something daft.

Thank you very much @dobromir-hristov
