### ISSUE TITLE
Add $dirty to forEach helper results

### ISSUE THREAD

**Issue by Weetbix** [vuelidate/vuelidate#1089]
**Is your feature request related to a problem? Please describe.**

Hi, I am updated a large code base from vuelidate 1 to 2, for vue 3 support.

Previously when using `$each`, we could pass the validation object to our component library, which checks `$dirty` on that item to decide if it should show the error state or not.

for example:
```js
<some-input v-model="item.name"
    :validate="$v.items.$each[index].name" />

// Inside component library:
isInvalid() {
    if (this.validate) {
        return this.validate.$invalid && this.validate.$dirty;
    }
    return false;
},
```

With the new `forEach` helper, this property is missing. Only `required`, `$invalid` and `$error` exist on the data items at: `v$.items.$each.$response.$data[index].propertyName`

So if we pass that to our component library, it wont show the validation error state:
```js
<some-input v-model="item.name"
    :validate="$v.items.$each.$response.$data[index].name" />
```

 it would be great if the `$dirty` state of the parent form could be attached in each `data` item, so that we can continue to simply pass these objects to our component library.

**Describe the solution you'd like**
The forEach helper to attach the `$dirty` property to each `data` item in the `$response`. For example:
```
"$data": [
        {
          "isActive": {},
          "name": {
            "required": false,
            "$invalid": true,
            "$error": true,
            "$dirty": true, // Here
          },
        }
      ],
``` 

**Describe alternatives you've considered**

I tried modifying the `forEach` helper myself, and then even just augmenting/wrapping it, but I run into a lot of issues when trying to use `v$.$dirty` inside the helper (from the component in the parameters, or from `useVuelidate()`) because I'm not very familiar with the code.

My work around at the moment looks something like this:
```js
<some-input
    v-model="item.name"
    :validate="validatePropFromForEach(v$, v$.items, index, 'name')" />


const validatePropFromForEach = (v$, collection, index, propertyName) => ({
    ...collection.$each.$response.$data[index][propertyName],
    $dirty: v$.$dirty,
});
```

**Additional context**
I understand that the forEach helper is not ideal, and that the recommended way is to convert to child components, but at the moment there is already a huge amount of work for us to migrate to vue 3, so we are attempting to do it with minimal changes, and we have unfortunately a lot of places where $each is used.

**Comment by dobromir-hristov** [comment]
Unfortunately that may not be possible. The validators are called for the entire array, on each individual Item sequentially. It does not understand that each item is separate :/

I understand the frustration, but this was just an escape hatch. Could you perhaps use the forEach component wrapper instead?

**Comment by Weetbix** [comment]
Hey @dobromir-hristov thanks for the quick reply :)

Am I right thinking that your point is that previously $each would set dirty on each item individually, but if we tried to do it with the forEach helper it would be all or nothing?

Do you have an example of using `ValidateEach` with the options API? I have trouble passing `rules` to the component in that case.

**Comment by dobromir-hristov** [comment]
You understand correctly yea.

I don't have an example on me right now, and I am not sure if I will be able to quickly make something for you in time. What issues do you have with passing rules?

The rules can be defined as a plain property inside Data

**Comment by Weetbix** [comment]
@dobromir-hristov thanks, I will close this issue because as you mentioned the `$dirty` behaviour isn't ideal, and might lead to more confusion.

For us, we will keep migrating with our `validatePropFromForEach` helper to add `$dirty` to the result. The UX suffers slightly but we don't have the time to refactor all our forms. The `ValidateEach` is useful, but still requires a lot of changes per form.
