### ISSUE TITLE
migration: describe regex helper method signature change

### ISSUE THREAD

**Issue by dargmuesli** [vuelidate/vuelidate#1092]
Migrating to Vuelidate 2.x I noticed that while previously the regex helper signature was e.g. `helpers.regex('slug', /^[-A-Za-z0-9]+$/)` it now is `helpers.regex(/^[-A-Za-z0-9]+$/)` (without the first "title" parameter).

I did not find that change be part of the migration guide. If I'm correct about this change, I'd propose to add it to the migration guide, maybe explaining why the first parameter is not of use anymore.

**Comment by dobromir-hristov** [comment]
Oh yeah, sorry about that. Would you mind making a PR?

**Comment by dargmuesli** [comment]
I can do that, yes. But I'd like to explain why the first parameter is not used anymore too. I don't know that though. Why is that? What was its purpose in the first place?

**Comment by dobromir-hristov** [comment]
It uses to be required for registering the name of the validator for the withParams function. Now it's no longer a necessity.
