### ISSUE TITLE
Collection field mutation doesn't mark field as dirty

### ISSUE THREAD

**Issue by garf** [vuelidate/vuelidate#1093]
**Describe the bug**
The field tags is an array. I only need a dirty state for it.
I add it to the rules without validators, just an empty object.
But it's always pristine. Even when I explicitly invoke `$v.value.tags.$touch()`
Also it ignores even `$v.value.$touch()` for the entire model.

I'm adding or deleting entries in array like so:
`$v.value.tags.$model = [{id: 1, label: 'my tag 1'}, {id: 2, label: 'my tag 2'}]` (reassigning data entirely)

**Expected behavior**

invoking `$touch()` on the field or the whole model must mark it as dirty

**Additional info**

If I set `$autoDirty` it becomes dirty, but initially. Because the data is populated after initialization of the form. 

Also I use Vuelidate 2 for the Vue 2 project with `composition-api` plugin

**Comment by rdominl2003** [comment]
@garf Did you were able to make it work Vuelidate + vue 2.7 + composition-api ?
I was able to setup vuelidate + vue 2.6.14 + composition-api like a charm previously, but after the upgrade to vue 2.7.x everything I made stop working. 
If you were able to make it work, at least for an easy example, I would like to know if you have tip, suggestion or anything that helps me in somehow.
Thanks in advance.

@dobromir-hristov Do you have any example that I can take a look into using vuelidate + vue 2.7 and the built in composition api? I will appreciate any help.

**Comment by dobromir-hristov** [comment]
2.7 is broken atm. I will try to fix it today

**Comment by rdominl2003** [comment]
@dobromir-hristov is there any update regarding `2.7 is broken atm. I will try to fix it today`

**Comment by dobromir-hristov** [comment]
Give the latest version a try please.

**Comment by dobromir-hristov** [comment]
closing as stale. Let me know if you need more help.
