### ISSUE TITLE
$validate() method set all model property states to 'true'

### ISSUE THREAD

**Issue by lucianobosco** [vuelidate/vuelidate#1095]
**Describe the bug**
The `v$.value.$validate()` method set all model properties `$dirty` state to `true`

**Reproduction URL**
https://codesandbox.io/s/autumn-sunset-r4ocny?file=/src/App.vue

**To Reproduce**
1. Do not update input value ($dirty = false). Therefore no user interaction.
2. Click on 'validate' button
3. Click on  'Toggle All Ouput' button
4. See error: `"$dirty": true` despite no changes were made to input

**Expected behavior**
`$dirty` state for all model properties should remain as they are before validating.

**Additional context**
As per docs
```
A property is considered $dirty after it has received some sort of interaction from the user, which means all properties begin with a $dirty state of false.
```
When using a PATCH action, is a good practice to only send dirty fields to an API. 
The way I do it is by checking the dirty state of model properties. 
Unfortunately, once model is validated, all it properties are set as `dirty` despite there was not user interaction on the input

**Comment by dobromir-hristov** [comment]
Yes you are right, `$validate` does in fact touch all to be able to run validations.

Since every validation is ran as the user types, can you just check for `v$.$errors.length`, instead of calling `$validate`?

That way you will see if there are any errors in the form, without touching them all.

**Comment by lucianobosco** [comment]
> Yes you are right, `$validate` does in fact touch all to be able to run validations.
> 
> Since every validation is ran as the user types, can you just check for `v$.$errors.length`, instead of calling `$validate`?
> 
> That way you will see if there are any errors in the form, without touching them all.

I'm not looking for errors. I need to know the dirty fields after validating the entire form. 

The bahavior that you confirm does in fact mismatch with described in docs as I quoted in my question.

`A property is considered $dirty after it has received some sort of interaction from the user`

So that's not true, property will be considered `$dirty` even if you run the `$validate` method, despite user interaction or not.
