### ISSUE TITLE
nested validation

### ISSUE THREAD

**Issue by ultimate-solutions-user1** [vuelidate/vuelidate#1096]
validations() {
    return {
      form: {
        langs: {
          $each: helpers.forEach({
            branchName: {
              required,
              minLength: minLength(this.$minValueForInput),
              maxLength: maxLength(this.$maxValueForInput),
            }
          })
        }
      }
    }
  },

i use validation like this error is false untile i write in the input

**Comment by dobromir-hristov** [comment]
Validations are ran only on `$touch`
