### ISSUE TITLE
Issue with v-for & vuelidate

### ISSUE THREAD

**Issue by KazWar** [vuelidate/vuelidate#1098]
Hi, i'm struggling with getting vuelidate to properly work using a simple v-for. What i'm trying to do is to dynamically generate inputs, but it seems that vuelidate operates on a different lifecycle hook or something cause whenever I try to access the $invalid variable during component load, it cannot find it. To properly elaborate:

The code i'm using:
My Javascript:
```TS

import useVuelidate from '@vuelidate/core'
import { required, email } from '@vuelidate/validators'
import { FromAddress } from '@/common/models'

let form:FromAddress = $ref({} as FromAddress)

const inputs = [
    {
        model:"name",
        label:"Name",
        required:true,
    },
    {
        model:"company",
        label:"Company name",
        required:true,
    },
    {
        model:"email",
        label:"Email",
        required:true,
    },
    {
        model:"phone",
        label:"Phone",
        required:true,
    },
    {
        model:"address_1",
        label:"Primary address",
        required:true,
    },
    {
        model:"address_2",
        label:"Secondary Address",
    },
    {
        model:"postal_code",
        label:"Postal Code",
        required:true,
    },
    {
        model:"country",
        label:"Country",
        required:true,
    },
    {
        model:"state",
        label:"State",
    },
    {
        model:"city",
        label:"City",
        required:true
    }
]

const rules = {
    form: {
        "name": { required },
        "company" : { required }
    }
}

const v$ = useVuelidate( rules, { form })
```

My template
```TS
<q-form
    autocorrect="off"
    autocapitalize="off"
    autocomplete="off"
    spellcheck="false"
>
    <template v-for="(input, index) in inputs" :key="index">
        <q-input 
            class="q-py-xs"
            v-model='(form as any)[input.model]'
            :required="input.required"
            label-slot
            stack-label
            filled 
            square
        >
        {{ v$.form[input.model]["$invalid"] }}
            <template v-slot:label>
                <q-icon v-if="input.required" class="text-red-6 q-pb-xs" name="mdi-asterisk"/>
                <span class="text-weight-bold">{{ input.label }}</span>
            </template>
        </q-input>
    </template>

    <div class="row">
        <div class="col-8">
            <q-input v-model="form.street" label="Street" stack-label/>
        </div>
        <div class="col-4">
            <q-input v-model="form.house_number" label="Number" stack-label/>
        </div>
    </div>
</q-form>
```

This code results in the following error
![image](https://user-images.githubusercontent.com/24567052/183294334-a3810524-8307-4036-86a7-400786c17e99.png)

However, if I load the component in with
```TS
{{ v$.form[input.model] }}
```

it works fine.
![image](https://user-images.githubusercontent.com/24567052/183294413-e2c7e063-16ad-454a-848b-f4427f4a3559.png)

Following that I can change it back to the previous thing
```TS
{{ v$.form[input.model]["$invalid"] }}
```

And it'll work fine too
![image](https://user-images.githubusercontent.com/24567052/183294469-e1c7a11f-712f-4794-b5a8-cc4cf73887ac.png)

But a hard refresh with ctrl + f5, basically breaks it again. Hence my reasoning why there's some kind of weird lifecycle initialization which I don't quite understand. So, I would like some advice on the problem.

**Comment by ahsath** [comment]
it gives me the impression it is because your `form` reactive variable is being set as an empty object and vuelidate needs those properties to initialize, hence trying to do this: `v$.form[input.model]["$invalid"]` will result in an invalid object property access because there is no such thing `(v$.form.name.$invalid <- undefined)`

also your input's array model property is a plain string, it should be a reactive property otherwise it won't update its value when used with `v-model` i believe

**Comment by dobromir-hristov** [comment]
Your `rules` structure should match your `data` structure. In your case, `form` is empty object, that you want to fill as you input into it, from what I can see.

That just wont work :/ Take a look at [Validating Collections](https://vuelidate-next.netlify.app/advanced_usage.html#validating-collections) for more info
