### ISSUE TITLE
Add custom error messages within custom validator function?

### ISSUE THREAD

**Issue by Pazulay** [vuelidate/vuelidate#1100]
I started creating custom validators in external files and importing the functions as validators into my components so I don't bloat my code. And I was wondering if there already is a way to also attach a custom message from within the function to save more space. If not I think it would be a good feature for future versions.

Right now I have a setup like this:

``` 
// phone-number.validator.ts

export const PhoneFormatValidator = (value: string) => {
  const pattern = new RegExp(/^(\+\d+){0,1}[0-9 ]*(\(\d+\)){0,1}[0-9 ]+[0-9 /-]*[0-9 ]+$/);
  return pattern.test(value.toString());
};
```

``` 
// component.ts

...
validations: {
      phoneNumber: {
        PhoneFormatValidator: helpers.withMessage(
          'invalid number',
          PhoneFormatValidator
        )
      }
    }
  ...
```

But I would like to have the error message inside the function like this:

```
export const PhoneFormatValidator = (value: string) => {
  helpers.withMessage('Invalid Number', PhoneFormatValidator);
  const pattern = new RegExp(/^(\+\d+){0,1}[0-9 ]*(\(\d+\)){0,1}[0-9 ]+[0-9 /-]*[0-9 ]+$/);
  return pattern.test(value.toString());
};
```

**Comment by dobromir-hristov** [comment]
Just export the function with the wrapped call in it, aka call withMessage where you are exporting.

**Comment by Pazulay** [comment]
> 

Sorry I don't really understand what you mean. Can you give me an example?

**Comment by dobromir-hristov** [comment]
```js
export const phoneValidatorWithMessage = helpers.withMessage(
          'invalid number',
          PhoneFormatValidator
        )
```

**Comment by Pazulay** [comment]
> ```js
> export const phoneValidatorWithMessage = helpers.withMessage(
>           'invalid number',
>           PhoneFormatValidator
>         )
> ```

Ah yes okay. Thank you very much.
