### ISSUE TITLE
Using v$.field.$touch not working on custom input components.

### ISSUE THREAD

**Issue by Pazulay** [vuelidate/vuelidate#1102]
I have a custom Vue Component that acts as an input field with multiselect feature:
```
// callback-date-multiselect.component.html

<div>
  <multiselect
    v-if="hasOptions"
    v-model="selected"
    :name="name"
    track-by="date"
    label="label"
    key="select"
  >
  </multiselect>
  <input
    v-if="!hasOptions"
    type="text"
    pattern="[0-9]*"
    inputmode="numeric"
    v-model="selected"
    key="input"
    :name="name"
  />
</div>
```

When i call `@blur="v$.field.$touch" on the component inside another component it doesn't do anything`.

```
<callback-date-multiselect
              :initial="callbackDateDay"
              :name="'callbackDateDay'"
              v-model="callbackDateDay"
              @blur="v$.callbackDateDay.$touch"
>
</callback-date-multiselect>
```

Am I accessing the wrong instance?

When I change the element to <input> it works as intended.

**Comment by dobromir-hristov** [comment]
I need a minimal example to tell you for sure. Maybe you are passing it wrong, maybe it's loosing reference idk.

**Comment by Pazulay** [comment]
Having a hard time reproducing the code because I have a lot of packages in my projects to get my components to work the way they do so I am going to try to give a bit more detail.

I can call 
```
// testComponent.vue

<callback-date-multiselect v-model="callbackDateDay" @blur="foo" >

<script>
     setup(){
          function foo(){
                console.log('works')
          }
       }
<script />

output: works
```
and when I console log v$ I even get the whole object for the component back:

```
// testComponent.vue

<callback-date-multiselect v-model="callbackDateDay" @blur="foo(v$.callbackDateDay)" >

<script>
     setup(){
          function foo(obj){
                console.log(obj)
          }
       }
<script />

```

[screenshot](https://postimg.cc/TyQWH7BX)

And I just realised that when I call:
```
// testComponent.vue

<callback-date-multiselect v-model="callbackDateDay" @blur="v$.callbackDateDay.$touch" >

```
it updates v$.callbackDateDay.$error but doesn't rerun the validators so it can never turn back to 'true' if that makes sense.

**Comment by dobromir-hristov** [comment]
Sorry for the long wait. I will assume you were passing the data that is not matching the rules to Vuelidate.  I am closing for now, if you still have not resolved this, please give me a minimal reproduction I can play with.
