### ISSUE TITLE
Errors integrating Vuelidate 2 in a Vue 2.7 + Typescript project

### ISSUE THREAD

**Issue by uche789** [vuelidate/vuelidate#1103]
I am working on a project that was recently migrated to Vue 2.7 and is built with typescript. I'm trying to migrate to Vuelidate 2 but running into typescript errors. The documentation only covers integration for Vue 2.* projects with the `@vue/composition-api` plugin installed.

**Code Snippet:**
```
import { defineComponent } from 'vue';
import { required } from '@vuelidate/validators';
import { useVuelidate } from '@vuelidate/core';

export default defineComponent({
  validations() {
    return {
      files: {
        required,
      },
    };
  },
  data() {
    return {
      files: [] as string[],
    };
  },
  setup: () => ({ v$: useVuelidate() }),
});
```

**Here's the screenshot of the error**
<img width="550" alt="Screenshot 2022-08-31 at 07 58 32" src="https://user-images.githubusercontent.com/3889297/187604927-170c068f-e23a-4ab9-8e36-d01cb5ba3a67.png">

**Comment by ahsath** [comment]
This is not a bug, it is because defineComponent recognizes validations function as a foreign property, you need to some how extend the component type def with vuelidate's types
