### ISSUE TITLE
Custom validator is not updating after a reactive property changes.

### ISSUE THREAD

**Issue by raphaelparent** [vuelidate/vuelidate#1107]
**Describe the bug**

Custom validator is not updating after a reactive property changes. It always keeps the first value passed when the `rules` are created. In my case, it keeps `ca` instead of updating with the new form format.

I'll post a working fiddle if the code I'm using seems legit. Not sure if I am missing something else.

I'm also using the composition api with the `<script setup>` syntax.

**To Reproduce**

Versions
```
"@vuelidate/core": "^2.0.0-alpha.42",
"@vuelidate/validators": "^2.0.0-alpha.30",
```

The form
```js
const phoneForm = reactive({
    number: "",
    extension: "",
    type_id: 0,
    format: "ca",
});
```

The rules
```js
const rules = computed(() => {
    // this logs the correct value when the phoneForm.format value is updated
    console.log("rules", phoneForm.format); 
    
    return {
        number: {
            telephone: telephone(phoneForm.format),
            required,
        },
        type_id: {
            required,
        },
        format: {
            required,
        },
    };
});
```

The custom validator
```js
export const telephone = (format: string) => {
    return validators.helpers.withMessage(i18n.t("validations.telephone"), (value: string) => {
        // This always logs "ca" as the format, which is the default value in my form
        console.log("validation", value, format);
        return parsePhoneNumber(value, format.toUpperCase() as CountryCode).isPossible();
    });
};
```

**Expected behavior**

Validator should update with the new phone format whenever it changes.

**Comment by ahsath** [comment]
could you try:

```JS
export const telephone = (format: () => string) => {
...
telephone(() => phoneForm.format)
...
return parsePhoneNumber(value, format().toUpperCase() as CountryCode).isPossible();
```

**Comment by raphaelparent** [comment]
@ahsath thanks for answering!

Yes it did the trick and it makes a lot of sense. 

For those wondering, here's what I understand from it. Instead of calling the `telephone` validator only when the rules are created, we changed it with a function that returns the value we need to pass. That function is then called everytime the rules are checked which makes sure to pass the appropriate data.

**Comment by itsprathvi** [comment]
I was facing the same issue, and this solution really helped me!!
Thanks @ahsath
