### ISSUE TITLE
Migration guide missing how to handle $anyError no longer being available.

### ISSUE THREAD

**Issue by SlyDave** [vuelidate/vuelidate#1108]
0.x has a $anyError prop on elements within $v This is no longer available in 2.x, but the migration from 0.x to 2.x doesn't mention this.

I believe the work around is to simply check the length of $errors or use the newly available $validate, depending on the need to $touch.

**before:**

`$this.$v.form.$anyError`

**after:**

`$this.v$.form.errors.length`

or using the new this.v$.$validate()

`const isFormCorrect = await this.v$.$validate()`

More Examples:

**before:**
```
this.$v.form.$touch()
if (this.$v.form.$anyError) {
    return
}
```

**after:**
```
const isFormCorrect = await this.v$.$validate()
if (! isFormCorrect) {
    return
}
```

**Comment by thedamon** [comment]
We use this all over the place for general form validation. Odd to not mention it in the migration guide :/

**Comment by dobromir-hristov** [comment]
It must have slipped. If you guys think we must bring it back you can create a PR, otherwise we can just add it to the migration docs. I don't remember using it as I always $touch the entire variation tree.
