### ISSUE TITLE
ReferenceError: process is not defined

### ISSUE THREAD

**Issue by joseehilton147** [vuelidate/vuelidate#1109]
Error when install and use plugin with vue 2.7.7 + vite 3.1.1

I only deploy and started the project with this plugin and this error occur, when i uninstall it the project runs normally

![image](https://user-images.githubusercontent.com/53986027/190487275-6f1783e5-3a39-490a-acba-206878dcb930.png)

**Comment by joseehilton147** [comment]
I already "fixed" it by myself, but will be good if a PR was made to fix it.

The problem is, there's no "process.env" in Vitejs they use import.meta.env so a fix without change the "withParams.js" is to add this plugin: [vite-plugin-enviroment](https://github.com/ElMassimo/vite-plugin-environment) and then add this to your vite.config.js

![image](https://user-images.githubusercontent.com/53986027/190497026-94d2ca6d-ae37-44cc-a54d-611bd743771e.png)

and vuelidate will work again:

![image](https://user-images.githubusercontent.com/53986027/190497072-7a95a08f-6b34-4f47-a596-b7458dbb40bd.png)

**Comment by jayzun** [comment]
I encountered same problem.

**Comment by dobromir-hristov** [comment]
Hey, you can try with Vuelidate 2, it should work for you, as the old version is no longer maintained.
