### ISSUE TITLE
Nested Validation is not working as expected

### ISSUE THREAD

**Issue by ashishkularia** [vuelidate/vuelidate#1110]
Nested validation is not working as expected, neither on parent nor on child component. I'm creating dynamic forms whose count and data is being fetched through API. With $each of vuelidate 0.x it works like charm, however, with vuelidate 2.x nested validation is not working.

I have created a small demo app of what I am trying to achieve. Through 
https://codesandbox.io/s/practical-wind-lcxrje?file=/src/App.vue

Thanks, in advance for any advice :)

**Comment by dobromir-hristov** [comment]
I see whats wrong. You first need to fix those errors about identical `index` keys.

Then its not the best idea to directly v-model a prop, Vue warns you about that too.

And last, you were passing `person` as the data to Vuelidate, but your rules had a `person` object in them. That would imply you will have passed `data = { person: {} }` and not `data = person`, does that make sense?

```js
setup(props) {
    const { person } = toRefs(props);
    const rules = {
      person: {
        first_name: {
          $lazy: true,
          $autoDirty: true,
          required,
        },
        last_name: {
          $lazy: true,
          $autoDirty: true,
          required,
        },
      },
    };
    return { v$: useVuelidate(rules, { person }) };
```

**Comment by ashishkularia** [comment]
@dobromir-hristov Hey mate, sorry for the confusion earler, I'm kinda new to VueJs and have been using it for a month and so. I followed your advice and it worked on codesandbox. However, when I implimented the same solution on project, it started to throw an error. Therefore, I posted the question on stackoverflow and from there i found that I'm mixing up Composition API and options API.
I'm using Vue@2.6.14 for my project, so could you please guide me on how to use the nested validation on it.
Here is the link to stackoverflow question: https://stackoverflow.com/questions/73862310/vue2-composition-api-torefs-typeerror-object-is-not-a-function
