### ISSUE TITLE
How to load Vuelidate using Vue 3 and importmap type?

### ISSUE THREAD

**Issue by donnyv** [vuelidate/vuelidate#1113]
I'm using Vue3 with importmap type. When I add the Vuelidate cdn paths and call the imports it throws an error.
```
   <script type="importmap">
        {
          "imports": {
            "vue": "https://unpkg.com/vue@3.2.37/dist/vue.esm-browser.prod.js",
            "vueDemi": "https://cdn.jsdelivr.net/npm/vue-demi",
            "vuelidate": "https://cdn.jsdelivr.net/npm/@vuelidate/core",
            "vuelidateValidators": "https://cdn.jsdelivr.net/npm/@vuelidate/validators"
          }
        }
    </script>
```

Then when I try to import vuelidate like this.
```
import { useVuelidate } from 'vuelidate' 
```
I get this error...
![image](https://user-images.githubusercontent.com/2224189/192008775-132b6f8a-af55-4c87-a3a8-077767eaf0aa.png)

I get the same kind of error with vuelidateValidators. Except is complains it can't find the "email" validator.

I've looked at the doc and searched online but haven't found anyone come across this. What am I doing wrong?

**Comment by donnyv** [comment]
I have a work around for now. For anyone that comes across this.

Its not pretty but it works.

At the very top of vueDemi I add this line.
`import * as Vue from 'vue';`

Then I replace anything in the last line with "this" => "window"
Then add this at the end of the file.
`window.VueDemi = VueDemi;`

Also at the end of vuelidate and vuelidateValidators. I add these...
```
window.Vuelidate = Vuelidate;
window.VuelidateValidators = VuelidateValidators;
```

Now I can use it in my app.
```
<script type="importmap">
    {
      "imports": {
        "vue": "http://www-dev.nova.com/vendors/vuejs-3.2.37/vue-debug.js",
        "vueDemi": "http://www-dev.nova.com/vendors/vuelidate-2.0.0/vue-demi.js",
        "vuelidate": "http://www-dev.nova.com/vendors/vuelidate-2.0.0/vuelidate-core.js",
        "vuelidateValidators": "http://www-dev.nova.com/vendors/vuelidate-2.0.0/vuelidate-validators.js"
      }
    }
</script>
<script type="module">

    import { createApp } from 'vue'
    import "vueDemi"
    import "vuelidate"
    import "vuelidateValidators"

    const app = createApp({
        setup() {
            return {
                v$: Vuelidate.useVuelidate()
            }
        },
        data() {
            return {
              name: ''
            }
        },
        validations() {
            return {
                name: { required: VuelidateValidators.required }
            }
        }
    }).mount('#app');

</script>

<div id="app" v-cloak>
    <label>
        <input v-model="name" @blur="v$.name.$touch">
        <div v-if="v$.name.$error">Name field has an error.</div>
    </label>
</div>
```

**Comment by dobromir-hristov** [comment]
I could be mistaking, but shouldnt it import the ESM builds instead of it IIFE builds?

Looking at the output from jsdelivr, https://cdn.jsdelivr.net/npm/vue-demi - this serves an iife variant, but you actually need the esm one - https://cdn.jsdelivr.net/npm/vue-demi/lib/index.mjs

Same for Vuelidate - https://cdn.jsdelivr.net/npm/@vuelidate/core/dist/index.esm.js

**Comment by donnyv** [comment]
Is this in the help somewhere? Do you have a full static html file example on how to use the ESM builds?

**Comment by dobromir-hristov** [comment]
```html
   <script type="importmap">
        {
          "imports": {
            "vue": "https://unpkg.com/vue@3.2.37/dist/vue.esm-browser.prod.js",
            "vueDemi": "https://cdn.jsdelivr.net/npm/vue-demi/lib/index.mjs",
            "vuelidate": "https://cdn.jsdelivr.net/npm/@vuelidate/core/dist/index.esm.js",
            "vuelidateValidators": "https://cdn.jsdelivr.net/npm/@vuelidate/validators/dist/index.esm.js"
          }
        }
    </script>
```

**Comment by gsntscm** [comment]
tiktok
