### ISSUE TITLE
NPM dependency error with Vue 3

### ISSUE THREAD

**Issue by lacorde** [vuelidate/vuelidate#1114]
Since the latest tag (2.0.0), I get the following error when installing vuelidate (with `npm install @vuelidate/core @vuelidate/validators`)

EDIT: using Node v18.9.1 and NPM 8.19.1

```
...
npm ERR! Could not resolve dependency:
npm ERR!  @vuelidate/core@"^2.0.0" from the root project
npm ERR! Conflicting peer dependency: vue@2.6.14
npm ERR! node_modules/vue
npm ERR!   peer vue@">= 2.5 < 2.7" from @vue/composition-api@1.7.1
npm ERR!   node_modules/@vue/composition-api
npm ERR!     peerOptional @vue/composition-api@"^1.0.0-rc.1" from @vuelidate/core@2.0.0
npm ERR!     node_modules/@vuelidate/core
npm ERR!       @vuelidate/core@"^2.0.0" from the root project
...
```
I'm using Vue 3, and it seems that the following vuelidate peer dependency: `vue@2.6.14`, is conflicting with latest [@vue/composition-api](https://github.com/vuejs/composition-api)'s own peer dependency: `vue>= 2.5 < 2.7`.

This also creates conflicts with any packages having the peer dependency `vue@"^3.0.0`.

Is there anything that could be done here ? Thanks for the great work on vuelidate !

**Comment by dobromir-hristov** [comment]
What node and npm versions do you have?

**Comment by lacorde** [comment]
My bad here they are :
Node `v18.9.1` and NPM `8.19.1`
Both latest I think.

EDIT: I thought about using `--legacy-peer-deps` but it would be a bit of a workaround since I'm not going to be the only user of vuelidate coming accross this issue.

**Comment by dobromir-hristov** [comment]
I just installed the package in a Vite project with Vue 3 and I had no issues in both Yarn and NPM 8.19.2.

**Comment by lacorde** [comment]
This is indeed not related to vuelidate, but a NPM issue.
Thank you for the quick response and sorry for the inconvenience @dobromir-hristov.

For anyone interested, the ongoing thread is [here](https://github.com/vuejs/pinia/issues/853)
