### ISSUE TITLE
Enhance Typings

### ISSUE THREAD

**Issue by ig-onoffice-de** [vuelidate/vuelidate#1115]
**Is your feature request related to a problem? Please describe.**

1. Type of `ValidationRule` doesn't have the possibility to pass the Params type to the generic
2. Function `helpers.withParams` doesn't have the possibiltiy to pass the Params type neither
3. Function `helpers.regex` doesn't habe a ReturnType at all

**Describe the solution you'd like**

1.  Change
```
export type ValidationRule <T = any> = ValidationRuleWithParams<any, T> | ValidationRuleWithoutParams<T> | ValidatorFn<T>;
```
to
```
export type ValidationRule <T = any, P extends object = object> = ValidationRuleWithParams<P, T> | ValidationRuleWithoutParams<T> | ValidatorFn<T>;
```
2. Change
```
withParams: <T = unknown>(params: object, validator: ValidationRule<T>) => ValidationRuleWithParams
```
to
```
withParams: <T = unknown, P extends object = object>(params: P, validator: ValidationRule<T>) => ValidationRuleWithParams<P, T>
```
3. Change
```
regex: Function
```
to
```
regex: <T = any, K = any, S = any>(regex: RegExp)=>ValidatorFn< T, K, S>
```
With this one I'm not really sure about the return type.

**Describe alternatives you've considered**

**Additional context**

**Comment by dobromir-hristov** [comment]
Please feel free to open a PR.
