### ISSUE TITLE
TypeErrors after upgrading to Vue 2.7: error in setup()?

### ISSUE THREAD

**Issue by plweil** [vuelidate/vuelidate#1116]
### Make sure that you are familiar with documentation before submitting an issue.

  https://vuelidate-next.netlify.com/

**Describe the bug**
After upgrading to Vue 2.7, I'm suddenly getting a couple of TypeErrors when loading a page with a simple form. I did remove the @vue/composition-api package. However, it doesn't seem to be affecting any functionality. The validation works properly.

@vuelidate/core 2.0.0
@vuelidate/validators 2.0.0

![image](https://user-images.githubusercontent.com/1033771/193273153-d0c2724f-ae24-478c-a329-9f66780fb05a.png)

The complaint about "length" doesn't seem to have anything to do with my template; I removed all references to it.

My setup():

```javascript
  setup() {
    return {
      v$: useVuelidate(),
    }
  },
```

**Comment by dobromir-hristov** [comment]
Hey there. I just setup a brand new project with Vuelidate@2, Vue@2.7.10, and Vite and I have no issues. Please give me a repo to reproduce this, thanks.

**Comment by AlexGodbehere** [comment]
> ### Make sure that you are familiar with documentation before submitting an issue.
> https://vuelidate-next.netlify.com/
> 
> **Describe the bug** After upgrading to Vue 2.7, I'm suddenly getting a couple of TypeErrors when loading a page with a simple form. I did remove the @vue/composition-api package. However, it doesn't seem to be affecting any functionality. The validation works properly.
> 
> @vuelidate/core 2.0.0 @vuelidate/validators 2.0.0
> 
> ![image](https://user-images.githubusercontent.com/1033771/193273153-d0c2724f-ae24-478c-a329-9f66780fb05a.png)
> 
> The complaint about "length" doesn't seem to have anything to do with my template; I removed all references to it.
> 
> My setup():
> 
> ```js
>   setup() {
>     return {
>       v$: useVuelidate(),
>     }
>   },
> ```

I'm having exactly the same issue. Did you find a solution to this?

**Comment by AlexGodbehere** [comment]
For anyone else stumbling across this, removing the Vue composition API package seemed to solve the issue. [It appears as though it's not required for Vue 2.7+](https://github.com/vuejs/composition-api#vuecomposition-api).
