### ISSUE TITLE
Docs: unclear statement about variables not starting with "$"

### ISSUE THREAD

**Issue by thedamon** [vuelidate/vuelidate#1117]
**Describe the bug**

In the migration guide when explaining the reason of using a different var name for vuelidate by default, it states:

> Vue3 does not allow you to return variables, starting with $. 

I can find no reference anywhere to Vue3 not allowing the return of variables starting with `$` and in fact see it happening in other plugins.

**Reproduction URL**
https://vuelidate-next.netlify.app/migration_guide.html#v-instead-of-v

**Expected behavior**
This statement should be explained with a reference, or removed.

**Comment by dobromir-hristov** [comment]
Well you can just do whatever you want actually. There is nothing stopping you from calling your Vuelidate instance `validation` or just `v`. 

If you try to return `$v` you will see in your console what I mean.

**Comment by thedamon** [comment]
I have not attempted the upgrade yet, so I will look at the console once I get that far. In the meantime I note that $router and $i18n in vue-3 are using dollar prefixed variables and I can't find anything in any docs saying not to do this. Is it because vuelidate is no longer a plugin and `$` is the domain of plugins and other global shared config, while vuelidate now operates on a local scope?

I find that statement in the docs is confusing when I can't find corroboration anywhere online, and I would like to suggest a change to it, but I do not understand it enough to.

**Comment by dobromir-hristov** [comment]
They both attach their instances in a very clever way, alas we cannot do that, because we need to create and return an instance from within each component. 

Vue warns you for that, but not if you attach it to the global scope.

**Comment by thedamon** [comment]
Hmm..
i tried to replicate in the REPL SFC playground and am not seeing any warnings or errors: https://sfc.vuejs.org/#__DEV__eNqVUMtKxEAQ/JV2EKKwm7mHKIgXv0Avc4lJZ80yL7on8RDy7/a4mzUoLHjrquqprqlZPcVYTiOqStXc0hATMKYxPho/uBgowQyEPSzQU3BQyGpxkZ6Di2e+1BlkJ5GNb4PnBI4P8JCf3xUvaG2At0C2uynuja/16ZrcEZDQRdskFFRnH50HfWHVTp0u7l0TyyMHL3Fn4wHMWWCjKvhmMicpMjbqI6XIldbctznakctABy1TSaNPg8MS2e3fKXwykhgbtdt4aCEnpD2h75CQrnn+Wv3jm20X4xf5ylrU/ypfO71tR07BvTa0VtvAJKBtrMVuI19teZ5/FhfJtS17+QKebbuj
