### ISSUE TITLE
Validating forms with regex helpers is not working...

### ISSUE THREAD

**Issue by hannanmiah** [vuelidate/vuelidate#1141]
**Description**
Validating forms with regex helpers is not working in vuelidate 2.0.0. When I try to input some text with phone number validation with specific regexp (/^\+?[0-9]{10,17}$/g) it shows invalid error response. When it in this specific regex range, for every key up it shows first valid & next invalid. It continues till validation boundary crosses its range. After crossing its range its working perfectly. But when it is in the range , it shows this awkward behavior. Kindly fix my probleam as soon as possible. I'm having trouble resolving it. It may me mentioned that I'm using vuelidate in a crm which is live now. 

## Code
![image](https://user-images.githubusercontent.com/36930986/205708973-2ab0d8ed-3ae7-4353-8e50-f599d358c870.png)
## Output
![image](https://user-images.githubusercontent.com/36930986/205708820-bf47078c-5d3f-4705-95f0-2072763f22fa.png)

**Reproduction URL**
[Vuelidate 2 with Vue 3 + Vite codesandbox](https://codesandbox.io/s/vue3test-4cq7yf?file=/src/components/HelloWorld.vue)

**To Reproduce**
1. Go to 'phone number field of the form'
2. Enter some number which length is bigger than 9 and not bigger than 17.
3. Then it will show one is valid and other is invalid keystroke repeatedly till it reaches to 17 characters.
4. After reaching 17 characters it behaves as usual.

**Expected behavior**
It should trigger validation error when the number of characters are smaller than 10 and bigger than 17, it also accept + sign at the front, and also all characters should be numeric.

**Comment by dobromir-hristov** [comment]
I think this is because we create a computed from the regex, but because it has the global modifier it causes some issues. Try removing that /g and see what happens.

**Comment by hannanmiah** [comment]
Thanks, it solved my issues.
