### ISSUE TITLE
$validate not triggering validation of collections of helpers.forEach

### ISSUE THREAD

**Issue by Brunnn** [vuelidate/vuelidate#1161]
@vuelidate/core: 2.0.0
@vuelidate/validators: 2.0.0
typescript: 4.9.5

I'm using helpers.forEach to validate collections of my model, and i'm wondering why does the `v$.$validate` function does not trigger validations and errors of collections. How can i make that possible? is there another function to trigger it?
Here is my validations code

```ts
const discountValidations: ValidationArgs<ICampaignWizardDiscountStep> = {
        categories: {
            $each: helpers.forEach({
                id: {
                    required: helpers.withMessage(
                        "Choose a category",
                        required
                    ),
                },
                discountValue: {
                    requiredIf: helpers.withMessage(
                        "Discount value is required for category",
                        requiredIf(
                            () =>
                                campaignWizardDiscountStep.value.discountType ==
                                DiscountType.per_item
                        )
                    ),
                },
            }),
        }
};
``` 
Here is the screenshot after i added 3 items into the model collection and called the `$validate` function:
![image](https://user-images.githubusercontent.com/42523274/217648899-599bd170-73a0-4e03-b8ed-f43a647475dd.png)
As it seems, the v$discount instance does not indicate any errors, despite the 3 items of the models having errors.
The errors are triggered only when the user types in the fields of each item.

**Comment by MikeyBeLike** [comment]
to get around this I had another ref() `const submitAttempted = ref(false)` and I used that together with `v$.FORM_STATE.$invalid` to simulate what `$dirty` would have done. Also used `v$.value.$invalid` to simulate `v$.validate()`
