### ISSUE TITLE
Doesn't work with vite4

### ISSUE THREAD

**Issue by webigorkiev** [vuelidate/vuelidate#1166]
When I updated vite to version 4 I get an error
Warning: To load an ES module, set "type": "module" in the package.json or use the .mjs extension

Perhaps this is due to these lines

```
"exports": {
    ".": {
      "import": "./dist/index.esm.js",
      "require": "./dist/index.js"
    },
    "./*": "./*"
  },
```

**Comment by lermontex** [comment]
#1153
