### ISSUE TITLE
Vuelidate sameAs method always returns to password is not equal error?

### ISSUE THREAD

**Issue by eguvenc** [vuelidate/vuelidate#1181]
**Describe the bug**
I tried to vuelidate 2.0 sameAs function with Vue 3 version. Although the password and confirm password is equal it always returns to "password not equal" error when i click to submit.

**Reproduction URL**
[Codesandbox Url](https://codesandbox.io/p/github/eguvenc/test/main?layout=%257B%2522activeFilepath%2522%253Anull%252C%2522openFiles%2522%253A%255B%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522fullScreenDevtools%2522%253Afalse%252C%2522rootPanelGroup%2522%253A%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clgsaiw6z00623n6ja5j8x8qu%2522%257D%255D%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS_PANELS%2522%252C%2522sizes%2522%253A%255B100%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clgsaiw6z00623n6ja5j8x8qu%2522%253A%257B%2522id%2522%253A%2522clgsaiw6z00623n6ja5j8x8qu%2522%252C%2522activeTabId%2522%253A%2522clgsaixoz009j3n6j4jg0qffa%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clgsaiw6z00613n6jabor6dqt%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clgsaixoz009j3n6j4jg0qffa%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%257D%252C%2522showSidebar%2522%253Atrue%252C%2522showDevtools%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%252C%2522editorPanelSize%2522%253A30.57291666666667%252C%2522devtoolsPanelSize%2522%253A54.42708333333333%257D)

**To Reproduce**
1. Go to form validation
2. Write same password to each field
3. Click to submit button
4. See the validation error, it always returns to "password is not equal"

**Expected behavior**
After that form submit i need to see the javascript alert like "ok form submitted".

**Screenshots**
![682UB](https://user-images.githubusercontent.com/482833/233825451-9eab01d5-7672-4ba7-8a19-f1d833f45a2b.png)
**Additional context**
[Stackowerflow link](https://stackoverflow.com/questions/76081295/how-can-use-vue-3-vuelidate-sameas-method-it-always-returns-to-password-not-equ)

**Comment by ThibaultVlacich** [comment]
`sameAs: sameAs("newPassword"),`

You should pass the ref, not the name. Because here, you are asking `confirmPassword` to be exactly equals to the string `newPassword`.

`sameAs: sameAs(this.newPassword),`

https://vuelidate-next.netlify.app/validators.html#sameas

**Comment by eguvenc** [comment]
> `sameAs: sameAs("newPassword"),`
> 
> You should pass the ref, not the name. Because here, you are asking `confirmPassword` to be exactly equals to the string `newPassword`.
> 
> `sameAs: sameAs(this.newPassword),`
> 
> https://vuelidate-next.netlify.app/validators.html#sameas

i tried this but i get a blank page error.

Test it --> 
[Codesandbox Url](https://codesandbox.io/p/github/eguvenc/test/main?layout=%257B%2522activeFilepath%2522%253Anull%252C%2522openFiles%2522%253A%255B%255D%252C%2522sidebarPanel%2522%253A%2522EXPLORER%2522%252C%2522gitSidebarPanel%2522%253A%2522COMMIT%2522%252C%2522fullScreenDevtools%2522%253Afalse%252C%2522rootPanelGroup%2522%253A%257B%2522type%2522%253A%2522PANEL_GROUP%2522%252C%2522panels%2522%253A%255B%257B%2522type%2522%253A%2522PANEL%2522%252C%2522panelType%2522%253A%2522TABS%2522%252C%2522id%2522%253A%2522clgsaiw6z00623n6ja5j8x8qu%2522%257D%255D%252C%2522direction%2522%253A%2522vertical%2522%252C%2522id%2522%253A%2522DEVTOOLS_PANELS%2522%252C%2522sizes%2522%253A%255B100%255D%257D%252C%2522tabbedPanels%2522%253A%257B%2522clgsaiw6z00623n6ja5j8x8qu%2522%253A%257B%2522id%2522%253A%2522clgsaiw6z00623n6ja5j8x8qu%2522%252C%2522activeTabId%2522%253A%2522clgsaixoz009j3n6j4jg0qffa%2522%252C%2522tabs%2522%253A%255B%257B%2522id%2522%253A%2522clgsaiw6z00613n6jabor6dqt%2522%252C%2522type%2522%253A%2522TASK_LOG%2522%252C%2522taskId%2522%253A%2522dev%2522%257D%252C%257B%2522type%2522%253A%2522TASK_PORT%2522%252C%2522taskId%2522%253A%2522dev%2522%252C%2522port%2522%253A3000%252C%2522id%2522%253A%2522clgsaixoz009j3n6j4jg0qffa%2522%252C%2522path%2522%253A%2522%252F%2522%257D%255D%257D%257D%252C%2522showSidebar%2522%253Atrue%252C%2522showDevtools%2522%253Atrue%252C%2522sidebarPanelSize%2522%253A15%252C%2522editorPanelSize%2522%253A30.57291666666667%252C%2522devtoolsPanelSize%2522%253A54.42708333333333%257D)

**Comment by ThibaultVlacich** [comment]
Read the doc that I linked. You need to write `validations` as a function.

Like this:
```
  validations () {
    return {
	    newPassword: {
	      required,
	      minLength: minLength(8),
	      maxLength: maxLength(16),
	    },
	    confirmPassword: {
	      required,
	      sameAs: sameAs(this.newPassword),
	    },
    }
  }
```

**Comment by eguvenc** [comment]
> 

Thanks. It works.
