### ISSUE TITLE
Vuelidate copies validations from child components

### ISSUE THREAD

**Issue by szulcus** [vuelidate/vuelidate#1187]
**Describe the bug**
Validations from the child component are merged into the parent component.

**Reproduction URL**
https://stackblitz.com/edit/github-qqpbrj?file=components/ValidatedComponent.vue
https://githubqqpbrj-4l5v--3000--9c984a48.local-credentialless.webcontainer.io/

**To Reproduce**
1. Fill first input with email
2. Fill second input with password (6+ characters)
3. See silent error from child component

**Expected behavior**
`vuelidate.$silentErrors` in `app.vue` should be empty, when form is filled properly.

**Screenshots**
![image](https://user-images.githubusercontent.com/48328739/236872217-3ebc4b65-4aa8-4da3-a2be-ec2f8513357c.png)

**Comment by beljand** [comment]
@szulcus this is by design, so you can have nested forms. If you want to treat forms separately, do not nest them.

**Comment by dobromir-hristov** [comment]
Or set the stopPropagation boolean.

**Comment by szulcus** [comment]
@dobromir-hristov Thank you very much!
