### ISSUE TITLE
Issue with async rules 

### ISSUE THREAD

**Issue by hivokas** [vuelidate/vuelidate#1194]
**Describe the bug**
Sometimes error message is incorrect.

**Reproduction URL**
https://codesandbox.io/s/unruffled-dream-3v8g7p

**To Reproduce**
1. Open reproduction URL
2. Type "111" (not copy-paste, but type symbol by symbol so it fires validation for "1", "11" and "111")
3. You'll see "111 failed" error, and then it'll become "11 failed".

<img width="213" alt="Screenshot 2023-06-23 at 19 02 55" src="https://github.com/vuelidate/vuelidate/assets/22997803/046a45f2-37e3-4e96-b585-94ee8f2f67fd">

**Expected behavior**
I would expect to see "111 failed" in the end. But I see "11 failed". It happens because validation for "11" input takes more time than for "111" input. 

**Screenshots**

**Additional context**
This is a simple reproduction to understand the problem. In our app in production it can sometimes happen because we send a request to backend to run validation and response time varies.

**Comment by dobromir-hristov** [comment]
Vuelidate cannot control your async requests. It waits for everything to resolve and the last one to finish wins.

In this case you have to cancel previous validators that are still running before firing new ones.

**Comment by hivokas** [comment]
> Vuelidate cannot control your async requests. It waits for everything to resolve and the last one to finish wins.
> 
> In this case you have to cancel previous validators that are still running before firing new ones.

Thanks for quick reply. 

Do you have any tips on how to cancel previous validators?

**Comment by dobromir-hristov** [comment]
Depends if you use fetch or Axios.

In both cases they share some state or I'd of some sorts. Each time you call the validator you first cancel the previous one.

Remember to catch the error so it doesn't error out in the validator.

**Comment by hivokas** [comment]
I think the easiest way to solve this problem would be to neither reject nor resolve $validator Promise. Do you see any bad consequences if I use this approach?

**Comment by hivokas** [comment]
> Each time you call the validator you first cancel the previous one.

I don't fully understand how can validator be cancelled? Is it possible to do from within validation rule?

**Comment by hivokas** [comment]
> I think the easiest way to solve this problem would be to neither reject nor resolve $validator Promise. Do you see any bad consequences if I use this approach?

Looks like doing this will make validation stuck in pending state even if it's validation for previous value which is no longer relevant.

**Comment by dobromir-hristov** [comment]
Here is how I would do this. Ofc this is just pseudo code but you should get the idea. AbortController is part of the fetch spec.

```js
let controller
function someAsyncRule(){
  // abort old requests
  controller?.abort()
  // initiate a new abort controller
  controller = new AbortController()

  // call your API with whatever you need. Make sure to pass the `controller.signal` if using Fetch. Axios uses something else.
  return fetchWrapper(somePath, someValue, controller.signal).catch((error) => {
    // if the error is from aborting, just resolve
    if(error.aborted) return
    // otherwise re-throw the error so we can catch in in Vuelidate.
    throw error
  })
}
```

**Comment by hivokas** [comment]
Thank you Dobromir! I will give it a try

**Comment by hivokas** [comment]
I think this is a good direction. Thank you Dobromir for pointing me to this direction!
