### ISSUE TITLE
$error is true even though required is false

### ISSUE THREAD

**Issue by iulianwebdev** [vuelidate/vuelidate#1212]
### Make sure that you are familiar with documentation before submitting an issue.

  https://vuelidate.netlify.com/

**Describe the bug**
Hi, so I have a dynamic `required` property on the validation. It has to be optional, so it depends on an external model value
But when the value is empty and `required: false`, `$error` seems to be set to true. This messes up the form error highlighting in my projects
So 2 cases are wrong:
1. When `$model: ""` and `required: false` ($error will show as true)
   1.a Also when `$model` is not `""`, `required` will turn to true? Why is that?
2. When `$model:""` and `required: true` ($error will show as false although it should be true, cause it is required)

**Reproduction URL**
I have a small sandbox here:
https://jsfiddle.net/2seokxmf/1/

[Vuelidate Template](https://codesandbox.io/s/vuelidate-0x-template-rxbkz)

Issues without a working fiddle are generally much harder to solve and usually take much more time to actually do it.

**To Reproduce**
Type in the textbox and toggle the checkbox

**Comment by iulianwebdev** [comment]
Any hint on how can I proceed with this?

**Comment by irsyaadbp** [comment]
Change with this, because if you want to custom validation, it must validate the value, not the this.tick

```js
validations() {
  return {
    text: {
    	required: function (value) {
          if(this.tick) return !!value
          return true
      }
    }
  }
},
```

Or if you want to add condition with required, you can use required if

```js
validations() {
  return {
    text: {
    	required: requiredIf(() => this.tick)
    }
  }
},
```

**Comment by iulianwebdev** [comment]
This was it. I was missing the requiredIf function. Thank you for taking time and clarifying this for me.
