### ISSUE TITLE
Validator 'numeric' only accepts positive integers

### ISSUE THREAD

**Issue by SirLamer** [vuelidate/vuelidate#136]
The name of the validator implies it is looking for any numeric value, including decimal and negative values. The current implementation only accepts positive integers. Either the accepted validation text should be broadened or this validator should be renamed.

Example: https://jsfiddle.net/gregpeden/hmcLdc5a/

I could provide a PR for this (fix this + provide actual integer test) if there is interest in changing it.

**Comment by Frizi** [comment]
That's true. I think having a few properly named separate validations for that should do the trick. Changing that slightly breaks the API though, but we are still at a version 0 for a reason (hopefully this will change soon). A PR would be greatly appreciated :)

**Comment by SirLamer** [comment]
I think it's fine to expect developers to combo "decimal + between/min/max" and "integer + between/min/max" for those who need it, we don't need lots of number format tests.

**Comment by Frizi** [comment]
About the number formats, remember that we are validating model. The formatting can always be taken care of on the view layer separately, so your data variable will always hold just a plain number. But that's only one of ways to to it. Your proposal seems very reasonable. 
How i see it:
- `integer`: current numeric with support for negative values, should also accept and verify data of type `Number` to be actually integer
- `decimal`: any valid number format (anything that passes parseFloat i guess)
- `atLeast`: `min => withParams({type: 'atLeast', min}, val => val >= min`
- `atMost`: `max => withParams({type: 'atMost', max}, val => val <= max`

Nothing prevent you to use the latter one with strings, like

```javascript
{
  singleChar: maxLength(2),
  minChar: atLeast('😀'),
  maxChar: atMost('😎')
}
```
because why not ¯\\\_(ツ)\_/¯

**Comment by SirLamer** [comment]
Personally I would like to copy the validation pattern set by Laravel. Using the same validation test names and input parameters has some advantages, for example implementation of the error feedback messages with localization, using the test name to perform the lookup and using any one of many "export language files to Javascript" packages with Laravel to seed the Javascript localization package from the Laravel server-side set.

https://laravel.com/docs/5.4/validation#available-validation-rules

**Comment by SirLamer** [comment]
I can't get the development environment to run in Windows 10. During "npm install" I get an error "build is not recognized as an internal or external command". This happens after the npm download is done, however when I run "npm run dev" the lint testing flips out and it seems to just give up, then I can't use the test environment. So..... kinda hard to prepare a PR, then. ;-)

**Comment by SirLamer** [comment]
Hey, so... with no change on the above I cannot really provide new validation tests to you as I intended so I am writing them and keeping them in my own project. I'd love to share them!

**Comment by samtheson** [comment]
+1 for extended numerics validation. Also, default auto-gen error messages would be nice, like how VeeValidate has them. Will see if I can make time for a PR or two, you've already done so much work on this Paweł! :+1:

**Comment by SirLamer** [comment]
Yeah I am actually preparing validation messages right now.

I have mentioned this before... but personally I would vote for the validation test names and parameter names exactly matching Laravel's validation types so that the validation tests from Laravel can be shared with Vuelidate. I do understand why this package doesn't include error messages itself, though.

**Comment by samtheson** [comment]
Small world. Doing the exact same thing!

My first guess was time constraints maybe? We're only at 0.4. Hopefully with contributions we can get it up to par with Laravel's at some point, much like how [VeeValidate has tried](http://vee-validate.logaretm.com/rules.html#available-rules).

@SirLamer Is your modified fork public?

**Comment by SirLamer** [comment]
I can't run the dev environment on this package so I am just sort of writing validation tests within my own environment. Otherwise I totally would share them.

**Comment by SirLamer** [comment]
By the way, I am using vue-i18n so validation messages I prepare will follow that convention. Maybe I'll share some code later on how I'm doing this.

**Comment by samtheson** [comment]
That'd be great. All the best!

**Comment by SirLamer** [comment]
This is super crude and work-in-progress but works...

Here are my validation messages, shared as vuelidate.php within Laravel. There are extras beyond the included default tests because I am preparing extra tests.
```php
<?php

return [

    /*
    |--------------------------------------------------------------------------
    | Vuelidate JS Language Lines
    |--------------------------------------------------------------------------
    |
    | The following language lines contain the default error messages used by
    | Vuelidate for client-side validation.
    |
    */

    'alpha'                => 'The :attribute may only contain letters.',
    'alphaDash'            => 'The :attribute may only contain letters, numbers, and dashes.',
    'alphaNum'             => 'The :attribute may only contain letters and numbers.',
    'array'                => 'The :attribute must be an array.',
    'between'              => 'The :attribute must be between :min and :max.',
    'email'                => 'The :attribute must be a valid email address.',
    'integer'              => 'The :attribute must be an integer.',
    'max'                  => 'The :attribute may not be greater than :max.',
    'maxLength'            => 'The :attribute may not be greater than :max characters.',
    'min'                  => 'The :attribute must be at least :min.',
    'minLength'            => 'The :attribute must be at least :min characters.',
    'numeric'              => 'The :attribute must be a number.',
    'required'             => 'The :attribute field is required.',
    'required_if'          => 'The :attribute field is required when :condition.',
    'required_unless'      => 'The :attribute field is required unless :condition.',
    'sameAs'               => 'The :attribute and :sameAs must match.',
    'length'               => 'The :attribute must be :length characters.',
    'size'                 => 'The :attribute must be :size.',
    'url'                  => 'The :attribute format is invalid.',
];
```

I use this package to encode Laravel language files to i18n for embedding. This is because I have to write for both English and French. If you are using one language only, you might care to find a different lookup method for validation messages.
https://github.com/martinlindhe/laravel-vue-i18n-generator

Each of my form elements is designed as a Vue component which can be collected together within larger form elements. For each form field, I pass in the Vuelidate test object as a component property called 'validation'.

I have these computed properties within the input item component:
```js
        computed: {
            hasErrors() {
                return this.validation && this.validation.$error
            },

            getErrors() {
                if (!this.hasErrors) {
                    return false;
                }

                const buffer = [];

                Object.keys(this.validation).forEach((key) => {
                    if (!key.startsWith('$') && typeof this.validation[key] === 'boolean' && !this.validation[key]) {
                        buffer.push({
                            type: key,
                            message: this.$t(
                                'vuelidate.' + key,
                                Object.assign({attribute: this.displayTitle}, this.validation.$params[key])
                            )
                        });
                    }
                });

                return buffer;
            },

            displayTitle() {
                return this.title || this.formName || null
            }
        },
```

Note the "$t()" function is from vue-i18n, so that's where you might want to stick in simpler lookup logic for your validation messages, however i18n supports messages with variables, so I just pass the "$params" object in as well as the "attribute" property I am adding myself.

Then the component template is just set up to use different CSS as a warnning when an error exists, and display the error messages when they exist.

When the the input 'blur' DOM event occurs, I fire "$touch()" on the Vuelidate object, so messages only display once the user clicks away, however you might care to do this differently such as touching the validation immediately upon every keystroke.

**Comment by SirLamer** [comment]
You'll see right away a fault condition where "displayTitle" might be null and yet passed for the 'attribute' message variable as null. So... gotta fix that. ;-)

Generally, the point is "displayTitle" is whatever the user knows to be the display name for the form field.

**Comment by samtheson** [comment]
Sweet, thanks so much @SirLamer. It's a really good starting point. If I come across anything interesting as I implement it on my end I'll let you know.

**Comment by Frizi** [comment]
@SirLamer I like your approach, but now even more as a separate thing. Keeping things consistent end-to-end is a valuable thing to have, but that's your responsibility as a developer. With Vuelidate I'm trying to not close any doors. You are free to write, use and publish your own adapter to Laravel messages and validations, and I'd be really happy to help make it more ergonomic as long as it doesn't put a bias towards a specific stack. Every library and framework has it's own convention, supporting a single specific one contradicts the initial goal.

I'm personally using Vuelidate in combination with `vue-intl` and my own FormattedMessage component (you have it in `vue-intl`s repo as a PR now). All translation strings are kept on the frontend. That's as valid approach as yours.

Now, I'd like to focus on the initial subject of this issue, the `numeric` validator. You pointed out that we could use a scheme from lavavel, but the docs simply state

> The field under validation must be numeric.

That's not very descriptive actually. Could you elaborate by providing a set of example functions, as I did previously?

**Comment by SirLamer** [comment]
I don't want Vuelidate to includes messages and stuff either, I just suggest that the naming schema for tests should follow Laravel's naming pattern to avoid duplication of validation messages. It doesn't necessarily have to include all of Laravel's test, I am just saying that when they are validating the same thing, the name ought to match. I am assuming most users will be using Laravel.

"Numeric" means any number of any kind. This includes integer and decimal numbers, even exponential format in concept though I think it's reasonable to expect the developer to know exponential format is not meant to be supported.

I have written several tests but I cannot submit them as PR because the project's dev environment does not run on my Windows development environment.

**Comment by Frizi** [comment]
I don't agree about the naming schema. I'd prefer to not change what's already established if that's the option. You can always make your own aliases if you want it like that. I simply don't want to favour Laravel above anything else in particular, even if I actually don't have anything against it.

```javascript
const necessary = required
...
validations: {
  field: { necessary }
}
```

You could actually make a library that focuses on doing exactly that - bringing a set of validators implemented in JS that closely match the ones in Laravel, including the naming convention.

Regarding the supposed numeric validator that could match exponents, what about precision and bounds? Is `1e309` a valid number if it's get "rounded" to `Infinity` in JS?

**Comment by SirLamer** [comment]
I meant to suggest that we can forgive ourselves for not expecting "numeric" to accept exponents, however it can if you want it to. If you do <input type="number"> so that Chrome imposes its own constraints, it does allow exponential notation then.

If 1e309 gets rounded to infinity, well, infinity is a number.

**Comment by Konafets** [comment]
What is the status here?

**Comment by DaniG2k** [comment]
I was also expecting

```
lat: {
  required,
  numeric,
  between: between(-90, 90)
},
lng: {
  required,
  numeric,
  between: between(-180, 180)
}
```

to accept values between (-90.0, 90.0) for latitude and (-180.0, 180.0) for longitude but indeed this only seems to accept positive integers. Would be great if it accepted decimals and negative numbers as well!

**Comment by dsbert** [comment]
@SirLamer technically `infinity` is not a `real` number, even though `isNaN(Infinity) === false` is true in javascript.

This seems to have gotten off topic - does anyone still plan to create a pull request for adding `integer` validation and expanding `numeric` validation to include positive and negative decimal numbers? If not, I might work on it.

**Comment by SirLamer** [comment]
@dsbert I think you're being a little obtuse if you're discussing my original point around the context of the meaning of infinity. ;-)

I have written the test as I described, as well as several others, however as I have reported before, the dev tools included in this package seem to be very unhappy with a Windows development environment so I cannot submit them as PRs.

**Comment by dsbert** [comment]
@SirLamer I was able to run the tests successfully on windows. Are you willing to push your changes or create a WIP pull request so I can try it?

**Comment by SirLamer** [comment]
Admittedly I last tried a long time ago, I will review this shortly.

**Comment by garhbod** [comment]
Is it just me or is this a simple solution that no body is bothering to do?

I agree with naming convention after a framework with a large user base. If someone comes from another framework they can simply do as suggested and create aliases but following/conforming to something that already exists and is widely used makes it easier/quicker to develop as you have a guide to follow

I think there is an opportunity here. We could create vanilla js validators and have vuelidate implement them.

```
export const numeric = value => { return !isNaN(value) }
export const integer= value => { return /^[0-9]*$/.test(value) }
```

Thoughts?

**Comment by samtheson** [comment]
@SirLamer Digressing, forgive me :pray:. Thought you might find [yup](https://github.com/jquense/yup) interesting, if you hadn't seen/used it already.

_Ok, carry on :) ..._

**Comment by SirLamer** [comment]
I tried the dev environment and still doesn't work on my system.

Here are the validation tests I wrote, have at it.

between.js
```js
import { req, withParams } from 'vuelidate/lib/validators/common'
import minTest from './min'
import maxTest from './max'

export default (min, max) =>
    withParams({type: 'between', min, max}, value =>
        !req(value) || (minTest(min)(value) && maxTest(max)(value))
    )
```

betweenLength.js
```js
import { req, withParams } from 'vuelidate/lib/validators/common'
import { minLength, maxLength } from 'vuelidate/lib/validators'

export default (min, max) =>
    withParams({type: 'betweenLength', min, max}, value =>
        !req(value) || (minLength(min)(value) && maxLength(max)(value))
    )
```

currency.js
```js
import {regex} from 'vuelidate/lib/validators/common'
export default regex('currency', /^-?(0|[1-9]\d{0,})(\.\d{1,2})?$/)
```

integer.js
```js
import {regex} from 'vuelidate/lib/validators/common'
export default regex('integer', /^-?\d+(?:\.?\d+)?$/)
```

length.js
```js
import { req, withParams, len } from 'vuelidate/lib/validators/common'

export default (length) =>
    withParams({type: 'length', length}, value =>
        !req(value) || len(value) === length
    )
```

max.js
```js
import {req, withParams} from 'vuelidate/lib/validators/common'

export default (max) =>
    withParams({type: 'max', max}, value =>
    !req(value) || (!/\s/.test(value) && +max >= +value))
```

min.js
```js
import {req, withParams} from 'vuelidate/lib/validators/common'

export default (min) =>
    withParams({type: 'min', min}, value =>
    !req(value) || (!/\s/.test(value) && +min <= +value))
```

numeric.js
```js
import {regex} from 'vuelidate/lib/validators/common'
export default regex('numeric', /^[\$%]?(((-?(?!0)(([0-9]{1,3})(,\d{3})*|\d+)|0)?(\.\d+)?)|[\(](((?!0)(([1-9]{1,3})(,\d{3})*|\d+)|0)?(\.\d+)?)[\)])$/)
```

primaryKey.js
```js
import { req, withParams } from 'vuelidate/lib/validators/common'
import { integer, min } from './index'

export default () =>
    withParams({type: 'primaryKey'}, value =>
        !req(value) || (integer(value) && min(1)(value))
    )
```

index.js (for my project)
```js
import between from './between'
import betweenLength from './betweenLength'
import currency from './currency'
import integer from './integer'
import length from './length'
import max from './max'
import min from './min'
import numeric from './numeric'
import primaryKey from './primaryKey'

export {
    between,
    betweenLength,
    currency,
    integer,
    length,
    max,
    min,
    numeric,
    primaryKey
}
```

**Comment by dsbert** [comment]
@garhbod 

The following does not return the expected result in all cases.

`export const numeric = value => { return !isNaN(value) }`

From https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/isNaN

```
isNaN(true);      // false
isNaN(null);      // false
isNaN('');        // false: the empty string is converted to 0 which is not NaN
isNaN(' ');       // false: a string with spaces is converted to 0 which is not NaN
isNaN(new Date());                // false
```

**Comment by garhbod** [comment]
Cheers @dsbert 
Will keep that in mind in the furture

**Comment by akhtarmunir1143** [comment]
I still don't understand, why I can't figure out the negative numbers to be detected. I have written a rule like `field` must be `numeric|min:0` I want to say it should not be negative. But still it doesn't give me error and save the negative value. 😒
