### ISSUE TITLE
Required validator treats `false` as "empty" value

### ISSUE THREAD

**Issue by petridw** [vuelidate/vuelidate#156]
In 0.5.0, commit 383f1e11f3a6a59499f750d39de5a4250b13254a, the required validator was changed to treat false as an "empty" value.

My understanding of the "required" validator is that it validates that a field is not empty. Empty to me includes things like `null`, `undefined`, empty strings, or empty arrays. `false` does not mean empty however. It is often a desired valid input, such as for radio yes/no inputs that are v-modeled to a boolean in data. As long as the user selects one option, the field is valid.

I'm curious as to the intention of this change. Not a big deal as I can roll a custom validator for this use case, but I just wanted to see if you could clarify this for me. If this change is to stay, I would suggest updating the documentation for the required validator to include that `false` is invalid. Happy to PR that.

Here's the reproduction, I'd expect clicking the "false" button to cause `$v.$invalid` to be set to `false`. However, the only way to make the form valid is to click "true".

https://jsfiddle.net/su1z053a/

Thanks!

**Comment by Frizi** [comment]
I agree it's not clear, that's an edge case and it needs documentation. Using `false` as a valid value surely isn't common, especially in comparison to checkboxes.

I'd say there is an additional validator required to fix this, but I'm not yet sure what the configuration would be.
One option would be to:
- go with current `required`
- create validator `defined = v => v !== undefined && v !== null`.

In your case `defined` would be used for the radio group value.

Second option:
- remove false check from `required` restoring previous behaviour
- create validator `checked` or `truthy` that would simply be an boolean cast `v => !!v`

I'm in slight favour of the first option, but it's hard for me to find any specific reason why that would be better. Any argument from you in either direction would be appreciated.

**Comment by shanemgrey** [comment]
I just ran into this also.  My example of false as a valid value is that I'm using radio options with true and false as the options the API uses.  But either answer is an indication that the question was answered, while it should only give the error if neither was chosen. 

Looking forward to a resolution to this.  Until then I am turning off validation for these radios.

**Comment by mokkabonna** [comment]
My background is from knockout validation, also model based.

There the required validator only checks:

- not undefined
- not null
- not empty string

In vuelidate it checks the three above and:

- not invalid date
- not empty array
- not empty object
- not false


I was surprised that it did validate that much, considering that vuelidate is model based. Personally I would have expected more fine grained control. If I want to validate an empty array I would use required and minLength:1 together.

The inclusion of date, empty array and empty object is fine though, I can live with that.

The false check really surprised me. Tons of times I want a boolean, and false is also a valid choice. I think it would be almost equally wrong to make **0** a non-valid value when using the required validator. It is a falsy number, but yet a number. Same with false, it's false but a boolean.

My opinion is to do the following:

- Remove false check from required
- Add a **equal** validator that check for **strict equality** to use when true or false is wanted. Can also be used to check for other values like numbers and object references.

This is like your second option, but using a more generic validator **equal** that I think has more use cases.

**Comment by shanemgrey** [comment]
Is there any decision on this?  @mokkabonna makes some very good points and suggestions for how to handle.

**Comment by Frizi** [comment]
I agree, it just needs some time investments to forge it into some code and tests. I'm probably going to do that eventually but it's not the highest priority ATM for me. Any PR is very welcome 🙂

**Comment by arvel** [comment]
Just encountered this with **requiredIf*.* +1 for allowing false as a valid option.

**Comment by bbugh** [comment]
This seems to have been fixed in #288

**Comment by dobromir-hristov** [comment]
Closing as it was merged into Vuelidate.
