### ISSUE TITLE
Using $each with array that contains multiple classes

### ISSUE THREAD

**Issue by DimitriosLisenko** [vuelidate/vuelidate#171]
I'm trying to use the `$each` property in `validations` with an array that has multiple classes in it - see https://jsfiddle.net/oejb3px8/3 for an example.

I can't seem to find a way to check the current element before actually creating the validation keys. For example, if I have an array like `[{ common: 'first', propertyOne: '' }, { common: 'second', propertyTwo: ''}]`, then I don't want the `propertyOne` validation to exist for the second element.

What I've managed to do so far:
1) Create the propertyOne validator anyway and use a custom validator to return true always if that class is not supposed to have that property. This is not ideal because the validation will still be present on that array element, and it can never be made $dirty.
```
$each: {
  propertyOne: {
    required: function(val, elem) {
      if (elem is a specific class) {
        return true;
      }
      return required(val); // use default vuelidate required function
    }
  }
}
```

2) This doesn't quite work because I can't access the element inside `$each` - I'm gonna write some pseudocode below to show what I would ideally like to happen:
```
function returnValidator(element) {
  if (element.constructor.type === A) {
    return { propertyOne: { required: required, minLength: minLength(4) } }
  } else if (element.constructor.type === B) {
    return { propertyTwo: { required: required, minLength: minLength(6) } }
  }
}

$each: {
  common: { required: required, minLength: minLength(8) },
  ...returnValidator(element),
}
```

Would love to hear your thoughts on this!

**Comment by Frizi** [comment]
`$each` assumes a collection of consistent type. You can use an approach i described in https://github.com/monterail/vuelidate/issues/166#issuecomment-319924309 as a workaround.

**Comment by DimitriosLisenko** [comment]
Thank you! That worked.

I'll try add this to the documentation if it's possible - would there be a workaround for the `$trackBy` option if using this?

**Comment by DimitriosLisenko** [comment]
In case anyone has the same issue with needing to use `$trackBy`, I'm currently resolving it by mapping my array of different objects (all of which have a UID parameter) - `[{ uid: x, propertyOne: p1 }, { uid: y, propertyTwo: p2 }]` - to a computed object whose keys are the uid - `{ x: { uid: x, propertyOne: p1 }, y: { uid: y, propertyTwo: p2 } }` - and creating a validation object against this new object.

https://jsfiddle.net/b5v4faqf/234/

**Comment by Frizi** [comment]
Your `$trackBy` can be a function if necessary :) It is given the object in question and the thing it returns must be unique.

https://github.com/monterail/vuelidate/blob/3baf496ce15f1cdcd5c9a8bcd1e9ee85ef0d067b/src/index.js#L308-L310

https://github.com/monterail/vuelidate/blob/3baf496ce15f1cdcd5c9a8bcd1e9ee85ef0d067b/src/index.js#L14-L18
