### ISSUE TITLE
Conditional validation with Vuelidate?

### ISSUE THREAD

**Issue by Zewkin** [vuelidate/vuelidate#222]
I have a form, where different validations can apply, depending on the parameter action, stored in VUEX store. I try this:

```javascript
data: function() {
   const validations = {
      sendToProject: {
        cardProject: {
          required,
        },
      },
      recallToBranch: {
        fioReceiver: {
          required,
        }
      }
   }
   return {
     validations,
   }
},
validations() {
  return {
    q: this.validations[this.action]  // supposed to be this.validations['sendToProject']
  }
},
computed: {
  ...mapGetters({
    action: 'action',
  }),
},
```

This actually works, but throws an error while bootstraping:

`[Vue warn]: Error in render function: "TypeError: can't convert undefined to object"`

and that error prevents non-Vue code (Bootstrap jQuery plugins initializations, etc) from execution.

How to fix? Thanks.

**Comment by Frizi** [comment]
Seems like `this.action` is not defined when validations are run first.
You can shortcut it with `if (!this.action) return {}`, that should prevent the error.

Other than that, You should not really set `this.validations` as your data if it's not going to be modified ever. Instead you could make it a `const validations` before your component definition. That way you have one less dependency and it is guareanteed to always be present.
