### ISSUE TITLE
Accessing data of a collection in a custom validation

### ISSUE THREAD

**Issue by aphilippartd** [vuelidate/vuelidate#230]
Hi,

I am currently having issues trying to perform custom validations on a collection in my data model. The JsFiddle reproducing my problem is the following: https://jsfiddle.net/b5v4faqf/467/  

The explanation of the problem/situation is below.
1) I have a set of user that can either be a Person or a Company
2) Users need to have 
     - A firstName (if person)
     - A lastName (if person)
     - A legalName (if company)
     - isCompany field that is true if it is a company and false is it is a person
3) I would want to be able to perform custom validation that is dependent on wether the user is a Person or a Company.

My question is the following, is there any way i can pass the user item (complete object or just the the related key) in the validations loop in order to use its value (and more precisely the value of isCompany) in my custom validation:
`
 validations: {
  	users: {
    	    $each: {
      	       firstName: {required},
               lastName: {required},
               legalName: {required}
             }
         }
  }
`

Thanks in advance for your help!!

**Comment by aphilippartd** [comment]
Hi, I actually found the answer to my question by digging into some other people issues and examples. In order to be able to call a custom validation (eg: for firstName) passing the current item of a collection one have to do the following:
`validations: { users: { $each: { firstName: { valid: (firstName, user) => yourCustomValidator(firstName, user) } } } }`

firstName and user can then be user in yourCustomValidator method to perform the actual validation. 

As this is not clear in the documentation, it could be useful to others to mention this point in the documentation.

Thanks!!

**Comment by sofiageo** [comment]
Thanks, your example helped me add a custom validator for a collection.

**Comment by WillTang888** [comment]
Hi I have the same issue of needing to check other attribute values on the same collection item in order to perform custom validation, Looking at the code below can you explain how **user** is the idividual component that you are passing to a custom function? It just says it is undefined when i trieds something similar. 

validations: { 
  users: { 
    $each: { 
      firstName: { valid: (firstName, **user**) => yourCustomValidator(firstName, user) } 
     } 
  } 
}
