### ISSUE TITLE
Custom validation of array

### ISSUE THREAD

**Issue by luke-hawk** [vuelidate/vuelidate#236]
This is rather a question than an issue, I guess. I would like to validate a collection of inputs using $each, so that:

 `formData.$each[index-1].input < formData.$each[index].input` returns `"$invalid" : false`  

and

`formData.$each[index-1].input > formData.$each[index].input` returns `"$invalid" : true` 

Can you give me some advice how to handle this validation? Any help highly appreciated :)

**Comment by Frizi** [comment]
Sorry but I miss much of the context in this issue. Could you provide a jsfidde with reproduction?
