### ISSUE TITLE
Validating  computed properties returning an object

### ISSUE THREAD

**Issue by bawesto** [vuelidate/vuelidate#241]
I have a problem to validate items of an object returned by a computed property.
In "real live" this object is returned via a getter from vuex, but i can reproduce it with a computed property returning a simple object.
The values are validated exaclty once at first input/blur an then stay frozen in the state of this first call $touch
Here the fiddle:
https://jsfiddle.net/vk3z6c4t/

HTML:
```
<div id="app">
  <input type="text" v-model="user.name"
    v-on:blur="$v.user.name.$touch"
    v-bind:class="{error: $v.user.name.$error, valid: $v.user.name.$dirty && !$v.user.name.$invalid}"
  >
   <input type="text" v-model="user.email"
    v-on:blur="$v.user.email.$touch"
    v-bind:class="{error: $v.user.email.$error, valid: $v.user.email.$dirty && !$v.user.email.$invalid}"
  >

</div>
```
JS:
```
Vue.use(window.vuelidate.default)
const { required, email } = window.validators

new Vue({
	el: "#app",
  data: {
  	
  },
  computed: {
    user () { return { name: '', email: '' } },
  },
  validations: {
  	user: {
    	name: { required },
      email: { required, email }
    }
  }
})
```
CSS of standard Example

**Comment by Frizi** [comment]
Data returned from computed values is not observable. You are not supposed to mutate it. The same goes to Vuex getters - you should treat them as read-only. You have vuex mutations as a mechanism to modify the state, and then the corresponding getters will be automatically updated when needed.

if you still prefer to use `v-model` with computed values, you should define two separate values for `name` and `email`, then create both `get` and `set` function for them. You will still need to store the data somewhere though.
