### ISSUE TITLE
Parent object not invalidated on child reset

### ISSUE THREAD

**Issue by ankitsinghaniyaz** [vuelidate/vuelidate#250]
I am trying to reset the child elements and expect the parent element to be in the same state.

Here is a JS fiddle for the same
https://jsfiddle.net/b5v4faqf/651/

I have the following validation:
```javascript
name: {
    firstName: { required },
    lastName: { required }
}
```

So I expect my name object to not error if both of the children are not in error state. Is there something wrong with my expectation?

**Comment by ankitsinghaniyaz** [comment]
Anyone any comments on this?

**Comment by dobromir-hristov** [comment]
This IS how it works. The example shows an invalid usage of the plugin. https://jsfiddle.net/dobromir/jqbonz0a/1/
