### ISSUE TITLE
Missing declaration for decimal and integer validators in lib/index.js

### ISSUE THREAD

**Issue by jess8bit** [vuelidate/vuelidate#256]
Hi,
 just testing 0.6.2 and ran into an issue, so just had a real quick look at /lib/validators/index.js where it seems there are missing declarations for the new decimal and integer validators.

Adding them manually solved my issue.
Like:
var _decimal = require('./decimal');
var _decimal2 = _interopRequireDefault(_decimal);
...
exports.decimal = _decimal2.default;

Sorry I didn't provide any reproduction environment.

Hope it helps though!

**Comment by jess8bit** [comment]
probably related to https://github.com/monterail/vuelidate/pull/245#issuecomment-369389789

**Comment by philpoore** [comment]
+1

**Comment by kosanr1** [comment]
This issue was resolved with #261 Please give update if you still have problem with that.
