### ISSUE TITLE
Best practice when dealing with object properties?

### ISSUE THREAD

**Issue by travisfisher** [vuelidate/vuelidate#265]
In my project, I'm passing in an object to a component that is being used to populate the form.

I can get Vue to react to the changes properly, but I can't get Vuelidate to do the same.

Any ideas?

[https://jsfiddle.net/cthbtvc9/](https://jsfiddle.net/cthbtvc9/)

**Comment by UnnoTed** [comment]
https://monterail.github.io/vuelidate/#sub-data-nesting

**Comment by bryndyment** [comment]
i'm having the same problem … my suspicion is that i'm overlooking something simple …

**Comment by sarkiroka** [comment]
> https://monterail.github.io/vuelidate/#sub-data-nesting

404

**Comment by shentao** [comment]
The docs have a different URL now.
