### ISSUE TITLE
How to check password strength in Veulidator

### ISSUE THREAD

**Issue by rubencool** [vuelidate/vuelidate#274]
I am using your vuelidate in my project for form validation. I Wanted to check 'password strength' but i could not found any validator for password strength in your vuelidator.. how can i check my password strength suggested me what to do??

**Comment by kevintruby** [comment]
Hi @rubencool  -- I posted an example of this a few months ago in another issue.

Take a look at https://github.com/monterail/vuelidate/issues/193#issuecomment-367918602
