### ISSUE TITLE
Conditionally adding validation models

### ISSUE THREAD

**Issue by DinsmoreDesign** [vuelidate/vuelidate#276]
Hi all,

I recently made the switch with Vuelidate from Vee-Validate a few weeks ago for all our apps and have been loving its flexibility so far; however, I've run across an issue that I'm not quite sure how to solve...

I've added the (primitive) example, using my real data here:

https://jsfiddle.net/80cuuagp/18/

The problem is - I'm conditionally rendering fields based on the user's input. If he or she selects "Yes" to any of the questions, a secondary fieldset will appear below it and ask for input. These fields are only required if yes is selected and they appear on the DOM (and will also have different validations, which I'm not sure how to address, either without hard-coding everything). I've tried looping through the data by making validations a function, but even though it seems to compile, it's not dynamically adding any validations based on the _question[index].value_ being set to true.

I feel like there has to be a simple way to do this, but I'm definitely overthinking it at this point. Any help would be greatly appreciated!

Thanks!

**Comment by deckar01** [comment]
Validations can be a function and the validation schema will react to dependency changes automatically.

https://monterail.github.io/vuelidate/#sub-dynamic-validation-schema
