### ISSUE TITLE
Having errors on server to show these  errors in vuelidate errors output ?

### ISSUE THREAD

**Issue by sergeynilov** [vuelidate/vuelidate#277]
Hello,
 I use vuelidate in my vue.js2.5.7 / vuetify,1.0.8 application and with validating on client with vuelidate
 I also make validation on server(php7.1/laravel5.6). If there is a way having errors on server to show these  errors in vuelidate errors output ? I mean that some validations could be done only on server(like unique name of item).
 Also I prefer to duplicate validation on server too...
 
Thanks !

**Comment by sergeynilov** [comment]
Sorry, I still search for a decision. In my Laravel 5.5/vue.js2.5 application I used vee-validate and vee-validate-laravel ( https://www.npmjs.com/package/vee-validate-laravel ) libraries. The last was usefull to work with server errors as with client vuejs errors, and i my code I wrote like :

```
        axios({
            method: ( 'post' ),
        }).then((response) => {
            ...
        }).catch((error) => {
            this.$setLaravelValidationErrorsFromResponse(error.response.data);
            ...
        });

```That was very usefull.
Is there is some similar decision for vuelidate library? Can custom methods be used here?
        
Thanks!

**Comment by ajarti** [comment]
Hi @sergeynilov, I had the same error, no way to accommodate server errors (also Laravel, but serverside is unimportant as it's just returning JSON).  In my case an email might be correct, so all client validations are OK, but the email is in use, so server FAIL. I did not want to use async custom validations .. to complex for me, so just use a simple custom validation that watches a data array called serverErrors. All I do is update the array with the field that errored on the server using the field as the key and the message as the value.  You can then just lookup the key for the errored field and get the server message.

~~~

validations : {
        email        : {
            required,
                email,
                maxLength    : maxLength(64),
                serverFailed : function(){
                         return !this.hasServerError('email');  
            }
        }
    }

~~~

The hasServerError is a simple method. (N.B. I use lodash for basic js functions)

~~~
        hasServerError(field)
        {
            return (field && _.has(this, 'serverErrors.' + field) && !_.isEmpty(this.serverErrors[field]));
        },

~~~

Then there are various reset methods that just set all serverErrors keys to '' before submission.  Not the most elegant in the world .. but it works and most of the time unless you are optimising for 100M users that's fine!

I hope that helps you and any others with a similar challenge.

**Comment by paolog22** [comment]
@ajarti this is good, i am trying to implement this with 

> vuelidate-error-extractor to place it on a single location for easy management but i am having trouble

**Comment by dobromir-hristov** [comment]
Use the https://github.com/dobromir-hristov/vuelidate-error-extractor for this. 
Save the errors in your component and feed them to the error-extractor as `:server-errors` and then you can clean them on next submit or something.

**Comment by votintsev** [comment]
Hi @dobromir-hristov .

Can you be kind and set an example?

**Comment by dobromir-hristov** [comment]
@votintsev https://codesandbox.io/s/nkqk6pzyp this is something rough.

**Comment by votintsev** [comment]
> @votintsev https://codesandbox.io/s/nkqk6pzyp this is something rough.

Awesome! Thank you!

**Comment by entermix** [comment]
@dobromir-hristov Is this package no longer supported? Is this package relevant for Vue 3 and Vuelidate 2, or is there a better solution in the new version of Vuelidate?

**Comment by dobromir-hristov** [comment]
It is not needed anymore, ass validators can have messages now. We may update it at some point, to do something else, but for now it's for v 0.x only

**Comment by entermix** [comment]
@dobromir-hristov Thanks for the answer! I would be grateful if you can show an example of how best to implement the display of external validation messages (using vuelidate 2). Unfortunately, I have not found a suitable example in the documentation.

**Comment by dobromir-hristov** [comment]
https://vuelidate-next.netlify.app/guide.html#collective-properties

This should get you started

**Comment by entermix** [comment]
I have not been able to find information on how I can add external messages that came up after the form was submitted.

Have you thought about adding some kind of native method that would allow you to add such messages?

Here's a simple example:
https://codesandbox.io/s/eager-clarke-nmz2q

If I understand correctly, there is currently no native method that can nicely solve this problem?

**Comment by dobromir-hristov** [comment]
@entermix make a new issue for Vuelidate 2, let's not spam a 2 year old thread.

There are ways, I will show you.
