### ISSUE TITLE
validate checkbox fieldset?

### ISSUE THREAD

**Issue by plweil** [vuelidate/vuelidate#290]
Has anyone come up with a custom validator or some other means to validate that a fieldset of checkboxes has at least one option checked?

**Comment by Frizi** [comment]
Could you provide an example?

**Comment by plweil** [comment]
I have a form which enables the suer to create a new project. The project has all sort of properties, some mandatory and some not. One mandatory property is "subject area". There are about ten possible subject areas. In the form I do this with a fieldset that contains ten checkboxes, each with a field name of "area". At least one of these checkboxes must be checked to be valid. With other types of fields, you can use blur to trigger touch() while the user is still filling out the form. But not so with a fieldset like this. A user can simply skip over them. I'm wondering whether the only option is to wait until the form is submitted before you can validate the "area" field.

**Comment by chrismartinez99** [comment]
Peter, have you come up with a solution for this? 

I have a similar situation - where at least one checkbox has to checked IF another condition is true.

**Comment by plweil** [comment]
Yes. Before I was relying too much on events as the only hooks. Now I'm using a combination of 1) showing an error if one or more boxes get checked and then all get unchecked (field name is "areas"):

    <div id="areas-error" class="form-group__message" aria-live="polite" v-show="$v.areas.$error">
       Please select at least one focus area.
    </div>

and 2) running a method on submit, as described in the documentation/examples. If there's an error, the form doesn't submit and the error message is displayed.

The first relies on the the field already being "dirtied"; the second explicitly runs $touch() on the field.

It sounds as though you also need a conditional validation rule, which I have not tried. I hope this helps!
