### ISSUE TITLE
Use vuelidate globally causes problem with other libs [Failed to resolve filter]

### ISSUE THREAD

**Issue by dariuszjastrzebski** [vuelidate/vuelidate#313]
I have the a problem with initial code:
```js
import Vue from 'vue';
import Vuelidate from 'vuelidate';
import VueMoment from 'vue-moment';

Vue.use(Vuelidate);
Vue.use(VueMoment);
```
In template of some component I have:
```html
<span class="created">{{ notification.created_at | moment("from") }}</span>
```
I have got error in console: 
```
[Vue warn]: Failed to resolve filter: moment
```

But if I change order 
```js
Vue.use(VueMoment);
Vue.use(Vuelidate);
```
It works and there is no errors on console.
It looks like Vuelidate doesn't work property and removes declared filters before?
```
Vue version: 2.5.16
VueMoment version: 3.2.0
Vuelidate version: 0.7.4
Webpack version: 3.12.0
```

**Comment by dariuszjastrzebski** [comment]
I resolved my issue. The problem was with wrong bootstrapping Vue to main application but it's weird that changing order on above issue causes warning in console.

**Comment by probil** [comment]
@dariuszjastrzebski You should close the issue then
