### ISSUE TITLE
How can I use vuelidate for validate date?

### ISSUE THREAD

**Issue by kedcomsci** [vuelidate/vuelidate#324]
I use [flatpickr](https://github.com/flatpickr/flatpickr) for do datepicker and I want to validate this input 

How can I do it?

**Comment by b4dnewz** [comment]
if the datepicker returns a iso string as model you can simply do this:
```js
startDate: {
        required,
        minValue: value => value > new Date().toISOString()
},
```
it will validate the date selected is not less than the moment when the input value change

**Comment by larigyn** [comment]
@b4dnewz sir, how can I used to validate a date. using this  minValue: value => value > new Date().toISOString(). I tried but still no luck

**Comment by b4dnewz** [comment]
@larigyn depends on the **value** that is returned from the datepicker you use, than compare it with another date

in your function try to log the value of value to see what it is:
```js
minValue: value => {
  console.log(value)
  // compare value with another date or iso string
}
```

**Comment by kgrosvenor** [comment]
could mix with moment and possible return a boolean? 
//yyyy-mm-dd
var date = moment(value);
return date.isValid();

**Comment by wooooodward** [comment]
You can create a [custom validator using the `withParams` helper](https://vuelidate.js.org/#sub-props-support).

```
import { helpers } from 'vuelidate/lib/validators'
export default date =>
  helpers.withParams(
    { type: 'minDate', min: date },
    value => !helpers.req(value) || value >= date
  )
```

Usage: 
```
date: {
  minDate: minDate(new Date().toISOString().substring(0, 10))
}
```

**Comment by bofcarbon1** [comment]
Reflecting back on date validation in C#.NET, Java or even Angular I always seemed to need a customized validation that returned a boolean value something like 'isValidDate'. Reusable functions for all the exhaustible combinations of date validation scenarios there can be.  Keep things simple at the Vuelidate method level. I was hoping that options minValue or maxValue would be able to automatically convert a validate of say '10-05-2020' and compare it.  After all my simple validation was that a date of birth be at least 1 day less than the current date. If you already have a robust set of date functions use them.

**Comment by slavyanofil** [comment]
_//With using helpers and CompositionAPI:_

```
const d = new Date();
    
const mustBeValidDate = helpers.withParams(
        {type: 'mustBeValidDate'},
        (value: string) => !helpers.req(value) || moment(value)
            <= moment(new Date(d.getFullYear() - 5, d.getMonth(), d.getDay()))
    )

 const rules = {
...
      date: {
        required,
        mustBeValidDate
      }
 }
```
