### ISSUE TITLE
Collection error summary

### ISSUE THREAD

**Issue by pareeohnos** [vuelidate/vuelidate#325]
Forgive me if I've missed something obvious in the docs but it would be really useful to have a more detailed breakdown than just `$anyError` on a collection's $each object. 

As an example, I'm working on a form for creating invoices, which consists of a few normal fields and then a list of line items, each of which contain a number of other fields. My validations looks a bit like this

    validations: {
      invoice: {
        lineItems: {
          $each: {
            quantity: {
              required,
            },
          },
        },
      },
    }

The validations are working just fine, but due to the line items being in a table, I don't particularly want to render inline errors for each cell of each row. This would be messy. Instead, what I want to do is have a summary alert above the table describing the errors.

Currently, from what I can gather I would need to loop through `$v.invoice.lineItems.$each` and for each one, grab the `quantity` validator and check if it is valid or not. Then if one of these is invalid, display my errors. 

Instead what would make this a lot nicer to work with, would be a breakdown of which validators have failed anywhere in the collection. So something like

    $v.invoice.lineItems.$each.quantity.$anyError

This would allow me to display the error without checking through each line item for an invalid input.

Sorry of this doesn't make any sense or is similar to another issue

**Comment by downace** [comment]
Maybe I misunderstood you intentions, but you can just use `$v.invoice.lineItems` props to check the entire collection state (e.g. `$v.invoice.lineItems.$invalid` or `$v.invoice.lineItems.$anyError`)

**Comment by pareeohnos** [comment]
Yeah I can get the `$anyError` from the line items themselves, but that doesn't tell me which properties specifically within the line items has failed validation, just that some property, somewhere in one of the children there is a validation error. I then have to loop over each child and find out which one it is.

What I'm proposing would be similar to the `$anyError`, but rather than just on the lineItems, it would be on each of the possible properties of any child within that. So `lineItems.$each.quantity.$anyError` would let me know that there is an error on the quantity field on one of the line items. This way, I can then simply check for this to display a single error about the quantity being required

**Comment by downace** [comment]
IMO, this use case is quite specific and I doubt that developers will implement it: it's more common to show error near related field.

You can use something like this as a workaround:

```javascript
quantityRequired() {
  return this.invoice.lineItems.some((v, i) =>
    !this.$v.invoice.lineItems.$each.$iter[i].quantity.required
  );
}
```

With [Lodash](https://lodash.com/docs) (AFAIK, `$iter` is not a real array, so it doesn't contain methods like `some`):

```javascript
quantityRequired() {
  return _.some(this.$v.invoice.lineItems.$each.$iter, v => (
    !v.quantity.required
  ));
}
```

More abstract:

```javascript
function collectionPropInvalid(collection, prop, validator) {
  return _.some(collection.$each.$iter, v => (
    !v[prop][validator]
  ));
}

quantityRequired() {
  return collectionPropInvalid(this.$v.invoice.lineItems, 'quantity', 'required');
}
```

Even more abstract (possible nested items props):

```javascript
function collectionPropInvalid(collection, prop, validator) {
  return _.some(collection.$each.$iter, v => (
    !_.property(propPath)(v)[validator]
  ));
}

quantityRequired() {
  return collectionPropInvalid(this.$v.invoice.lineItems, ['quantity'], 'required');
}
```

**Comment by pareeohnos** [comment]
I agree it's definitely not the most common scenario, but in this case I can't display the error inline with the field. I mean, I could, but there's no space (it's a table) so it would be pretty hideous. I do highlight the cells but just want the summary.

I have got it working, although a little more involved than your example

```javascript
const lineItems = this.v[this.modelName].lineItems;// eslint-disable-line prefer-destructuring
const lineItemValidations = lineItems.$each.$iter;
const hasError = val => val.$anyError;
const lineItemsWithErrors = values(pickBy(hasError, lineItemValidations));

if (isEmpty(lineItemsWithErrors)) { return []; }

const validationPredicate = (val, key) => !startsWith('$', key);
const errors = lineItemsWithErrors.reduce((result, lineItem) => {
  const validations = pickBy(validationPredicate, lineItem);
  const assignError = (value, key) => {
    if (!result[key]) { result[key] = {}; }
    const statuses = pickBy(validationPredicate, value);
    forEachObjIndexed((valStatus, valKey) => {
      if (value.$error && !result[key][valKey]) {
        result[key][valKey] = valStatus;
      }
    }, statuses);
  };
  forEachObjIndexed(assignError, validations);
  return result;
}, {});

return errors;
```

This gives me a list of all validation errors within the nested list, which I can then display in the view.

Since writing this however, I came across the library (vuelidate error extractor)[https://github.com/dobromir-hristov/vuelidate-error-extractor] which does the bulk of what I needed here, so if it's not something that the developers would consider adding to vuelidate itself, then it's not the end of the world :)

**Comment by dobromir-hristov** [comment]
We may add this at a later phase when we release the new version. For now use the extractor.
