### ISSUE TITLE
$dirty spread in wrong direction

### ISSUE THREAD

**Issue by telran** [vuelidate/vuelidate#328]
Hello,
I have built a form which has several fields and these also have more areas.

Example:
Form {
  field1,
  options: {
    fieldA,
    fieldB,
  }
}

For example, editing fieldA calls $touch on this field. FieldA is thus "dirty" but options and form are "clean". Why?! The Submit button can not be deactivated on !$v.$dirty.

Solution: Call $touch with a parameter 'child' or 'parent' to determine in which direction the value should spread. This does not change the previous behavior.

PS: $valid spread in correct direction.

Thx

**Comment by shentao** [comment]
Thanks for the feedback. We will try to take it into consideration during the rewrite.
