### ISSUE TITLE
check  checkbox validation vuelidator

### ISSUE THREAD

**Issue by rubencool** [vuelidate/vuelidate#332]

**Comment by rubencool** [comment]
I am using Vue.js and I am new on it. I am currently working on validation. I had used vuelidate as my validation library. I had successfully done form validation, but trouble came when I had to check validation for check box.

How can I check validation for check box? Also, I had used bootstrapvue to display check box.

**Comment by ZjanPreijde** [comment]
The changed  required, now false is also a valid value.
If you want to make sure checkbox is checked, you can use 
`myCb : { sameAs: sameAs( () => true ) }`

**Comment by ghodgey** [comment]
Thanks @ZjanPreijde  this helped me!
My full solution:

<div class="input inline" :class="{invalid: $v.terms.$invalid}">
          <input type="checkbox" id="terms" @change="$v.terms.$touch()" v-model="terms">
          <label for="terms">Accept Terms of Use</label>
</div>
validations: {
terms: {
        sameAs: sameAs( () => true )
      }
}

**Comment by reilue** [comment]
Hi, i've to reopen cause checkbox validation doesn't work in 0.7.4. I made a regression until the last working version, that is 0.6.2

Version not working.
```
    "vuelidate": "^0.7.4",
```

Last Version working 

```
    "vuelidate": "^0.6.2",

```

**Comment by kaleb4eg** [comment]
The same for me... `require` validation is not working anymore for boolean value and workaround from @ZjanPreijde working good but looks too cumbersome for such simple validation.

**Comment by kaleb4eg** [comment]
as I see here https://github.com/monterail/vuelidate/pull/317 is implemented validator for boolean values.

**Comment by SimonFricker** [comment]
+1

**Comment by chaderenyore** [comment]
> sameAs: sameAs( () => true )

You must be using the same Video tutorial By max that I'm Currently using. the solution works Perfect for me too

**Comment by bogdaniculae** [comment]
For me, it worked like this.

 `terms: {
        sameAs: sameAs(true)
 }`
