### ISSUE TITLE
validation to check that atleast 1 field cannot be null

### ISSUE THREAD

**Issue by HellzGamer** [vuelidate/vuelidate#337]
Hi guys, This issue might be simple but i am relatively new to using this library. 
At the moment this is the validation i have for 3 fields. My question is how can i make the foreignIdNum field to be required only if idNumber and passpnumber are null/empty

Code 
Example.js
import {required} from 'vuelidate/lib/validators'

data(){
return{
model: {
              idNumber: "",
              passpNum: "",
              foreignIdNum: ""
           }
      }
},

Validations: {
              model: {
                             idNumber: {
                                                 required
                                               },
                             passpNum: {
                                                  required
                                                 },
                        foreignIdNum: {
                                                  required
                                                }
                            }
                      }

**Comment by space87** [comment]
You could use the dynamic validation option which is https://monterail.github.io/vuelidate/#sub-dynamic-validation-schema

**Comment by kosanr1** [comment]
You can use `requiredIf` validator https://monterail.github.io/vuelidate/#validators
```
        required: requiredIf(function (v) {
        	return v.idNumber === '' && v.passpNum === ''
        })
```
