### ISSUE TITLE
Error messages generation

### ISSUE THREAD

**Issue by GerardRodes** [vuelidate/vuelidate#339]
It would be great to have inside each field a list of a generated error strings or keywords
Something like this:

```javascript
Vue.prototype.$errors = function (fieldName, i18nName) {
  const context = this.$v[fieldName]
  const errors = []

  if (context.$error) {
    for (const validatorName in context.$params) {
      if (!context[validatorName]) {
        errors.push(
          i18n.t(`validations.errors.${validatorName}`, {
            ...context.$params[validatorName],
            fieldName: i18n.t(`validations.fields.${i18nName || fieldName}`)
          })
        )
      }
    }
  }

  return errors
}
```

**Comment by dobromir-hristov** [comment]
Use the https://github.com/dobromir-hristov/vuelidate-error-extractor for this for now.

**Comment by scniro** [comment]
This should be folded into the main project. @dobromir-hristov your work looks great, have you through about contributing back here with the feature? Kind of a smell to pull your effort as a dep to do something fundamental: tell me all of my errors... Can yourself, @NataliaTepluhina or @GerardRodes re-open this?
