### ISSUE TITLE
Passing validation requirements to parents

### ISSUE THREAD

**Issue by foustcg** [vuelidate/vuelidate#342]
I am trying to make a library of reusable form components using Vuelidate.  This fiddle shows my basic approach:
https://jsfiddle.net/0thdsr41/

As you can see, I am placing all form data and validation requirements in the root component.  Then I pass each child component a validation record.  The child component can bind to $model to update the data and can display error messages in a manner appropriate for that child.  In the example I made two different instances of the `text-input` component, each with its own validation logic.

For a text input, placing all validation logic in the parent works well.  However, I would like to allow some components to add their own validation logic to the parent.  In the example I have an `email-input` component.  However, as you can see, using this component requires both adding the `email-input` component to the form as well as adding the `email` validator to the validation specification.  What I would like is that simply adding the `email-input` component to the form somehow also adds the `email` validator to the validation specification.  That way I could simply use the `email-input` component without having to remember to add the correct validation every time.

Email validation is a very simple example and arguably doesn't even need its own component, but more complicated components may have more complicated validation requirements.  For example, a date range component may have two inputs that both need to be valid dates, and the first one needs to come before the second one.  Or an address component may have several different inputs, each with its own validation requirements.  I would like to avoid having to re-enter these validation requirements every time I use the component.

As of yet I have found no good way to combine validation requirements from multiple sources.  Any help would be appreciated.

**Comment by foustcg** [comment]
A comment after more consideration:  It would be nice if there was a way to modify the validation requirements using `$v`, similar to the way I can modify the data using `$v.$model`.  If I could also modify the validation requirements, using, say, `$v.$rules`, then I could give `$v` to a child component and the child component could (1) check the validation results using, e.g., `$v.$error` and `$v.dirty`, (2) modify the data using `$v.$model`, and (3) modify the validation rules using `$v.$rules`.

**Comment by shentao** [comment]
This might not be something to be implemented in this line of releases, but we’re thinking about a rewrite of the library. One of the ideas that we have is to make it possible for the parent to collect all validation results of all of its child components, even if the rules were declared by the children.
Hopefully, this would allow solving the problem you described, though in a slightly different way.
Closing this, since we’re now working on cleaning the issue list.
