### ISSUE TITLE
minLength(1) validates true empty array

### ISSUE THREAD

**Issue by romankierzkowski** [vuelidate/vuelidate#343]
minLength(1) must be used with required otherwise minLength(1) validates true empty array:

How to reproduce:
https://jsfiddle.net/b5v4faqf/4979/

Expected behaviour:
Setting minLenght(1) should make empty array $v.array.minLength == true.

Current behaviour:
$v.array.minLength should be false for empty array.

**Comment by OCJvanDijk** [comment]
Most built-in validators return true for 'empty' values. This is so you can separately specify if a value is required or not. Maybe an e-mail is not required but once you fill one in it has to be valid. For arrays I can't immediately think of an obvious example like that but it still works the same way. So add a 'required' validator to "array" in your example and it works.
