### ISSUE TITLE
How would Vuelidate work with custom FormInput components?

### ISSUE THREAD

**Issue by domagoj03** [vuelidate/vuelidate#354]
Is there any natural way to handle validation with vuelidate on custom components that contain input field but are not directly responsible for handling model data. For example, a multiple custom components which contain input fields are handled by parent component which is also responsible for model data. 

Here is a general example of what I'm asking: 
https://repl.it/@domagoj03/DefinitiveExemplaryNetworks

Using vuelidate's `validations` key in parent component doesn't seem to work, so I guess I would have to pass some sort of options from parent component to each custom input component which would be used in child component to handle validations. 

Using vuelidate for this example from Basic Usage examples results in form not returning any errors. If vuelidate is using some sort of events to handle change in input field, perhaps it would be possible to emit them from custom input component? Just like there's an example with @blur and @input events.

**Comment by matteplus** [comment]
Yes, you should basically pass each validator as prop to the child component, then in the child component call the $touch method when it best suits you. Here you can find a better explanation: https://vuejsdevelopers.com/2018/08/27/vue-js-form-handling-vuelidate (look at "Breaking down large forms into child components")
