### ISSUE TITLE
Dynamic Inputs Not Validating

### ISSUE THREAD

**Issue by jeremyrambo** [vuelidate/vuelidate#356]
I do apologize if this is a duplicate, but I have been fighting this issue all morning and scouring the internet for solutions.

**HTML**
```
<div class="chemical three columns" :key="object.key" v-for="object in waterReportReadings">
	<div class="water-report-item" :class="waterReportClass( object )">
		<input type="text" :state="!$v.report.readings[object.key].$invalid" 
				v-model.trim="$v.report.readings[object.key].$model" 
				@blur="$v.report.readings[object.key].$touch()"
				autocomplete="off" :placeholder="object.unitOfMeasure"/>
	</div>
</div>
```

**JS**
```
		data () {
			return {
				showModal: false,
				report: {
					source: 'retailer',
					author: '',
					type: 'manual',
					readings: {}
				}
			};
		},
	
		validations () {
			const validations = {
				report: {
					readings: {
					}
				}
			};

			_.each( this.waterReportReadings, wrr => {
				validations.report.readings[wrr.key] = {
					decimal,
					between: between( 0, 1000 )
				};
			});
			console.log( 'water report ready', validations);
			return validations;
		},
```

The validations appear to be correct.

I also have a simple snippet in the HTML:

```
Invalid: {{$v.$invalid}} {{ $v.report.readings['TH']}}
```

When the page initially renders the HTML logging outputs:
```
Invalid: false { "decimal": true, "between": true, "$invalid": false, "$dirty": false, "$anyDirty": false, "$error": false, "$anyError": false, "$pending": false, "$params": { "decimal": { "type": "decimal" }, "between": { "type": "between", "min": 0, "max": 1000 } } }
```

This lets me think that the validation is setup correctly.  However, if I type `2000` into the input (which should violate the `between` validator, I get the following:

```
Invalid: false { "decimal": true, "between": true, "$model": "2000", "$invalid": false, "$dirty": true, "$anyDirty": true, "$error": false, "$anyError": false, "$pending": false, "$params": { "decimal": { "type": "decimal" }, "between": { "type": "between", "min": 0, "max": 1000 } } }
```

So the `$model` is updating, but it appears the validations themselves are not running.  Any insight you can provide would be wonderful.  Including if this just isn't possible out of the box.

Thanks in advance!

**Comment by alekseyboyko** [comment]
+1
I have the same problem.

**Comment by Sweetyy** [comment]
@jeremyrambo did you find any solution for that by chance please ?

**Comment by kosanr1** [comment]
You should declare in data those readings, for example
```
data () {
  return {
    showModal: false,
    report: {
      source: 'retailer',
      author: '',
      type: 'manual',
      readings: {
        TH: ''
      }
    }
  };
},
```
or add it dynamically in _.each
```
...
_.each( this.waterReportReadings, wrr => {
  validations.report.readings[wrr.key] = {
    decimal,
    between: between( 0, 1000 )
  };
  this.$set(this.report.readings, wrr.key, '')
});
...
```

**Comment by krugerpl** [comment]
I have the same problem. Validation is not working with @blur="$v.form.[field].$touch()" but after call this.$v.form.$touch() @blur validation works as it should.

**Comment by dietrichg** [comment]
This is still not working. It just randomly stopped working in my production application.

**Comment by jack1012t** [comment]
@dietrichg @krugerpl did you solve this?  I have the same issue.  

this works: 

`this.$v.form.configurationFields.dynamicField_sellerId.$touch()`

and this does not: 
`
element = 'configurationFields.dynamicField_sellerId'
this.$v.form[element].$touch()
`

**Comment by jbmikk** [comment]
I was having the same problem and I found a workaround.

I used a dynamic component I build each time the list of inputs changes. So when the fields changes I create a new component with a new data object and a new validations config.

From vuelidate's point of view the model never changes, because a whole new component is created with static data. When the data needs to change, a new component is created using the new data.

So I have a wrapper component that manages the data, and dynamically creates a child component.

This is a simplified version of the code just to show the idea, it does not work.

    <template>
      <component v-bind:is="component" @global="onGlobal" :help="help">
      </component>
    </template>

    <script>
    import { required } from 'vuelidate/lib/validators';

    let formTemplate = `
      <form>
        <div class="form-group" v-for="(field, name) in fields">
           **RENDER INPUTS HERE**
        </div>
      </form>
    `;

    function buildComponent(fields) {
      return {
        template: formTemplate,
        data: function() {
          return {
            fields: {
              ...fields
            }
          };
        },
        validations: function() {
          let v = {
            fields: { }
          };
          for(var i in fields) {
            v.fields[i] = {
              value: {
                // Or whatever you want to validate
                // can be different for each field
                required
              }
            }
          }
          return v;
        }
      };
    }

    export default {
      data: function() {
        return {
          data: {
            // Dynamic data
          },
          component: null
        };
      },
      watch: {
        data: function(inputs) {
          let fields;
          // Define your fields
          this.component = buildComponent(fields);
        }
      }
    }
    </script>

**Comment by Jasecharloote** [comment]
I also meet this problem.Of course, I dynamically added parameters to component data() declaration area without declaring them before. So is there some solutions to solve this problem?

**html like this:**
`<b-form inline ref="userDetailForm" v-if="loading===false">
      <b-form-group class="col-6" v-bind:key="index" label-size="sm" label-cols-sm="12" v-for="(field,index) in userFields" label-cols-lg="12" :label="field.required?'* '+field.label+':':field.label+':'" :label-for="`userDetail${field.key}`">
        <b-form-input v-if="field.config.type==='input' && field.config.required" size="sm" @input="input(field.key)" :state="!$v.info[field.key].$invalid" :id="`userDetail${field.key}`" :aria-describedby="field.key+'-feedback'" v-model="info[field.key]" :readonly="readOnly(field.key)"></b-form-input>
        <b-form-input v-if="field.config.type==='input' && !field.config.required" size="sm" @input="input(field.key)" :id="`userDetail${field.key}`" v-model="info[field.key]" :readonly="readOnly(field.key)"></b-form-input>
        <model-select v-if="field.config.type==='select'" :id="`userDetail${field.key}`" class="form-control form-control-sm" v-dictType="field.config.dic" :options="dicData[field.config.dic]?dicData[field.config.dic]:[]" v-model="info[field.key]" placeholder="select item"></model-select>
        <b-popover v-if="field.config.required" :target="`userDetail${field.key}`" title="" :disabled.sync="disabledSync[field.key]" :show.sync="showSync[field.key]" triggers="focus" variant="danger" :content="field.invalidTip"></b-popover>
      </b-form-group>
      <span style="word-wrap: break-word;width:100%" v-html="show$v">
      </span>
    </b-form>`

**scripts like this:**
`validations() {
    if (this.mode === 'add') {
      console.info('add--validations')
      return {
        info: {
          email: {
            required,
            email
          },
          phoneNumber: {
            required
          },
          firstName: {
            required
          },
          lastName: {
            required
          }
        }
      }
    } else {
      return {
        info: {
          phoneNumber: {
            required
          },
          firstName: {
            required
          },
          lastName: {
            required
          }
        }
      }
    }
  },
  data() {
    return {
      show$v: {},
      showSync: {},
      disabledSync: {},
      loading: false,
      dicData: {},
      info: {
        enabled: true,
        sysRoleName: 'ROLE_USER'
      },
      options: {
        format: 'YYYY-MM-DD HH:mm:ss',
        useCurrent: false,
        // locale: 'zh-cn',
        tooltips: {
          selectTime: ''
        },
        icons: {
          time: 'far fa-clock',
          date: 'far fa-calendar',
          up: 'fas fa-arrow-up',
          down: 'fas fa-arrow-down',
          previous: 'fas fa-chevron-left',
          next: 'fas fa-chevron-right',
          today: 'fas fa-calendar-check',
          clear: 'far fa-trash-alt',
          close: 'far fa-times-circle'
        }
      }
    }
  },`

**Comment by kosanr1** [comment]
@Jasecharloote How did you dynamically added parameters to component data() ? Did you used `$set`? https://vuejs.org/v2/api/#Vue-set

**Comment by Jasecharloote** [comment]
@kosanr1 Firstly,thanks a lot for your suggestion.Luckily, this morning, I tried to use `$set` to set parameters,and it works.
Here is my code:
```
var obj = {};
Object.assign(obj,this.info);
Object.assign(obj,this.item);
this.$set(this,"info",obj);
```

**Comment by Roywcm** [comment]
I'm having the same issue. Also tried to use $set, but still not working?

**Comment by webmint** [comment]
Thanks about $set - worked for me

**Comment by Wankishh** [comment]
Hi Guys, I had the same problem like 2 hours ago, fixed it with $each, validations and other kinds of stuff just worked perfect, when you add a dynamical data to the array, just add one more property which you'll validate. if you need help just pm on email.

**Comment by jeremyrambo** [comment]
Hello everyone, thanks for all the feedback and I apologize for sorta mic dropping this.  @Wankishh was right, using the `$each` has resolved the problem.

**Comment by rafaelbdb** [comment]
@jeremyrambo How exactly did you use $each to solve the problem?

**Comment by wfaguy** [comment]
@jeremyrambo, I have the same issue, would still know your fix.  Not understanding your reference to "$each".
tx
