### ISSUE TITLE
Unexpected $invalid state when testing nested data with jest

### ISSUE THREAD

**Issue by andMayer** [vuelidate/vuelidate#359]
A snippet of the component can be found here: https://jsfiddle.net/k5mh6sn4/1/

The validation works without any problems when entering different values.
However, testing the component with jest leads to some unexpected results.

```
import { mount } from '@vue/test-utils'
import LoginForm from '@/components/login/login.vue'

describe('LoginForm.vue', () => {
  const wrapper = mount(LoginForm)

  describe('submit()', () => {
    beforeEach(() => {
      wrapper.vm.credentials.id = '01234'
      wrapper.vm.credentials.pw = 'foo'
      wrapper.vm.$forceUpdate()
    })

    it('button enabled', () => {
      expect(wrapper.vm.$v.credentials.id.$invalid).toBe(false)   // passes
      expect(wrapper.vm.$v.credentials.pw.$invalid).toBe(false)   // passes
      expect(wrapper.vm.$v.credentials.$invalid).toBe(false)      // expected: false, received: true
    })
  })
})
```

**Comment by 3tasker1** [comment]
Hi there, is there any update on this at all? I'm having an identical issue?

Thanks
Chris

**Comment by shentao** [comment]
Is this still an issue? Which version of Vue are you running?

**Comment by RyanAtViceSoftware** [comment]
@shentao can we reopen this issue? I'm having what seems to be the exact same problem. Here's the output of writing out my `$v.myModel`.

```javascript
{
  "first_name": {
    "required": true,
    "$model": "first name",
    "$invalid": false,
    "$dirty": true,
    "$anyDirty": true,
    "$error": false,
    "$anyError": false,
    "$pending": false,
    "$params": {
      "required": {
        "type": "required"
      }
    }
  },
  "last_name": {
    "required": true,
    "$model": "last name",
    "$invalid": false,
    "$dirty": true,
    "$anyDirty": true,
    "$error": false,
    "$anyError": false,
    "$pending": false,
    "$params": {
      "required": {
        "type": "required"
      }
    }
  },
  "maiden_name": {
    "required": true,
    "$model": "madien name",
    "$invalid": false,
    "$dirty": true,
    "$anyDirty": true,
    "$error": false,
    "$anyError": false,
    "$pending": false,
    "$params": {
      "required": {
        "type": "required"
      }
    }
  },
  "email": {
    "required": true,
    "email": true,
    "$model": "first@name.com",
    "$invalid": false,
    "$dirty": true,
    "$anyDirty": true,
    "$error": false,
    "$anyError": false,
    "$pending": false,
    "$params": {
      "required": {
        "type": "required"
      },
      "email": {
        "type": "email"
      }
    }
  },
  "social_security": {
    "required": true,
    "numeric": true,
    "minLength": true,
    "maxLength": true,
    "$model": "4443322222",
    "$invalid": false,
    "$dirty": true,
    "$anyDirty": true,
    "$error": false,
    "$anyError": false,
    "$pending": false,
    "$params": {
      "required": {
        "type": "required"
      },
      "numeric": {
        "type": "numeric"
      },
      "minLength": {
        "type": "minLength",
        "min": 10
      },
      "maxLength": {
        "type": "maxLength",
        "max": 10
      }
    }
  },
  "confirm_social_security": {
    "sameAsSocialSecurity": true,
    "maxLength": true,
    "$model": "4443322222",
    "$invalid": false,
    "$dirty": true,
    "$anyDirty": true,
    "$error": false,
    "$anyError": false,
    "$pending": false,
    "$params": {
      "sameAsSocialSecurity": {
        "type": "sameAs",
        "eq": "social_security"
      },
      "maxLength": {
        "type": "maxLength",
        "max": 10
      }
    }
  },
  "date_of_birth": {
    "required": true,
    "$model": "2016-10-15T05:00:00.000Z",
    "$invalid": false,
    "$dirty": true,
    "$anyDirty": true,
    "$error": false,
    "$anyError": false,
    "$pending": false,
    "$params": {
      "required": {
        "type": "required"
      }
    }
  },
  "$model": {
    "first_name": "first name",
    "last_name": "last name",
    "maiden_name": "madien name",
    "email": "first@name.com",
    "social_security": "4443322222",
    "confirm_social_security": "4443322222",
    "date_of_birth": "2016-10-15T05:00:00.000Z",
    "prefix": "",
    "suffix": "",
    "prefixList": [
      "Mr",
      "Mrs",
      "Ms"
    ],
    "suffixList": [
      "I",
      "II",
      "III",
      "IV"
    ]
  },
  "$invalid": true,
  "$dirty": true,
  "$anyDirty": true,
  "$error": true,
  "$anyError": true,
  "$pending": false,
  "$params": {
    "first_name": null,
    "last_name": null,
    "maiden_name": null,
    "email": null,
    "social_security": null,
    "confirm_social_security": null,
    "date_of_birth": null
  }
}
```

Note that each property is showing `"$invalid": false`,  `"$anyError": false`, and `"$error": false` but that the parent object is showing true for all these properties.

Here's the configuration

```javascript
  validations: {
    general_informations_form: {
      first_name: {
        required
      },
      last_name: {
        required
      },
      maiden_name: {
        required
      },
      email: {
        required,
        email
      },
      social_security: {
        required,
        numeric,
        minLength: minLength(10),
        maxLength: maxLength(10)
      },
      confirm_social_security: {
        sameAsSocialSecurity: sameAs('social_security'),
        maxLength: maxLength(10)
      },
      date_of_birth: {
        required
      }
    }
  },
```

**Comment by dobromir-hristov** [comment]
@RyanAtViceSoftware I just tried with your setup and it worked. Create a jsfiddle or codepen, showing your issue and I can take another look.

**Comment by RyanAtViceSoftware** [comment]
@dobromir-hristov 

Here's a repository that recreates the issue. The readme should have all the details you need.

https://github.com/RyanAtViceSoftware/vuelidate-test-problem

Thanks!

**Comment by RyanAtViceSoftware** [comment]
@shentao @dobromir-hristov Is there a way to get this issue reopened based on my reproduction above?

**Comment by dobromir-hristov** [comment]
Hey. I just downloaded and tried it, works pretty good here. Vuex action gets busted when not invalid, but thats minor detail.

![image](https://user-images.githubusercontent.com/9863944/70134027-e9fc9380-168f-11ea-9762-fe9eb972b370.png)

![image](https://user-images.githubusercontent.com/9863944/70134102-0c8eac80-1690-11ea-97eb-80b77b6600ad.png)

**Comment by RyanAtViceSoftware** [comment]
@dobromir-hristov Thanks for looking into this but that's not the issue. This issue is about vueliedate in jest tests, not in the browser in the same way that @andMayer described above. If you follow the guidance that I put in the read me of the repo above (copied below for convenience) you should easily be able to reproduce the issue.

> To reproduce the problem **run the test** and you will **see that generalInformationForm.vm.$v.$invalid is true when we would expect it to be false** as the form is valid. Below is the output is of generalInformationForm.vm.$v and as you can see all the child properties are showing "$invalid": false but the top level is showing "$invalid": true.

If we can use this library in our tests then it looses most of it's value.

**Comment by dobromir-hristov** [comment]
@RyanAtViceSoftware because you are using watchers. Just mount with `sync:false` and your tests pass. https://vue-test-utils.vuejs.org/api/options.html#sync

**Comment by RyanAtViceSoftware** [comment]
@dobromir-hristov thanks again but I'm not seeing the sync options on the link you provided.

When I google for the option I found this issue saying that it was removed. 

https://github.com/vuejs/vue-test-utils/issues/1137

Am I missing something? I'm not clear on the way forward.

**Comment by dobromir-hristov** [comment]
It's there and is set to true by default for now. When you mount, pass a sync: false parameter

`mount(Component, { ...options, sync: false })`

**Comment by RyanAtViceSoftware** [comment]
@dobromir-hristov that worked, thanks a ton man! is there a button to buy someone a beer on this thing?

**Comment by dobromir-hristov** [comment]
Glad I could help :)

Well if you want to help the project, you can check the main page on how to contribute, otherwise here is my ko-fi link, you know what to do there :) https://ko-fi.com/dobromir_hristov

**Comment by RyanAtViceSoftware** [comment]
Hadn’t heard of kofi but that is perfect thanks!
