### ISSUE TITLE
'required' is not exported

### ISSUE THREAD

**Issue by entwicklerRepo** [vuelidate/vuelidate#361]
anyway that you can explain how to exactly setup vuelidate, as right now seems that with bundling it's not possible to run it. 
seems that vuelidate is totally separate thing from validators and I'm not getting how to get it work. how to do import { required } from 'vuelidate/lib/validators' if validators are based within node_modules folder, even if I include full path I'm getting this error:
[!] Error: 'required' is not exported by node_modules/vuelidate/dist/validators.min.js
101: import {required} from 'node_modules/vuelidate/dist/validators.min.js';

Thanks in advance

**Comment by carlosriveros** [comment]
hey, were you able to solve this issue?
