### ISSUE TITLE
Console error after Jest test finishes: Cannot find $error of undefined from nested object in an array.

### ISSUE THREAD

**Issue by cshomo11** [vuelidate/vuelidate#362]
Hi,

I'm running Jest tests on a Vue component using Vuelidate and I run into an odd issue where the test is passing as expected but when the test completes I get a console error.
```
[Vue warn]: Error in render: "TypeError: Cannot read property '$error' of undefined"
```

I have an array of objects that looks like this.
```javascript
validations: {
     warnings: {
         $each: {
             rationale: {
                 required
             }
         }
     }
 }
```
So each object in the array has a rationale property that must be a string before the validation passes. I use a computed in the component to check each object for errors then I display an error count message. 
That looks like this.
```javascript
   get rationaleWarningsErrorCount() {
        let errorCount: number = 0;
        let warningCount: number = this.warnings.length;
        let warnings = <Validation>this.$v.warnings;

        for(let i = 0; i < warningCount; i++){
            if (warnings.$each[i].rationale.$error){ 
                errorCount++; 
            }
        }

        return errorCount;
    }
```

My Jest test looks like this. 
```javascript
test("rationaleWarningsErrorCount will be 1 required errors when 1 warnings are present", () => {
    comp.setData({
        warnings: [{
            interactions: [message: "This is a test warning", rationale: ""}]
        }]
    });
    comp.vm.$v.warnings.$touch();
    expect(comp.vm.rationaleWarningsErrorCount).toBe(1);
    comp.vm.$v.warnings.$reset();
});
```

When I debug using ndb I can see that the $error property exists on the rationale object. The computed returns the correct value and the test passes. However once the test ends, I get that console error claiming that the error is coming from the `comp.vm.$v.warnings.$touch();` line. Nothing else is hitting this code and I am at my wits end on this one. Any help or guidance would be appreciated.

**Using**
- Vue.js 2.5.16,
- Vuelidate 0.7.4,
- Jest 23.4.1
- Vue Test Utils 1.0.0-beta.24
- Typescript 2.9.2
- TS-Jest 23.0.1

**Comment by YunitsynNikita** [comment]
Add
`import Vue from "vue";
import Vuelidate from "vuelidate";

Vue.use(Vuelidate);`
Into your Jest test file
