### ISSUE TITLE
Make $touch() wait for asynchronous validators

### ISSUE THREAD

**Issue by Timusan** [vuelidate/vuelidate#364]
This has been mentioned earlier in ticket #179 but since it was closed as the original issue in that ticket was somewhat resolved it did not get the needed attention.

The gist of the problem is that when we have one or more asynchronous validators in the chain this works perfectly for checking the *individual* fields on blur or keypress but provides a problem when validating the *overall* state. 

A common scenario is to check for validation when hitting the submit button (on top of checking each individual field on blur/key press). Touching your overall data (`$v.$touch()`) and then checking its overall validation state (`$v.$invalid`) will currently not wait for asynchronous validators.

A workaround has been [proposed](https://github.com/monterail/vuelidate/issues/179#issuecomment-326202539) in the previously mentioned ticket by using a watch with a promise polling the `$pending` state. This works great the first time you do an overall validation, but doing this a second time around will break as this watch is set to return immediately thus now `unwatch()` becomes undefined.

It is common for a user to make a mistake unknowingly and hitting the submit button. With the above workaround all async validators will be correctly checked, the invalid state set correctly and any error message displayed the first time around. But when the user then fixes their error and hits the submit button again we will encounter an error regarding the now unknown watch.

The core of the issue seems to be that `$touch()` is not asynchronous, making for difficult or broken overall validation in asynchronous scenarios. Forgive me for jumping to any conclusions here and correct me if I am wrong, but if `$touch()` would return a promise instead could it be used to wait for all asynchronous validators to do their bidding?

Or ... am I missing something obvious here?

I created contrived example of this problem in this [fiddle](https://jsfiddle.net/fz1q73cd/15/). Using the rigged asynchronous validator from the documentation this will set the input as valid when the data is of uneven length, after ~1 second. If you hit the submit button too soon the validation state will be invalid, even if the input is of uneven length. Waiting a second or two and hitting submit again will show a valid state again.

**Comment by jnarowski** [comment]
It would make my code much cleaner to allow touch to return a promise, and ideally support async await. I have some rather hackish code that allows my async validators to complete before the form is submitted, but would much rather have this supported within the library, to eliminate a lot of boilerplate. I find that I often use async validators in my enterprise application, so this would be huge.

**Comment by shentao** [comment]
Async validators are an important thing for the upcoming rewrite. Will keep this feedback in mind. Thank you!

**Comment by danieleconnect** [comment]
Any updates on this feature?

**Comment by dobromir-hristov** [comment]
We have progress on the V2 branch. This feature exactly is done differently, but we are still prototyping, might add a `$validate` method once we wrap up outstanding issues.

**Comment by Jaimies** [comment]
Any updates on this feature?

**Comment by dobromir-hristov** [comment]
Closing as this is already in V2.

**Comment by sudiptochoudhury** [comment]
Hi all,

May be this can help those who are still using pre-v2 versions. I am successfully using the following method mimicking v2's `$validate` function. Tested in v0.7.5.


    async $validate(v) {
      v = v  || this.$v
      v.$touch()
      await this.$nextTick()
      return new Promise((resolve) => {
        const unwatch = this.$watch(
          () => v.$pending,
          (isPending) => {
            if (!isPending) {
              resolve(!v.$invalid)
              if (unwatch) {
                unwatch()
              }
            }
          },
          {
            immediate: true
          }
        )
      })
    }

**Comment by amrshakya** [comment]
> Hi all,
> 
> May be this can help those who are still using pre-v2 versions. I am successfully using the following method mimicking v2's `$validate` function. Tested in v0.7.5.
> 
> ```
> async $validate(v) {
>   v = v  || this.$v
>   v.$touch()
>   await this.$nextTick()
>   return new Promise((resolve) => {
>     const unwatch = this.$watch(
>       () => v.$pending,
>       (isPending) => {
>         if (!isPending) {
>           resolve(!v.$invalid)
>           if (unwatch) {
>             unwatch()
>           }
>         }
>       },
>       {
>         immediate: true
>       }
>     )
>   })
> }
> ```

@sudiptochoudhury May i know how can this be implemented. so instead of this.$v.$touch(); we now use this method to validate?

**Comment by sudiptochoudhury** [comment]
> > Hi all,
> > May be this can help those who are still using pre-v2 versions. I am successfully using the following method mimicking v2's `$validate` function. Tested in v0.7.5.
> > ```
> > async $validate(v) {
> >   v = v  || this.$v
> >   v.$touch()
> >   await this.$nextTick()
> >   return new Promise((resolve) => {
> >     const unwatch = this.$watch(
> >       () => v.$pending,
> >       (isPending) => {
> >         if (!isPending) {
> >           resolve(!v.$invalid)
> >           if (unwatch) {
> >             unwatch()
> >           }
> >         }
> >       },
> >       {
> >         immediate: true
> >       }
> >     )
> >   })
> > }
> > ```
> 
> @sudiptochoudhury May i know how can this be implemented. so instead of this.$v.$touch(); we now use this method to validate?


1. You can add this as a method of your component or mixin.
2. Let's assume that you have a method to submit the form where you use `this.$v.$touch()`
3. Make that method `async` if not already done
4. Use `await this.$validate()` instead of `this.$v.touch()`
5. You can then check with `this.$v.$invalid` in the next line and everything following should remain same

Example:

    async submit() {
      this.formIsValidating = true // use this to show or hide a UI blocker + message
      await this.$validate()
      this.formIsValidating = false
      if (!this.$v.$invalid) {
        // code to submit form
      }
    }

NOTE: Since `$validate()` call may keep the user waiting, you may add a pre-loader or progress animation + message etc. to block your UI and show it's validating/processing, disable submit button till it's complete.

### How it works?

When you perform a `$touch`, all validation rules are executed. A validation rule, while executing keeps its own `$pending` flag to `true` and on completion sets it to `false`. The root `$v.$pending` remains `true` until all rules' `$pending` status is `false`.  Evidently, an async rule's `$pending` flag remains `true` until it's resolved, so is the root `$pending`. 

This method returns a promise which is resolved when root `$v.$pending` is `false` or is already `false`.
