### ISSUE TITLE
[feature request] Make it easier to determine a failure reason if multiple validations are used

### ISSUE THREAD

**Issue by wujekbogdan** [vuelidate/vuelidate#367]
Consider the following example:

``` javascript
validations: {
  city: {
    required,
  }
}
```

In such case it's easy to determine a failure reason. we can read the vale of the `$v.city.$error` property.

But in the case of multiple validators, let's say:

``` javascript
validations: {
  city: {
    required,
    email,
  }
}
```

If we read the value of `$v.city.$error` then all we know is that something went wrong. In order to determine which validator returned false, we have to compare the field's value against all `$v.city.params` fields, one by one.

It would be great if there was an additional property, let's say `$v.city.failures` that would contain only a list of validators that returned `false` or even better a list of all validators with true/false values. 

It would be extremely useful especially when it comes to displaying different validation message depending on the failure reason.

**Comment by dobromir-hristov** [comment]
Please use the https://github.com/dobromir-hristov/vuelidate-error-extractor/ for now. We will consider this in v2.0
