### ISSUE TITLE
dynamic minLength and maxLength

### ISSUE THREAD

**Issue by Ethan0007** [vuelidate/vuelidate#374]
Hi,

How can i make the validations for maxLength and minLength to be dynamic.

I have parent component that define maxLength  and minLength pass as props to child component.
the issues when assigning the property to max/min length it will not work.

not working:
![image](https://user-images.githubusercontent.com/12542052/46240803-83bb1780-c3df-11e8-933f-35a59de49b0f.png)

working:
![image](https://user-images.githubusercontent.com/12542052/46240807-93d2f700-c3df-11e8-930c-23e8cca2ec0c.png)

Please be guided thanks.

**Comment by cendrizzi** [comment]
I'm curious about this to, just making the validation dynamic in general...

**Comment by arturs-buls** [comment]
I encountered same issue one day. Found a solution. It is working with my custom validators, but I guess you can do same with minLength()

```
  newPassword: {
    complexPassword(value) {
      return complexPasswordIf(this.passwordEntered)(value);
    }
  },
```
passwordEntered is computed variable and reactivity works fine for me

My custom validators, if you are interested

```
// check if password contains lowercase, uppercase and number with minimum length of 8 symbols
export const complexPassword = value => /^(?=.*[a-z])(?=.*[A-Z])(?=.*\d).{8,}$/.test(value); 

// Check password complexity if "check" is true
export const complexPasswordIf = (check) => withParams(
    { type: 'complexPasswordIf', check },
    value => check ? complexPassword(value) : true
)

```

**Comment by Solant** [comment]
According to example in https://monterail.github.io/vuelidate/#sub-dynamic-parameters
you can define `validations` as a function to use dynamic validation schema and allow usage of `this` context.
```
validations() {
  something: {
    numeric,
    maxLength: maxLength(this.maxlength)
  }
}
```

**Comment by Solant** [comment]
@priithansen 
Yes. As `min` should hold a function that returns true/false, you should get `minValue(1)` actual return value:
```
validations() {
  people: {
    // How would one call minValue inside function?
    min: (value, model) => model.tomorrow ? false : minValue(1)(value)
  },
}
```

**Comment by priithansen** [comment]
This is brilliant, thanks! Couldn't seem to find any examples for this from web. 
Only catch seems to be that with first versions false = valid while inside the function returning true = valid

**Comment by shelru** [comment]
@Solant awesome thanks.
```
validations() {
return{
  people: {
    // How would one call minValue inside function?
    min: (value, model) => model.tomorrow ? false : minValue(1)(value)
  },
}
}
```
Lil fix.
