### ISSUE TITLE
[BUG] Validators change the model 

### ISSUE THREAD

**Issue by isametal88** [vuelidate/vuelidate#378]
Hi guys,

we are trying to use your library in our application, but we got stuck on an apparent misbehaviour.

We built a JSFiddle to show you : [link](https://jsfiddle.net/ng2rfzLt/)

We need to use nested data as models, but it seems that entering a typo in the validations (we wrote username2 on purpose both in the HTML and the validations) is not handled correctly by the library.
We expected it to warn us about the mistake (the library could detect that the key of the model I'm trying to validate is not in the model definition) but it appears that the two models are joined after the first validation, changing the underlying model and adding the third key. We think it's a mistake to change the model during the validation (wrong data could be sent to a server).

Also, we don't really understand the need to change the input-related model, given that the field that are validated are explicitely declared in the component configuration. Maybe a simple directive should do the trick. But that's just our opinion.

**Comment by shentao** [comment]
This shouldn’t happen. Is this still an issue?
