### ISSUE TITLE
Validate a collections with collection item has sync properties cause reactive performance issues

### ISSUE THREAD

**Issue by ghost** [vuelidate/vuelidate#381]
I am investigating the problem when I use v-for and $iter to render a collection while value items are affected by another global input.

I have a built a simple implement of my case: https://codesandbox.io/s/o45949yrq6

I this re-procedure, I implemented a form with 10 custom-input elements, it have a prop to tracking previous value and the value itself, a radio group to change the `unit`, and I use lodash `uniqueId` to tracking number of times the for loop run.

The problem is when I change the value of radio button, it re-render the items list, but it doesn't works as I expected. I imaged that I will render the list only one time, but what i saw is for each input change, it render all the input on the list.

Because of the radio value change, the inputs changed, for each input change, it render all the item in the list, for each input element I have 2 values changed, the number of for loop will approximate is: 

Number of props changed: 2
Total Item in the list: 10
For each input change, 10 items on the list will be re-render
2 * 10 => ~100 times.

Any suggestions?

**Comment by shentao** [comment]
I have a strong feeling about removing `$each` since it is the source of lots of issues. Using it might also lead to bad practices when it comes to app architecture, since it’s usually a good idea to encapsulate the v-for content to a new component.
