### ISSUE TITLE
version 0.7.4 "import { required } from 'vuelidate/lib/validators'"  has an error

### ISSUE THREAD

**Issue by fe-hunk** [vuelidate/vuelidate#386]
vue-router.esm.js?fe87:1905 SyntaxError: Unexpected token ,
    at Object../node_modules/vuelidate/lib/withParams.js (18.js:335)
    at __webpack_require__ (app.js:708)
    at fn (app.js:113)
    at eval (common.js?511b:14)
    at Object../node_modules/vuelidate/lib/validators/common.js (18.js:175)
    at __webpack_require__ (app.js:708)
    at fn (app.js:113)
    at eval (alpha.js?1568:8)
    at Object../node_modules/vuelidate/lib/validators/alpha.js (18.js:143)
    at __webpack_require__ (app.js:708)

**Comment by kosanr1** [comment]
Please provide more information for this issue.

**Comment by neldrak** [comment]
Got the same error with Quasar.
vuelidate 0.7.4
Quasar CLI........ v0.17.22
Quasar Framework.. v0.17.18

Added vuelidate as described here:
https://quasar-framework.org/components/form-validation.html

Thanks for looking into it!

**Comment by menthol** [comment]
Same as #336

**Comment by dabulla** [comment]
Same issue here. I'm still a node.js/vue/vuelidate/vue-material - newbie, but when I add the line
import { email } from 'vuelidate/lib/validators';
the whole page does not load without an errormessage/with a timeout on "localhost:8080/vendors~<route>.js".

**Comment by dobromir-hristov** [comment]
@dabulla mind making a small reproduction on codesandbox?

**Comment by ChinaRedArmy1930** [comment]
in vuelidate\lib\withParams.js,  I changed:
var withParams = **process.env.BUILD** === 'web' 
to
var withParams = **'lib'** === 'web'
and resolves the issue.
I didn't find "process.env.BUILD" in webpack document.

**Comment by dobromir-hristov** [comment]
That is injected on build step, via webpack.

**Comment by uoc1691** [comment]
Ran into similar issue while trying Vuetify + Vuelidate. Webpack is used. 
![image](https://user-images.githubusercontent.com/1751412/73643258-49464680-46c7-11ea-9ef1-b768dc4c5cb6.png)

**Comment by shentao** [comment]
I think this comes from the fact that `/lib` are the pre-build files (that is noncompiled files straight from src). You either need to add this env variable or use the `/dist/validators.min.js` file.

**Comment by uoc1691** [comment]
Vuelidate document does not mention anything about setting the process.env.BUILD. Not every application is a nodejs application and it is not recommended to meddle with the global variable, **process**.
![image](https://user-images.githubusercontent.com/1751412/73734234-6cd5c380-4791-11ea-9b70-78d4863d9d9f.png)

withParams.js checks process.env.BUILD and requires another js file accordingly. If any of the authors can comment on this would be appreciated.

**Comment by shentao** [comment]
Just import from the `/dist/validators.min.js` file in that case. I already said that in my previous reply.

**Comment by tripflex** [comment]
Related to https://github.com/vuelidate/vuelidate/issues/365
