### ISSUE TITLE
Jest, Vuex Error in render: "TypeError: Cannot read property 'proxy' of undefined"

### ISSUE THREAD

**Issue by ParsonsProjects** [vuelidate/vuelidate#388]
Hello,

I am having an issue when writing my unit tests using Jest, vuelidate is throwing a warning.

TypeError: Cannot read property 'proxy' of undefined
        at VueComponent.refProxy (F:\wamp64\www\vue-cli-sandbox\node_modules\vuelidate\lib\index.js:364:32)

This is specifically happening when validating an array of items using $each and trying to add an item to the array through the store mutations, when the $v is passed down to a child component. 

After several days of investigation it might be something to do with how Vue is rendering the data. However this warning is not shown when running the App with npm run serve. I have now hit a brick wall and not sure what to do next to resolve this issue.

I have created a repo with a small example of the code structure to be able to show and replicate this warning.
https://github.com/ParsonsProjects/vue-cli-sandbox/tree/jest-vuelidate

Any help would be greatly appreciated. Thanks

**Comment by dobromir-hristov** [comment]
In your example you are directly mutating the store, through the getter, which is being proxied by Vuelidate. This is overall a very brittle and bad approach and I would avoid it. 

Refrain from looping the `$each.$iter` property and using it to `v-model` data to it.

**Comment by ParsonsProjects** [comment]
Would you be able to provide a better way of doing this? This is the example given by vuelidate when using $each https://vuelidate.netlify.com/#sub-collections-validation

**Comment by dobromir-hristov** [comment]
Well its usually best to merge the object into the parent one and direclty merge that. It is allot more boilerplate but its less error prone. I dont have time now to write it out fully, but I have used it and it works pretty well.
