### ISSUE TITLE
Validator "required" working in v0.6.1, not working in v0.7.4

### ISSUE THREAD

**Issue by alexalexson143** [vuelidate/vuelidate#390]
Hi,

I was working on a project [here](https://github.com/alexalexson143/vuelidate-notworking) and noted that the validation on the Signup page - "Accept terms" part was **not working** as expected. Vuelidate version is **v0.7.4**.

I have the same project [here](https://github.com/alexalexson143/vuelidate-working) but with a Vuelidate version of **v0.6.1** and it is **working** as expected.

I expected the "required", "$invalid", and "$error", properties to toggle.

Not sure if this is a bug or maybe I missed something.

**Comment by kosanr1** [comment]
It works as expected. Validator `required` returns `true` if model has value `false`. Here #305 you can get more information.
