### ISSUE TITLE
Set dynamic Error Messages on validator params using withParams

### ISSUE THREAD

**Issue by frankievx** [vuelidate/vuelidate#394]
I have tried multiple methods to set a dynamic prop that provides an error message based upon the the ID on another validated field. It seems to be impossible to set a parameter with context. If anyone has any insights it would be greatly appreciated.
`
const driversLicense = (field) => {
  let error = ''
  return helpers.withParams({ error }, (value, vm) => {
    const dlStateId = vm[field]
    const state = sharedState.states[dlStateId - 1].STATE
    const stateRegex = new RegExp(USDLRegex[state].rule)
    // Test State regexp, strip all dashes, trim whitespace and uppercase letters.
    const valid = stateRegex.test(value.replace(new RegExp('-','g'),'').trim().toUpperCase())
    error = USDLRegex[state].description.join(', ')
    return valid
  })
}
`

**Comment by dobromir-hristov** [comment]
Code is unreadable. If you still have issues, post a jsfiddle or sandbox with a working example, showing your issue.
