### ISSUE TITLE
Can the error message text when the verification fails can be written into the validator?

### ISSUE THREAD

**Issue by 941477276** [vuelidate/vuelidate#397]
The current vuelidate is very light and flexible in use. The personal feeling is that a field usually has multiple verification rules, and each verification rule has an error message.
At present, these error prompt texts need to be manually written on the page, and then displayed and hidden according to the verification rules, as follows:
```
export default {
  data() {
    return {
      name: ''
    }
  },
  validations: {
    name: {
      required,
      minLength: minLength(4)
    }
  }
}

<div class="form-group" :class="{ 'form-group--error': $v.name.$error }">
    <label class="form__label">Name</label>
    <input class="form__input" v-model.trim="$v.name.$model"/>
  </div>
  <div class="error" v-if="!$v.name.required">Field is required</div>
  <div class="error" v-if="!$v.name.minLength">Name must have at least {{$v.name.$params.minLength.min}} letters.</div>
</div>
```

Personally feel so much trouble, although it is very flexible! Can there be any way to write the error prompt corresponding to the field to the data instead of writing it directly on the page? I am using jquery for development
I have used jquery.validator.js and I feel that this design idea is quite good. I don't know if it can be applied to vuelidate. Such as:
```
export default {
  data() {
    return {
      name: ''
    }
  },
  validations: {
    name: {
      required,
      minLength: minLength(4)
    }
  },
  // Imagine
  validationMessages: {
    name: {
      required: "Field is required",
      minLength: "Name must have at least 4 letters."
    }
  }
}

<div class="form-group" :class="{ 'form-group--error': $v.name.$error }">
    <label class="form__label">Name</label>
    <input class="form__input" v-model.trim="$v.name.$model"/>
  </div>
  <div class="error">{{$v.name.errorMsg}}</div>
</div>
```

**Comment by jean-moldovan** [comment]
Yes, I think simple computed is totally fine if have no more than 2-3 validators

**Comment by jean-moldovan** [comment]
@venticco Can we close this? Seems to be resolved.

**Comment by 941477276** [comment]
Yes, thank you very much for your solution!
