### ISSUE TITLE
requiredIf does not work in combination with other validaitons.

### ISSUE THREAD

**Issue by harrystaley** [vuelidate/vuelidate#399]
I am having an issue with multiple validations included with a requiredIf validation.
```
faith: {
        requiredIf: requiredIf(() => {
          return this.ch_class == 'Paladin'|| this.ch_class == 'Druid'|| this.ch_class == 'Cleric'
        }),
        alpha,
        maxLength: maxLength(25)
      }
```

**Comment by kosanr1** [comment]
You need to use dynamic validations, then `this` will point to Vue instance, here are docs https://monterail.github.io/vuelidate/#sub-dynamic-validation-schema

Here is your example https://jsfiddle.net/b5v4faqf/7368/

**Comment by harrystaley** [comment]
My issue is that dynamic validations require that I define every validation twice form my estimation. This is very inefficient.

**Comment by harrystaley** [comment]
for example from the docs.
```
if (!this.hasDescription) {
      return {
        name: {
          required
        }
      }
    } else {
      return {
        name: {
          required
        },
        description: {
          required
        }
      }
    }
```

in this example I need to redefine every other form validation to make one dynamic. I need to define name twice making maintainability a pain.

**Comment by kosanr1** [comment]
You can create base object and then assign more validations
```
validations () {
  const baseValidation = {alpha, maxLength: maxLength(25)}
  const requiredValidation = this.ch_class == 'Paladin'|| this.ch_class == 'Druid'|| this.ch_class == 'Cleric' ? {required} : null
  return  {
    faith: Object.assign(baseValidation, requiredValidation)
  }
}
```
and example with requiredIf
```
validations () {
  return  {
    faith: {
      requiredIf: requiredIf(() => {
        return this.ch_class == 'Paladin'|| this.ch_class == 'Druid'|| this.ch_class == 'Cleric'
      }),
      alpha,
      maxLength: maxLength(25)
    }
  }
}
```

**Comment by harrystaley** [comment]
Given the second example what if I had other validaitons that were not apart of this. do I need to wrap all of them in a return statment?

I have a custom regex validation called alphaSpaces that catches for spaces in regex.

```
validations: {
      name: {
        required,
        requiredIf,
        alphaSpaces,
        maxLength: maxLength(25)
      },
      race: {
        required
      },
      ch_class: {
        required
      },
      strength_base: {
        required,
        between: between(3, 18)
      },
      dexterity_base: {
        required,
        between: between(3, 18)
      },
      constitution_base: {
        required,
        between: between(3, 18)
      },
      intelligence_base: {
        required,
        between: between(3, 18)
      },
      wisdom_base: {
        required,
        between: between(3, 18)
      },
      charisma_base: {
        required,
        between: between(3, 18)
      },
      ch_background: {
        required
      },
      ch_alignment: {
        required
      },
      faith: {
        requiredIf: requiredIf(() => {
          return this.ch_class == 'Paladin'|| this.ch_class == 'Druid'|| this.ch_class == 'Cleric'
        }),
        alphaSpaces,
        maxLength: maxLength(25)
      }
    },
```

**Comment by harrystaley** [comment]
I see where you have defined validations as a method. Given the structure of my other validaitons where would I place this?

**Comment by dveleztx** [comment]
So, here's the issue. Working alongside Harry on this, when I make the following change:
`validations () {
  return  {
    faith: {
      requiredIf: requiredIf(() => {
        return this.ch_class == 'Paladin'|| this.ch_class == 'Druid'|| this.ch_class == 'Cleric'
      }),
      alpha,
      maxLength: maxLength(25)
    }
  }
}`

We get a blank page. I scrapped our current validation and just used the above code and it still renders the page completely blank.

I found this documentation that is similar to what we may be having issues with, but I try that method as well listed on that report, same issue: https://github.com/monterail/vuelidate/issues/198

**Comment by kosanr1** [comment]
> Given the second example what if I had other validaitons that were not apart of this. do I need to wrap all of them in a return statment?

Yes, just wrap all of them in a return statment.

**Comment by harrystaley** [comment]
how is the implementation different? 

```
validations:
```
vs
```
validations()
```

As david stated the second version displays a blank page.

**Comment by kosanr1** [comment]
Implementation is not different. With `validations()` it just call validation object with vue component, so you can use `this` in your validations. 
You have only blank page? any errors?

**Comment by dobromir-hristov** [comment]
Closing as this is not a Vuelidate issue, more of a lack of javascript knowledge. Defining `validations` as a method allows you to return an object that can be changed based on conditions. You can construct that object however you like, keeping it DRY is up to you.

**Comment by ninjasitm** [comment]
Hi Everyone,

I believe I'm having a simialr issue so didn't want to open a new issue.

```
validations() {
    const validations = {
      form: {
        required,
        user_id: {
          required
        },
        pipeline_stage_id: {
          required
        }
      }
    };

    validations.form.metadata = {
      $each: {
        value: {
          max: (value, model) => {
            return parseInt((model.options || {}).maxLength) > 0 ? maxLength(model.options.maxLength)(value) : false;
          }
        }
      }
    };

    /**
     * TODO: Fix issue with required always being true
     */

    if ((this.form.metadata || []).length && this.isInputsRequired) {
      validations.form.metadata.$each.value.required = requiredIf((model) => {
        return !!model.is_required === true;
      });
    }
    return validations;
  },
```

Having a similar issue. When using the above in a function `validations()` pattern requiredIf is always true. Any insight on this?

**Comment by edreesjalili** [comment]
Figure i'll just pop in my thoughts using this previous example. Might help someone out.
```js
validations () {
  return  {
    faith: {
      requiredIf: requiredIf(() => {
        return this.ch_class == 'Paladin'|| this.ch_class == 'Druid'|| this.ch_class == 'Cleric'
      }),
      alpha,
      maxLength: maxLength(25)
    }
  }
}
```

You can spread your optionally required validators across the base validation schema if the required test passes doing by doing something like this.
```js
validations () {
  const hasRequiredCharacterClass = ['Paladin', 'Druid',  'Cleric'].includes(this.ch_class);
  return  {
    faith: {
      requiredIf: requiredIf(hasRequiredCharacterClass),
      ...hasRequiredCharacterClass && {alpha, maxLength: maxLength(25)},
    }
  }
}
```

**Comment by ninjasitm** [comment]
Thank you for this. Will see if I can implement this logic. Much
appreciated.

Malcolm Paul
NITM Inc
(347) 241-2690

**Comment by ariellevitsky** [comment]
I've read the docs, but I still don't understand the benefit of using a dynamic validation schema over requiredIf/Unless as demonstrated in the Dynamic validation schema section of the docs.

**Comment by Uraharadono** [comment]
I had issue with this because I was setting up my validation like this:

HTML: 
```
              <input v-model="$v.writtenSignature.$model" class="text-signature" type="text">
              <div
                v-if="!$v.writtenSignature.requiredIf && $v.writtenSignature.$dirty"
                class="text-danger">
                This field is required
              </div>
```

Vue (wrong): 
```
      writtenSignature:{
        requiredIf: function() {
           return this.signatureTextVisible;
        },
      }
```

Vue (right):

```
      writtenSignature:{
        requiredIf: requiredIf(() => {
          return this.signatureTextVisible;
        }),
      }
```

So yeah, that was because I was not paying attention how I setup my validators.
