### ISSUE TITLE
Allow array of regex on regex helper

### ISSUE THREAD

**Issue by waghcwb** [vuelidate/vuelidate#400]
We can create a custom regex validation with the regex helper
`const customValidation = helpers.regex('custom', /^[a-zA-Z]*$/)`

It will be nice if we can pass an array of regex to validate
`const customValidation = helpers.regex('custom', [/^[a-zA-Z]*$/, /^[a-zA-Z]*$/])`

**Comment by mahdikmg** [comment]
@NataliaTepluhina can i implement this?

**Comment by dobromir-hristov** [comment]
Feel free
