### ISSUE TITLE
How to use 'not' validator ? 

### ISSUE THREAD

**Issue by duythang** [vuelidate/vuelidate#405]
Dear all

Do you know how can i use 'not' validator ? I checked in tutorial site but there is not any guide for using it.

Thank you so much.

**Comment by kosanr1** [comment]
You have to use it with some validation function which gets model value as argument. And it will pass if validator will not pass. You can chain it with other builtin validators.
```
isValid: not((model) => {
  return model === 'secret'
})
```
```
isValid: not(sameAs('someValue'))
```

**Comment by duythang** [comment]
Thank you so much
