### ISSUE TITLE
Decimal validation

### ISSUE THREAD

**Issue by getzvnm** [vuelidate/vuelidate#407]
Is there any method to validate decimal fields which allows only length 16 and only 2 decimal places  ?

**Comment by venticco** [comment]
I suggest using regexp validator with proper rule or custom validator (e.g. convert number to string and count digits in related parts).

**Comment by dobromir-hristov** [comment]
Closing. May add this as a recipe to the new FAQ docs section

**Comment by wooooodward** [comment]
Not sure what the protocol is here for commenting on a closed issue but I thought this might help someone.. the following validator can be used in the same way as the `maxLength` validator

```
import { helpers } from 'vuelidate/lib/validators'
export default length =>
  helpers.withParams(
    { type: 'maxDecimals', max: length },
    value =>
      !helpers.req(value) ||
      new RegExp(
        `^\\s*-?(\\d+(\\.\\d{1,${length}})?|\\.\\d{1,${length}})\\s*$`
      ).test(value)
  )
```

**Comment by budiardy** [comment]
great. thanks @wooooodward. it works

**Comment by Asef00** [comment]
Here's my approach to this:
```js
export const maxDecimals = (length: number) => {
  const regexx = new RegExp(`^\\d+(\\.\\d{1,${length}})?$`);
  return helpers.withMessage(`Maximum ${length} decimal places allowed`, helpers.regex(regexx));
};
```
Hope it helps.
