### ISSUE TITLE
How to apply and use parentVM in a Custom Validators ? 

### ISSUE THREAD

**Issue by duythang** [vuelidate/vuelidate#409]
Hello
Recently i am using Custom Validator solution to create my own validator. However, i want to 
use parentVM in my validator to access global vue data or method (like ```SameAs```).

Can you help me to explain  how i can apply and use parentVM in a Custom Validator

Thank you so much.

**Comment by kosanr1** [comment]
Hello, here you can find info about this https://monterail.github.io/vuelidate/#sub-accessing-component
