### ISSUE TITLE
Button cancel validates the form

### ISSUE THREAD

**Issue by stevenbustos** [vuelidate/vuelidate#414]
Hello.
I have 2 buttons in my view, one(save) is for post data in server and validates the fields with required, the other one(cancel) only function is to redirect out of the view.
Here is my problem, when I enter in the view I want to be able to get out without changing anything by clicking the cancel button, but when I click cancel it validates the fields in the form and show me the alert that I have in the function save for the button submit.

Here is a [jsfiddle](https://jsfiddle.net/Jormvngandr/grzsohvy/4/) with a recreation of the problem, basically,  I want to click cancel, see the alert of "are you sure?" and then see the alert with "3.no error" without see the alert with "1. error"

**Comment by lbottle** [comment]
![wechatimg58](https://user-images.githubusercontent.com/3881469/49632246-fffd5700-fa2f-11e8-9e4b-ce0d9b13a886.png)

**Comment by pvrsouza** [comment]
```
<button @click.prevent="cancel">
          CANCEL
</button>
```
