### ISSUE TITLE
How to check input contains any of a set of string values?

### ISSUE THREAD

**Issue by jeremyburton** [vuelidate/vuelidate#422]

**Comment by jeremyburton** [comment]
I've read through the docs but have not been able to work out how to check whether an input contains one of multiple string values. I was thinking maybe something like this would work, but it doesn't:

`sameAs: sameAs(() => 'Pass' || 'Fail')`

**Comment by senta** [comment]
`sameAs` stands for check an input has the same value as another input. This used for a password and the confirmation of the password for example. In your case, you can just use JavaScript String's method `indexOf()` or `match()`.

To check an input has one of the value "apple" or "banana", you can define your own custom validation like below.

```
validations () {
    return {
        fruit: {
            isFruit: (value)  =>
                ["apple", "banana"]
                .some(fruit => value.indexOf(fruit) !== -1)
        }
    }
}
```

https://jsfiddle.net/shotasenga/eywraw8t/513040/

Hope this help!
