### ISSUE TITLE
new release 0.7.5 for Christmas? : )

### ISSUE THREAD

**Issue by vesper8** [vuelidate/vuelidate#423]
I really want to use the fix(es) to $anyReady from https://github.com/monterail/vuelidate/pull/316 that @Akryum added

Any chance of tagging a new release with it included? Or is there a way to get all the latest commits since 0.7.4 was released in May?

Many thanks!

**Comment by mwielbut** [comment]
Bump 👍

**Comment by CoolGoose** [comment]
Bump x2. Do you need help with the library ? I think there are a couple that would like helping you guys out.

**Comment by CoolGoose** [comment]
@Frizi any updates on this ?

**Comment by CoolGoose** [comment]
Thank you for the reply, I will keep an eye on this, maybe it will be fork time at some point :)

**Comment by windymindy** [comment]
Bumping a fork. The project must live.

**Comment by shentao** [comment]
We’re currently working on a roadmap and investigating all the open issues. See #439 for details.

**Comment by jbmikk** [comment]
> We’re currently working on a roadmap and investigating all the open issues. See #439 for details.

Has there been any progress on the roadmap?
