### ISSUE TITLE
Object missing attribute $model not updated on change

### ISSUE THREAD

**Issue by yamsellem** [vuelidate/vuelidate#428]
If an object is missing an attribute (in component's data or props), it's `$model` is not working.
In the above reproduction example, a `text` attribute is given with an empty string and everything works fine. But, a `missing` attribute is given without a default empty string and it's `$model` seems not to be linked and doesn't work.

Reproduction link:  https://jsfiddle.net/dkp3yx7m/1/

Initializing every object attribute to a default value seems overkill to fix that issue.

**Comment by dobromir-hristov** [comment]
This is intended. Vuelidate cannot instantiate the validators otherwise.

**Comment by yamsellem** [comment]
@NataliaTepluhina you've added the `enhancement` label and @dobromir-hristov you've just close this as a "work as designed" — maybe leaving this open for a future release enhancement will be more clear, don't you think?
