### ISSUE TITLE
Feature request - group validation on specific validator

### ISSUE THREAD

**Issue by mkapiczy** [vuelidate/vuelidate#430]
I would like to propose a feature request (or extension to the documentation if this is possible) as I could not figure out how to do it without my own validation function outside of the framework.

Let's say I have a group of fields I want to validate:
```
validations: {
     fieldA: {
        customValidator: customValidationFunction,
        minLength: minLength(4)
      },
      fieldB: {
         customValidator: customValidationFunction,
         minLength: minLength(4)
      },
      fieldC: {
         customValidator: customValidationFunction,
         minLength: minLength(4)
      },
      fieldD: {
         customValidator: customValidationFunction,
         minLength: minLength(4)
      }
}
```

Now, I would like to be able to create a group validating only my customValidator (and leave vuelidate to validate every field separately on minLength). Something as follows:

```
groupCustomValidation: [
      'fieldA.customValidator',
      'fieldB.customValidator',
      'fieldC.customValidator',
      'fieldD.customValidator'
    ]
```

The end goal is to have access to `$v.groupCustomValidation.$anyError` which takes into consideration only errors from `customValidationFunction`, and still have access to `$v.fieldA.minLength.$anyError`.

**Comment by dobromir-hristov** [comment]
Why not just define your data in an object, that would act as a group?
```
data: {
  form: {
    group: { 
      fieldA: '',
      fieldB: ''
    }
  }
}
```
That way you still have individual validation, and per group one.

**Comment by mkapiczy** [comment]
But that requires me to create a specific object to pass to the form and I would have to do it only to enable validation, which seems counterintuitive to me.

I get my object from the server, preprocess it as needed for my application and want to display the data on the view without encompassing it into a separate `form` object.

This would also require me to transform the `form` object into my specific object on save/update action.

Not saying that wouldn't be a solution but in my specific scenario

**Comment by dobromir-hristov** [comment]
Well, currently that is the way. You can always do a data transformer on incomming and outgoing data, its super simple with rest/spread these days.
