### ISSUE TITLE
Specifying error message in model

### ISSUE THREAD

**Issue by devWaleed** [vuelidate/vuelidate#438]
There should be an option to specify error message with the rule.

For example:

```
name:{
	rules: { 
		required, 
		minLength: minLength(5)
	},
	errors: {
		required: 'This field is required',
		minLength: 'Value must be 5 characters long'
	}
}
```

and to show errors, instead of specifying each error in div just do:

```
<div v-if="$v.name.errors.length > 0">
	{{ $v.name.errors.showFirst() }}
</div>
```

**Comment by denis-pujdak-adm-it** [comment]
Also looking for something described above. In addition an ability to add your own errors to the model manually. Eg. form is sent and the response contains an error message and the property name.

**Comment by marco-fiset** [comment]
Is there any progress on this? It's pretty much a dealbreaker for me at the moment.

**Comment by giero** [comment]
I'm already working with `next` branch and basing a bit on documentation and a bit on code itself, found some solutions how to change/translate validation messages - my examples:

```javascript
import {
    helpers,
    required,
    maxLength,
} from '@vuelidate/validators';

const myRequired = helpers.withMessage(
    'Translated "required" message',
    required,
);
const myMaxLength = (max) => helpers.withMessage(
    `Translated "maxLength" message with ${max} characters.`,
    maxLength(max),
);
const hexColor = helpers.withMessage(
    'Message about invalid hex color',
    helpers.regex(/^#[0-9a-f]{6}$/),
);

const validations = {
    name: { required: myRequired, maxLength: myMaxLength(50) },
    color: { required: myRequired, hexColor },
};
```
But I've got a question - is maxLength wrapped correctly? It works, but IDE gives me a hint:

> Argument type {$params: {max: any}, $validator: (function(any=): any), $message: (function(any): string)} is not assignable to parameter type NormalizedValidator | Function

**Comment by dobromir-hristov** [comment]
I just made a pr about this @giero. Thanks for noticing. There is also a PR for TS typings so this should no longer be an issue. And yes you are doing it correctly 😄
