### ISSUE TITLE
decouple validation from representation

### ISSUE THREAD

**Issue by doncatnip** [vuelidate/vuelidate#443]
Sometimes a form consists of multiple vue components. Not all of those vue components exist and are active at the same time - for example when using tabs. In such cases it would be nice if validation could take place outside of vue components, I.e. in a vuex store. Then only the result of that validation would be used in the actual component.

It doesn't look like this would be an easy task, but has such architecture been considered at some point ?

**Comment by erickwilder** [comment]
So far, whenever I got myself in this situation the easiest solution (with less maintenance burden) was to consider these tabs as separate forms. You can still use Vuex to manage the internal state of the application and keep a reference of an already validated piece of information that another form _may_ depend on.

If you can build the interface with this assumption it also makes life easier when it comes to lazy-load and code-splitting as one form _may_ never be opened by a user.

**Comment by doncatnip** [comment]
Thanks for the quick response. I am aware. That would not satisfy the requirement for that particular part of the application for it to be an all-or-nothing kind of deal. It's fine, I'll manage.

**Comment by dobromir-hristov** [comment]
You can define your validations dynamically using [Dynamic validation schema](https://vuelidate.netlify.com/#sub-dynamic-validation-schema)

**Comment by doncatnip** [comment]
Yes, but not the schema, right ? This has to go into a component .validators property.

**Comment by dobromir-hristov** [comment]
Use the `validations() { }` as a method and return just those validations that have visible fields atm. You can construct an object with the validators dynamically based on the same rules that you hide/show elements in the UI.

**Comment by doncatnip** [comment]
Meant to say the state of the validation, not the schema as objects can of course be defined anywhere. Like I said, though .. it's all good :) I'm working on something like that. Thanks again guys.
