### ISSUE TITLE
Question: validate phone or email

### ISSUE THREAD

**Issue by mrcasablr** [vuelidate/vuelidate#447]
My app requires either email or phone number as their primary id.  In the same text field. how do I validate if the users has entered a valid email or a phone number and display the error appropriately? 

I'm able to do this on 2 separate fields as either phone or email. However, i'm exploring validation on a single text field to accept either one and validate.

**Comment by dobromir-hristov** [comment]
You could use the `or` validator 
```
or([phone, email])
```
