### ISSUE TITLE
Submit button disabled bug

### ISSUE THREAD

**Issue by alkeinaiduko** [vuelidate/vuelidate#449]
I put a vuelidate on my selection input and when I try to click submit button without adding something on the selection, the error message and color will appear and the button will disabled but when I change something on the selection, the color and the error text are gone but the button still disabled. Please help me to fix this one. Thanks!

here's my code

![image](https://user-images.githubusercontent.com/37724575/54149644-90a16400-4471-11e9-886a-97ba28474fc5.png)

this is what I have when the error is present

{
  "required": false,
  "$model": null,
  "$invalid": true,
  "$dirty": true,
  "$anyDirty": true,
  "$error": true,
  "$anyError": true,
  "$pending": false,
  "$params": {
    "required": {
      "type": "required"
    }
  }
}

and this is after I changed something on the selection

 
{
  "required": true,
  "$model": 3,
  "$invalid": false,
  "$dirty": true,
  "$anyDirty": true,
  "$error": false,
  "$anyError": false,
  "$pending": false,
  "$params": {
    "required": {
      "type": "required"
    }
  }
}

**Comment by dobromir-hristov** [comment]
I dont see a button in there. Please make a reproducable example in a codepen, fiddle or codesandbox.
