### ISSUE TITLE
Third Party Validation

### ISSUE THREAD

**Issue by garhbod** [vuelidate/vuelidate#452]
Hi,

This is not an issue just a query. Would it be more beneficial for this package if it relied upon a third party package to do the actual validations and focused solely on integrating vuelidate with vue?

It's just validation rules are already being maintained elsewhere what is the point of redoing work that is done?

Or if another package cannot be found could we extract the validation functions from this package into a separately maintained package that could be used throughout any javascript not just vue.

**Comment by dobromir-hristov** [comment]
Thats probably the plan for v 2.0.
