### ISSUE TITLE
Form Validation for generic forms using Vuelidate ? Is there a recommendable approach?

### ISSUE THREAD

**Issue by awacode21** [vuelidate/vuelidate#453]
Hi guys,

i have the following scenario. Forms which do not know their child components (form fields) and the child components do not know their parent form, as everything is put together by a content management system.
So the form fields need to contain their validation configuration by themself. But there needs to be the connection to the whole form.
I would like to do the validation with vuelidate but do not find an elegant way to build it generic.
How would you do the form validation with vuelidate in my case?

Thanks for your help! Best regards, Annick

**Comment by dobromir-hristov** [comment]
I'm sorry but there is no elegant way at this point. This will be one of the core-focus features in the upcoming v 2.0 release

**Comment by awacode21** [comment]
Thanks for your reply! Good to know, I've already doubted my qualities, that I don't see the solution. I have found a workaround that I don't think is so great, but that somehow works. I think it's good that the 2.0 release addresses the issue. Are there any plans as to when the 2.0 release will be approximately?

**Comment by AndreasCag** [comment]
I have successfully build validations for generic forms with function.

Here is copy-paste example of what I have in some project:
```

    validations() {
      const validation = { values: {}, files: {} };

      _.forEach(this.fields, field => {
        if (field.realType === 'hidden' || field.realType === 'button') {
          return;
        }

        if (field.realType === 'file') {
          if (field.required) {
            validation.files[field.name] = {
              required,
            };
          }

          return;
        }

        const fieldValidations = {};

        if (field.realType === 'number' && field.name.toLowerCase() === 'amount') {
          let limit;
          if (!this.currency) {
            limit = field.personalLimits;
          } else {
            limit = _.find(field.limits, { currency: this.currency });
          }

          limit && _.extend(fieldValidations, {
            between: between(limit.min, limit.max),
          });
        }

        if (field.required) {
          _.extend(fieldValidations, {
            required,
          });
        }

        validation.values[field.name] = fieldValidations;
      });

      return validation;
    },
```

**Comment by dobromir-hristov** [comment]
The above example has nothing to do with the question.

**Comment by pju-** [comment]
I think I have a pretty neat solution for the problem you are describing, using a "ValidationObserver" and "ValidationProvider" functional wrapper component around form/the individual fields that communicate the validations using Vue's provide/inject syntax and scoped slots. The only problem is that you can't use simple a simple v-model anymore but need to manually manage the update events, but that's no big deal.

That way the form with the ValidationObserver has the info about the whole nested validation state, the ValidationProvider wrapper does the import of all rules  you need, and the individual field components define the rules/validation configuration for themselves and (through a scoped slot) receive $invalid, $dirty, $error and so on.

It's inspired by the equivalent components VeeValidate comes with but much more lightweight, I think it's a pretty elegant solution.

Built it for work, but I can ask if we will open source it. If you have any questions in the meantime, let me know.

**Comment by jarsofrice** [comment]
@dobromir-hristov, has this feature been released? I have the same scenario where my form elements are coming from an API. I want to build the form dynamically and need a way to pass in v-model so that its unique to each input field in the form. Thanks.

**Comment by awacode21** [comment]
@jarsofrice as far as i understood it the feature will be provided with the next major release of vuelidate which will also be compatible für Vue 3. At the Vue.js Amsterdam conference we heard about some great features which are coming for vuelidate!

In the meantime you need to workaround it.
I did it by using the vuex store. Each form field ist generic and independent and does not know anything about the others or its parent, it also includes it's own validation and error handling, but it saves its validation state within a map in the vuex store. The form component accesses the store object and checks wether there are any errors or not. It does not need to know more! So it is absolutely possible to workaround the issue but with next major release it should be so much easier!

**Comment by jarsofrice** [comment]
@awacode21 - thank you for the information!
Do you have any example code on how to do that? thanks.

**Comment by awacode21** [comment]
@jarsofrice i am sorry, i haven't seen your comment in the past. Hope you found your solution.

**Comment by awacode21** [comment]
@dobromir-hristov in 2019 i generated this issue/question. The last month i had the chance to build up a completely generic form as described above based on Vue 3 and your newest Vuelidate version. It's so much smoother now, it is much less code now, so simple, it really amazes me. The Validation scopes are amazing. You really achieved a great piece of work here, congrats! I guess we can close my issue now, as i feel it is solved by the newest version.
