### ISSUE TITLE
Required validator returns true for whitespace string when docs say it should return false.

### ISSUE THREAD

**Issue by cfoucher** [vuelidate/vuelidate#454]
The Docs say that the Required Validator should fail for strings that are pure whitespace: 
`Requires non-empty data. Checks for empty arrays and strings containing only whitespaces.`
However this is not occuring. Strings containing spaces only, pass validation.

There is a test that explicitly checks for this, so either the Documentation should be updated, or the Required validator updated to strip whitespace (i.e `.trim()`)

https://github.com/vuelidate/vuelidate/blob/master/test/unit/specs/validators/required.spec.js#L40

This can be seen by going to the default fiddle https://jsfiddle.net/Frizi/b5v4faqf/ and simply typing in 5 spaces.

**Comment by cfoucher** [comment]
I've created a pull request that fixes the issue. So that the outcome of the `required` validator matches the documentation.
#455

**Comment by dobromir-hristov** [comment]
I am both in favor of this and against it... Vee-validate handles it exactly as you described, though we can also use `v-model.trim` to prepare our input to not do this. @shentao what do you think?

**Comment by shentao** [comment]
I don't have a strong opinion on this topic. I would lean towards changing it so that it trims the string before checking.

**Comment by nolde** [comment]
Hello!

Did this ever get released? I don't see it listed in releases. We are currently using **vuelidate v0.7.4**, and `required` still accepts spaces as proper input.

**Comment by mbaev** [comment]
I don't actually think that the "validation process" should make any changes in source data. For example space can be valid symbol to use in password, somewhere.

Case of life: usually a password is required on registration and login pages and not required on edit profile page. It means that users have an ability to set new password using space, but can't login with it.

My thought is that developers should trim value by themselves before check, if it's required by an app or the trimming should be optional, somehow.

**Comment by mbaev** [comment]
It can be different rule like: "requiredWithTrim"
