### ISSUE TITLE
When field type is "number" and the value is invalid, model is empty string. How to go around that?

### ISSUE THREAD

**Issue by luiz-brandao-jr** [vuelidate/vuelidate#458]
If we have a field with type _number_ and we enter an invalid value like "123123-" the model value becomes an empty string. Is this a bug?

Because of that I can't really check if the field is really empty or not.

Please check this jsfiddle for reference:
https://jsfiddle.net/218tqr0n/

**Comment by luiz-brandao-jr** [comment]
So it seems that the model becoming empty is cause by Vue itself. How would one go around that into checking if there is an invalid value in the field and that it's not empty?

If I use the "required" rule, then it will be in an invalid state when empty, but it will also be in that state if the number is invalid. Any suggestions?

**Comment by dobromir-hristov** [comment]
Why not do `text` with a `v-model.number` ? You can add a `numeric` validator too.

The problem with `input[type=number]` is that the browser itself will not allow for adding anything else, except numbers.

https://jsfiddle.net/dobromir/b7fsxjtp/5/

**Comment by adamreisnz** [comment]
The problem with using `type=text` is that on mobile devices it will default to alphanumeric keyboard, whereas with `type=number` it will show the numeric keyboard, which is what you want for number type inputs.

I don't think we should be avoiding the use of `input[type=number]`.

**Comment by dobromir-hristov** [comment]
Yeah you are right here. Well then you just have to deal with it as its more of a browser thing.

**Comment by luiz-brandao-jr** [comment]
I got around this issue by using input[type=tel]
