### ISSUE TITLE
Null $params issue

### ISSUE THREAD

**Issue by xiaoshuw** [vuelidate/vuelidate#460]
Hi, it seems that I am unable to port customized validators to an external library. For instance, if I have this in a js file

export const myRequired = label =>
  helpers.withParams(
    { 'errMessage': `${label} is required` },
    required,
  );

I can create an parameterized validator without problem. For example, with

validations: {
  email: {required: myRequired('Email')
}

I can check that the this.$v.email.$params.required is an Object with property $sub and errMessage.

However, if I put myRequired in an external library, (i.e., not in the same project), then, the this.$v.email.$params.required is always null. 

I wonder if this is a bug or there is something that I did wrong?

**Comment by xiaoshuw** [comment]
Well, the external library was installed via 'npm link'. It seems it can work if I build it, publish it, and then use npm install, it can work.

**Comment by dobromir-hristov** [comment]
It should not matter where the validator comes from, as long as it's a function returning a Boolean

**Comment by jjlorenzo** [comment]
I'm experiencing this too.

**Comment by dobromir-hristov** [comment]
Please show a reproducible example on codesandbox or similar and we will try help

**Comment by jjlorenzo** [comment]
Well, unfortunately this will be difficult for me right now since I have to meet a deadline, but for me looks like @xiaoshuw guess is right, regarding that if the external library that contains the custom validators was linked into node_modules, the $params is null. Let me see if in the following days I can add a sample.

**Comment by a-stankevich** [comment]
I also have the same problem with $params being empty when using vuelidate from unpkg CDN.
Tried both mixins and global registration, also tried to revert to 0.6.2 as suggested in #302 with no luck.
One thing I noticed while browsing the code is that here https://github.com/vuelidate/vuelidate/blob/master/src/index.js#L114 unlike all other collections, values for $params are taken without calls to `getRef` or `refProxy`. Is it possible that this somehow causes a problem with $param when loading with CDN and not NPM?

**Comment by a-stankevich** [comment]
My problem was that `validators.min.js` were imported before `vuelidate.min.js`. There was no error or warning of any type, it was just that $params didn't work.

**Comment by jasperkennis** [comment]
I had this issue when trying to display data that was in a vuex store. To circumvent making direct changes to data in the store, I had a computed prop that would return a copy of the data in the store. This worked in some cases but not always. Shouldn't do this, instead you should read from the store to the components data when opening the form and write back to the store when saving the form.

**Comment by plumthedev** [comment]
I had the same problem with the vue-storefront theme that was rendered on the server-side. I received errors from the client and the API console. As suggested # 301, I updated vuelidate to 0.7.5 and the bug was resolved. Now the problem only occurs if I visit the page directly or refresh it. Has anyone else had a similar situation and can help me?

**Comment by nadhifikbarw** [comment]
> My problem was that `validators.min.js` were imported before `vuelidate.min.js`. There was no error or warning of any type, it was just that $params didn't work.

Thanks @a-stankevich , it solves my problem.

**Comment by tada5hi** [comment]
Any updates on that ?

**Comment by tada5hi** [comment]
This info might help: https://github.com/vuelidate/vuelidate/issues/874#issuecomment-1047694987
