### ISSUE TITLE
how to add validation to child component with multiple error messages

### ISSUE THREAD

**Issue by twalldesign** [vuelidate/vuelidate#461]
I have a parent component with some inputs and they validate fine. I cannot submit the form until the errors are fixed. I also have a child component with around 10 inputs, and they will not stop my form from submitting even if they have errors. So I was wondering:

1) How can I validate the inputs in my child component, which has multiple fields
2) Since it has multiple fields, where can I place the custom error messages for those fields. The closer to the field the better.

I like the idea of having the validation and error messages in the child, but from what I can tell that is not how Vuelidate works. So I am fine keeping the validation in the parent, but I have no idea how to handle the multiple errors messages that are linked to the fields that live in the child component. Ex. If I bring in:
`<child-component />`
and it has 10 fields. Where do I put the 10 error messages?

I am new to Vue, so the more detailed the answer the better. 

TIA

**Comment by dobromir-hristov** [comment]
Keep validator on the parent and pass the validators for each field down to the child as props. Then you can display errors there, either manually or with the error extractor.

**Comment by twalldesign** [comment]
Thanks. I was able to keep the error messages in the child by making v: a prop and using a child.validation.js file to house the child component validations. The one issue I could not get around was displaying the error messages in the child on blur. It would show all error messages after @blur of the first input. I opted for not displaying until on submit so it still worked out.

**Comment by dobromir-hristov** [comment]
Check this out for error display - https://dobromir-hristov.github.io/vuelidate-error-extractor/
Basically you need to `$touch` the input to make it dirty.
