### ISSUE TITLE
mapState examples

### ISSUE THREAD

**Issue by shelru** [vuelidate/vuelidate#465]
Show some mapState vuex examples.

**Comment by shelru** [comment]
computed: {
            ...mapState('auth', [
                'ShowLoginModal',
                'authenticating',
                'authenticationError',
                'authenticationErrorCode'
            ]),
            ...mapState('vars', [
                'minPasswordLength',
                'maxPasswordLength',
                'minLoginLength',
                'maxLoginLength',
            ]),
        },
validations(){
            return{
                szLogin: {
                    required,
                    minLength: minLength(this.minPasswordLength)
                },
                szPassword: {
                    required,
                    minLength: minLength(6)
                }
            };

        },

**Comment by hellboy81** [comment]
Please provide more comprehensive example
