### ISSUE TITLE
min/maxLength

### ISSUE THREAD

**Issue by shelru** [vuelidate/vuelidate#466]
minLength by default set's false? Why?
```
 validations: {
            szLogin: {
                required,
                minLength: minLength(5)
            },
            szPassword: {
                required,
                minLength: minLength(6)
            }
        },
```

![image](https://user-images.githubusercontent.com/9306996/55284348-dde46780-5385-11e9-89e6-c50035695dde.png)
![image](https://user-images.githubusercontent.com/9306996/55284351-e6d53900-5385-11e9-821c-92810cacb719.png)

**Comment by dobromir-hristov** [comment]
Validator works as expected. All validators are invoked immediately, check if it's dirty or not.
