### ISSUE TITLE
minLength: Cannot read property password of undefined

### ISSUE THREAD

**Issue by matheusgrieger** [vuelidate/vuelidate#467]
Whenever I use the `minLength` validation, it throws a `Cannot read property 'password' of undefined` error. Using Vuetify + TypeScript, no Nuxt. Here is a code sample demonstrating the issue:

```html
<template>
  <form>
    <v-layout column class="pa-3">
      <!-- other fields removed for brevity -->

      <!-- Password -->
      <v-text-field
        v-model="formData.password"
        :error-messages="$v.formData.password.$error ? [
          !$v.formData.password.required && 'Password is required',
          !$v.formdata.password.minLength && 'Password should have at least 8 characters',
        ] : []"
        label="Password"
        @input="$v.formData.password.$touch()"
        @blur="$v.formData.password.$touch()"
        type="password"
      ></v-text-field>
    </v-layout>
  </form>
</template>

<script lang="ts">
import Vue from 'vue';
import { required, email, requiredIf, minLength } from 'vuelidate/lib/validators';

export default Vue.extend({
  data: () => ({
    formData: {
      name: '',
      email: '',
      password: '',
    },
  }),

  validations() {
    return {
      formData: {
        name: {
          required,
        },
        email: {
          required,
          email,
        },
        password: {
          required: requiredIf(() => !this.$route.params.id),
          minLength: minLength(8),
        },
      },
    };
  },
});
</script>
```

The error only appears when upon typing and when the value is shorter than 8 characters.

Edit: When removing the `formData` object the errors stopped. Happens in any validation functions with the password field.

**Comment by matheusgrieger** [comment]
Actually, it breaks whenever I try to validate this field, for some reason. No matter what method of validation I'm using.

**Comment by dobromir-hristov** [comment]
I would first start by using something more sane to display errors, like https://dobromir-hristov.github.io/vuelidate-error-extractor/other_frameworks.html#usage-with-vuetify

As for the error, your template has a mistake:
```
 !$v.formdata.password.minLength
```
should be `formData`

**Comment by matheusgrieger** [comment]
Oh geez... My bad. And thank you so much for your time!
