### ISSUE TITLE
Question: How to transport non-boolean state of async validation ?

### ISSUE THREAD

**Issue by joerg-walter-de** [vuelidate/vuelidate#468]
Hi

I  want to create  an async validator like this:

const myValidator = (value, component) => {
    return api.getCheck().then(result => {
    return true;
  }).catch(error => {
    return false;
  });
};

the getCheck method returns one of  several results a, b, c.
Is there a legal way to use vuelidate structures to transport that result instead of or in addtion to true/false ?

**Comment by dobromir-hristov** [comment]
No, currently validators should only return a boolean.
