### ISSUE TITLE
Access to not siblings fields in custom validator

### ISSUE THREAD

**Issue by anorudes** [vuelidate/vuelidate#472]
Hey. I have the validation scheme:
```
  birthdayDate: {},
  passport: {
    date: {
    }
  }
```
I need the "passport.date" to be more than "birthdayDate"
I wrote a custom validator for "passport.date". How can I access to "birthdayDate"?
Helpers.ref and parentVm not working because there are only keys from "passport" object.
Also, I can't get the vue component instance to get the data from the data myself.

I have read all the documentation and see no way to do this.
If the fields are at the same nesting level, then it works, but in my case I can't get the "birtdayDate" value inside "passport.date" custom validator

How can I do this?

**Comment by dobromir-hristov** [comment]
if you use normal functions, the `this` context is your component instance.
```js
validations: {
 birthdayDate: { required },
  passport: {
    date: {
      beBiggerThanBirthDate(value){
        return this.birthDate < value
      }
    }
  }
}

**Comment by anorudes** [comment]
It works. I didn't guess that it should be inside the object. Thanks :)
