### ISSUE TITLE
$dirty and $error stays false

### ISSUE THREAD

**Issue by isaicus** [vuelidate/vuelidate#473]
no matter what, in a simple input type=text , $error and $dirty never gets updated...
and something else, if I try to touch like this @input="$v.name.touch" I get a console error that touch is not I function, so I do the touch like $v.name.touch

anyway, either if i use touch or touch() just the $invalid gets updated (and the rules)

**Comment by dobromir-hristov** [comment]
Show code how you use the library. Otherwise I am closing the issue. This sounds like user error.

**Comment by isaicus** [comment]
`<template>
  <div>
    <v-text-field name="name" label="label" id="id" v-model="name" @input="$v.name.touch"></v-text-field>
    <div>err: {{ $v }}</div>
  </div>
</template>

<script>
import { required, minLength } from "vuelidate/lib/validators";
export default {
  data() {
    return {
      name: null
    };
  },
  validations: {
    name: {
      required,
      minLength: minLength(3)
    }
  }
};
</script>

main.js
----------
import Vuelidate from "vuelidate";
Vue.use(Vuelidate);
`

**Comment by dobromir-hristov** [comment]
```
" @input="$v.name.$touch"
```

**Comment by ariellevitsky** [comment]
I have the exact same issue. The individual errors, i.e. "required" are updates, but the $error value never changes.

`               <p>
                    <label>
                        Language
                        <span class="asterisk">
                            *
                        </span>
                    </label>
                    <select
                        v-model="result.language"
                        :class="{ 'form-error': $v.result.language.$error }"
                    >
                        <option disabled selected>
                            ---
                        </option>
                        <option
                            v-for="language in languages"
                            :key="language.type"
                            :value="language.type"
                        >
                            {{ language.name }}
                        </option>
                    </select>
                    <span v-if="!$v.result.language.required" class="tooltip">
                        The language field is required.
                    </span>
                </p>

    validations: {
        result: {
            language: { required },
        }
    }`

**Comment by dobromir-hristov** [comment]
@ariellevitsky make a new issue with a link to a reproduction. Thanks.

**Comment by shirodkarpushkar** [comment]
> ```
> " @input="$v.name.$touch"
> ```
> 
> its `$touch` with a dollar sign.

I know it sounds somehow strange, but with above issue got resolved when I started using @input="$v.name.$touch()" instead of @input="$v.name.$touch"
