### ISSUE TITLE
add 'required' on text input and/or checkbox that disables it

### ISSUE THREAD

**Issue by twalldesign** [vuelidate/vuelidate#479]
Hey all

I have an input that can be disabled with a checkbox. I would like to have a 'required' error on the checkbox, and/or on the text input. You have to enter one or the other. You will either use the checkbox to disable the text input, or enter data into the text input. 

Any thoughts on how I can do this?

TIA

**Comment by dobromir-hristov** [comment]
Use the `requiredIf` validator on both, so they are mutually required.

**Comment by twalldesign** [comment]
Thanks!! I totally missed that when looking for a solution.
