### ISSUE TITLE
Require doesn't work well

### ISSUE THREAD

**Issue by afwn90cj93201nixr2e1re** [vuelidate/vuelidate#480]
```json
$v:Object
$anyDirty:true
$anyError:true
$dirty:true
$error:true
$invalid:true
$model:null
$params:Object
$pending:false
form:Object
$anyDirty:true
$anyError:true
$dirty:true
$error:true
$invalid:true
$model:Object
$params:Object
$pending:false
fname:Object
group:Object
$anyDirty:true
$anyError:true
$dirty:true
$error:true
$invalid:true
$model:3
$params:Object
$pending:false
integer:true
maxValue:true
minValue:true
required:false
```

![image](https://user-images.githubusercontent.com/9306996/57565447-1f2d5580-73cf-11e9-95fd-368f941a7b0b.png)

```js
group: {
                        required,
                        integer,
                        minValue: minValue(1),
                        maxValue: maxValue(0xFFFFFFFF)
                    },
```

![image](https://user-images.githubusercontent.com/9306996/57565462-6d425900-73cf-11e9-84dc-1828015e4f03.png)

@dobromir-hristov

**Comment by afwn90cj93201nixr2e1re** [comment]
```js
SetGroup(option){
                if(!option)return;
                console.log(option)
                this.$v.form.group.$touch();
                this.form.group = option.id;
                this.$nextTick(() => { this.$v.form.group.$touch(); })
            },
```
![image](https://user-images.githubusercontent.com/9306996/57565586-919f3500-73d1-11e9-887a-b68af07a4e53.png)

Seem's like req never called.

**Comment by afwn90cj93201nixr2e1re** [comment]
So, get, add in doc's something 'bout order, for example integer must be before require. @dobromir-hristov

**Comment by afwn90cj93201nixr2e1re** [comment]
Hm, strange.
![image](https://user-images.githubusercontent.com/9306996/57565742-01aeba80-73d4-11e9-8549-7ce25671a792.png)
Now minvalue doesn't work.

**Comment by dobromir-hristov** [comment]
They all work fine, stop spamming. If you need help, create a fiddle or codesandbox showing the issue.

**Comment by afwn90cj93201nixr2e1re** [comment]
I showed it to you. :/

**Comment by afwn90cj93201nixr2e1re** [comment]
![image](https://user-images.githubusercontent.com/9306996/57565925-1e002680-73d7-11e9-900a-e0ff43217cc3.png)
Never called.

**Comment by afwn90cj93201nixr2e1re** [comment]
https://github.com/vuelidate/vuelidate/issues/441 
https://github.com/vuelidate/vuelidate/issues/91
https://github.com/vuelidate/vuelidate/issues/81
https://github.com/vuelidate/vuelidate/issues/108#issuecomment-367979070
And more...
Seem's vulidate doesn't work well in browsers.
![image](https://user-images.githubusercontent.com/9306996/57565968-bbf3f100-73d7-11e9-98ea-384d411bfbed.png)
This show param's is null, but it's not null.

**Comment by afwn90cj93201nixr2e1re** [comment]
https://jsfiddle.net/ckL037yh/15/ check it (don't initialize text in data).

**Comment by afwn90cj93201nixr2e1re** [comment]
We must use get model in next tick, or create interface to recheck value manually, this.$v.a.$recheck()

**Comment by dobromir-hristov** [comment]
Text is not predefinied in your data, this it is not reactive.

**Comment by afwn90cj93201nixr2e1re** [comment]
But models in $v show rirght value as you can see.

**Comment by dobromir-hristov** [comment]
For validation to work, you need to cater your data as you would with Vue, meaning you need to have data predefined, for reactivity to work. I am closing this, as it looks like user error.

**Comment by afwn90cj93201nixr2e1re** [comment]
So, and why you don't wanna implement right check by getting $model in vuelidate computed instead getting reference?
What 'bout form resetting? What 'bout dynamic server answers?
