### ISSUE TITLE
Validate group of 3 or more radio buttons

### ISSUE THREAD

**Issue by twalldesign** [vuelidate/vuelidate#481]
Hey again

I am wondering how to add 'required' to a group of radio buttons. One of the 3 is required.  

What I thought would work:
`needToValidate: { required },`

data looks like this:`
needToValidate: {
         ONE: null,
         TWO: null,
         THREE: null,
}`

TIA

**Comment by shentao** [comment]
Hey. Check out the Vue docs on how to work with Radio Inputs: https://vuejs.org/v2/guide/forms.html#Radio
You put the same `v-model="myRadioValue"` on all the Radio Inputs and then you just validate:
```
myRadioValue: { required }
```

Your data model should look like this:
```
{
  myRadioValue: null,
  myRadioOptions: ['one', 'two', 'three']
}
```

**Comment by twalldesign** [comment]
Nice and simple. Thanks a lot!!

**Comment by shentao** [comment]
Happy to help! 👍
