### ISSUE TITLE
How to use and / or validators??

### ISSUE THREAD

**Issue by gtamas** [vuelidate/vuelidate#483]
Hi

How to use these?

```
validations: {
  somefield: {
    or: or(ipAddress(), url())
  }
}

```

Is this correct? Must not be, because it doesn't work :). Please help! Or these can be used in custom validator functions oinly?

**Comment by shentao** [comment]
Try
```
validations: {
  somefield: {
    or: or(ipAddress, url)
  }
}
```

**Comment by gtamas** [comment]
This results in a type error:

```
 validations: {
        endpoint: {
            or: or(ipAddress, url)
        },
```

Argument of type '() => ValidationRule' is not assignable to parameter of type 'ValidationRule | CustomRule'.
  Type '() => ValidationRule' is not assignable to type 'CustomRule'.
    Type 'ValidationRule' is not assignable to type 'boolean'

**Comment by gtamas** [comment]
I have latest vuelidate: 0.7.4
