### ISSUE TITLE
Add length to $each to support Array.from

### ISSUE THREAD

**Issue by chiptus** [vuelidate/vuelidate#484]
First I would like to thank you for this awesome library. It helps with validating all our forms easily :D Thanks!

Is it possible to add `.length` key to `$each`? I need to iterate this object and adding `.length` will help because I could easily wrap it with `Array.from` and iterate the result.

Thank you,
Chaim

**Comment by dobromir-hristov** [comment]
What do you loop it for? There is an "$iter" property you could also use?

**Comment by chiptus** [comment]
I want to find the dirty values, $iter is also an object.
Ideally I would do `Array.from($v.$each).filter(v => v.$dirty)`

**Comment by senta** [comment]
You can use `Object.values($v.$each.$iter)` instead, no?

**Comment by chiptus** [comment]
I can, but why not add a `length` to an array like object, or maybe
`toArray` method? it would be much more native (at least for me)

thanks!

**Comment by senta** [comment]
It would be convenient. However, since we can use `$each` for Objects, having length/toArray() doesn't make sense to me.

**Comment by chiptus** [comment]
If we take the length from the object it will be undefined if not an array

**Comment by dobromir-hristov** [comment]
If you need the length of the $iter, just do `Object.values`. This is unnecessary.
