### ISSUE TITLE
How to use requiredIf?

### ISSUE THREAD

**Issue by realtebo** [vuelidate/vuelidate#485]
First question
--

Probably I've not understood a basic thing: **must `requiredIf` return `true` to indicate that _the field itself is required_, or true _if the validation is successfully passed?_** 

> for example: when the password is not mandatory, must my function return false (because is not mandatory), or true (because the 'require' validation has been passed) ?!?!

Second question
-- 
**What is supposed to be the param of requiredIf?** 

I've a form used both for creating new users and for editing existing users.

If creating, the computed method `isNewUser` returns true.

If editing, it returns false,

I'm trying to implement the rule that password is mandatory only if isNewUser.
```

computed: {
        isNewUser() {
            return this.$store.getters["customers/getIsNewUser"];
        }
},
validations: {
    ....
    new_password: {
                minLength: minLength(8),
                sameAs: sameAs("repeat_new_password"),
                required: requiredIf(function(model) {

                    console.log("isNewUser", this.isNewUser);
                    console.log("model", model);
                    console.log("model.new_password", model.new_password);
                    const esit =
                        !this.isNewUser ||
                        (this.isNewUser && model.new_password);
                    console.log("esit", esit);
                    return esit;
                })
    }
   ...
}
```

This is my console output when inserting a new user.

![image](https://user-images.githubusercontent.com/1268699/58700932-ce8f9380-83a1-11e9-86e5-4126e2fc8c13.png)

What kind of what is the `model` param?

**Comment by realtebo** [comment]
I did this try

               required: requiredIf(function() {
                    return !this.isNewUser;
                })

but then with an empty field I see validation of required  'true'. But this is wrong. If required and field is empty i expect this validation fails,.... damn...what am I doing wrong?

**Comment by adamreisnz** [comment]
My understanding is that the function should return `true` if the field is supposed to be required.

**Comment by dobromir-hristov** [comment]
@realtebo  here you go mate.
https://jsfiddle.net/dobromir/1xe7mv3h/4/

**Comment by realtebo** [comment]
Thanks for the fiddle. Very clear !

**Comment by muarachmann** [comment]
Hi @dobromir-hristov thanks for the fiddle, i have been playing with vuelidate and its awesome. I however have a blocker... what if the field in question needs to be validated by another field of the model. I have this validation

```
                tracks: {
                    $each: {
                        title: {
                            required,
                            minLength: minLength(3)
                        },
                        price: {
                            required,
                            minValue: minValue(100)
                        },
                        gold_price: {
                             required: requiredIf(function() {
                             return ..... -> what to put here, 
                        })
                        },
                    }
                }
```
Basically in my object model track it has a prop called `is_gold_price` which is a check button that unhides and hides the gold price field. I wish to be able to access each instance of the `is_gold_price`, So the field is to be required if an only if the is_gold_price has been toggled on which is for some particular track. A little help would be appreciated thanks

**Comment by dobromir-hristov** [comment]
if `is_gold_price` is a property on the VM, and not in each track, then something like the line below. If however `is_gold_price` is part of each track, then you sadly cannot reach into it easily. 

```
gold_price: {
 required: requiredIf(function(value, vm) {
   return !!vm.is_gold_price
 })
},
```

**Comment by muarachmann** [comment]
> if `is_gold_price` is a property on the VM, and not in each track, then something like the line below. If however `is_gold_price` is part of each track, then you sadly cannot reach into it easily.
> 
> ```
> gold_price: {
>  required: requiredIf(function(value, vm) {
>    return !!vm.is_gold_price
>  })
> },
> ```

Thanks but unfortunately the `is_gold_price` is a property of each track. I however noticed that `requiredIf(function(value) {... }` on `console.log` returns the immediate parent but however can't return subsequent parents. That is it returns gold_price. I had to restructure my model to suit that case and ended up with 

```
   "vip_prices": {
       "gold_price": null,
       "platinum_price": null,
       "diamond_price": null,
       "is_gold_price": false,
       "is_platinum_price": false,
       "is_diamond_price": false,
   },
```


```
validations: ....
.....
 vip_prices: {
      gold_price: {
           required: requiredIf((vip_prices) => vip_prices.is_gold_price === true), ---> this is from the direct parent
            minValue: minValue(this.dataMinTrackPrice) ----> this is from the VM
  },
```

**Comment by bonno123** [comment]
how to add custom error messages with requiredIf ?

```
requiredifPasswordIsFilled: requiredIf(
                        (isNewBOUserguid.value) && (!!state.BOUserAddEdit.password),
                    ),
```
