### ISSUE TITLE
Conditional built-in validators

### ISSUE THREAD

**Issue by adamreisnz** [vuelidate/vuelidate#486]
Hi there, I'm looking for a super basic conditional validation using built-in validators, but can't seem to figure out how to accomplish it with vuelidate.

In essence:

```js
fixedFee: {
  required: requiredIf('hasFixedFee'),
  minValue: minValue(1),
},
```

Problem is that `minValue` validator always triggers, even if `fixedFee` is empty or not required. How can I use the built-in `minValue` validator but make it conditional to `hasFixedFee` like `requiredIf`?

Having to supply my own validation function for such a simple use case seems overly complicated to me.

**Comment by adamreisnz** [comment]
E.g. I know I can do this, but it seems overly verbose for such a simple use case:

```js
fixedFee: {
  required: requiredIf('hasFixedFee'),
  minValue: function(value) {
    return (!this.model.hasFixedFee || value >= 1);
  },
},
```

Some kind of helper like this would be useful:

```js
fixedFee: {
  required: requiredIf('hasFixedFee'),
  minValue: conditional('hasFixedFee', minValue(1)),
},
```

**Comment by dobromir-hristov** [comment]
You could create such a helper.

Here is an example - https://jsfiddle.net/dobromir/d20bL4oj/10/

```js
const validateIf = (prop, validator) =>
  helpers.withParams({ type: 'validatedIf', prop }, function(value, parentVm) {
    return helpers.ref(prop, this, parentVm) ? validator(value) : true
  })
```
If anyone finds this useful, please vote or something, I could add it as a helper :)

**Comment by adamreisnz** [comment]
Would be great to have this as a built-in helper

**Comment by afwn90cj93201nixr2e1re** [comment]
@dobromir-hristov what 'bout situations when we have more than 2-3 validator's except required?
For example:
```
 data() {
            return {
                id:0,
                isRegister:false,
            }
        },
 validations(){
            return{
                    id:{
                        requiredIf:requiredIf(()=>{console.log(this.isRegister);return !this.isRegister}),
                        minValue:minValue(1),
                        maxValue:maxValue(0xFFFFFFFF)
                    },
```
we should validate this field only if this is not register page, this.isRegister == false.

Can you give an example?
Coz requiredIf confusing peoples so much.

**Comment by afwn90cj93201nixr2e1re** [comment]
So, seem's like it should be like this:
![изображение](https://user-images.githubusercontent.com/9306996/60401166-89bc6f80-9b8e-11e9-834c-3bc1dc5ca20b.png)

Can you add it into build? And write some tips into doc's near requiredIf.
![изображение](https://user-images.githubusercontent.com/9306996/60401174-9d67d600-9b8e-11e9-995d-aead9d4b1c1d.png)

**Comment by afwn90cj93201nixr2e1re** [comment]
@dobromir-hristov 
Seem's like this doesn't work well.
`helpers.ref(prop, this, parentVm) undefined`
![изображение](https://user-images.githubusercontent.com/9306996/60412784-9d45f580-9be3-11e9-846a-94b674b48ed0.png)
![изображение](https://user-images.githubusercontent.com/9306996/60412834-c8304980-9be3-11e9-8b13-ba918c08200c.png)
![изображение](https://user-images.githubusercontent.com/9306996/60412843-d2524800-9be3-11e9-9c97-08a3fb2a8bd7.png)



Why it's returning undefined?
![изображение](https://user-images.githubusercontent.com/9306996/60413639-ad130900-9be6-11e9-9ce7-8524fbd500da.png)
![изображение](https://user-images.githubusercontent.com/9306996/60413643-b308ea00-9be6-11e9-8783-6867853f129b.png)
![изображение](https://user-images.githubusercontent.com/9306996/60413655-ba2ff800-9be6-11e9-92d6-e8883d5d6963.png)
![изображение](https://user-images.githubusercontent.com/9306996/60413666-c1570600-9be6-11e9-9323-0c05b6d5d1bc.png)

**Comment by afwn90cj93201nixr2e1re** [comment]
So, seem's like it should be:
![изображение](https://user-images.githubusercontent.com/9306996/60414427-2b70aa80-9be9-11e9-82f1-b66684fe094c.png)
```
const validateIf = (prop, validator) =>
        helpers.withParams({ type: 'validatedIf', prop }, function(value) {
            return this[prop] ? validator(value) : true
    })
    const validateIfNot = (prop, validator) =>
        helpers.withParams({ type: 'validateIfNot', prop }, function(value) {
            return !this[prop] ? validator(value) : true
    })
```

**Comment by eduarguz** [comment]
@afwn90cj93201nixr2e1re looks like your validator works... Thank you so much 

Question: Is this a good practice/pattern to use `this[prop]`. What about `ref()`? cannot this access computed properties or component data?

**Comment by dobromir-hristov** [comment]
NO, because the ref is intended to work with the parent scoped object or a function callback.
```
data:{ form: { name: '' } } 
```
Here ref('anything') will search in form, when invoked from the context of 'name` validator.

Nothing is stopping you from using this, but if you need a deeper accessor, than a top level thing, you cant do that, neither with a callback.

**Comment by fractalf** [comment]
This helper is super nice! I was stuggling a lot creating my own validator when I found this thread.  One comment though, the $params are a bit messed up. 

What I mean is, when I use this as `minLength: validateIf('isMyVarSet', minLength(3))` and I want to get the min value of 3 for the error message I have to do this: `{{ $v....$params.minLength.$sub[0].min }}`. The array part of this is what i feel is not right/consistent. Would be cool if `minLength.min` could just inherit this value (bubble it up or something)

I don't understand enough to fix this myself..

Example output:
```
"$params": {
    "minLength": {
        "type": "validatedIf",
        "prop": "isMyVarSet",
        "$sub": [
            {
                "type": "minLength",
                "min": 3
            }
        ]
    }
}
```

**Comment by fractalf** [comment]
Also just noticed that this helper doesn't work if you use it with ie the `sameAs` validator:
```
email2: {
    requiredIf: requiredIf('email'),
    email: validateIf('email', email),
    emailVerify: validateIf('email', sameAs('email'))
}
```
...if I wanna check if two emails are the same, but I don't wanna trigger the second email validators before user punshes in something for the first. I know it's a bit of an edge case, but I got curious about this helper, trying to find out how it works, etc.

Debugging this, I found out that it fails because `parentVm` inside `sameAs` is not set

**Comment by dobromir-hristov** [comment]
Yeah, thats pretty much stretching it 😆 I may try to see what I can do there.

**Comment by ekntrtmz** [comment]
> You could create such a helper.
> 
> Here is an example - https://jsfiddle.net/dobromir/d20bL4oj/10/
> ### Helper
> 
> ```js
> const validateIf = (prop, validator) =>
>   helpers.withParams({ type: 'validatedIf', prop }, function(value, parentVm) {
>     return helpers.ref(prop, this, parentVm) ? validator(value) : true
>   })
> ```
> 
> ### Usage
> 
> ```js
> validations: {
>     form: {
>       password: {
>       	minLength: validateIf('change_password', minLength(5))
>       }
>     }
>   }
> ```
> 
> If anyone finds this useful, please vote or something, I could add it as a helper :)

I find it very useful. Thank you!

**Comment by afwn90cj93201nixr2e1re** [comment]
@dobromir-hristov what about something like that?

```
login: {
                    validateIf: validateIf(()=>{if(condition)return true;return false;}),
                    required,
                    minLength: minLength(this.minLoginLength),
                    maxLength: maxLength(this.maxLoginLength)
                },
                password: { 
                    validateIfNot: validateIf(()=>{if(condition)return true;return false;}),
                    required: requiredIf(() => {if(this.isCreate)return true;return !(this.form.password==='');}), 
                    minLength: minLength(this.minPasswordLength),
                    maxCharLength: (value)=>{return _charsLength(value)<=this.maxPasswordLength*4;}
                },

```

I think that we should have main validation rule, which can be easy configured, so, then in validators we should just add 'validateIf/validateIfNot' && near https://github.com/vuelidate/vuelidate/blob/master/src/validators/minLength.js#L5.


What do you think about it? Like general condition to easy switch off validation.

**Comment by afwn90cj93201nixr2e1re** [comment]
I can create a PR if you gonna review it asap.

**Comment by afwn90cj93201nixr2e1re** [comment]
@dobromir-hristov what about something like that?

```js
login: {
                    validateEnabled: validateEnabled(()=>{if(condition)return true;return false;}),
                    required,
                    minLength: minLength(this.minLoginLength),
                    maxLength: maxLength(this.maxLoginLength)
                },
                password: { 
                    validateEnabled: validateEnabled(()=>{if(condition)return true;return false;}),
                    required: requiredIf(() => {if(this.isCreate)return true;return !(this.form.password==='');}), 
                    minLength: minLength(this.minPasswordLength),
                    maxCharLength: (value)=>{return _charsLength(value)<=this.maxPasswordLength*4;}
                },

```

I think that we should have main validation rule, which can be easy configured, so, then in validators we should just add validateEnabled logic near https://github.com/vuelidate/vuelidate/blob/master/src/index.js#L401.


What do you think about it? Like general condition to easy switch off validation. I think that that's better than wrapped validators also it's not a breakable change.

**Comment by shentao** [comment]
@afwn90cj93201nixr2e1re this looks like a potential use of `$config` fields that we are working on for the next release. One of them is `$autoDirty` which sets the $dirty state after the first change to the data model fragment. I imagine we could also make it so that the fragment of the tree would be validated only if it’s enabled (but return an "all-good" placeholder validation results so that one does not have to worry about checking if certain `$v.model.submodel` exists. 
Wdyt? 
/cc @dobromir-hristov

**Comment by afwn90cj93201nixr2e1re** [comment]
Where and when we can get it? For tests, reports, improvments?
Coz now im using this branch and there is ton of boilerparte code instead built-in.

>  I imagine we could also make it so that the fragment of the tree would be validated only if it’s enabled

Yes, that's should be done, like some conditional function, with hardcoded name. We should just skip all validation rules and set them true if $validateIt return false/true.

Coz i thinked at first time that requiredIf - works as pre validator, like if it's not required other rules not gonna be called, but, no.

**Comment by dobromir-hristov** [comment]
Pardon, I should leave what? The packages are in very alpha stage and are not fully documented, nor finished.
We will improve along the way, no ETA thought

**Comment by afwn90cj93201nixr2e1re** [comment]
I know. Just suggestion.

**Comment by afwn90cj93201nixr2e1re** [comment]
@fractalf try this, i build it now, seem's like it's works as expected, so, and field error extractor by @dobromir-hristov also works with that.

```
import { helpers } from 'vuelidate/lib/validators'
const validateIf = (prop, validator) => (value,parentVm) => {
        console.log('prop',prop)
        console.log('validator',validator)
        console.log('value',value)
        console.log('parentVm',parentVm)
        let result = undefined;
        result = typeof prop === 'function' ? prop(value,parentVm) : this[prop];
        console.log('result',result)
        return result ? validator(value) : true;
    };

export default validateIf;

```


```
import { helpers } from 'vuelidate/lib/validators'
const validateIfNot = (prop, validator) => (value,parentVm) => {
        console.log('prop',prop)
        console.log('validator',validator)
        console.log('value',value)
        console.log('parentVm',parentVm)
        let result = undefined;
        result = typeof prop === 'function' ? prop(value,parentVm) : this[prop];
        console.log('result',result)
        return !result ? validator(value) : true;
    };

export default validateIf;

```


```
validations() {
        return {
            form: {
                password: { 
                    minLength: _validateIf((value,parentVm) => {
                        console.log('_validateIf value is',value);
                        console.log('_validateIf parentvm is',parentVm);
                        if(this.isCreate)return true;//if this a register page enable minLength checking
                        if(!this.form.password.length)return false;//if this is a user info page and there no password typed, disable minLength checking
                        return true;//else if this is a user info page and password was typed, then enable minLength checking
                    },minLength(this.minPasswordLength)/* , { type: 'minLength', min: this.minPasswordLength } */),
```

![изображение](https://user-images.githubusercontent.com/9306996/68287332-fc3cdf00-009b-11ea-9917-0a5a39e9be58.png)


That's wrappers are surely better than @dobromir-hristov posted.

**Comment by afwn90cj93201nixr2e1re** [comment]
So, @dobromir-hristov can you explain for us, how minLength, type and min expanded to $params? Coz i really don't get it, with code lines from src please.

**Comment by dobromir-hristov** [comment]
I am sorry but I dont get what I should explain?

Create a readable, reproducible fiddle, explaining your issue and I will see it, when I have time. 

And a tip, those jabs against my "style" and "coding practices", without a valid explanation are not cool. If you want to give constructive criticism, you can do that with a PR in the correct places.

If you want to be on your own, continue in that fashion.

**Comment by afwn90cj93201nixr2e1re** [comment]
:/

**Comment by afwn90cj93201nixr2e1re** [comment]
![изображение](https://user-images.githubusercontent.com/9306996/68289864-5b9cee00-00a0-11ea-804c-b73df338b8fa.png)
How it was calculated. I wanna know that for better understanding how get rid off recursive here.

**Comment by skajfes** [comment]
I have solved a similar problem using dynamic validation schema, and it seems to me this is closely related. The docs are here: https://vuelidate.js.org/#sub-dynamic-validation-schema

My problem was having to validate a different set of fields based on selection. Ie, based on paymentType selection validate the appropriate input fields: 

```
    validations() {
        let v = {
            // validators that are always applied
            
        };

        // different set of validators based on selection
        if (this.paymentType === 'credit-card') {
            v.creditCardNumber = {required};
        } 
        else if (this.paymentType === 'invoice') {
            v.companyName = {required};
            v.companySSN = {required};
        }
        return v;
```

Applied to the OP's problem it would look like: 
```
validations() {
     var v = {  };
    
     if (this.hasFixedFee) {
          v.fixedFee = { required, minValue: minValue(1) };
     }

     return v;
}
```

**Comment by shentao** [comment]
Thank you @skajfes, I think this pretty much explains it. 

I don’t think there is a need for conditional validators, given that you can use JavaScript to just apply the existing validators conditionally.

**Comment by parker-codes** [comment]
Here is my solution in case it helps anyone. We show the text "(required)" next to the label if an input should be required. The problem was, when using `requiredIf` we could not detect the difference between if the input was not required OR if it was required and valid. This is because the data Vuelidate provides us with includes whether the rule has been met, not the result of `requiredIf`.

Original:
```js
validations() {
    return {
        occupation: {
            required: requiredIf(function(applicant) {
                return isOccupationRequired(applicant.employmentStatus);
            }),
            maxLength: maxLength(26),
        },
    };
}
```

So I came up with a solution to conditionally attach the property (by spreading a ruleset or an empty object). `requiredIf` always attaches the given property, but of course it evaluates it based on the function.

Helper:
```js
// used by spreading result
// rule is { string: validatorFunction }
function validateIf(condition, rule) {
    return condition ? rule : {};
}
```

Usage:
```js
validations() {
    return {
        occupation: {
            ...validateIf(
                isOccupationRequired(this.form.employmentStatus),
                { required }
            ),
            maxLength: maxLength(26),
        },
    };
}
```
