### ISSUE TITLE
Suggestion for easy error messages

### ISSUE THREAD

**Issue by magpiedigital** [vuelidate/vuelidate#488]
Would you ever consider updating your syntax for easier error messages?

I really like the way Vuetify does validation, and the perfect vue validator for me would be a mix of vuelidate and vuetify. Something like:
```
validators: {
   title: [
      isRequired() || 'Title is required',
      v => v.length >= 3 || 'Title must be 3 characters or more'
   ]
}
```

Thanks for your hard work!

**Comment by dobromir-hristov** [comment]
This would make the job of defining validations very repetitive and brittle. No such intentions.

**Comment by magpiedigital** [comment]
Am I right in that the only way to write error messages now is to specify it in the template i.e. 
```
<div class="error" v-if="!$v.name.required">Field is required</div>
<div class="error" v-if="!$v.name.minLength">Name must have at least {{$v.name.$params.minLength.min}} letters.</div>
```

That's much more repetitive than the syntax I outlined above, in which you could do something like
`<div class="error" v-for="error in $v.name.errors">{{ error }}</div>`

**Comment by dobromir-hristov** [comment]
https://dobromir-hristov.github.io/vuelidate-error-extractor/ :) Dont even need to loop errors now.
