### ISSUE TITLE
Vuelidate validate input as metric or imperial unit

### ISSUE THREAD

**Issue by twalldesign** [vuelidate/vuelidate#489]
Hey all
I am wondering how to approach validating an input that could be metric or imperial units, depending on the user's setting.  How do I validate and display the appropriate error for ex. kg or lbs?

ex. 'must be less than 1000lbs' 
or 
'must be less than 450kg'

TIA

**Comment by dobromir-hristov** [comment]
I would use a custom validator function, define two error messages, one for imperial, one for metric, then depending on some global setting, validate properly.

### Some pseudo code
```js
// this will convert your unit to pound
const convertUnit = (unit, value) => unit === 'pound' ? value * 2.205 : value
// this is your validator factory. We use the vuelidate minValue, just transform our mininum threshold accordingly
const validateFor = (unit, threshold) => minValue(convertUnit(unit, threshold))

export default {
    data() {
        return {
            form: {
                value: 50
            },
            user: {
                units: 'metric'
            }
        }
    },
    validations() {
        return {
            form: {
                value: {
                    // this allows us to have different validation messages, based on the used units
                    [this.user.units]: validateFor(this.user.units, 500)
                }
            }
        }
    }
}
```
And for error display I would use https://dobromir-hristov.github.io/vuelidate-error-extractor/ but you can do manual check too.

**Comment by twalldesign** [comment]
This looks great. I will give it a try!
