### ISSUE TITLE
How to properly add custom validation to array

### ISSUE THREAD

**Issue by NeoTianHow** [vuelidate/vuelidate#499]
Hi, I have an array of objects with the following structure:

` varientSections: [
        {
          type: "",
          values: [
            {
              varientId: 0,
              individualValue: ""
            }
          ]
        }
      ]`

I created a custom validation called isDuplicate, which checks for duplicate value for the property **"type"**. For example, 

` varientSections: [
        {
          type: "basket",
          values: [
            {
              varientId: 0,
              individualValue: ""
            }
          ]
        },
         {
          type: "basket",  // ERROR: Duplicate with the "above" object
          values: [
            {
              varientId: 0,
              individualValue: ""
            }
          ]
        }
      ],`

I was able to get my custom validation to work. However, the $invalid property will be false for all the objects present in the array. Hence, all the objects in the array will be highlighted in **red**

![image](https://user-images.githubusercontent.com/43518077/60827804-99b5fe00-a1e3-11e9-8be5-b1042166d8ca.png)

Below is my validation code: 

`validations: {
    varientSections: {
      $each: {
        type: {
          required,
          isDuplicate(type, varient) {

            console.log(varient);

            const varientIndex = this.varientSections.findIndex(
              v => v.type === type
            );

            var isWrong = true;
            this.varientSections.forEach((varObject, index) => {
              if (index !== varientIndex) {
                if (varObject.type === varient.type) {
                  isWrong = false;
                }
              }
            });

            return isWrong;
          }
        },
        values: {
          $each: {
            individualValue: {
              required
            }
          }
        }
      }
    }
  },`

**Comment by NeoTianHow** [comment]
Still trying to solve this issue. Any help is greatly appreciated !

**Comment by dobromir-hristov** [comment]
Well yeah, because you are validating whether each of them is unique. The moment you get a duplication, all validators are falsy. 
You have to either think of a way to distinguish between the different entries, ie. first one reservers a keyword, all the rest get errors if they duplicate it.
Extract the validator from `$each` to a simple top level validator on the `varientSections`.

**Comment by Petri-Oosthuizen** [comment]
I think I've found a way to make this work but it is not pretty... I'm using composition API btw.
```
  $each: helpers.forEach({
    name: {
      unique: helpers.withMessage(t("validation_unique"), (value: string, siblings: any, ...vmArgs) => {
        // Vuelidate's types are not correct in this case (I think)
        // vmArgs by index starting at the leaf object:
        //  n - index in the array (value)
        //  n+1 - object containing this array (siblings)
        //  The array's field name is unfortunately not available in the vmArgs and has to be passed in
        const indexOfThisValue = vmArgs[0];
        if (indexOfThisValue === 0) return true;
        const fields = (vmArgs as any)?.[1]?.[arrayName];
        const fieldValues = fields.map((f: any) => f.name).filter(Boolean);

        console.log(vmArgs);

        return new Set(fieldValues).size === fieldValues.length;
      }),
    },
```

The result: 
![image](https://github.com/vuelidate/vuelidate/assets/4954611/82244c0a-7481-4948-877f-e9ac45b2ef7b)
