### ISSUE TITLE
Vuelidate and Vue Test Utils

### ISSUE THREAD

**Issue by MatthewBooth** [vuelidate/vuelidate#511]
Vuelidate is not testing well with Jest/Vue Test Utils. 

**What's the problem?**

Vuelidate is returning `$invalid` as false even though ALL conditions are met and true.

I have a validation on a numeric:

`number: { required, minLength: minLength(15), numeric, maxLength: maxLength(15) }`

When I console out the conditions:

```javascript
console.log(wrapper.vm.$v.number.numeric)
console.log(wrapper.vm.$v.number.required)
console.log(wrapper.vm.$v.number.maxLength)
console.log(wrapper.vm.$v.number.minLength)
console.log(wrapper.vm.$v.number.$invalid)
```
Gives:
```javascript
 console.log 
    true
 console.log 
    true
 console.log 
    true
 console.log 
    true
 console.log 
    true
```

So why, then, does `$invalid` come back as true also?

EDIT:

Apparently I needed to mount the component with `sync: false` and use `return localVue.nextTick()` to get this working.

I'll close this :)

**Comment by nbilly7** [comment]
Your edit solves two awful blocking days.
Thank you bro !
I also needed to mount with `sync: false` and in my unit test I writed
```  
wrapper.setData({ myObject: { attribute: 'bla' } });
wrapper.vm.$v.$touch();
await wrapper.vm.$nextTick();
```
After that vuelidate worked great.
