### ISSUE TITLE
Validating a nested object in an array

### ISSUE THREAD

**Issue by super2ni** [vuelidate/vuelidate#515]
Hello,

I am trying to validate an array ("localisationsPrincipales" in the fiddle). For this, I use a "$each" and validates each item. 
For each item, the validation rule is quite complicated. I need to ensure that the item has either a property "adresse" equals to null. If "adresse" is not null, I need to validate its "codePostal" property.

I have no idea how to do this.

Could anyone help me?

Here is the fiddle mimicing my situation:
https://jsfiddle.net/Lx6g49mw/

**Comment by dobromir-hristov** [comment]
If address is not null, you want to validate the it's codePostal field?
```
$each:{
  address(value) {
    return value === null ? true : (value.codePostal === 'cookies') // do some extra checks if its an object or not.
  }
}
```
