### ISSUE TITLE
Unable to validate objects inside an array

### ISSUE THREAD

**Issue by eakenbor** [vuelidate/vuelidate#525]
I am unable to validate my objects inside an array. I get the error that "name" and "years" of undefined cannot be read, whereas the item of which the name and the years are in are the elements in the array. 
See a snippet here https://jsfiddle.net/eakenbor/wjLtmv0y/6/

Please can someone tell me what I am doing wrong? Thanks.

**Comment by dobromir-hristov** [comment]
$v does not have `item` in it. Try like this or use Vuelidate-error-extractor to extract these for you. 
`!$v.mainObject.array.$each[index].years.required` Take a look how I am accessing the `array` property and then its `$each`.That is an array, which I use the current looped index to fetch the validation for it. Then I check the `year` property and the required validation.

If you use the error extractor. you would need to pass it `$v.mainObject.array.$each[index].years` and it will show all validations for that property.

**Comment by eakenbor** [comment]
Thanks @dobromir-hristov, that worked.  If you have the access, maybe you should add a similar example to the vuelidate documentation, unless it was me who could not find it there.

However, please do you know the built-in validator to check for any repetition in the array?

**Comment by dobromir-hristov** [comment]
For repetition, you need to create a manual validator.
