### ISSUE TITLE
Bug in Group Selected

### ISSUE THREAD

**Issue by 7rows** [vuelidate/vuelidate#528]
I found the bug. When we select a group, all items in the group are highlighted, then when we deselect one item from that group and then click again to select the whole group, the following occurs.
The selected values contain the same element twice.

![Снимок экрана от 2019-08-27 09-59-42](https://user-images.githubusercontent.com/31033038/63748636-65d98980-c8b2-11e9-83a2-f32236a7cace.png)

**Comment by dobromir-hristov** [comment]
Not related to this library.
