### ISSUE TITLE
URL returns true when field is not required but empty

### ISSUE THREAD

**Issue by buzzclue** [vuelidate/vuelidate#532]
Behavior of field when not required but URL is incorrect. Field itself when empty is valid which is ok but it is not a URL.

https://jsfiddle.net/hp24eawo/

**Comment by dobromir-hristov** [comment]
Just combine with the `required` validator.

**Comment by buzzclue** [comment]
Why would you make a field required when you only want to validate if its URL? Sorry but what kind of approach is that?

**Comment by azamanaza** [comment]
@buzzclue 
I think that is the expected behavior.
The url validator only runs it's validation if the input is not empty.
Suggested answer is if you want to validate non empty, add required.

**Comment by buzzclue** [comment]
@azamanaza i agree with you it should only run if field is not empty but there are several flags to validate each field and method. I don't think it should state URL true when field is empty. $error state is already false which indicates that there are no errors.

```json 
"text": {
    "url": true,
    "$model": "",
    "$invalid": false,
    "$dirty": true,
    "$anyDirty": true,
    "$error": false,
    "$anyError": false,
    "$pending": false,
    "$params": {
      "url": {
        "type": "url"
      }
    }
  },
```

**Comment by dobromir-hristov** [comment]
All regex validators dont run if value is empty. Just add a `required` validator if you need it to be not empty. Sorry bud, this one is staying as is :/
