### ISSUE TITLE
Problem with populated $model with $v-model on text input on Android devices 

### ISSUE THREAD

**Issue by niemaco** [vuelidate/vuelidate#534]
Example:
https://codesandbox.io/embed/vuelidate-problem-on-mobile-ugnft

I created a parent component with dynamic validation of email and password fields and send data to two child components via props. When I run this code on a desktop device, everything works fine, but when I do it on a mobile device, the validation of the emial field stops working.
I tested this on Samsung Galaxy S7 in Chrome browser.

Can you tell me what I'm doing wrong?

**Comment by dobromir-hristov** [comment]
Sorry, but I just tried with a galaxy s10 and it works as it should :/ The validation is not connected in any way to a mobile device, so it should work the same.

**Comment by niemaco** [comment]
When I start entering the email in the field on desktop, I have the following properties in $v.email:
```
{
  "required": true,
  "email": false,
  "$model": "a",
  "$invalid": true,
  "$dirty": true,
  "$anyDirty": true,
  "$error": true,
  "$anyError": true,
  "$pending": false,
  "$params": {
    "required": {
      "type": "required"
    },
    "email": {
      "type": "email"
    }
  }
}
```

However, when I do the same on the phone I only have the error related to required and the object looks:
```
{
  "required": false,
  "email": true,
  "$model": "",
  "$invalid": true,
  "$dirty": true,
  "$anyDirty": true,
  "$error": true,
  "$anyError": true,
  "$pending": false,
  "$params": {
    "required": {
      "type": "required"
    },
    "email": {
      "type": "email"
    }
  }
}
```

I attach a screenshot from the smartphone screen:
https://www.dropbox.com/s/n2ptlp0yayxr9lp/Screenshot_20190905-130734_Samsung%20Internet.jpg?dl=0

I tested this case on other devices in my office and I found some pattern: this not work on older devices with Android: Samsung Galaxy S5, S7, Huawei P8 Lite and I think it's related to device because I have the same problem in different browsers on the same smartphone.

**Comment by dobromir-hristov** [comment]
Looks like the `$model` is not populated. However I cant reproduce it, as I have no such old device :( 
In general, the way you are doing it is not great. Those are two different forms and they should not mix their responsibilities like that. That however does not fix the issue you are having. 

Is this persisting when you click away, focus the other input?
Check for JS errors on the mobile browser. Could be something there.

**Comment by niemaco** [comment]
After clicking off the input everything works fine, but after clearing the field again and entering the text the error appears again.

I connect my device to computer via Remote Device and check in Google Chrome Devtools , but there were no JS errors.

>In general, the way you are doing it is not great
Yes, now I know that is not the best solution :)
But earlier it seemed ok and entered well in the place where it is used, in the login popup.

**Comment by niemaco** [comment]
After spending a few long hours determining the cause of the problem, I can safely say that it is related to this comment https://github.com/vuejs/vue/issues/9777#issuecomment-478831263
So IMO it's always better to use `:value/@input` instead `of v-model` on text inputs because it is almost impossible not to have Android users.

I changed the subject to help other developers.

I think we can close this issue.
