### ISSUE TITLE
Clean form after submission - Becomes Unusable

### ISSUE THREAD

**Issue by bmpf** [vuelidate/vuelidate#537]
So I'm building an single page app and I'm trying to reuse the form after submission. For instances if the user wants to submit again. 

After the user clicks submit button, and the form is sent correctly , I wish to clean all the fields on the page to the original state. 

The fields are clean ( _sort of_ ) after the code **this.$v.$reset()**, but if I resubmit the form again **without any data**, the errors come in as **expected** but the form is **unusable** even if I put the correct data. 

There are no errors in the console and the application is stuck.

I almost spent all the afternoon testing this. 

(The solution for me is after the success response from the backend I hide the form an only show the success message. `<form action="#" @submit.prevent="submit" enctype="multipart/form-data" v-if="this.success === null">`)

Code Submit () 
```
this.$v.$touch()
if ( this.$v.$invalid ) { 
this.formErrors = true
return 
 }

await axios.post( '/api/submissao-poster' , formData , config ).then(response=> {
                    this.success = response
                    this.form = {}
                    this.$v.$reset()
                }).catch(error => {
                    if (error.response.status === 422) {
                        this.errors = error.response.data.errors
                    }
                    if (error.response.status === 404) {
                        this.$router.push('/404');
                    }
                });
                this.loadingForm = false
```

Form with correct data before submission : 
![Capturar](https://user-images.githubusercontent.com/33966960/64495165-436e4580-d28e-11e9-9843-0ae05b9983b0.PNG)

After submission with success response from the backend:
![image](https://user-images.githubusercontent.com/33966960/64495176-6e589980-d28e-11e9-9a6e-ebed37f4660b.png)

If I submit the form again its unusable even with correct data: 
![image](https://user-images.githubusercontent.com/33966960/64495189-a19b2880-d28e-11e9-8745-86e49604a7ce.png)

**Comment by dobromir-hristov** [comment]
Create a reproducible example, otherwise I cannot help. Sharing screenshots of your UI is useless. Especially in a language other than English.

**Comment by bmpf** [comment]
Sorry @dobromir-hristov .
I resolve the issue.
For some reason the `this.form = {}` and `this.$v.$reset()` don't work inside `await axios`

I had to create another method to clean the form. 
After the success response from the server I called the method `this.clearForm()`

**Now it works fine :)** 

```
clearForm () {
                this.$v.form.$reset()
                this.form = {}
          }
```
