### ISSUE TITLE
CLI 3 Issues

### ISSUE THREAD

**Issue by mituller** [vuelidate/vuelidate#539]
I am trying to Vuelidate to a CLI 3 project, but have been getting errors. I have looked around, and haven't seen the solution.

I took the HTML from the example:
```
<label class="form__label">Name</label>
   <input class="form__input" v-model.trim="$v.name.model"/>
   <div class="error" v-if="!$v.name.required">Field is required</div>
  <div class="error" v-if="!$v.name.minLength">Name must have at least {{$v.name.$params.minLength.min}} letters.</div>
```
I then added
```
import Vuelidate from 'vuelidate'
export default {
  name: 'HelloWorld',
  data() {
    return {
      name: ''
    }
  },
  validations: {
    name: {
      required,
      minLength: minLength(4)
    }
  }
}
```

And I get an error "Uncaught ReferenceError: required is not defined" If I change the call to Vuelidate to 
`import {required, minLength} from 'vuelidate'`

I get "Uncaught TypeError: Object(...) is not a function"

**Comment by dobromir-hristov** [comment]
Read the docs, import validators from "vuelidate/lib/validators"

**Comment by mituller** [comment]
I'm sorry, I did miss that thinking that if I called the package vuelidate, it would work. Even using directly what is in the documentation however, I still get errors. I am asking if there is anything that I need to do different with CLI 3. To try to eliminate any issues, I used the code directly from the documentation. I am getting an error "Property or method "$v" is not defined on the instance but reverenced during render." Also, "TypeError: Cannot read property 'name' of undefined"

If I am not seeing something in the documentation, please point me to the correct location.

Here is the code:
```
<template>
  <div>
  <div class="form-group" :class="{ 'form-group--error': $v.name.$error }">
    <label class="form__label">Name</label>
    <input class="form__input" v-model.trim="$v.name.$model"/>
  </div>
  <div class="error" v-if="!$v.name.required">Field is required</div>
  <div class="error" v-if="!$v.name.minLength">Name must have at least {{$v.name.$params.minLength.min}} letters.</div>
  <tree-view :data="$v.name" :options="{rootObjectKey: '$v.name', maxDepth: 2}"></tree-view>
  <div class="form-group" :class="{ 'form-group--error': $v.age.$error }">
    <label class="form__label">Age</label>
    <input class="form__input" v-model.trim.lazy="$v.age.$model"/>
  </div>
  <div class="error" v-if="!$v.age.between">Must be between {{$v.age.$params.between.min}} and {{$v.age.$params.between.max}}</div><span tabindex="0">Blur to see changes</span>
  <tree-view :data="$v.age" :options="{rootObjectKey: '$v.age', maxDepth: 2}"></tree-view>
</div>
</template>

<script>
import { required, minLength, between } from 'vuelidate/lib/validators'

export default {
  data() {
    return {
      name: '',
      age: 0
    }
  },
  validations: {
    name: {
      required,
      minLength: minLength(4)
    },
    age: {
      between: between(20, 30)
    }
  }
}
</script>
```

**Comment by dobromir-hristov** [comment]
You have not initiated the plug-in.
