### ISSUE TITLE
Good example of validations for state properties using Vuex/mapState

### ISSUE THREAD

**Issue by plweil** [vuelidate/vuelidate#545]
A recent issue asked for this, but the example someone provided was not terribly helpful. I could really use some clarity and a more complete answer on this. If my validations reference computer properties via mapState(), I get a warning about having no setter and the Vuelidate validations don't work regardless. If I am using mapState to map state properties, as in:

`    ...mapState([
      'isAdmin',
      'isLeader',
      'currentUserId',
     'project',
     'selected Areas'
])`

1. how should I write validations for these, e,.g., project.description, project.website, selectedAreas, etc.?

2. can I use v-model with Vuelidate/Vuex as I did before moving to Vuex, or must I treat the data as external and use separate :input and @event bindings?

3. What I have now for validations is not working:

`  validations: {
project: {
      description: {
        required,
        maxLength: maxLength(750)
      },
      department: {
        maxLength: maxLength(150)
      },
      website: {
        url,
        maxLength: maxLength(250)
      }
    },
    selectedAreas: {
     required
    }
}`

**Comment by dobromir-hristov** [comment]
If you create computed setter/getter pairs that call a mutation on each `set` then you can use vuex state as before, along with `v-model` and normal validators.

**Comment by plweil** [comment]
Ok, thanks, I will try this. With forms that have many (10-15) fields, that's a lot of boilerplate.

**Comment by dobromir-hristov** [comment]
Thats what you get with moving form state to Vuex bud. Make a helper that generates getters. Or use a plugin like this: https://github.com/maoberlehner/vuex-map-fields or https://github.com/davestewart/vuex-pathify

**Comment by plweil** [comment]
Yeah, I know. I asked for it! Thanks!
