### ISSUE TITLE
How do I make sameAs validate the model for a difference component?

### ISSUE THREAD

**Issue by lou00011** [vuelidate/vuelidate#546]
I am trying to make a simple password match validation.

I created a generic component for individual input field which takes a number of attributes which includes the validators.

Now the problem I have is this:

Both `password1` and `password2` are different components, different children of the same parent form which seed all necessary inputs. I wish to use `sameAs` to validate that a component 1 data is == to component 2 data, but according to docs, using function inside `sameAs` gives access only to THAT component, which means if I do something like 
`function () { return this.model }` is effectively making sure that it is equal to itself, which is always true.

Now I've tried to make `sameAs` access the emitted value returned by the `password1` component but somehow that always returns false.

Does `sameAs` support such a feature or do I have to roll my own validators?

**Comment by dobromir-hristov** [comment]
You can access the component's data by passing a function and either `this` or the provided parameter to the function. This should work:
```js
password1: {
  sameAs: sameAs(function () { return this.password2 })
} 
```
However this is conceptually the same as `sameAs('password2')`.
Hope this helps.

**Comment by lou00011** [comment]
Passing as parameter is a good idea. I just rolled my own function at the end. Thanks.
