### ISSUE TITLE
not detected when using normal v-model

### ISSUE THREAD

**Issue by bagaskarala** [vuelidate/vuelidate#547]
vuelidate version 0.7.4
i use bootstrap-vue v 2.0.0-rc28

```
<b-form-input
  id="interval"
  v-model.number="gauge.interval"
  type="number"
  placeholder="Enter value interval"
  :state="$v.gauge.interval.$dirty ? !$v.gauge.interval.$error? null:false : null"
></b-form-input>
```
When i use v-model like above, the $v that is change is only $invalid, the rest is still same.
This will work properly if i use v-model like this:
```
<b-form-input
  id="interval"
  v-model.number="$v.gauge.interval.$model"
  type="number"
  placeholder="Enter value interval"
  :state="$v.gauge.interval.$dirty ? !$v.gauge.interval.$error? null:false : null"
></b-form-input>
```

How this thing happened?

**Comment by dobromir-hristov** [comment]
It is stated in the docs. To initiate a dirty state you need to call the `$touch` method or use the `$model` which does it for you.
