### ISSUE TITLE
Access $v from modal window?

### ISSUE THREAD

**Issue by uclnj** [vuelidate/vuelidate#548]
Trying to put a 2FA popup inside of a bootstrap modal popup and am getting this error in the input field.

[Vue warn]: Error in render: "TypeError: Cannot read property '$model' of undefined" for the HTML
<input class="form-control" type="text" maxlength="6" v-model="$v.twofactor.$model" />

The modal command is done programmatically with $('#two-factor').modal('show') as this occurs after u/p validation.  Does $v have to be bound into the modal popup?

**Comment by dobromir-hristov** [comment]
Please give us a reproducible example, without code, nothing much we can do.

**Comment by uclnj** [comment]
Forgot to post the link

https://jsfiddle.net/gmerideth/ysqo610r/2/

**Comment by dobromir-hristov** [comment]
The example is broken. twoFactor does not have validation rules, thus no $model.

**Comment by uclnj** [comment]
a two second change of the template from "text" to "twofactor" has the same results (as does my code.)

https://jsfiddle.net/gmerideth/ysqo610r/5/

**Comment by dobromir-hristov** [comment]
Please fix your console errors. 
To have access to `$model` of any field, it requires a validation rule to be set.
