### ISSUE TITLE
Vuelidate and vue-map-fields: Cannot read property '$model' of undefined

### ISSUE THREAD

**Issue by plweil** [vuelidate/vuelidate#549]
Is anyone successfully using Vuelidate with Vuex and vue-map-fields? In trying to implement these together, the v-model is unreadable:

`TypeError: Cannot read property '$model' of undefined`

I'm not sure whether Vuelidate just doesn't recognize the generated computed properties, or whether I'm naming things improperly.

I'm using mapFields() to map fields in a nested object:

`    ...mapFields([
     'form.project_name',
     'form.description',
     'form.tangible_outcomes',
      'form.website',
      'form.department',
      'form.school_id',
    ]),`

In vue-map-fields, when using nested data structures, the string after the last dot is used for defining the name of the computed property.

`validations: {
      project_name: {
        required,
        maxLength: maxLength(150),
      }
}`

And in my blade template:

`    <input
      type="text"
      id="project_name_input"
      name="project_name_input"
      v-model="$v.project_name.$model"
    >`

**Comment by dobromir-hristov** [comment]
Could you give me a codesandbox reproducing the issue? 
:)

**Comment by plweil** [comment]
This was due to an error on my part. My mistake. Please disregard.

**Comment by embarekmessai** [comment]
What was the solution ? because i have the same issue.

**Comment by plweil** [comment]
I don't recall all of the specifics, but it was a naming issue (by the way, I mistakenly referred to "vue-map-field", when I should have said "vuex-map-fields"). I was able to solve it by renaming the computed properties by passing an object instead of an array. E.g.,

``` computed: {
    ...mapFields({
      form_project_name: 'form.project_name',
      form_description: 'form.description',
    [etc.]
    }),
  },
```

Then I used  the names of these computed properties in my validations:

```validations: {

    form_project_name: {
        required,
        maxLength: maxLength(150),
      },
    form_description: {
        required,
        maxLength: maxLength(750)
      },
   [etc.]
   },
```

And then referenced these validations in my html:

```
   <input v-model="$v.form_project_name.$model">
```

So the moral of the story is be careful with how you are naming the computed properties and reference those names properly and consistently in your validations and html. It's easy to get confused and get the names mixed up. I hope this helps.

**Comment by plweil** [comment]
> I'm in a similar boat -- vuex, vuex-map-fields, vuelidate -- but I would like to stop the commit if validation fails.

You mean stop the form from submitting ? There’s a sample method in the docs under Form Submission.

**Comment by bryanbuchs** [comment]
> You mean stop the form from submitting ? There’s a sample method in the docs under Form Submission.

No, not quite. I need to stop the field from making the commit. There's no "submit" button, just binding from the component to the store with vuex-map-fields. 

What I've come up with is a proxy. My "form" model passes to the proxy. Proxy checks if `$v` contains any errors, and if not passes to the "store".  It's workable, but I've now got to set that up for 20 fields, and that's a lot of boilerplate. 

This isn't really a vuelidate now that I think about it. Sorry for hijacking the ticket!
