### ISSUE TITLE
Triggering validation for single keys on an $each validation?

### ISSUE THREAD

**Issue by dugajean** [vuelidate/vuelidate#551]
How to trigger validation for a list of items? Here's an example of validation declaration:

```
  validations: {
    request: {
      currency: {
        required
      },
      total_amount: {
        required,
        decimal,
      },
      cover_until: {
        required,
      },
      invoices: {
        $each: {
          amount: { required, decimal },
          vat: { required },
          issued_at: { required },
          due_at: { required }
        }
      }
    }
  },
```

Now when I want to trigger the validation for invoices, I presume I would do something like this:

```
this.$v.request.invoices.$touch()
```

What about when I want to validate only the `issued_at` key of a single invoice? How would that look like?

Thanks

**Comment by dobromir-hristov** [comment]
Just use `this.$v.request.invoices.$each[i].issued_at.$model` on your `v-model` or trigger `this.$v.request.invoices.$each[i].issued_at.$touch()` if you like.

**Comment by dugajean** [comment]
Thanks!

**Comment by Sonit90** [comment]
this.$v.request.invoices.$each[i].issued_at.$touch() Doesn't work with latest Vue 3 build.  
$v.request.invoices.$each is not an array anymore, so there is no way to trigger field from collection directly.

**Comment by dobromir-hristov** [comment]
That API is no longer available in the new Vuelidate.

You have to use child components instead. Those would have their own vuelidate instances

**Comment by Sonit90** [comment]
There should be a way to not introduce another component.

const state = reactive( 
{
translations: [{id: 1, title: 'Sample title', description: 'Sample description'}]
}
)


const rules={
 translations: {
            $each: helpers.forEach({
                title: {
                    required,
                },
                description: {
                    required,
                },
            }),
        },
}
useVuelidate(rules as any, voucher, { $lazy: true });

<input v-model = state.translations[0].title/>
<input v-model =  state.translations[0].description/>

i can trigget v$.translations.$touch, but it will trigger both title and description

**Comment by dobromir-hristov** [comment]
Sorry, there isnt. That's the drawback of this helper.

**Comment by robertkabat** [comment]
For what it is worth, I figured out that you can ditch this `$each` helper and just create your schema dynamically. 

```javascript
const rules = computed(() => ({
        candidateRequirements: jobStore.jobAd.candidateRequirements.map(() => ({
            id: { required, numeric },
            requirement: { required, text },
        })),
    }));
```

In my specific case I have a Pinia store where I am dynamically adding the fields on button click. I am grabbing these from the store. Then I am creating new rule for each and every one of them, this way I can dynamically construct my schema without using `$each`. 

Now thanks to this I can do: `@blur="jobAdFormValidation?.candidateRequirements[index].requirement.$touch"`

I hope it helps!
