### ISSUE TITLE
Validation against parent object

### ISSUE THREAD

**Issue by mlaw93** [vuelidate/vuelidate#557]
I have a vue page that takes an object that is an array of objects.  Those objects are displayed in a v-datatable.  When a user clicks on one or creates a new entry that item is loaded into an "editedItem" object for a popup form. I need to make sure that they are not creating a duplicate (checking object's name property against all the objects already defined in the parent object).

Imagine the vuetify example of desserts.  There is an array of dessert objects and they each have  name, calories, fat, etc properties.  On adding a new dessert, I want to prevent the person from adding another dessert by the same name.

I've googled and googled and cannot find any example of what I am attempting to accomplish.  Any help to get me going in the right direction would be much appreciated.

**Comment by dobromir-hristov** [comment]
You could add a validator on the `deserts` array that check if all of its items have unique names.
Here are some ideas how to check. https://stackoverflow.com/questions/30735465/how-can-i-check-if-the-array-of-objects-have-duplicate-property-values
This should trigger an error on the whole parent, not on the individual repeated item. If you want each item to have its own error, that will be quite allot of looping around. I would just move this to the BE at the time of saving.

**Comment by dobromir-hristov** [comment]
I will close for now so we dont clutter.
