### ISSUE TITLE
custom validation..

### ISSUE THREAD

**Issue by rubencool** [vuelidate/vuelidate#559]
I faced a problem while using Or validation. Since i had to check both phone number and landline number in single input field know as agent/customer Contact, i had listed code below.
 
**Template Section**
>  <b-form-group>
        <label required>Agent/Customer Contact </label>
                  <b-form-input  
                                 v-model.trim="customerContact"
                                 placeholder="Agent/Contact Number">
                  </b-form-input>
                  <div class="form-group__message"
                       v-if="!$v.customerContact.required  && $v.customerContact.$error" >
                    Field is required
                  </div>
                  <span class="form-group__message" v-if="$v.customerDetail.customerContact.required
                               && $v.customerContact.$invalid">
                             Please enter Valid mobile number.
                  </span>
                   <span class="form-group__message" v-if="$v.customerContact.required
                               && $v.customerContact.$invalid">
                             Please enter valid landline number
                  </span>
               

**On Data section..**
`validations: {
       customerContact: {
              required,
              mobileNumberWithOutCountryCode,
              landlineNumber
            }
}`

please note that both **mobileNumberWithOutCountryCode** and **landlineNumber** is my custom validation which is imported and i have written its validation myself. so how can i perform Or validation on mobileNumberWithOutCountryCode and landlineNumber. Since user must be able to write both valid mobile number and landline number in customerContact input field.

**Comment by dobromir-hristov** [comment]
Please provide a valid fiddle or codesandbox, showing your validators in action.
The template doesnt give much, if any light on the issue.

Generally, you should use it like 
```js
validations: { 
  required,
  customerContact: or(validator1, validator2)
}
```
