### ISSUE TITLE
It's time to make a bump version to 1.0 and stick to semver

### ISSUE THREAD

**Issue by MaG21** [vuelidate/vuelidate#583]
3 years ago (23 releases later) someone asked if this project was production ready, issue #18 and the response was:

> We’re yet to release the 1.0 version. We started from 0.1 to have the flexibility to make some breaking changes if needed before we reach 1.0, but I hope this won’t be necessary.
> After that we will try to stick to semver.
> 
A perfectly reasonable response but, Github says this project is used by +9k projects which means a breaking change at this point is something pretty much unfeasible, unless breaking those people's projects is the ultimate goal.

Why not just make a bump version to 1.0 and start using Semver and from that point any release should stick to semver's guidelines?.

Semver, as we all know, will make things more predictable and compatible with many dependency tools.

**Comment by shentao** [comment]
I agree. We will likely release the current version as 1.0. There are however things done for v2.0 which is already in alpha. https://github.com/vuelidate/vuelidate/tree/next
