### ISSUE TITLE
Integer validator does not reject trailing alpha characters

### ISSUE THREAD

**Issue by mhldtna** [vuelidate/vuelidate#586]
A field has an integer validation, as in:

`      weight: {
        integer,
        between: between(-99999, 99999),
      },`

... it (correctly) rejects input such as "a" but (incorrectly) accepts "1a".  In other words, it is accepts as valid trailing characters that are not numeric.

**Comment by dobromir-hristov** [comment]
You sure about this? Because the regex is pretty solid on this one, we also have tests for this.

**Comment by mhldtna** [comment]
My apologies, this turned out to be my bug.

**Comment by bryanbuchs** [comment]
I had the same issue, resolved it by removing the `.number` modifier from my v-model biding

`v-model.number="dataModel"`
