### ISSUE TITLE
Remove ref helper from Vuelidate 2

### ISSUE THREAD

**Issue by dobromir-hristov** [vuelidate/vuelidate#589]
- Start Date: (02-12-19)
- Reference Issues:
- Implementation PR: 

# Summary

Remove the `ref` helper from Vuelidate 2's `@vuelidate/validators` package and related validators as it is mostly inconsistent and incompatible with the new build.

Instead of passing strings to reference values or functions, we directly pass a reference to the required properties.

# Basic example

For validators like `sameAs` or `requiredIf` which use the `ref` helper internally, users will have to change the way they use those validators. 

Instead of passing a string with the name of the reference field, they would need to pass the field itself.

```js
data: ()=>({
  form: {
    password: '',
    confirmPassword: '',
    over18: ''
  }
}),
validations(){
  return {
    form: {
      password: { required },
      confirmPassword: { sameAs(this.form.password) },
      over18: { requiredIf(this.someComputedProperty) }
    }
  }
},
computed: {
  someComputedProperty(){}
}
```

# Motivation and Detailed design

### Confusing syntax

In the current Vuelidate 0.x implementation, the `ref` helper when passed a reference as a **string,** it only retrieves properties in the same object scope as the currently validated property.

Check the example below:

```js
{
  form: {
    personal: {
      first_name: '',
      last_name: ''
    },
    business: {
      email: '',
      address: ''
    }
  }
}
```

If we want to have access to `email` from `first_name` we cant do `requiredIf('form.business.email')`, we can only access properties inside the `personal` property.

To achieve that, we had to pass a function, which then has it's `this` scope bound to the Vue instance or use the passed `parentVM` parameter.

Deep property selectors are also not possible with the `string` notation, you need to use the function method, mentioned above. (There is a PR for this, but it only works with simple objects, not with arrays, maps and so on).

### Incompatible with Composition API

As **Vuelidate 2** is now built with [Composition API](https://vue-composition-api-rfc.netlify.com/#api-introduction), and can be used with it, we need to comply with some of the limitations that it brings with it.

1. There is no Vue instance yet inside the `setup` hook, which prevents us from binding a validator's `this` context to it.
2. We do not have a way to find properties inside the parent object.

# Drawbacks

1. Users will have to use a function for `validations`  opposed to a simple object, to have access to component state.
2. Not backwards compatible. A manual rewrite on custom written validators using `ref` is needed + update the usage for `sameAs,requiredIf,requiredUnless`.
3. All custom validators need to return a higher order function, which returns a validator
4. For simple use cases, it may be a bit more boilerplate to pass a reference than just the property name of the state -  `sameAs('password')` vs `sameAs(this.form.personal.passsword)`.

```js
// OLD WAY
// definition
const oldComparisonValidator = value => ref('someProp') === value
// usage
{
  name: { isEqualToSomeProp: oldComparisonValidator } 
}

// NEW WAY
// definition
const newComparisonValidator = compareTo => value => value === compareTo
// usage
{
  name: { isEqualToAnything: newComparisonValidator(this.someProp) } 
}
```

# Alternatives

1. We leave it as is, and those validators and helpers just dont work with composition api (worst case)

# Adoption strategy

1. The `validations` property would need to be transformed to a method:

```js
// from
{
  validations: { ... }
}
// to
{
  validations() {
    return {...}
  }
}
```

  2. All custom validators using a `ref` would need to be re-written into higher order functions like:

```js
// before
const validator = (value) => value === ref('someValue')
// after
const valudator = (referenceToCompare) => (value) => value === referenceToCompare
```

# Unresolved questions

**Comment by miralize** [comment]
> The validations property would need to be transformed to a method:

Is this for all validation properties or only ones that are based on reactive data?

**Comment by dobromir-hristov** [comment]
It works for both for now, as long as you dont need to use `sameAs`, `requiredIf` and `requiredUnless`. We have not decided of we want to enforce a function declaration yet.

**Comment by blowsie** [comment]
> There is no Vue instance yet inside the setup hook, which prevents us from binding a validator's this context to it.

True but there is this `import { getCurrentInstance } from '@vue/composition-api'`
Im not sure if that will be in vue 3, or if its any help.

**Comment by blowsie** [comment]
Is there vuelidate 2 branch?

**Comment by dobromir-hristov** [comment]
That is something fairly new, that was not in the initial spec. We will investigate further, but I do think that having the current app instance in the validators nice.

**Comment by dobromir-hristov** [comment]
Yeah there is - https://github.com/vuelidate/vuelidate/tree/next

**Comment by blowsie** [comment]
To be clear, is it currently not possible to use vuelidate 2 with the `setup()` hook?

**Comment by dobromir-hristov** [comment]
You can, import the default export and pass an object for your data and another for the validations.
I will document it these days.

**Comment by blowsie** [comment]
Thanks, I think i got it

```
<script>
import { ref, reactive } from '@vue/composition-api'
import { email, required } from '@vuelidate/validators'
import useVuelidate from '@vuelidate/core'
import useLogin from '@/composables/auth/useLogin'
export default {
  name: 'LoginForm',
  components: { BaseButton, BaseInput },
  setup() {
    // Wrapping this in reactive since the plugin has a bug with .value
    const loginService = reactive(useLogin())
    const username = ref('sblowes')
    const password = ref()
    const submit = () => {
      loginService.login(username.value, password.value)
    }

    let validation = useVuelidate(
      {
        username: { required, email },
        password: { required }
      },
      { username, password }
    )

    return {
      username,
      password,
      submit,
      loginService,
      validation
    }
  }
}
</script>
```

**Comment by blowsie** [comment]
My sample above didn't totally work, the model updated but `$dirty` and `$valid` did not update. Looking forward to the docs 👍

**Comment by blowsie** [comment]
https://github.com/vuelidate/vuelidate/issues/607

**Comment by mycarrysun** [comment]
I just tried to get `sameAs` working and I can't figure out how to make it use the reactive state from my component...is this actually possible or does there need to also be additional functionality added to the `useVuelidate` to take a function as a parameter for the validations?

**Comment by RamRivas** [comment]
Hi, I'm having the same problem, this is my vue code:

SignUp.vue

```
import axios from 'axios'
import { useVuelidate } from '@vuelidate/core'
import { requiredH, availableH, emailH, minLengthH, sameAsH } from '../utils'

export default {
	name: "login",
	data: ()=>
	({
		usuario: {
			id: 0,
			username: '',
			password: '',
			pwd2: '',
			dui: '',
			nit: '',
			nombres: '',
			apellidos: '',
			code: 0,
			mail: '',
			confirm: 0,
		},
		modal: {
			active: ""
		},
		errors: {
			session: null
		}
	}),
	setup: () => ({ v$: useVuelidate()}),
	validations: () => ({
			usuario: {
				nombres: { requiredH },
				apellidos: { requiredH },
				username: {
					requiredH,
					availableUser: availableH("usuario","User", "usuario", axios),
					minLength: minLengthH("El usuario", 6)
				},
				mail: {
					requiredH,
					emailH,
					availableMail: availableH("email", "Email", "correo electrónico", axios)
				},
				pwd: { requiredH, minLength: minLengthH("La contraseña", 8) },
				dui: { requiredH },
				nit: { requiredH },
				pwd2: { sameAsPassword: sameAsH( "Las contraseñas", function(){
					return this.usuario.password
				} ) }
			}
	})
```
Please take special atention to pwd2 validation

I'm importing sameAsH helper from utils.js

utils.js
```
import { required, minLength, email, helpers, sameAs } from '@vuelidate/validators'
import config from './Config'

const sameAsH = (impresion, parametro) => {
    let compare  =  helpers.withMessage(
        impresion + " no coinciden",
        sameAs(parametro)
    );

    return compare;
}

exports {
   sameAsH
}
```

However, the sameAs() function is always returning false,  until my password match or not. and "parametro" content print this when I make a console.log with it:

```
function(){
	return this.usuario.password
}
```
As if the function were a string, and i can't access the password value in my v-model.

Please help :C

**Comment by dobromir-hristov** [comment]
Change the validations to a normal function. Fat arrow functions cannot get their context changed.

**Comment by RamRivas** [comment]
> Change the validations to a normal function. Fat arrow functions cannot get their context changed.

Like this?

validations: function(){
		return {
			usuario: {
				nombres: { requiredH },
				apellidos: { requiredH },
				username: {
					requiredH,
					availableUser: availableH("usuario","User", "usuario", axios),
					minLength: minLengthH("El usuario", 6)
				},
				mail: {
					requiredH,
					emailH,
					availableMail: availableH("email", "Email", "correo electrónico", axios)
				},
				pwd: { requiredH, minLength: minLengthH("La contraseña", 8) },
				dui: { requiredH },
				nit: { requiredH },
				pwd2: { sameAsPassword: sameAsH( "Las contraseñas", function(){
					return this.usuario.password
				} ) }
			}
		}
	},

**Comment by dobromir-hristov** [comment]
```js
validations(){
  return {
    pwd2" {
      sameAsPassword: sameAs('message', this.password)
    }
  }
}
```

**Comment by RamRivas** [comment]
> ```js
> validations(){
>   return {
>     pwd2" {
>       sameAsPassword: sameAs('message', this.password)
>     }
>   }
> }
> ```

Omg man thank you so f*cking much, I have a month and a few weeks dealing with this sh*t.
It works, but I have to do all out of utils.js

Do you know a way for passing this.usuario.pwd value to utils.js?, because when I'd tried to set "parametro" with this value, in utils.js "parametro" is empty, of course because in utils.js there are no some v-model.

**Comment by dobromir-hristov** [comment]
I am going to close this for now, as we removed the ref helper.

**Comment by folmert** [comment]
@dobromir-hristov Why the [migration guide](https://vuelidate-next.netlify.app/migration_guide.html) doesn't cover this change?
