### ISSUE TITLE
Array validation

### ISSUE THREAD

**Issue by ravindraplande** [vuelidate/vuelidate#590]
I have an array and i want anyone row is required from that.

$each - Apply on every row
` images: {
       $each : {
           path : {required}
      }
  } `

$anyOne - I want anyone row is required or IfRequired
` images: {
       $anyone: {
           path : {required}
      }
  } `

**Comment by dobromir-hristov** [comment]
I am sorry, are you requesting a feature or asking for help? Have you tried anything yet?

Overall you can have a validator on `images` that checks it's inner state. Something like:
```js
import { common } from 'vuelidate/validators'
{
  images: {
    allPathsValid(){
       return this.images.some(img => common.req(img.path))
    }
  }
}
```
