### ISSUE TITLE
[HELP] Problem working with quasar and validate with external API

### ISSUE THREAD

**Issue by abkrim** [vuelidate/vuelidate#591]
Hi
I've a problems with the understanding of the validation with external rules (API) and I am unable to see the problem
In [codesandbox example](https://codesandbox.io/s/sharp-merkle-mp7wf?fontsize=14&hidenavigation=1&theme=dark) I need use 3 validators:

- Validad domain name
- Required
- And check with open API if domain is taken.

Api return 200 and message 'Domain is taken

```
{
    "success": true,
    "data": "auer.org",
    "message": "Domain is taken"
}
```

And 404 if domain is not taken

```
{
    "error": "No query results for model [App\\Models\\Domain] aueraa.org"
}
```
I have spent practically all my day going around solving this problem, and I am not able.
My apologies if this is not the right way

**Comment by dobromir-hristov** [comment]
Just use these instead - https://quasar.dev/vue-components/input#External-validation
```
      error-message="Please use maximum 3 characters"
      :error="!isValid"
```
