### ISSUE TITLE
Vuelidate 2 / Vue composition API example.

### ISSUE THREAD

**Issue by blowsie** [vuelidate/vuelidate#607]
I tried to get up and running with vuelidate 2 and the vue composition api.

I got as far as setting it up, and I have the validation model being returned, but its not totally working, the model updated but `$dirty` and `$valid` did not update.

Could we please get an example of how it should work?

**Here is what i tried:**
```vue
<script>
import { ref, reactive } from '@vue/composition-api'
import { email, required } from '@vuelidate/validators'
import useVuelidate from '@vuelidate/core'
import useLogin from '@/composables/auth/useLogin'
export default {
  name: 'LoginForm',
  setup() {
    // Wrapping this in reactive since the plugin has a bug with .value
    const loginService = reactive(useLogin())
    const username = ref()
    const password = ref()
    const submit = () => {
      loginService.login(username.value, password.value)
    }

    let validation = useVuelidate(
      {
        username: { required, email },
        password: { required }
      },
      { username, password }
    )

    return {
      username,
      password,
      submit,
      loginService,
      validation
    }
  }
}
</script>
```

**Comment by blowsie** [comment]
Perhaps it have something to do with `$autoDirty`? Im not sure how to use `$autoDirty` in my component.

**Comment by blowsie** [comment]
Works with the following config.  👍 .
Would be great to get a clarification to make sure this is the right way of using it.
 
 ```
  let $autoDirty = true,
  let validation = useVuelidate(
      {
        username: { required, email, $autoDirty  },
        password: { required, $autoDirty }
      },
      { username, password }
    )
```

**Comment by javiercbk** [comment]
hey @blowsie can you post the full solution ... I'm currently experiencing the same issue but I'm not sure what am I doing wrong.

Here is my vue file

```vue
<template>
  <div class="container">
    <div class="columns is-centered">
      <div class="column is-5-tablet is-4-desktop is-3-widescreen">
        <form action="" class="box" @submit="login" novalidate>
          <div class="field">
            <label for="" class="label">Email</label>
            <div class="control has-icons-left">
              <input
                type="email"
                v-model="email"
                class="input"
                :class="{ 'is-danger': $v.email.$invalid && $v.email.$dirty }"
              />
              <span class="icon is-small is-left">
                <b-icon pack="fas" icon="envelope"> </b-icon>
              </span>
            </div>
          </div>
          <div class="field">
            <label for="" class="label">Password</label>
            <div class="control has-icons-left">
              <input
                type="password"
                v-model="password"
                class="input"
                :class="{
                  'is-danger': $v.password.$invalid && $v.email.$invalid
                }"
              />
              <span class="icon is-small is-left">
                <b-icon pack="fas" icon="lock"> </b-icon>
              </span>
            </div>
          </div>
          <div class="field">
            <button
              class="button is-success"
              :disabled="$v.$invalid && $v.$dirty"
            >
              Login
            </button>
          </div>
        </form>
      </div>
    </div>
  </div>
</template>

<script lang="ts" src="./login-form.ts"></script>

```

and my typescript file

```ts
import { createComponent, reactive, toRefs } from "@vue/composition-api";
import { useState } from "@u3u/vue-hooks";
const { email, required } = require("@vuelidate/validators");
const useVuelidate = require("@vuelidate/core").default;
import store from "@/store";
import router from "@/router";
import { AuthCredentials } from "@/store/login";

export default createComponent({
  setup() {
    const storeState = {
      ...useState("login", ["loading", "error"])
    };

    const model = reactive({
      email: "",
      password: ""
    });

    const $v = useVuelidate(
      {
        email: { required, email, $autoDirty: true },
        password: { required, $autoDirty: true }
      },
      model
    );

    const login = function(e: Event) {
      e.preventDefault();
      if (!$v.$invalid) {
        const credentials: AuthCredentials = {
          email: model.email,
          password: model.password,
          onLoginSuccess: () => {
            let nextRoute = store.getters["session/savedRoute"];
            if (nextRoute) {
              nextRoute = { name: "events" };
            }
            router.replace(nextRoute);
            store.dispatch("session/clearSavedRoute");
          }
        };
        store.dispatch("login/login", credentials);
      }
    };

    return {
      ...storeState,
      ...model,
      login,
      $v
    };
  }
});
```

**Comment by fajuchem** [comment]
Did anyone manage to make it work with reactive? I have a nested ref and it doesn't update the $v even though the $model is updated correctly.

**Comment by javiercbk** [comment]
@fajuchem Nope. I was forced to use `ref`. Please add a comment if you find a way!!!

**Comment by ansarizafar** [comment]
Is there an ETA for Vuelidate@next release? Is anyone using it in production with composition API?

**Comment by shentao** [comment]
We should have a working alpha/beta release within a few weeks! We recently managed to restore backwards compatibility but are still struggling with some smaller issues.
Once we ship that, we would hugely appreciate if people tried it and reported their feedback.

**Comment by ansarizafar** [comment]
> We recently managed to restore backwards compatibility but are still struggling with some smaller issues.

@shentao If there are issues with backwards compatibility than why not just first release a version for Vue 3 composition api  without backwards compatibility. 

I have started working on a new project with Vue 3 and I badly need Vuelidate@next.

**Comment by shentao** [comment]
Well, in that case, @ansarizafar keep your fingers crossed for this weekend! 🤞

**Comment by raphaelkieling-egsys** [comment]
@javiercbk, @fajuchem well, i did the without problem (in my project). I use `toRefs(form)` to transform all to refs. I not have nested entities but i think that you can create a recursive function to make that. If i found a better way (i need to my work) i bring.

```ts
<script lang="ts">
import { defineComponent, reactive, toRefs } from "@vue/composition-api";
import useCrudSave from "@/compositions/useCrudSave";
import ProvidenciaTipificacao from "@/data/types/providenciaTipificacao";
import { required } from "@vuelidate/validators";
import useVuelidate from "@vuelidate/core";

export default defineComponent({
  props: ["store", "routePath"],
  setup({ store, routePath }: any, { root }) {
    const form = reactive({
      codigo: "",
      desmembramento: null,
      descricao: "",
      medidaAdministrativa: "",
    });

    const v$ = useVuelidate(
      {
        codigo: { required, $autoDirty: true },
        desmembramento: { required, $autoDirty: true },
        descricao: { required, $autoDirty: true },
        medidaAdministrativa: { required, $autoDirty: true },
      },
      toRefs(form)
    );

    const crudSaveRefs = useCrudSave<ProvidenciaTipificacao>({
      route: root.$route,
      router: root.$router,
      basePath: routePath,
      store: store(),
      form,
    });

    return {
      ...crudSaveRefs,
      v$,
    };
  },
});
</script>
```

**Comment by mfru** [comment]
@raphaelkieling-egsys which version of vuelidate are you running?

I am on  `"@vuelidate/core": "^2.0.0-alpha.21"` and `"@vuelidate/validators": "^2.0.0-alpha.18"` and the following example code (trying with your toRefs suggestion) is not working for me (the fields will never validate even though required should be satisfied):

```vue
<script>
// Relevant issues
// https://github.com/vuelidate/vuelidate/issues/589
// https://github.com/vuelidate/vuelidate/issues/607
import { ref, reactive, computed, toRefs } from '@vue/composition-api';
import useVuelidate from '@vuelidate/core';
import { required } from '@vuelidate/validators';

export default {
	setup() {
	       // NOTE: fieldsTest and formTemplateTest mimic dynamic data that is coming from
	       // another class in prod
		const fieldsTest = ['email', 'password'];

		const formTemplateTest = {
			email: '',
			password: ''
		};

		const state = reactive({ ...formTemplateTest });

		// Dynamic rule generation
		let validationFields = reactive({});
		fieldsTest.forEach(fieldName => {
			validationFields[fieldName] = { required };
		});
		const rules = computed(() => {
			return {
				state: {
					...validationFields
				}
			};
		});

		const $v = useVuelidate(rules.value, toRefs(state));

		const updateValue = (key, value) => {
			console.debug('=== Entering updateValue ===');
			console.debug('key', key);
			console.debug('value', value);

			state[key] = value;

			$v.value.state[key].$touch();

			console.debug('=== Leaving updateValue ===');
		};

		console.debug('$v', $v);
		console.debug('state', state);
		console.debug('rules', rules);

		return {
			state,
			$v,
			updateValue
		};
	}
};
</script>
```

**Comment by dobromir-hristov** [comment]
> @raphaelkieling-egsys which version of vuelidate are you running?
> 
> I am on  `"@vuelidate/core": "^2.0.0-alpha.21"` and `"@vuelidate/validators": "^2.0.0-alpha.18"` and the following example code (trying with your toRefs suggestion) is not working for me (the fields will never validate even though required should be satisfied):
> 
> ```vue
> <script>
> // Relevant issues
> // https://github.com/vuelidate/vuelidate/issues/589
> // https://github.com/vuelidate/vuelidate/issues/607
> import { ref, reactive, computed, toRefs } from '@vue/composition-api';
> import useVuelidate from '@vuelidate/core';
> import { required } from '@vuelidate/validators';
> 
> export default {
> 	setup() {
> 	       // NOTE: fieldsTest and formTemplateTest mimic dynamic data that is coming from
> 	       // another class in prod
> 		const fieldsTest = ['email', 'password'];
> 
> 		const formTemplateTest = {
> 			email: '',
> 			password: ''
> 		};
> 
> 		const state = reactive({ ...formTemplateTest });
> 
> 		// Dynamic rule generation
> 		let validationFields = reactive({});
> 		fieldsTest.forEach(fieldName => {
> 			validationFields[fieldName] = { required };
> 		});
> 		const rules = computed(() => {
> 			return {
> 				state: {
> 					...validationFields
> 				}
> 			};
> 		});
> 
> 		const $v = useVuelidate(rules.value, toRefs(state));
> 
> 		const updateValue = (key, value) => {
> 			console.debug('=== Entering updateValue ===');
> 			console.debug('key', key);
> 			console.debug('value', value);
> 
> 			state[key] = value;
> 
> 			$v.value.state[key].$touch();
> 
> 			console.debug('=== Leaving updateValue ===');
> 		};
> 
> 		console.debug('$v', $v);
> 		console.debug('state', state);
> 		console.debug('rules', rules);
> 
> 		return {
> 			state,
> 			$v,
> 			updateValue
> 		};
> 	}
> };
> </script>
> ```
> 

Your rules are not correct. The rules should have the same structure as the state, you are nesting them in a `state` key.

	```js
const rules = computed(() => {
			return {
				...validationFields
 			};
});

const v = useVuelidate(rules, state);
```

Also Rules and State accepts `computed` and `reactive`.

Last, `$v` should be renamed with `v` or `v$`.
