### ISSUE TITLE
Dynamically validating object properties not yet defined  

### ISSUE THREAD

**Issue by RiqueBR** [vuelidate/vuelidate#611]
Hope I'm not repeating what somebody may have mentioned this. But I've got an issue where I need to dynamically emit values based on which input text the user may type in, could be in one or the other or even  both. Therefore, the actual overarching value being emitted is an empty object. 

Here's an example: https://jsfiddle.net/zqb560u4/3/

I'm still relatively new to vuelidate and vue, but just wondering if the above can be achieved?

Thanks

**Comment by dobromir-hristov** [comment]
The values need to be pre-defined in the data for it to work. I am sorry.
You could set `validations` to be a function that returns a validation object. You would have to use `Vue.set` to set your response as well.
