### ISSUE TITLE
$error value never updates (remains false)

### ISSUE THREAD

**Issue by ariellevitsky** [vuelidate/vuelidate#612]
The individual errors (i.e. "required") are updated once an input is touched but the $error value never changes.

`               <p>
                    <label>
                        Language
                        <span class="asterisk">
                            *
                        </span>
                    </label>
                    <select
                        v-model="result.language"
                        :class="{ 'form-error': $v.result.language.$error }"
                    >
                        <option disabled selected>
                            ---
                        </option>
                        <option
                            v-for="language in languages"
                            :key="language.type"
                            :value="language.type"
                        >
                            {{ language.name }}
                        </option>
                    </select>
                    <span v-if="!$v.result.language.required" class="tooltip">
                        The language field is required.
                    </span>
                </p>`

    validations: {
        result: {
            language: { required },
        }
    }

**Comment by dobromir-hristov** [comment]
You are probably not calling the `$touch` to make the field dirty. Either to that or use `$v.result.language.$model` in your `v-model.

The docs always help with those issues :)

**Comment by ariellevitsky** [comment]
I was under the impression that you only had to call $touch manually if you are not using v-model.

"In case you don't want to modify your model directly, you can still use separate :input and @event bindings. This is especially useful if you are using data from external source, like Vuex store or props. In that case you have to manually take care of setting the $dirty by calling $touch() method when appropriate."

Did I read that wrong?

**Comment by ariellevitsky** [comment]
I created the fiddle:

https://jsfiddle.net/a0eoptuw/1/

The error persists. I'm not sure if it's because it's a dropdown. I was under the impression that as long as a required dropdown is null then $error would be true.

**Comment by ariellevitsky** [comment]
Never mind, I misread the $error value API. I didn't realize that for $error to be true the field would BOTH have to be dirty and invalid.

I was treating it as invalid.

I'm just going to change all of my conditional error classes to apply when $invalid = true.
