### ISSUE TITLE
Styles bugs

### ISSUE THREAD

**Issue by jakubstankowski** [vuelidate/vuelidate#613]
### Make sure that you are familiar with documentation before submitting an issue.

  https://vuelidate.netlify.com/

### Please use the following jsfiddle to provide a reproduction of your problem

  https://jsfiddle.net/koc7x6h4/

Issues without a working fiddle are generally much harder to solve and usually take much more time to actually do it.

I have problem with styles, because it's looking very bad, totaly different like in documentation example

I used the same code from documentation, and it's lloking that:
![image](https://user-images.githubusercontent.com/36790120/71980212-cf35b580-321f-11ea-9daa-0d62e1912dc6.png)

Look my code in jsfiddle:  https://jsfiddle.net/koc7x6h4/

thanks for helping!

**Comment by dobromir-hristov** [comment]
Vuelidate does not style your components. That is up to you, I am sorry.
