### ISSUE TITLE
v-model.trim for child inputs don't work as expected

### ISSUE THREAD

**Issue by luizmacfilho** [vuelidate/vuelidate#614]
When I try to validate an input by passing its validator as prop, the behavior of v-model.trim is affected.

The biggest problems are:
- Start input value with space (the first space entered is not displayed).
- Insert spaces at end and blur (spaces are still displayed in input).

Here is an example with a child input as a component and a common input: https://jsfiddle.net/luizmacfilho/ngvp78y0/

**Comment by dobromir-hristov** [comment]
I dont think its a bug. You are v-model-ing the `$model` which will change the `$dirty` state. Even if you hit space, an action is performed, and thus the validator is triggered.

**Comment by luizmacfilho** [comment]
It is okay to change the `$dirty` state, but the value should be displayed in the input, even if there is an error, like the second input in the example.
