### ISSUE TITLE
Docs don't match the functionality of $anyError on 0.7.4

### ISSUE THREAD

**Issue by keisha-rw** [vuelidate/vuelidate#618]
According to the docs on https://vuelidate.js.org/#sub-v-values, $anyError should be set based on the values of $error for each field.  However, the code for this is not yet released and $anyError still depends on $anyDirty, $pending, and $invalid.  Can we get a release for this commit (https://github.com/vuelidate/vuelidate/commit/9e15b2277b8da04dfe2161b12c5ee4df32a21d12), so the docs match the latest code release?  If not, can the docs be reverted?  This caused us quite a bit of confusion when we were working through a validation issue on our app.

Thanks for all the great work you've been doing!

**Comment by dobromir-hristov** [comment]
Very sorry about this. We were just too focused on the rewrite. Released as https://www.npmjs.com/package/vuelidate/v/0.7.5. Give it a go :)

**Comment by keisha-rw** [comment]
Completely understandable.  Thanks for the quick turnaround!
