### ISSUE TITLE
How to use custom validation function from my component methods?

### ISSUE THREAD

**Issue by jack-fdrv** [vuelidate/vuelidate#621]
Instead
`const mustBeCool = (value) => value.indexOf('cool') >= 0`
How to call a method from component
```
validations: {
  gsurl: {
    this.mustBeGgl
  }
}
```
and
```
methods: {
  mustBeGgl(v) {
    return v.indexOf('google.com') >= 0		
  },
}
```

How?

**Comment by dobromir-hristov** [comment]
use validations as a function
```js
validations(){
  return {
    gsurl: { required: this.myRequiredMethod }
  }
}
```

**Comment by jack-fdrv** [comment]
Sorry for this kind of questions. But how if I have nested data and other fields to validate?

```
validations() {
        user: {
            name: {
                required,
                minLength: minLength(4),
                maxLength: maxLength(10)
			},
			gsurl: {
				return {
					gsurl: { required: this.mustBeGgl }
				}
			}
        }
	},
```

**Comment by dobromir-hristov** [comment]
Just give it a try, you will get it :)

**Comment by dobromir-hristov** [comment]
That is deff not a valid object mate :)

**Comment by jack-fdrv** [comment]
Sry, right.

I tried

```
validations() {
	return {
		gsurl: { required: this.mustBeGgl }
	}
},
validations: {
    user: {
        name: {
            required,
            minLength: minLength(4),
            maxLength: maxLength(10)
		},
    }
},
```

![image](https://user-images.githubusercontent.com/4230282/72525061-f3227800-386b-11ea-8fc1-c23e2587b9b1.png)

**Comment by jack-fdrv** [comment]
So it works. Sry for stacking

```
validations() {
    return {
        user: {
            name: {
                required,
                minLength: minLength(4),
                maxLength: maxLength(10)
            },
            gsurl: {
                required: this.mustBeGgl 
            }
        }
    }
},
```

**Comment by agalya043** [comment]
Hi jack


im also trying the same

        validations() {
            return {
                test: {
                    number: {
                        required,
                        minLength: minLength(9),
                    },
                    gsurl: {
                        required: this.check
                    }
                }
            }
        },


also i was using some other validation in the same component



validations: {
    user: {
        address: {
            required,
            minLength: minLength(4),
            maxLength: maxLength(10)
		},
    }
},

can i use this, because im getting the error as

Cannot read property '$error' of undefined

because in the input class i declared
:class="{ 'is-invalid': submitted && $v.test.number.$error }"
