### ISSUE TITLE
Vue validate- If the value in the input field is not equal to the datalist throw the validation error

### ISSUE THREAD

**Issue by agalya043** [vuelidate/vuelidate#624]
if i'm entering some data that is not in the datalist then the validation error needs to throw when clicking submit button(Vue validate)
For example
--HTML--
<input list=listdetail" v-model="test.data">
<datalist id="listdetail">
<option></option>
</datalist>
---script---
  validations: {
routevalidate1() {
                        if(this.test.data != document.getElementById("listdetail").innerHTML)
                        {
                            return true
                        }
                    },}

**Comment by dobromir-hristov** [comment]
Please give us a proper reproduction. This is just nonsense.
