### ISSUE TITLE
Callback for touch()

### ISSUE THREAD

**Issue by bapfnet** [vuelidate/vuelidate#625]
I suggest to implement a callback option to touch()

I am using v-on:blur="$v.myinput.touch()" and can input an invalid value, if I do not blur before submitting the form.

I helped me out creating an interval to wait a few ms unit touch() has updated the $v object. Once updated, I can finally check if the submit is valid, e.g. if( !$v.error )

If we do not need this I'm interested how to fix without setTimeout.

**Comment by dobromir-hristov** [comment]
maybe `await this.$nextTick()` ?

**Comment by bapfnet** [comment]
$nextTick didn't work as reliable as setTimeout for me, because I am using some async validations as well.

**Comment by dobromir-hristov** [comment]
You are correct, $touch does not resolve once validators are finished. At this point in time, there is no way to do this, it is planned for Vuelidate 2.

**Comment by bapfnet** [comment]
Ok, thank you
