### ISSUE TITLE
Bind error message text with validation configuration

### ISSUE THREAD

**Issue by it-xtech-dev** [vuelidate/vuelidate#630]
Hello,

I have read the docs but cannot find a way to bind error messages with error occurence. I can inside the examples seen that error messages are defined outside validation model (as part of component template).

I would expect some thing like:

```
var requiredMessage = "This field is required";

new Vue({
  data: ...
  methods: ...
  validations: {
    data: {
      body: {
        serverUrl: {
          required: { message: requiredMessage },
          url: { message: "Please specify proper url address" }
        },
        userName: {
          required: { message: requiredMessage }
        },
        password: {
          required: { message: requiredMessage }
        }
      }
    }
  }
});
```

This would allow also to use translated messages with i18n. Is something like that possible, if not can this be considered as an improvement?

**Comment by dobromir-hristov** [comment]
Current version of Vuelidate does not support this out of the box. Use VuelidateErrorExtractor for now.
Vuelidate 2 has error messages baked in.

**Comment by it-xtech-dev** [comment]
OK, I'll check VuelidateErrorExtractor.

What do you mean by Vuelidate 2, next planned version? Is it in development at the moment?

**Comment by dobromir-hristov** [comment]
Yes. It will be out around Vue 3.
