### ISSUE TITLE
twice nested components validation

### ISSUE THREAD

**Issue by z1haze** [vuelidate/vuelidate#631]
I am trying to find an example on how i'd use vuelidate on a twice nested component setup. eg:

Root component FormComponent
Form component contains some input components, and also an AddressFields component
AddressFields component contains more input components.

The goal is to initialize the validation at the form component, and establish rules for whatever input components are direct children of FormComponent. I would need to pass down this validation to AddressFields component where I would further extend the validations to all of the input components included from there.

**Comment by shentao** [comment]
This is addressed in the upcoming Vue 3.0 compatible version. In there are direct and indirect child components report back to the nearest ancestor with Vuelidate enabled. Thus your root FormComponent will be aware of all nested validation results. 
You can check the progress on the `next` branch.
