### ISSUE TITLE
Does this support unit test integration?

### ISSUE THREAD

**Issue by joecodecreations** [vuelidate/vuelidate#633]
- Start Date: (YYYY-MM-DD)
- Reference Issues: (fill in existing related issues, if any)
- Implementation PR: (leave this empty)

# Summary

Just wondering if this is covered already before we take this on for use on our project. I don't see any documentation regarding testability of the validation functions etc. Is this currently available? If not, would you be open to contribution around this? 

# Motivation

High testability is an industry standard.

**Comment by shentao** [comment]
Validation functions are all tested. So is the library. Custom validators are pure functions that you can simply pass to vuelidate so I would recommend unit testing them saparately.
As for testing `$v` on the components – as long as you install vuelidate during the tests it should be working normally. 
/cc @dobromir-hristov

**Comment by dobromir-hristov** [comment]
The library is fully tested.

How you write tests for your components is not the library's concern, as each developer has their own style. Generally developers would change an input and assert the proper messages are shown.
