### ISSUE TITLE
validation multistep

### ISSUE THREAD

**Issue by mourareaupro** [vuelidate/vuelidate#634]
I need to make form validation from multisteps

```
computed: {
            rules () {
                return this.currentActive === 1
                    ? { age: { minValue : minValue(1) } }
                    : { height: { minValue : minValue(2) } }
            }
        },
        validations() {
            return {
                form: this.rules
            }
        },
```

for the first step it's ok but how can i manage for the second step ? i'm not sure how to achieve this. many thanks in advance

**Comment by shentao** [comment]
I think you can go for validation groups. https://vuelidate.js.org/#sub-validation-groups
