### ISSUE TITLE
Vue 3 setup compatibility

### ISSUE THREAD

**Issue by raphaelkieling-egsys** [vuelidate/vuelidate#637]
Someday we'll have possibility to include the vuelidade on setup methods with `composition-api` or vue 3?

Something like:

```js
export default {
        setup(){
            const state = useVuelidate({
                name:{ required }
            })
        
            return { state }
        }
}
```

**Comment by dobromir-hristov** [comment]
This will be done in Vue 3 branch. Current version will not be able to work like that.

**Comment by shentao** [comment]
Just to clarify - this is how the current alpha of Vuelidate v2 (for Vue 3.0) works. You can preview it on the next branch.
