### ISSUE TITLE
'$touch' not working

### ISSUE THREAD

**Issue by courtscout** [vuelidate/vuelidate#639]
I'm using following this library.
- "@vue/composition-api": "^0.4.0",
- "@vuelidate/core": "^2.0.0-alpha.0",
- "@vuelidate/validators": "^2.0.0-alpha.0"

This is My code.
``` vue
setup () {
    const $autoDirty = true
    const validation = useVuelidate(
      {
        court: {
          name: { required, email, $autoDirty },
          state: { required, $autoDirty },
          city: { required, $autoDirty },
          town: { required, $autoDirty },
          zipCode: { required, numeric, minLength: minLength(5), maxLength: maxLength(5) },
          zipAddr1: { required, maxLength: maxLength(255), $autoDirty },
          zipAddr2: { required, maxLength: maxLength(255), $autoDirty },
          coordX: { required, numeric, $autoDirty },
          coordY: { required, numeric, $autoDirty }
        }
      },
      {
        court: {
          ...toRefs(court)
        }
      }
    )

   return { validation }
}
```
But '$touch' method has been not working. Why?

**Comment by dobromir-hristov** [comment]
First the alpha version is not ready, so bugs may occur. 
Now with that said, please make a codesandbox showing your issue, so we can give it a test.
There have been many fixes that are not yet released as a version, just because we are constantly tweeking it.

**Comment by Quineone** [comment]
hi @dobromir-hristov , the` useVuelidate()` don't return the `$touch` and `$reset` methods: pls have a check
![image](https://user-images.githubusercontent.com/15320933/88285351-80fe8480-cd21-11ea-99c5-679656517f8f.png)

**Comment by dobromir-hristov** [comment]
Hey, they are I think not pushed to npm yet. They should be in the `next` branch.

**Comment by bisubus** [comment]
@dobromir-hristov I'm investigating the problem and not sure if it's the same issue or another one needs to be created. A side effect of `$autoDirty` is that it sets `$dirty` permanently, so `$touch()` followed by `$validate()` doesn't retrigger validators if fields weren't actually changed. In order to retrigger them I had to do `$reset()` followed by `$validate()`. Is this the way it's supposed to be done?

**Comment by dobromir-hristov** [comment]
Once dirty, you cannot retrigger validators, as they are ran on each change of the field.

You can call $validate, and it should return a promise, once all validations resolve.

**Comment by dobromir-hristov** [comment]
I will close this for now. If we see other issues, let's open new tickets :)
