### ISSUE TITLE
Radio Button required never gets error

### ISSUE THREAD

**Issue by kishorpatel85** [vuelidate/vuelidate#642]
### fiddle to provide reproduction 
https://jsfiddle.net/9bt8Lm0j/6/

I have included the code in error. It is as if just does not consider required for radio button.

The case i want to work with is check if any one of the radio button is clicked else show error

**Comment by dobromir-hristov** [comment]
Your code was not valid. True and False are both correct values for the `required` validator.

Here is working example.
https://jsfiddle.net/dobromir/sc69v8ez/1/
