### ISSUE TITLE
Ho to set dynamic parameters

### ISSUE THREAD

**Issue by Serhioromano** [vuelidate/vuelidate#644]
For instance, I have a validator that checks minimal or maximal value based on another field `dataType`

```js
const maxNum = (type) => (value) => {
    let val = parseInt(value);
    switch (type) {
        case 10: // int16
            return val <= 32767;
        case 11: // uint16
            return val <= 65535;
        case 20: // int32
            return val <= 2147483647;
        case 21: // uint32
            return val <= 4294967295;
        case 30: // int64
            return val <= 9223372036854775807;
        case 31: // uint64
            return val <= 18446744073709551615;
        case 40: // int8
            return val <= 127;
        case 41: // uint8
            return val <= 255;
        case 22: // float32
            return val <= 3.402823e38;
        case 32: // float64
            return val <= 1.7976931348623158e308;
    }
    return true;
};
```

and then

```js
validations() {
    return {
        myField: {
            required,
            maxNum: maxNum(dataField),
        }
    }
}
```

When I create an error message I want to show that maximum number. How to save it so I could access it through `.$params` when I what to display an error messages?

I tried `withParams` but those set params before validation return.

**Comment by shentao** [comment]
Take a look at this file: https://github.com/vuelidate/vuelidate/blob/master/src/validators/minValue.js

**Comment by Serhioromano** [comment]
> Take a look at this file: https://github.com/vuelidate/vuelidate/blob/master/src/validators/minValue.js

Really? I did not explain well? I do not have `min` paзфкфьуеукюthis value is sed dynamically. I pass the number type. I can access the type. But how do I store my dynamic number?

**Comment by dobromir-hristov** [comment]
You cannot use that by default. Vuelidate error extractor can do that for you I think.

**Comment by Serhioromano** [comment]
> You cannot use that by default. Vuelidate error extractor can do that for you I think.

@dobromir-hristov read your answer a few times. So the answer is I cannot do that or I can? _You cannot do that_ and it _can do that_ kind of confusing.

**Comment by shentao** [comment]
This is what he means: https://github.com/dobromir-hristov/vuelidate-error-extractor

**Comment by Serhioromano** [comment]
I think I was not understood right. ьay be I did not explain it properly. How can I get any param if it is a constant?

Once more. In my validator

```js
const maxNum = (type) => (value) => {
    let val = parseInt(value);
    switch (type) {
        case 10: // int16
            return val <= 32767;
        case 11: // uint16
            return val <= 65535;
        case 20: // int32
            return val <= 2147483647;
        case 21: // uint32
            return val <= 4294967295;
        case 30: // int64
            return val <= 9223372036854775807;
        case 31: // uint64
            return val <= 18446744073709551615;
        case 40: // int8
            return val <= 127;
        case 41: // uint8
            return val <= 255;
        case 22: // float32
            return val <= 3.402823e38;
        case 32: // float64
            return val <= 1.7976931348623158e308;
    }
    return true;
};
```

let, say the value of type 41 and it is <=255 means it is an error. I want to display a message 

> The value should not be more than 255.

How I can write this message if nowhere in the code I save 255 to a variable? It is a simple constant. еруку is nothing in the world that can exract it unless I do at least something like this

`this.level = 255;`

then I might have a chance to get this variable in the future.

So what should I do inside my validator to save what was the number that triggers an error and how to access that later?

**Comment by shentao** [comment]
Create another method that will get you the error based on the `type` that you pass to the validator.

So if you pass `type = 41`. You will likely do it like this:
```js
validations () {
  return {
    someNumber: { maxNum(this.type) }
  }
}
```
And then for the error message you do something similar:
```js
getErrorMessageForType (type) {
  switch (type) {
    case 41:
      return 'The value should not be more than 255.'
    // other cases
  }
}
```

**Comment by Serhioromano** [comment]
How do I know in an error message what was the type?

**Comment by shentao** [comment]
You set the type when setting up the validator for a specific property (read the above code). Thus when showing the error you should use the same type. 
If that's not enough, use the withParams helper as it was mentioned earlier.

Anyway, everything has been explained already from the library side.
