### ISSUE TITLE
Best way to get only the dirty fields?

### ISSUE THREAD

**Issue by sabrinanne** [vuelidate/vuelidate#646]
What's the best way to get only the dirty fields? I'm currently doing this approach:

            let dirtyFields = [];
            let form = this.$v.formData;
            for (let field in form) {
                if (form.hasOwnProperty(field)) {
                    if (form[field].$dirty) {
                        dirtyFields.push(field)
                    }
                }
            }
            return dirtyFields;

Thank you!

**Comment by dobromir-hristov** [comment]
There is no built in way sorry. This looks ok.

**Comment by VoiD2008** [comment]
except your (let field in form) will also iterate through $model, $dirty and other vuelidate fields
my aproach is 

`let dirtyFieldsModel = {};
        let model = this.$v.myModel;
        const recurModel = (node,model)=>{
          for (let field in node) {
            if (node.hasOwnProperty(field)) {
//check if field is your model field and it changed
              if (typeof node[field].$model != 'undefined' && node[field].$dirty) {
                model[field] = node[field].$model;
//check if field is your model field and it is object that has changed childs
              } else if (typeof node[field].$model != 'undefined' && node[field].$anyDirty && typeof node[field].$model == 'object'){
                model[field] = {};
//recursive iterate through children of current object type field
                recurModel(node[field],model[field]);
              }
            }
          }
        }
        recurModel(model,dirtyFieldsModel);`

typeof node[field].$model != 'undefined' allows you to be sure that field is your model field
and recursion allows you to use not only plain models
(also this variant targeted on creating model for POST not only field names list)
