### ISSUE TITLE
Async validation rules always trigger invalid state

### ISSUE THREAD

**Issue by jammy-git** [vuelidate/vuelidate#647]
Not sure if this is specific to Vuelidate or when used with Quasar. I do note that most of the Vuelidate examples have error messages hardcoded and shown using `v-if="$v.field.$invalid"`, which with Quasar is not needed, but might be the cause of this issue?

I've put together a pen to demonstrate the problem
https://codepen.io/jammy-git/pen/OJVWjWZ

I understand the fetch API call should return true/false, but in this example, the call response still evaluates to true. As you can see, the error message is always displayed?

**Comment by jammy-git** [comment]
Apparently the fetch call is blocked in Safari, but not in Chrome.

**Comment by dobromir-hristov** [comment]
This looks correct. Did you manage to resolve it?

**Comment by jammy-git** [comment]
We didn't.

One of my other devs had a look at the problem and believed traced it to an issue with Quasar rather than Vuelidate. It seemed Quasar didn't wait for the promise to return and always returned true.

Annoyingly, trying to create an example in just Quasar or Vuelidate would not result in the issue occurring, it was only when Vuelidate was used with Quasar!

However, we did manage to find a workaround which was just to use `error` and `error-message` props of the Quasar q-input component, rather than Vuelidate itself to operate any async validation rules.

**Comment by shentao** [comment]
Thanks for the explanation! Sorry to hear that Vuelidate has caused some issues.
