### ISSUE TITLE
Is it possible use different error messages in an asynchronous validator?

### ISSUE THREAD

**Issue by MrEko** [vuelidate/vuelidate#649]
I'm trying to create a custom validator that is one asynchronous call that validates many things(syntax and content for example).

And I would like to have a different message for each error. (xx is invalid, xx is out of range, ...)
Is it possible?

**Comment by dobromir-hristov** [comment]
You could, but you would have to manage the messages yourself. You can do something like
`{{ !$v.name.async ? asyncErrors[errorType] : '' }}` so `asyncErrors` would hold  your messages and you can save the `errorType` in a simple vue data property, based on some response in your async call? I mean you can go nutz here, but Vuelidate just understands booleans :/
