### ISSUE TITLE
No validator for input type="file"?

### ISSUE THREAD

**Issue by Skeeve** [vuelidate/vuelidate#653]
I couldn't find a file validator.

**Comment by dobromir-hristov** [comment]
Because there is none.

**Comment by Skeeve** [comment]
Hmm… Shouldn't there be one? Just asking because vee-validate has.

**Comment by shentao** [comment]
We might add it for the new major version as it won’t affect the bundle size anymore.

**Comment by tsangaris** [comment]
> We might add it for the new major version as it won’t affect the bundle size anymore.

Any idea when this is going to be out?

**Comment by shentao** [comment]
Not that far away actually! Feel free to submit a PR with that validator towards our `next` branch. Here is the `@vuelidate/validators` package: https://github.com/vuelidate/vuelidate/tree/next/packages/validators
