### ISSUE TITLE
access to store or computed properties for custom validators?

### ISSUE THREAD

**Issue by plweil** [vuelidate/vuelidate#654]
I have forms fields that are filled with current values on page load. I want to prevent users from submitting forms where the value has not changed. The old values are in the vuex data store. When I try to reference the latter in customer validators, they come back as undefined. Neither the store, nor computed properties, nor methods (this) seem to be available to the validator. What is the best way to do this in Vuelidate?

**Comment by shentao** [comment]
I think this is something that has nothing to do with Vuelidate. To solve an issue like this, I would make use of a pattern that looks like this:
```js
{
  data: () => ({ changes: {} }),
  computed: {
    ...mapGetters('vuexValue'),
    valueWithChanges() {
      return { ...this.vuexValue, ...changes }
    }
  }
}
```
And then in forms you do:
```html
<input :value="valueWithChanges[prop]" @input="changes[prop] = $event" type="text">
```

This works really nicely with solutions like FormVueLatte where you can automate the whole form.
Anyway, with this approach, you can do a simple check. You can make it into a Vuelidate validator if you want.
```js
!!Object.keys(this.changes).length // if false, prevent from submitting the form
```

I hope this helps!

**Comment by plweil** [comment]
Thanks @shentao. I like the solution you suggested, but I don't think it will work in my particular case since I am already using v-model and vuex-map-fields. My main issue was figuring out how to access the component from within a validator. After some more fumbling around and trial and error, I was able to add a `changed` param. For some reason --probably my own error -- I was unable to do this using a function and `this`. 


```javascript
validations: {
  myField: {
     required,
     changed:  (value, vm) => vm.originalValueInVuex!== value,
     maxLength: maxLength(150)
  },
 },
 computed: {
    ...mapState(['originalValueInVuex']
 }
```

And in the template:

```html
   <p v-show="!$v.myField.changed">There are no changes to save.</p>
```

**Comment by shentao** [comment]
Hey! To access `this` you can declare validations as a function similar to `data`. 
```js
validations () { 
  return {
    myField: { 
      ... // `this` is available here
    }
  }
}
```

**Comment by plweil** [comment]
Ah! Got it! Thanks!

**Comment by shentao** [comment]
Glad I could help!
