### ISSUE TITLE
requiredIf inside $each don't have full form scope data

### ISSUE THREAD

**Issue by pumano** [vuelidate/vuelidate#659]
sometimes I need to check if some field is meet condition for another array of objects:

```
isRecommendations: { required },
recommendations: {
    required: requiredIf(function (form) { return form.isRecommendations; }),
    $each: {
         fullname: { required: requiredIf(function (form) { return form.isRecommendations; }) },
         employeer: { },
         jobTitle: { },
         phone: { }
    }
}
```

but **requiredIf** function inside **$each** just get only current array fields, don't have parent scope for checking conditions. How to solve it without changing structure?

**Comment by jakecjones** [comment]
I am also looking for the best practice here.

**Comment by shentao** [comment]
I think that if you declare `validations` as a function:
```
validations () {
  return {
    ...rulesHere
  }
}
```
you should be able to use `this` wherever you need, which in turn means, you get access to the whole form.

**Comment by pumano** [comment]
@shentao yes, I use it as you mentioned, but inside $each block requiredIf receive only object in array not a whole form.

**Comment by shentao** [comment]
Would it be possible to do something like this?
```
validations () {
  const vm = this
  return {
    ...rulesHere,
    myList: {
      $each: {
         prop: { requiredIf(vm.something) }
       }
    }
  }
}
```
