### ISSUE TITLE
How can I fire a custom validation only if another validation is currently passing?

### ISSUE THREAD

**Issue by arbokrad** [vuelidate/vuelidate#660]
Hello and thanks for the great plugin!

I am trying to get an expensive custom validation to only actually perform its expensive logic when another validator thinks the value is ok. In this instance, when the built-in email validator thinks the value is fine, I want to then continue and fire the more expensive custom validator to do a more in-depth check on that email (an async call). I have tried a number of ways of going about but I'm clearly not doing this correctly or wildly missing a straightforward approach.

https://jsfiddle.net/go39evuf/3/

For the sake of this fiddle, I replaced out the expensive call with a simple check for a gmail email address.

Any guidance on how I should approach this would be much appreciated, thanks in advance.

**Comment by shentao** [comment]
This is a tricky one! /cc @dobromir-hristov.
I think you could use the dynamic validation schema https://vuelidate.js.org/#sub-dynamic-validation-schema for that.

**Comment by arbokrad** [comment]
@shentao Is dynamic validation schema compatible with using TS and the vue class component approach?

Something like this:
`
@Component({
	components: {},
	validations: {
		email: {
			required,
			email,
			gmailEmail: gmailEmail
		},
})
export default class MyComponent extends Vue {
	...
}
`

If I define the component config beforehand, would it be something like:
`
let config = {...};
if( !this.$v.email ) {
  config.validations.email.gmailEmail = gmailEmail;
}
`

... or is there a more correct way of getting this?

**Comment by shentao** [comment]
Dunno about TS and vue-class-component. If it allows you to defined `validations` as a function, then yes, I think it should be possible. The function will be called with the artificial `this` that is also available in all Vue methods/computed properties.

**Comment by arbokrad** [comment]
Fair enough, I thought that might be a longshot :)

With that said, I _think_ I have this actually working even though how it is done feels pretty bad: 

```
const guestEmailPlaceholder = async function(value) {
  // always return true so this is completely ignored while it is in place
  return true;
};

const guestEmail = async function(value) {
  return await expensiveValidationCall();
};

let cmpConfig = {
  validations: {
    required
    email,
    guestEmail: guestEmailPlaceholder
  }
}

@Component(cmpConfig)
export default class MyComponent extends Vue {

  // this function is used in @blur and @input event handlers
  private touchEmail() {
    this.$v.email.$touch();

    // when we detect email is valid, we may need to add the real guestEmail validator
    // if the email becomes invalid, we want to remove the guestEmail validator
    // but also attempt to not thrash the cmpConfig unnecessarily if the actual state hasnt changed
    if (this.$v.email.email && cmpConfig.validations.email.guestEmail.name == 'guestEmailPlaceholder') {

      // email is valid, need to see if we have to add the real validator or if its already on there
      cmpConfig.validations.email = {
        required,
        email,
        guestEmail: guestEmail
      };
    } else if (!this.$v.email.email && cmpConfig.validations.email.guestEmail.name == 'guestEmail' )  {
      cmpConfig.validations.email = {
        required,
        email,
        guestEmail: guestEmailPlaceholder
      };
    }
  }
}
```

If there's a cleaner way to do this, I'd be happy to adopt it instead!

**Comment by shentao** [comment]
Hmm.  What if you were to make that `guestEmail` validator actually check if `$v.email.$invalid` is true?
You can get access to component’s `this` through the 2nd argument.
See: https://vuelidate.js.org/#sub-accessing-component

So it would be something like:
```js
const guestEmail = async function(value, vm) {
  if (vm.$v.email.$invalid || vm.$v.required.$invalid) return false
  return await expensiveValidationCall();
}
```
Likely not the best solution as it couples the execution of this validator to the presence of other validation results. But I think you can take it from here and make it better.

**Comment by arbokrad** [comment]
Yeah thats how I started, but vm does not appear to have access to $v and I'm not sure why. If that works outside of vue-class-component/TS then it may be an issue of how these two things are interacting. I'll keep playing with it but at least I have something working, nasty as it may be.

**Comment by shentao** [comment]
Interesting! That might be very hard to fix in the current version, but should be something to explore in the work-in-progress v2 version that we are now working on.

By default, all validators there are already lazy (not executing) unless dirty. Might be worth a shot to look for some easy ways to conditionally enable/disable validators for specific fields.

Good luck on the issue!

**Comment by paulhaem** [comment]
With v2 being available now is there a better solution to this use case?

**Comment by dobromir-hristov** [comment]
Not really. You will have to reach into the vm.

I am not sure if there is another way, as coupling validators means they will run each other on each change.

**Comment by paulhaem** [comment]
Instead of hooking up validation dependencies I would like to propose a "validate by order"-mode. So instead of executing all validators simultaneously the validators are executed one after another providing that the predecessor was successfull or the conditions are met. The validation mode would be configured in the component scope. This would help to lower performance needs for complex validation logic and would be really handy for multiple async validators.

An example for the given problem:
execute `required` > met? > execute `email` > met? > execute `uniqueEmail` > met? > field is valid

The validations that are not being executed yet would utilize the already given `pending` property.

I'm not sure but it might be possible to achieve this kinda behaviour with turning every validation into a async one and checking on them using the vm but that would blow up the code unnessecarily instead of helping to reduce complexity.

**Comment by dobromir-hristov** [comment]
@paulhaem that would require a very big refactor on our behalf, because validators are just computed properties, which are fired on change.

Also, because validators are defined as properties in an object, they do not have a solid order. JS engine generally keeps the order, but it's not guaranteed.

**Comment by paulhaem** [comment]
I see, thanks for the explanation. That would be indeed a huge change. I will try to figure out an adequate solution to the given problem using v2 and will post it here if successful.

**Comment by ggueyraud** [comment]
This can be done by watch the state object property, if $invalid === false then we send the request to the api to check if email is unique. 
In this way we can solve the problem, but it seems not the good way when using a form validator library.

Is today a solution to create a validator which could have the result of other validator link to a specific state property ? If it is, can someone provide a minimal example to make sure the question will be not reopen?
