### ISSUE TITLE
v-model input required doesn't work as expected

### ISSUE THREAD

**Issue by RokasDie** [vuelidate/vuelidate#666]
Hello,

I have a question, when I use input together with v-model, I would expect when launching/entering the webpage required error: "*Field is required" would not show up (because the input is not dirty), however, in this example it is showing up:

https://jsfiddle.net/yqnap0hz/2/

How would I need to set this up so that the input field required error would show up after interacting with the input?

Regards,
Rokas

**Comment by dobromir-hristov** [comment]
Check for $error.

**Comment by RokasDie** [comment]
Could then the documentation "basic form" be updated, because the code which is used there is: 

```
import { required, minLength, between } from 'vuelidate/lib/validators'

export default {
  data() {
    return {
      name: '',
      age: 0
    }
  },
  validations: {
    name: {
      required,
      minLength: minLength(4)
    },
    age: {
      between: between(20, 30)
    }
  }
}

```

And it works as I wanted it tow work and it doesn't say anything about $error
