### ISSUE TITLE
[Vue 3] Support for reactive state

### ISSUE THREAD

**Issue by javiertury** [vuelidate/vuelidate#670]
- Start Date: 2020-6-12
- Implementation PR: (leave this empty)

# Summary

Right now @vuelidate/core works only for refs, that is, it assumes that `state[key]` to validate is a ref and always unwraps it. I argue that support for `reactive` structures should also be added. In the case of nested structures it becomes cumbersome to deal with collection of references.

# Basic example

```
// Right now this is not supported
const form = reactive({
  foo: '',
  bar: ''
});

const validationArgs = {
  form: {
    foo: {
      required,
      $autoDirty
    },
    bar: {
      required,
      $autoDirty
    },
    required
};

const validation = useVuelidate(validationArgs, { form });
```

# Motivation

The restrictions that exist now makes it cumbersome to use vuelidate if there are many nested fields. Whereas one would tipically work with a reactive object, vuelidate requires that they break down everything to refs.

```
const fooRef = ref('');
const barRef = ref('');

const formRef = ref({
  foo: fooRef,
  bar: barRef
});

const validationArgs = {
  form: {
    foo: {
      required,
      $autoDirty
    },
    bar: {
      required,
      $autoDirty
    },
    required
};

const validation = useVuelidate(validationArgs, { form: formRef });
```

# Detailed design

So `isRef` should be used to check if the value is a reference. For instance:

```
  const model = computed(() => unwrap(state[key]))
```

```
  let $model = key ? computed({
    get: () => unwrap(state[key]),
    set: val => {
      $dirty.value = true
      if (isRef(state[key])) {
        state[key].value = val
      } else {
        state[key] = val;
      }
    }
  }) : null

  if (config.$autoDirty) {
    const watchedRef = isRef(state) ? state[key] : toRef(state, key);

    watch(
      watchedRef,
      () => { $dirty.value = true }
    )
  }
```

**Comment by shentao** [comment]
Hey @javiertury! Thanks a lot, for posting this. The issue with `reactive` is a known one and after some changes on one of the PRs, it already works in multiple cases.

For example:
```js
const form = reactive({
  foo: '',
  bar: ''
});

const validationArgs = {
  form: {
    foo: {
      required,
      $autoDirty
    },
    bar: {
      required,
      $autoDirty
    },
    required
};

const validation = useVuelidate(validationArgs, { form });
```
Is now working.

However, using `$model` would still be broken, thus based on your suggestion, I will be now updating the `$model` implementation. Thank you a lot! Would you like to review the changes?

**Comment by javiertury** [comment]
Yes, I would like to take a look.

**Comment by shentao** [comment]
Take a look at #662 in that case. It adds the old Options API support. However, there is currently the problem of the validation state being reset due to `$v` being a `computed` property that uses `setValidations` internally. 
I think to solve that we will need to introduce another layer of persistance somewhere between that computed property and dynamic validation rules.

**Comment by javiertury** [comment]
I have some suggestions at [options-api-alternative_chain](https://github.com/javiertury/vuelidate/tree/options-api-alternative_chain).

1. Using the mixin, I found out that `validations` was passed to `setValidations` as a reference. It was problematic. Suppose I wrote: 
```js
defineComponent({
  validations: {
    foo: {
      required
    }
  }
});
```
Vuelidate interpreted it without unwrapping it first, as if I had written:
```js
defineComponent({
  validations: {
    value: {
      foo: {
        required
      }
    }
  }
});
```

2. Refs of nested objects lose reactivity after the first level. Imagine I can only use a ref.
```js
defineComponent({
  setup (props) {
    // "props" is a shallow reactive object, so it means "foo" is not reactive
    // All I can do is to extract a reference.
    const {
      foo
    } = toRefs(props);

    const validation = useVuelidate({
      foo: {
        bar: {
          x: {
            required
          }
        }
      }
    }, { foo });

    return {
      validation
    };
  }
});
```

Vuelidate will lose reactivity after the `foo` level. To see why, let's take a look at how vuelidate transverses the state tree.
```
    const nestedState = key ? state[key] : state
```

This translates to a simple `state['foo']['bar']['x']`. It works well for reactive objects but not for references. Even if references were unwrapped, reactivity is lost.

To preserve reactivity, I thought about chaining references using `computed`.
```
    const nestedState = !key ? state : computed(() => unwrap(unwrap(state)[key]))
```

There are many `unwraps` but I believe they are necessary. In the first level, the key `foo` in the state `{ foo }` is a reference. But in subsequent levels, the state itself is a reference because it was generated from `computed()`. So we have to beware of references in both `state` and `state[key]`.

Finally, I also learned that "@vue/composition-api" and vue3 references are incompatible, so vuelidate@next can't be used on vue2 projects :(

**Comment by shentao** [comment]
Hey @javiertury! This is very helpful! Would you be able to create a PR out of your fork so we can see what exactly is changing? I pushed a new PR that enables a fully dynamic set of validations (https://github.com/vuelidate/vuelidate/pull/673 still a work-in-progress though). I’d love to see your take on the issues you mentioned! Really appreciate the involvement.

**Comment by dobromir-hristov** [comment]
Already supported in latest version.
