### ISSUE TITLE
Validations Lifecycle

### ISSUE THREAD

**Issue by lgmf-daitan** [vuelidate/vuelidate#671]
Hello :)

Basically, I have a form control that has synchronous validators and asynchronous.
```
  validations: {
    form: {
      username: {
        required, // sync validator
        min: minLength(6), // sync validator
        uniqueUsername, // async validator
      },
    },
  },
```

The problem is that even if the synchronous ones already triggered an error the asynchronous ones still executes. 

**The expected behavior**, considering performance issues due to unnecessary API calls, would be to **execute the asynchronous validators only if the form has no errors coming from the synchronous validators**.

I think that's the Angular's forms module behavior.

Is there a way to work around this problem?
Is this a nice feature to add to the library?

**Comment by dobromir-hristov** [comment]
There is no easy of the box way. Also not sure how to stop the async request, there must be some order of execution or something..

**Comment by shentao** [comment]
This is an interesting problem. The only way I see this done right now is probably setting up an existing component method as the validator (not 100% sure it will work).
```
{
  uniqueUsername: this.uniqueUsername
}
```
And then, inside that method return a promise that checks the status of all other validation results for that property before sending a request to the API. That is if any of the other checks fail, just return false.

**Comment by lgmf-daitan** [comment]
Thanks for the quick answer.

I've already tried to check if there was an error inside my async validator function. 

My code looks like the example below and for some reason when I try to validate if there is some error before sending the request I'm stuck with an infinite loop

```
// Utility function that creates an async validator
export default function createAsyncValidatorFor(field) {
  return async function asyncValidator(value) {
    // standalone validator ideally should not assume a field is required
    if (!value) {
      return true;
    }

    // The this here is the component that uses the async validator
    if(this.$v.form[field].$error) {
      // this is generating a infinite loop
      return true;
    }

    const { valid } = await validationService.validate(field, value);
    return valid;
  };
}

// Form Component
const usernameAsyncValidator = createAsyncValidatorFor('username');

export default {
  data() {
    return {
      form: {
        username: ''
      }
    }
  },
  validations: {
    form: {
      username: {
        required,
        min: minLength(6),
        uniqueUsername: usernameAsyncValidator,
      },
    },
  },
}
```

I've created a [sandbox](https://codesandbox.io/s/dry-framework-mgpxb?file=/src/components/Form.vue) to simulate my code 


If there is a workaround this I'd suggest to add on the documentation in the async validator section describing how to prevent async validators for being executed if there is at least one error

**Comment by lgmf-daitan** [comment]
> There is no easy of the box way. Also not sure how to stop the async request, there must be some order of execution or something..

This would not be necessary, because the logic would be not to call the request if a synchronous validator returns an error

**Comment by lgmf-daitan** [comment]
My proposal would be to implement a change on the library.

Something like this:

```
    validations: {
      form: {
        username: {
          required,
          minLength(6),
          async: {
            uniqueUsername
          }
        }
      }
    }
```
Because then there is a way to split the async from the sync validators on the execution pipeline

**Comment by rubenslopes** [comment]
Based upon @shentao answer I come up with this, that worked for my case.

```javascript
  validations: {
    form: {
      username: {
        required, // sync validator
        min: minLength(6), // sync validator
        uniqueUsername: async () => {
            if (!this.syncValidations) return true;

            return await uniqueUsername();
        }
      },
    },
  },
  computed: {
    syncValidations() {
        return $v.form.username.required && $v.form.username.min;
      }
  }
```

To avoid infinite loop we have to check each sync validation bellow `username` to avoid recursion.

**Comment by lgmf-daitan** [comment]
Thanks a lot guys! @shentao @rubenslopes  @dobromir-hristov

**Comment by lgmf-daitan** [comment]
I've updated my code based on the suggestion

```javascript
const validationService = {
  async validate(field, value) {
    return new Promise((resolve) => {
      setTimeout(() => {
        resolve({
          valid: typeof value === "string" && value.length % 2 !== 0
        });
      }, 350 + Math.random() * 300);
    });
  }
};

const hasSyncError = (form, field, syncValidators = []) => {
  return syncValidators.some((syncValidator) => !form[field][syncValidator]);
};

export default function createAsyncValidatorFor(field, { syncValidators }) {
  return async function asyncValidator(value) {
    if (!value || hasSyncError(this.$v.form, field, syncValidators)) {
      return true;
    }

    const { valid } = await validationService.validate(field, value);
    return valid;
  };
}
```


```javascript
validations: {
    form: {
      username: {
        required,
        min: minLength(6),
        uniqueUsername: createAsyncValidatorFor("username", {
          syncValidators: ["required", "min"]
        })
      }
    }
  }
```

**Comment by shentao** [comment]
Glad to hear that!
