### ISSUE TITLE
Async validation not working correctly

### ISSUE THREAD

**Issue by amirakbulut** [vuelidate/vuelidate#677]
I have the following Asynchronous validation, which works for 90%

The 10% issue:

After `this.checkUsername()` finishes, it correctly alerts 'finished' (just for visual confirmation). However, after the alert it should set the validation rule to `true`, but it always stays `false`, what am I missing?

```
validations: {
    slug: {
      available: async function(value) {
        if (!value) return;
        await this.checkUsername(value).then(isAvailable => {
          alert("finished");
          return true;
        });
      }
    }
  }
```

**Comment by dobromir-hristov** [comment]
I think you should return that async func.

```js
return await this.checkUsername(value).then(isAvailable => {
```
