### ISSUE TITLE
Is it possible to not generate a $v object n case the valdiations of the component is an empty object?

### ISSUE THREAD

**Issue by rkoole** [vuelidate/vuelidate#678]
I have a dynamic form component and sometimes there are no validations on that form. In that case the validations component property will be an empty object. If that is the case the $v computed property will still be generated . Is there a way to not generate the $v object?

Many thanks

Rutger

**Comment by dobromir-hristov** [comment]
With new Vuelidate, you can use the composition API to stop validation creation.
