### ISSUE TITLE
Validating does not work correctly when the data model is different from validations model

### ISSUE THREAD

**Issue by SimonFricker** [vuelidate/vuelidate#681]
When the data model is different from validations model, required and minLength are not validating correctly. 
https://jsfiddle.net/2vs9kdb3/4/

```

<input v-model="text" @blur="$v.form.text.$touch()" :class="{ 'is-invalid': $v.form.text.$error }">
<template v-if="!$v.form.text.minLength">
    Text is too short
</template>


....


data: {
    text: ''
},

validations: {
    form: {
        text: {
        required,
        minLength: minLength(5)
        }
    }
}
 
```

**Comment by dobromir-hristov** [comment]
Text is not nested inside form.

**Comment by SimonFricker** [comment]
But why should it be? as the ``validations`` are detached from the v-model

**Comment by dobromir-hristov** [comment]
Text property must be inside a form object, so validations mimick the data structure

**Comment by shentao** [comment]
Or you can remove the `form` layer from validations.

Also, unless you're using `new Vue`, `data` should always be a function inside components.

**Comment by SimonFricker** [comment]
Thanks for the clarification. Is this stated in the docs?

**Comment by shentao** [comment]
I guess it might not be stated directly, though all the examples should suggest that. Will improve that in the next version of the docs for Vuelidate v2.
