### ISSUE TITLE
Dynamic parameters not working as expected

### ISSUE THREAD

**Issue by romanbogza** [vuelidate/vuelidate#685]
Hey Guys,

can someone please help me with dynamic properties. 
I am receiving a prop that contains a list of form attributes I need to add to Vuelidate. I am unable to set those properties dynamically in my validations method. Can someone help me understand why the below code will not work: 

``` 
props: ['cars']

validations() {
    return {
      data: {
        name: {
          required
        },
        [this.cars.forEach((item) =>  {
          return item.name
        })]: { required }
      }
    };
  }
```

**Comment by dobromir-hristov** [comment]
I think the validation object you are providing is wrong, along with probably there is no such data structure, that reflects on that.

Make a codesandbox, otherwise we cant help much

**Comment by TheMaikXX** [comment]
I dont know what exactly are you trying to achieve but `this.cars.forEach` does not return those `item.name`s, You are probably looking for `.map` instead.. 

And I think the `[]` object key notation is misused.. I would write it like that:
```javascript

validations() {
    return {
      data: {
        name: {
          required
        },
        ...(this.cars
          .map(x => x.name)
          .reduce((acc, x) => acc[x] = {required}, {})
        )
      }
    };
  }
```

You first get cars' names and then using `.reduce` you insert each name into object with key as car's name and value being: `{required}`
This would mean that for example if you would have one car named Ferrari then you would mark `data`'s field named `Ferrari` as required.
