### ISSUE TITLE
Parse error in index.py, line 416, unexpected token proxy

### ISSUE THREAD

**Issue by kevingill1966** [vuelidate/vuelidate#687]
I am trying to build a library that uses vuelidate.

When I import the library, I am getting a parsing error in the code  below. The code "get proxy()" seems to be invalid.

6348:15  error  Parsing error: Unexpected token proxy

This is line 416 at https://github.com/vuelidate/vuelidate/blob/master/src/index.js

Any thoughts?

```
const GroupValidation = Validation.extend({
    methods: {
      isNested(key) {
        return typeof this.validations[key]() !== 'undefined'
      },
      getRef(key) {
        const vm = this
        return {
          get proxy() {
            // default to invalid
            return vm.validations[key]() || false
          }
        }
      }
    }
  })
```

**Comment by dobromir-hristov** [comment]
I dont think this is something with Vuelidate, sorry.
