### ISSUE TITLE
Vuelidate 2: Dynamic Validation Schemas example

### ISSUE THREAD

**Issue by blowsie** [vuelidate/vuelidate#688]
I tried to create a [dynamic schema](https://vuelidate.js.org/#sub-dynamic-validation-schema) in vuelidate 2 using computed, however it doesn't appear to be reactive or working correctly. 

Is anyone able to assist with this example?

```
    // Form Handling
    const userIsPhone = ref(false)
    const onIsPhone = (value) => {
      userIsPhone.value = value
    }
    const form = reactive({ username: '', password: '' })
    let $autoDirty = true
    let validation = computed(() => {
      return useVuelidate(
        {
          username: userIsPhone.value
            ? { required, numeric, $autoDirty }
            : { required, email, $autoDirty },
          password: { required, $autoDirty },
        },
        toRefs(form)
      )
    })
```

Thanks in advance

**Comment by shentao** [comment]
Hey! What you get from `useVuelidate` should already stay reactive, so there is no need to wrap it inside a computed. 

Here’s an example:
```
    const rules = computed(() => {
      return x.value >= 6
        ? { y: { minLength: minLength(x) } }
        : { y: { minLength: minLength(3), required } }
    })

    const v$ = useVuelidate(
      rules,
      { x, y }
    )
```

Btw. are you using the current `next` branch (for Vue 3.0) or the old beta released for Vue 2.x? The latter might not support it...

**Comment by blowsie** [comment]
Thanks for the example!

Currently im using 
`^2.0.0-alpha.0` with vue 2 and the composition API

Should something be working for this vue 2 and the composition API? 
If so which version should I try?

Thanks!

**Comment by blowsie** [comment]
I found a small bug in your example which I addressed, but I still have the issue
```
    const form = reactive({ username: '', password: '' })
    const $autoDirty = true
    const validationRules = computed(() => {
      return userIsPhone.value
        ? {
            username: { required, numeric, $autoDirty },
            password: { required, $autoDirty },
          }
        : {
            username: { required, email, $autoDirty },
            password: { required, $autoDirty },
          }
    })
    let validation = useVuelidate(validationRules, toRefs(form))    const form = reactive({ username: '', password: '' })
    const $autoDirty = true
    const validationRules = computed(() => {
      return userIsPhone.value
        ? {
            username: { required, numeric, $autoDirty },
            password: { required, $autoDirty },
          }
        : {
            username: { required, email, $autoDirty },
            password: { required, $autoDirty },
          }
    })
    let validation = useVuelidate(validationRules, toRefs(form))
```

**Comment by shentao** [comment]
I see! That alpha is pretty dated (we are planning to release a new one for Vue 3.0 and maybe a compat version for 2.x, though we had limited success with something like vue-demi so far).

So far the roadmap is: get the tests running -> explore and patch more use cases -> release new alpha for Vue 3.0 -> try vue-demi again to create a compat version for Vue 2.x.

What project are you working on? I would strongly advise against using that alpha in anything serious...

**Comment by blowsie** [comment]
Well, its early development of a pretty large site (Alexa 500), so perhaps I should stop using this Alpha, I do wish to continue to use the composition api though. 

Should the old vuelidate version work with it?

**Comment by shentao** [comment]
That’s a tough problem. I wish we already had the library done.
Are you planning to migrate to Vue 3.0 anytime soon given it’s in RC stage already and most of the core libraries are already supporting it? 
If so, you could potentially use a branch ref to `next` and see how that goes. Hopefully we will be able to release something this weekend with @dobromir-hristov.

**Comment by blowsie** [comment]
Yep, looking to move to Vue 3 as soon as it reaches the official release.
Thanks fo your input on this one.

For now I have switched to this.
https://pikax.me/vue-composable/composable/validation/validation.html
