### ISSUE TITLE
Validation happens every time if dependent on another field

### ISSUE THREAD

**Issue by mantasink** [vuelidate/vuelidate#689]
If you have a custom validation, that depends on another field like so:

```javascript
validations () {
  return {
    username: {
      required,
      maxLength: maxLength(16)
    },
    email: {
      required
    },
    password: {
      required,
      validationDependentOnOtherField () {
        console.log('calls every time when dirty')
        return this.password !== this.username
      }
    }
  }
}
```

Then when you change the field being validated (`password`) and any other field (even not related one like `email`) - `validationDependentOnOtherField` is called. That's especially malevolent when you also have an API call to check something on that `validationDependentOnOtherField` validator.

**Comment by shentao** [comment]
Sadly I don’t think we can do anything about it in the current version of Vuelidate. However, the new one (which is currently in alpha) should handle this much better. There every validation is lazy. So if your form is not `$dirty`, none of the validators will execute. As you said, with async validators (that also got an upgrade) this is very important. Also, once properties are dirty, they can be selectively (or all) `$reset`. 

Additionally, in the new version, every validation result is it’s own computed property (unless it’s async then state+watch) and tracks its own dependencies. So it should only trigger validators for properties that have changed (or their dependants).

Currently, the new alpha is dedicated to Vue 3.0, but I intend to try building a compat version for Vue 2.x this weekend. With our initial research, the code should be compatible thanks to the composition-api plugin.

**Comment by dobromir-hristov** [comment]
Vuelidate next already supports Vue 2.0 as well as Vue 3.x. Could you give it a go if this is still an issue you are having?
