### ISSUE TITLE
Unable to implement vuelidate with renderless component

### ISSUE THREAD

**Issue by maverickpravin** [vuelidate/vuelidate#690]
I want to create a renderless form with vuejs - I'm using vuelidate for form validation. The form uses scoped slot to manage the model and controls.

Unfortunately i'm not able to implement the vuelidate for the form validation by renderless approach. Any ideas would be highly appreciated. Below is what i have tried.

**App.vue**
```vue
<renderless-form>
  <form @submit.prevent="submit" slot-scope="{ ele, submit }">
     <input type="email" v-model="ele.model.name" />
     <button> Submit </button>
  </form>
</renderless-form>

<script>
import renderlessFrom from "./components/renderless-form.vue";

export default {
  name: "App",
  components: {
    "renderless-form": renderlessFrom
  }
};
</script>
```
**Renderless-form.vue**

```js
import { required, minLength, between } from "vuelidate/lib/validators";
export default {
    data() {
      return {
        model: {
          name: ''
        }
      };
    },
    validation: model, //i am sceptical here how to put validation
    methods: {
      async submit() {
        console.log(this.model) 
      },
    },
    render() {
      return this.$scopedSlots.default({
        // Data
        ele: this.model,
        
        // Methods
        submit: this.submit,
      });
    },
  };   
```

**Comment by dobromir-hristov** [comment]
You could provide the validations via a prop to the renderless form. Then you would pass $v down as a slot prop. Use $model for changing the properties and that is it.

**Comment by maverickpravin** [comment]
Apologies, I am really not sure - is that what you are suggesting ?
```
<renderless-form :validation="$v">
  <form @submit.prevent="submit" slot-scope="{ ele, submit, $v }">
     <input type="email" v-model="ele.model.name" />
     <button> Submit </button>
  </form>
</renderless-form>
```

**Comment by dobromir-hristov** [comment]
Something like this probably. I dont really see the benefit though, as you need to pass both the validation rules as well as the validation state to it.

```vue
    <renderless-form :validation="validationRules" :state="state">
      <template slot-scope="{ $v, submit }">
        <form @submit.prevent="submit">
          <input type="email" v-model="$v.name.$model" />
          <button>Submit</button>
        </form>
      </template>
    </renderless-form>
```

**Comment by maverickpravin** [comment]
Right, my challenge is that i want to separate the view from the form logic + form validation.
When i am able to implement the form correctly - i would want to use mixins to handle form logic with the intention to keep validation login in a separate file

**Comment by maverickpravin** [comment]
I have a quick question regarding the vuelidate implementation from the my component above ..
Can't i access the validation from the  ```renderless-form.vue```

```
import { required, minLength, between } from "vuelidate/lib/validators";
export default {
    data() {
      return {
        model: {
          name: ''
        }
      };
    },
    validation () { 
       return this.model;
    },
    methods: {
      async submit() {
        console.log(this.model) 
      },
    },
    render() {
      return this.$scopedSlots.default({
        // Data
        ele: this.model, 
        // Methods
        submit: this.submit,
      });
    },
  };   
```

**Comment by dobromir-hristov** [comment]
your validation rules are wrong, should be:
```
{ rules: { model: { name: { required }}}}
```

In your case you dont need the rules to be inside the `data`, just write them in `validations`

**Comment by maverickpravin** [comment]
@dobromir-hristov  what if i want to implement validations as dynamic ?

**Comment by dobromir-hristov** [comment]
Pass them as a prop or just dynamic for this form?

You can still return an object from inside the `validations` function, making your rules dynamic.
