### ISSUE TITLE
Vue 2.6 + Composition API + Vuelidate

### ISSUE THREAD

**Issue by Melchyore** [vuelidate/vuelidate#691]
Hey, I'm trying to use the next branch with Vue 2.6 and Composition API (in quasar framework), but it doesn't work, I got the following error : 
```
TypeError: Object(...) is not a function
    at useVuelidate (index.esm.js?dc83:580)
    at useRegisterForm (use-register-form.ts?f336:57)
```
Quasar Framework is not yet shipped with Vue 3, so I tried the old version of Vuelidate, I export the validations object in the setup function but I think it has no effect as I can't find the $v object.

```ts
import { reactive, toRefs, defineComponent } from '@vue/composition-api'
import { api } from 'boot/axios'
import {
  required,
  email,
  minLength,
  sameAs
} from 'vuelidate/lib/validators'

type Selected = {
  label: string,
  value: string | number
}

export default function useRegisterForm () {
  const state = reactive({
    lastName: '',
    firstName: '',
    email: '',
    address: '',
    password: '',
    passwordConfirmation: '',
    terms: false,
    dialCode: 0,
    zipCode: null,
    mobile: '',
    countries: [] as Array<Selected>,
    country: {
      label: null,
      value: null,
      iso: null,
      dial_code: null
    },
    states: [] as Array<Selected>,
    state: {
      label: null,
      value: null
    },
    cities: [] as Array<Selected>,
    city: {
      label: null,
      value: null
    }
  })

  const validations = {
    email: {
      required,
      email
    }
  }

  // METHODS
  async function onSubmit (): Promise<void> {
    try {
      const { data } = await api.post<Array<Record<string, any>>>('/register', {
        last_name: state.lastName,
        first_name: state.firstName,
        email: state.email,
        mobile: `+${state.dialCode}${state.mobile.replace(/\s/g, '')}`,
        country: state.country.value,
        state: state.state.value,
        city: state.city.value,
        address: state.address,
        zip_code: state.zipCode,
        password: state.password,
        password_confirmation: state.passwordConfirmation,
        terms: state.terms
      })
    } catch (e) {
    }
  }

  return {
    state,
    onSubmit,
    validations
  }
}

export default defineComponent({
    name: 'Register',
    setup (props, context) {
        const { state, onSubmit, validations } = useRegisterForm()

        return {
           ...toRefs(state as any),
           validations
      }
   }
})
```

I have no JS error. Any idea please?

**Comment by shentao** [comment]
Hey! 

Sadly the next version doesn’t work with Vue 2.x right now (though I literally build a compat version that works, but it’s not yet published nor tested).
You’re also using it a bit wrong. Take a look at the examples here: https://github.com/vuelidate/vuelidate/blob/next/packages/test-project/src/components/SimpleForm.vue

**Comment by Melchyore** [comment]
@shentao Thanks for the answer, I understand now. Well, the example I've shown uses the old version of Vuelidate and yours, the new one. But now I've wrote the line : 
```ts
const { state, onSubmit, validations } = useRegisterForm()
```
outside the defineComponent function and then used ```validators``` before ```setup``` and it works like a charm but I think it's a bad idea, is it?

**Comment by shentao** [comment]
You could do 

```js
setun () {
  const { state, onSubmit, validations } = useRegisterForm()
  const $v = useVuelidate(validations, state)

  return { $v, state, onSubmit }
}
```

And it should work. You can also move that code into your `useRegisterForm`.

**Comment by Melchyore** [comment]
@shentao I got the following error : 
```
vue.runtime.esm.js?5593:1888 TypeError: Object(...) is not a function
    at useVuelidate (index.esm.js?dc83:580)
    at useRegisterForm (use-register-form.ts?f336:66)
    at setup (Register.vue?222f:289)
    at mergedSetupFn (vue-composition-api.umd.js?c2e3:623)
    at eval (vue-composition-api.umd.js?c2e3:846)
    at activateCurrentInstance (vue-composition-api.umd.js?c2e3:776)
    at initSetup (vue-composition-api.umd.js?c2e3:845)
    at VueComponent.wrappedData (vue-composition-api.umd.js?c2e3:830)
    at getData (vue.runtime.esm.js?5593:4748)
    at initData (vue.runtime.esm.js?5593:4705)
```

**Comment by shentao** [comment]
Well yeah, that’s what I said – the released version is Vue 3.0 only.

I’m working on a compat version with Vue 2.x, but it’s not yet available.

**Comment by Melchyore** [comment]
Well, I'm looking forward to it.

**Comment by alexdee2007** [comment]
@Melchyore 
You can use Vue 2.6 + Composition API + Vuelidate 0.7.5 in this way:

```
<template>
  /* ... */
</template>

<script>
import { getCurrentInstance } from '@vue/composition-api';

export default {
  setup(props, ctx) {
    const instance = getCurrentInstance();
    /* ... */
    const validate = () => {
      instance.$v.$touch();
      /* ... */
    };

    return {
      validate,
      /* ... */
    };
  },
  validations: {
    /* ... */
  },
};
</script>
```

**Comment by Melchyore** [comment]
@alexdee2007 Hi, yes that's how I'm using it. But I moved the validations inside the composable functions (with the data). Thanks!

**Comment by alexdee2007** [comment]
Hi @Melchyore, yes i see. A workaround in this case could be something like this:

Register.vue
```
<template>
  /* ... */
</template>

<script>
import { toRefs } from '@vue/composition-api';
import useRegisterForm, { validations } from './composition/use-register-form';

export default {
  name: 'Register',
  setup(props, context) {
    const { state, onSubmit } = useRegisterForm();
    /** ... */
    return {
      ...toRefs(state),
      onSubmit,
      /** ... */
    };
  },
  validations,
};
</script>
```

use-register-form.js

```
import { reactive, getCurrentInstance } from '@vue/composition-api';
import { required, email } from 'vuelidate/lib/validators';

export default () => {
  const instance = getCurrentInstance();
  const state = reactive({
    email: '',
    /** ... */
  });

  const onSubmit = async () => {
    instance.$v.$touch();
    /** ... */
  };

  return { state, onSubmit };
};

export const validations = {
  email: { required, email },
};
```

**Comment by lucasmb** [comment]
Im using vue 2.6 with composition api like @alexdee2007 suggested above,
it works great for simple validation, but I'm struggling to get variables or functions from the setup inside the validation section
for example 

`export default {
  name: 'Register',
  setup(props, context) {
    return {
      someYearVar
    };
  },
 year: {
           minValue: minValue(someYearVar)
}
};`

If I get the current Instance instance inside the validation section I could do this, but is not updating the values after any input change

`  validations() :{
    const instance = getCurrentInstance()

 year: {
           minValue: minValue((instance?.someYearVar)
}
}
};``

**Comment by dobromir-hristov** [comment]
You can use this `this` inside validations function, to get the current instance, or simply `useVuelidate` composable func.

**Comment by alexdee2007** [comment]
@lucasmb 
You don't need getCurrentInstance() inside validations() func. Just use gool old  `this` :

```
validations() {
      year: {
           minValue: minValue((this.someYearVar)
      }
};
```

**Comment by dobromir-hristov** [comment]
@lucasmb if you are using `setup` for data, use the composable directly - https://vuelidate-next.netlify.app/advanced_usage.html#composition-api

**Comment by alexdee2007** [comment]
@dobromir-hristov 
I understand that we are talking about vuelidate@0.7.5

**Comment by dobromir-hristov** [comment]
Oh sorry hah I was thinking the new Version

**Comment by shentao** [comment]
Well, if you are using Vue 2.6 + Composition API plugin then I would suggest trying out the new Vuelidate version 2.0 :)

**Comment by lucasmb** [comment]
Thanks for your responses!
@alexdee2007 using the good old `this` worked like a charm

> version 2.0 :)
Awesome ! 
I'll check that out

**Comment by mnguyen284** [comment]
@shentao 
> Well, if you are using Vue 2.6 + Composition API plugin then I would suggest trying out the new Vuelidate version 2.0 :)

I've got this error when calling useVuelidate
`TypeError: can't access property "$options", instance.proxy is undefined`

The error is at
`var componentOptions = isVue3 ? instance.type : instance.proxy.$options;`

Could you please give an example project with Vue 2.6 and Vuelidate 2?

I'm using Vue 2.6.12 + Composition API 0.6.7 + Vuelidate 2.0.0-alpha.14

Thank you

**Comment by dobromir-hristov** [comment]
> @shentao 
> > Well, if you are using Vue 2.6 + Composition API plugin then I would suggest trying out the new Vuelidate version 2.0 :)
> 
> I've got this error when calling useVuelidate
> `TypeError: can't access property "$options", instance.proxy is undefined`
> 
> The error is at
> `var componentOptions = isVue3 ? instance.type : instance.proxy.$options;`
> 
> Could you please give an example project with Vue 2.6 and Vuelidate 2?
> 
> I'm using Vue 2.6.12 + Composition API 0.6.7 + Vuelidate 2.0.0-alpha.14
> 
> Thank you
> 

File a new issue please. Also please update to the latest version of the composition api plugin. Vuelidate depends on changes done there.

**Comment by alexdee2007** [comment]
@mnguyen284

Just update vue-composition-api to the latest v1
