### ISSUE TITLE
Collection $each for doble use

### ISSUE THREAD

**Issue by nazordz** [vuelidate/vuelidate#692]
### Can I use double each ?
#ASK
i have some problem with this case. while i check variable `$v`, I see the `$error `is still false.
even if variable `form_category` has filled
```
validations() {
    return {
      form: {
        areas: {
          $each: {
            team_checklists: {
              $each: {
                form_category: { required },
              }
            },
            user: { required },
          }
        }
      }
    }
  },
```

**Comment by dobromir-hristov** [comment]
You should be able to yeah. Show your data object

**Comment by nazordz** [comment]
I think i was solved my problem by my self. Thanks for answered my question 😊
