### ISSUE TITLE
Vuelidate/Validators v2 implicit dependency on Vue - JSPM module broken

### ISSUE THREAD

**Issue by DanielAsher** [vuelidate/vuelidate#694]
[vuelidate@next](https://github.com/vuelidate/vuelidate/blob/next/packages/vuelidate/package.json) and [validators@next](https://github.com/vuelidate/vuelidate/blob/next/packages/validators/package.json) `package.json` don't declare their dependency on Vue 3. (vuelidate only declares it as one of its `devDependencies`)

As a result JSPM is unable to correctly create a working module. This can clearly be seen by comparing:
[vue-router@4](https://jspm.dev/vue-router@4) (working - vue resolved to `import "/npm:vue@3"`)
[vuelidate@2](https://jspm.dev/@vuelidate/core@2) (broken -  vue resolved to `import "/npm:vue!cjs"` )
[validators@2](https://jspm.dev/@vuelidate/validators@2) (broken - vue resolved to `import "/npm:vue!cjs"`)

[Here](https://codepen.io/DanielAsher/pen/wvGgeJr) is a codepen that illusrates the issue. Would be great to push out alpha 1 to `npm` with this fix.

**Comment by DanielAsher** [comment]
This can also be clearly seen in [skypack](https://www.skypack.dev/npm/@vuelidate/core)

Run the code to produce this console error:
```
Uncaught SyntaxError: The requested module '/-/vue@v2.6.12-iVG5t5wwFGETYQaGPTQc/dist=es2020/vue.js' does not provide an export named 'ref'
```

**Comment by dobromir-hristov** [comment]
Hey, I've never used those services, so sorry bout that.

I suppose Vue 3 would have to be a dependency, as we use it's composition API functions, correct?

**Comment by shentao** [comment]
I think we could move it to peerDependencies right?

**Comment by DanielAsher** [comment]
@dobromir-hristov Thanks for the quick reponse! @shentao `peerDependecies` seem the right place at first blush.

btw - I've successfully avoid introducing a bundler into my project to fix this issue by using [snowpack](snowpack.dev)

**Comment by dobromir-hristov** [comment]
Hey @DanielAsher can you check again? We did some changes because of Vue-demi.

**Comment by DanielAsher** [comment]
Hi,

I've reverted to Vue 2, as the ecosystem is not production ready. I'll try this again in a few months.

Please feel free to close this issue.
