### ISSUE TITLE
Phone validator

### ISSUE THREAD

**Issue by Roninii** [vuelidate/vuelidate#695]
👋  Hello,

Love this library! I've been slowly adding it to nearly all our Vue projects at work.

Today I built a custom validator for phone numbers using the built in regex helper. I was considering creating a PR for a phone validator but the PR template mentions creating an issue first so here I am (:

**Comment by shentao** [comment]
Hey! We’d love to accept that PR to the `next` branch. There’s a new package called `validators` that hosts all of the new validators.

**Comment by Roninii** [comment]
@dobromir-hristov That is what I was afraid of. What seemed like a simple addition could end up being a naive implementation that only works for my case (US). 

Do you have an alternative solution, or do you think this might just be out of the scope of the package. I submitted a PR [here](https://github.com/vuelidate/vuelidate/pull/708) for the approach I've already taken.

**Comment by dobromir-hristov** [comment]
As discussed, this is too complicated for a simple validator. Use an external dedicated library for this.
