### ISSUE TITLE
Bug with regex

### ISSUE THREAD

**Issue by NMFES** [vuelidate/vuelidate#699]
JSFiddle: https://jsfiddle.net/awetv6zk/
Video: https://drive.google.com/file/d/1HJl3HgASyAy4Jlp2oxh-hoWQXpDm0uZL/view
Video: https://drive.google.com/file/d/1qzOBIv3uArafG9n0wBQlHbRztFZs2nyt/view

This expression should fail only if we have 3 or more white spaces in the string. And it works correctly in browser console.
Even if we copy/erase/paste some string into the input it still fails or not with 50% chance :[

**Comment by dobromir-hristov** [comment]
Hey there. I see the issue yeah... Have you tried with a simplified regex? Not sure what could be the issue exactly atm.

**Comment by dobromir-hristov** [comment]
Interestingly enough, doing just this works:
```js
      reg: v => new RegExp(/^((?!\s{2,}).)*$/ig).test(v),
```

**Comment by dobromir-hristov** [comment]
Also does this happen inside a Webpack App or you have only tried in the browser? Like a fiddle or something?

**Comment by NMFES** [comment]
Hi. I have tried with simplified regex and found that the flag "g" is doing this effect. If we remove it - then it works. 
But issue with the flag happens only in plugin (Vue, Nuxt, ...). Even for simple expression like /^[a-z]+$/uig
Btw your variant with native usage of regex+test works for me.

**Comment by NMFES** [comment]
> Also does this happen inside a Webpack App or you have only tried in the browser? Like a fiddle or something?

Tried in the App, in JSFiddle and in browser. And in browser it works correctly as you could see.

**Comment by nurdism** [comment]
running into this aswell, in addition to regex flags, it seems if the regex is is stored in a variable it will also fail. 

```js
export const validator = v => new RegExp(/.../ig).test(v) // works

const regex = new RegExp(/.../ig)
export const validator = v => regex.test(v) // fails
```

**Comment by nurdism** [comment]
> https://stackoverflow.com/questions/19277254/javascript-regex-test-fails-when-regex-in-variable-during-jasmine-test

[`test` has weird and unhelpful behavior](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/test)

test called multiple times on the same global regular expression instance will advance past the previous match.

You can get around this by [setting RegExp.lastIndex = 0](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/RegExp/lastIndex?redirectlocale=en-US&redirectslug=JavaScript/Reference/Global_Objects/RegExp/lastIndex) before each match is attempted, but be wary of this behavior.

http://plnkr.co/edit/cne6He?p=preview
