### ISSUE TITLE
V2 $touch runs only for one input on blur and not for others

### ISSUE THREAD

**Issue by Melchyore** [vuelidate/vuelidate#700]
Hello,

Using the new Vuelidate version with Vue 2.6.12 and Composition API, I'm facing a problem : Let say we have 2 inputs, I focus on the first one and I click outside to lose focus, the input get dirty and validation runs. Now if I focus on the second input then click outside, it doesn't get dirty and no validation runs.

Here's a sandbox :  
[Issue demo](https://y6hut.csb.app/)

[Source](https://codesandbox.io/s/gracious-black-y6hut?file=/src/App.vue)

Is it intended or a bug?

**Comment by shentao** [comment]
Hey! Thanks for giving the new version a try! 
This looks most likely as a bug. There must somewhere be something that prevents a second `$touch()` from updating the dirty state.

If you'd like, feel free to investigate it and create a PR with a fix. 
Other wise I sould be able to work on this early next week.

**Comment by Melchyore** [comment]
@shentao I would like to, but when I clone the next branch and run `yarn dev` in the test-project dir I got the following error :

`Uncaught (in promise) SyntaxError: The requested module '/@modules/vue.js' does not provide an export named 'default'`

It only shows when adding these lines in the components : 

```ts
import useVuelidate from '@vuelidate/core'
import { required, helpers, minLength } from '@vuelidate/validators'
```

**Comment by shentao** [comment]
Uh, I think this might be something related to vue-demi and how it affects installing the app. Have you tried doing `yarn link` inside `src/packages/vuelidate` and then `yarn link @vuelidate/core` inside test-project? And then the same for validators.

**Comment by Melchyore** [comment]
I tried, I can see the sources in the browser's console but the error is still here. :(

**Comment by dobromir-hristov** [comment]
This should work with latest Vuelidate release :) Just tested it.
