### ISSUE TITLE
Passing rules from parent to child 

### ISSUE THREAD

**Issue by czzplnm** [vuelidate/vuelidate#712]
I am using Ionic with Vue/Vuelidate and am unable to pass the validation rules to a child input.

The heirarchy of my test app:

LoginPage (Contains the <login-form> component)
LoginForm(Contains username/password input and a submit button)

The LoginForm is using an <input-template> so I can share the style between all pages of the app.

```
    <input-template
        name="username"
        :model-value="this.username"
        :rules="this.rules"
        label="Username"
    >
    </input-template>
```

However I am unable to properly detect errors from the LoginForm -> Login method.

You can view the code here: https://github.com/czzplnm/vuelidate-test/tree/master/src

The LoginForm is using useVuelidate while the child <input-tempalte> is using the VuelidateMixin.

I am trying to dynamically pass the validation rules to the generic input template like: 

` validations(): object {
      return this.rules;
    },`

**Comment by dobromir-hristov** [comment]
I think this is the wrong approach. Either create the validations in the parent and pass down the rules and state for each input, or only pass the rules as a prop, and use setup again to create the validations.

**Comment by czzplnm** [comment]
Okay I refactored it how you suggested and the parent can now trigger validation, but the inputs always think there is an error:


Parent
`
  <div id="login-form">
    <input-template
        name="username"
        :model-value="this.username"
        :rules="{ username: this.rules.username}"
        label="Username"
    >
    </input-template>

    <input-template
        name="password"
        :model-value="this.password"
        :rules="{ password: this.rules.password}"
        label="Password"
    >
    </input-template>

    <button type="submit" @click="login()">Login</button>
  </div>

  methods: {
      login() {
        console.log('Logging in');
        this.v.$dirty = true
        this.v.$touch();
        if (this.v.$invalid) {
          console.log('Invalid form');
        } else {
          console.log('Valid form');
        }
      }
    }
`


Child
`  <div class="form-group">
    <div class="label-wrapper">
      <label>{{ label }}</label>
    </div>
    <div class="input-button-wrapper">
      <input :type="type"
             class="form-control"
             :name="name"
             :value="modelValue"
             :aria-label="label"
             @input="setValue($event)"
      />
    </div>

    <div :visible="v[this.name].$error">
      <p v-for="$error in v[this.name].$errors" :key="$error.$property">
        {{ $error.$message }}
      </p>
    </div>
  </div>

    setup(props) {
      const v = useVuelidate(props.rules)

      return {v}
    },

    methods: {
      setValue($event: any) {
        this.$emit('update:modelValue', $event.target.value)
      },
    }
`


However, if you type in the inputs and click login, it will always think it is invalid.

**Comment by shentao** [comment]
Where do you pass the value? I can only see `useVuelidate(props.rules)` where it should also have the value passed. Should likely be along the lines:
```js
setup (props) {
  const { modelValue, name, rules } = toRefs(props)
  const v = useVuelidate(rules, { [name.value]: modelValue })

  return { v }
}
```

**Comment by czzplnm** [comment]
I updated it to match your example @shentao however I get the same results.

**Comment by czzplnm** [comment]
@shentao  that worked. On the parent view I was also missing v-model on the input-template. Thanks guys
