### ISSUE TITLE
Change output of `useVuelidate` to a reactive object

### ISSUE THREAD

**Issue by adamreisnz** [vuelidate/vuelidate#713]
I noted a [comment in the `next` branch of the code](https://github.com/vuelidate/vuelidate/blob/next/packages/vuelidate/src/index.js#L76) indicating that there is already a TODO for this, but it'd be great if the return value of the `useVuelidate` composition function can be a reactive value instead of a computed.

Currently, this doesn't work:

```js
    const $v = useVuelidate(rules, {model})

    const submit = () => {
      $v.$touch()
      if ($v.$invalid) {
        return
      }
      //...submit form
    }
```

And it has to be rewritten to explicitly reference the underlying `.value`:

```js
    const $v = useVuelidate(rules, {model})

    const submit = () => {
      $v.value.$touch()
      if ($v.value.$invalid) {
        return
      }
      //...submit form
    }
```

By returning a `reactive` object instead, it is my understanding that you will be able to access `$v.$invalid` and `$v.$touch()` directly.

**Comment by shentao** [comment]
Hey! We want it to return a reactive instead of a computed, though for a slightly different reason. However, it then breaks the Options API support, so until we figure out how to handle the latter, this will have to stay as a computed.
Closing this issue as it isn’t really an issue. You can likely expect that change within the next 2 weeks or so.

**Comment by BlackDrakex** [comment]
Will it be implemented or there is some reason why this idea is abandoned?

**Comment by shentao** [comment]
The reason is pretty much the same as above. Additionally, that would be a breaking change by this point, thus no plans on changing this right now.
