### ISSUE TITLE
Overriding error messages in setup function

### ISSUE THREAD

**Issue by robyedlin** [vuelidate/vuelidate#714]
Has anyone figured out how to override the default error messages of a validator inside a component's setup function in Vue 3?

[This section of the next docs](https://vuelidate-next.netlify.app/guide.html#displaying-error-messages) says it points to it, but I don't see an example.

**Comment by dobromir-hristov** [comment]
Try this :) I am working on docs today.

```js
import { required, common } from '@vuelidate/validators'

const newRequired = withMessage('New Message', required);

const rules = {
  field: { 
    required: newRequired
  }
}
```

**Comment by robyedlin** [comment]
Ah, great! I noticed that `common` was not exported, but `helpers` was, and `withMessages` was a method on `helpers`

**Comment by dobromir-hristov** [comment]
Correct! 😆 sorry.
