### ISSUE TITLE
Optionally do not validate child components

### ISSUE THREAD

**Issue by LadislavBohm** [vuelidate/vuelidate#719]
In the new Vuelidate 2 when I have nested child component with using **useVuelidate** I don't seem have option to opt-out from including it's validations in parent component.

My use case is, that child component is modal dialog and my parent component has another form completely unrelated. Now when I am validating parent component it says it's invalid because of failing child rules. It would be nice to have an option to opt-out of this.

**Comment by dobromir-hristov** [comment]
Sounds reasonable. I have no clue how exactly, maybe it's possible via the configs, and providing a name to the valuation? @shentao

**Comment by shentao** [comment]
Hey! That is a great idea! No clue how we haven’t thought about that @dobromir-hristov! 😅 Should be pretty easy to add given that we worked on the config object (3rd argument). I think I might get it done this weekend along with some other changes, unless my cold gets worse. 🤧

**Comment by LadislavBohm** [comment]
Thanks, hope you get well soon.

Just to let others know about my current workaround. What works for me is to wrap modal dialog in div or something and use v-if on it. If the child component does not get mounted then the rules won't get into the parent.

**Comment by tiagoroldao** [comment]
Should this not be opt in, rather than opt out? Composition API - and passing an explicit state object - will likely lead to more usecases where error "bubbling" is not desired.

**Comment by aethr** [comment]
We had a similar issue in our app regarding where to show certain kinds of messaging, and we used named "scopes" for emitting a message that would then be displayed at the closest MessageArea that shared that scope.

Perhaps validations could optionally include a `scope` property, and only child components with the same `scope` in their validation definitions would be included in parent results? Might give more control than just turning validation bubbling on/off.

**Comment by LadislavBohm** [comment]
I like the idea of scopes and since $each is removed from 2.0+ and we are encouraged to use nested validators for collections I think it should be opt out. Otherwise I would agree since it's very confusing when you validator returns $invalid true and you know that it is valid but some child you forgot about might be invalid.

Another problem I can see with collection validations and nested validators is, that a validator in a component has to be rendered in order to be evaluated. What if you have a collection and you render it virtually, then only a few of the items are rendered and other won't get validated then. With $each I believe all of the items would get validated nonetheless.

**Comment by shentao** [comment]
@LadislavBohm Those are valid concerns. For those cases where you need to validate an array of elements that are not rendered, I was thinking about introducing two really simple helpers.

```javascript
// helpers
const every = validator => ({
  $message: validator.$message
  $validator: value => value.every(validator.$validator)
})
const some = validator => ({
  $message: validator.$message
  $validator: value => value.some(validator.$validator)
})

// usage
const requiredName = {
  $message: 'At least one user is missing email',
  $validator: user => rawRequired(user.name)
}

useVuelidate(
  { users }, 
  { users: { requiredName: every(requiredName) } }
)
```

One could also build a helper that would accept an object with rules instead of forcing you to create a dedicated rule/validator to handle specific objects. 

We also started working on the idea for validators to return more than just `true/false`, which would enable us to handle additional data. For example, the `every` helper could return the list of indexes that are failing.

**Comment by LadislavBohm** [comment]
I like those helpers, they seem almost a necessity to make collections transparently validatable. Also the more I work with the new version on a complex form with several tabs and sub-sections the more I think some sort of "scope" is a necessity. I sometimes need to have control over what child vuelidate instances get "attached" to what parent.

Example might be some sort of menu or tabs that take you to different parts of bigger form. I want to have several top-level vuelidates for each tab (in a single "menu" component) and then some child instances for each tab (in case tab contains a list of items for example). 

In this example I need a way to tell child vuelidate instance specific "scope" to which parent this instance gets attached to. Otherwise child can trigger unexpected parent (tab) as false. Use case might be to display error icons on tabs that have errors. Syntax like this might work? It also solves opt-out validation that started this ticket - just set different scope and it doesn't trigger parent vuelidate anymore.

Top level validator:
```
useVuelidate({ username: { required } }, user, { scope: "user" })  
```
Child validators with different scopes on the same screen:
```
useVuelidate({ roles: { required } }, user, { scope: "user" })  
useVuelidate({ order: { number: { required } } }, order, { scope: "order" })  
```

This way only the first validator would trigger the top user validator as false in case of an error.

**Comment by tiagoroldao** [comment]
I like that approach. The absence of `scope` can be a catch-all, and `{scope: false}` would be an explicit opt-out.

**Comment by LadislavBohm** [comment]
Sounds good to me I can't think of any broken scenarios with this. The only case I could think of is if you have two parents in the same component (two vuelidate instances) with same scope. Whether they both should collect the same error from their children (with same scope). Not sure why would you have two vuelidates at the same level but might happen?
I think they both should collect the errors. But if they do, then their parent might collect duplicate errors! Not even sure what happens currently in such a scenario and if it's even supported.
Like I said in my opinion having a scope like we discussed solves all the issues discussed here.

**Comment by dobromir-hristov** [comment]
It will detect the same Vuelidate name and just skip.

**Comment by dobromir-hristov** [comment]
I have done some initial work on this, soon we should have it merged.

General cases:
1. Parent collects all by default.
2. Child can specify it does not want to be collected.
3. If parent and child scope is the same, validations get collected.
4. If parent is set to collect all, child scope does not matter.

**Comment by robyedlin** [comment]
Hi @dobromir-hristov , do you have plans to merge this feature in the near future? It would be really handy!

**Comment by shentao** [comment]
Hey @robyedlin! We still need to figure out some details around validators cache (and its invalidation...).The development has been pretty much on hold during the holidays, but I think we should be back on track to work on this and more.

P.S. Thanks for the sponsorship! 💚

**Comment by robyedlin** [comment]
Cool, cool! Thanks!

**Comment by bisubus** [comment]
@dobromir-hristov Can you clarify how a child is supposed to indicate that it doesn't want to be collected? I ran against the scenarios where I needed both scoped sibling validators and nested validators that shouldn't be collected by any parent. I ended up with a similar approach by enhancing Vuelidate with scope option and `isolate` flag, where the latter is essentially a declarative way to set a scope to `'childScope' + uid`, in this scope name doesn't affect anything but helps debugging.
Would be glad to know where it's headed to not break future compatibility.

**Comment by dobromir-hristov** [comment]
Should be in latest version.
