### ISSUE TITLE
Custom validator - provide additional info with "invalid" result

### ISSUE THREAD

**Issue by TheMaikXX** [vuelidate/vuelidate#720]
Hello, 
I'm trying to achieve collection of objects validation and its working except that I would like to have error message to be more specific.

I have following structure:
```
...
export default {
  ...
  validations() {
    return {
      someModel: {
        fields: {
          fieldValidation
        }
      }
    }
  },
  data() {
    return {
      someModel: {
        fields: [
          {
            fieldLabel: "Some field 1",
            fieldName: "Field1",
            fieldType: "text",
            defaultValue: null
          },
          {
            fieldLabel: "Some field 2",
            fieldName: "Field1",
            fieldType: "number",
            defaultValue: "invalid default value"
          },
          {
            fieldLabel: "Some field 3",
            fieldName: "Field1",
            fieldType: "choice",
            options: [
              "Option 1",
              "Option 2",
              "Option 3",
            ],
            defaultValue: "Non existing option"
          }
        ]
      }
    }
  }
}
```

I'm validating each field of `someModel` by checking whether defaultValue has same type as `fieldType` states, defaultValue is listed in `options` field prop etc..
**And currently, in case of validation error, I'm just able to show to the user message like: _"One or more fields have invalid 'fieldName'"_ or _"One or more fields' default value does not fall within provided options"_** and User need to check manually which field is wrong.

Because the only thing that I can return from custom validator is whether the field is valid or not.

Is there any way to together with the 'validity', return some additional info that could be used inside the message template like:
```
const alwaysInvalid = () => ({
  valid: false,
  metadata: {fieldName: "Some~Field!@#", reason: "Field name contains invalid characters"}
})
```
With message template be like:
```
{
  validationMessages: {
    required: "Field {attribute} is required",
    fieldValidation: "Field {fieldName} is not valid. Reason: {reason}"
  }
}
```

**Comment by dobromir-hristov** [comment]
Hey there. It is on our list, validators can provide extra data. We just have not gotten to it yet.

You can move your field validators to a component that is dedicated to that field, it should work, as the parent will collect it's child validations

**Comment by TheMaikXX** [comment]
Hello,
thanks for quick reply.

You mean that I should inline the custom validator to the field component that has the specific data, like `fieldName` etc. available? But how would I get this data to the error message? Should the message be somehow provided in that nested field component instead?

Thanks

**Comment by dobromir-hristov** [comment]
Which version of Vuelidate are you using?

**Comment by TheMaikXX** [comment]
The latest on npm: 0.7.5

**Comment by dobromir-hristov** [comment]
Sorry, currently there is no way to do that in the library as of `0.x` and I am afraid we wont be doing that, as we are more focused on the new release.

This is on the TODO list for the `next` version.

**Comment by TheMaikXX** [comment]
Hello,
I have managed to workaround this issue. Tommorow I will post here solution.

**Comment by TheMaikXX** [comment]
I have created [gist](https://gist.github.com/TheMaikXX/7f168d5b9b026fd5b79c0a24774f23f2) for this.
I also tried to comment code where appropriate. Basically I'm transforming my model's fields from array to object with keys by which I can identify the field and then making validation attributes as `computed` thus being able to dynamically provide field's `{attribute}` mapping for current fields

**Comment by dobromir-hristov** [comment]
Glad you got something going. Its quite the solution.
