### ISSUE TITLE
vue-demi dependency causes issues

### ISSUE THREAD

**Issue by apathetic** [vuelidate/vuelidate#738]
In `@vuelidate/validators/`, it looks like there is a hard dependency on `vue-demi`. For example, in the `dist` files: 

```import { unref } from 'vue-demi'```  or ```var vueDemi = require('vue-demi')```

However, this package isn't installed with `@vuelidate/validators`, nor listed in its peerDependencies. This leads to: `Module not found: Error: Can't resolve 'vue-demi' in '<...>/node_modules/@vuelidate/validators/dist'`.

I can install `vue-demi` manually and things work great, but I'm not sure if I should need to. 

Note: I'm using the validators in isolation. (For example, the relevant bits from my package.json are: 

```
   ...
    "@vue/composition-api": "^1.0.0-beta.14",
    "@vuelidate/validators": "^2.0.0-alpha.2",
   ...
    "vue": "2.6.11",
```

**Comment by dobromir-hristov** [comment]
Sorry bout that, will fix it asap.
