### ISSUE TITLE
$touch only enabled fields

### ISSUE THREAD

**Issue by lgmf-daitan** [vuelidate/vuelidate#742]
Hello

I have a FormGroup component that triggers all controls validations before actually triggering a submit event

```javascript
    onSubmit() {
      this.formGroup.$touch();

      if (this.formGroup.$invalid || this.formGroup.$pending) {
        return;
      }

      this.$emit('submit', this.formValue);
    },
```

But this is causing a problem, since the _$v_ doest no know about the disabled state of the controls and treats them like regular controls.

Is there a way to only _$touch_ the form elements that are not disaled?

Thanks in advance

**Comment by shentao** [comment]
No. The validations are disconnected from the form elements by design. If a field shouldn’t be validated, it shouldn’t be in the validation rules (hence the ability to have dynamic validation schema).

**Comment by lgmf-daitan** [comment]
Ok. 

I understand

Thanks
