### ISSUE TITLE
Misleading explanation when changing errors messages in the docs

### ISSUE THREAD

**Issue by digital-audits** [vuelidate/vuelidate#748]
## The text
From [https://vuelidate-next.netlify.app/guide.html#displaying-error-messages](url) 
<blockquote><p>Error messages come out of the box with the bundled validators in <code>@vuelidate/validators</code> package. You can check how change those them over at the <a href="./custom_validators.html">Custom Validators page</a></p></blockquote>

## The problem

After navigating to <a href="https://vuelidate-next.netlify.app/custom_validators.html">Custom Validators page</a>, I still don't know how to change the error messages. 
IMO, it lacks a proper explanation otherwise it may mislead the reader.

**Comment by aethr** [comment]
Hi @digital-audits, thanks for raising an issue, I think I encountered the same thing while I was looking at the `next` docs a few weeks ago.

I added a short section to the docs in #750, would you mind reviewing it and let me know if it reads well and answers your question?
