### ISSUE TITLE
Capital letters in domains are invalid

### ISSUE THREAD

**Issue by WhiskeeDev** [vuelidate/vuelidate#753]
https://jsfiddle.net/rfdsvh0m/

Not much extra information I can give for this one, title and jsfiddle cover technical.

`email@domain.com`: Valid
`email@Domain.com`: Invalid

**Comment by aethr** [comment]
@WhiskeeDev this was brought up a couple of weeks ago in https://github.com/vuelidate/vuelidate/issues/747#issuecomment-720807766

Given that domains are case-insensitive, this seems like a good safety feature, but others may not agree. What's your opinion?

**Comment by WhiskeeDev** [comment]
In terms of preventing duplicate email address, this does seem like a good feature.
However the alternative method of converting a user's input before validation can cause alarm, especially to those less aware of how email addresses how.
From a UX perspective, if I was a user who thought domains _were_ case-sensitive, I could become confused/annoyed when an input field keeps changing my email to lower-case.
And with the way vuelidate works at the moment, it's not possible to validate the email without either forcing a change in the value or cloning the original value (to avoid distracting the user) and then changing that, to be validated.

**Comment by bstapleton** [comment]
Agree that case sensitivity **may** be a concern regarding potential for duplicates, but having it as a toggleable state (perhaps with a default of CI) for developers to apply would allow the best balance between UX and back-end requirements for data formatting.

**Comment by aethr** [comment]
@WhiskeeDev I agree that changing the user's input on the fly would not be a good UX, I would probably create a computed property with a sanitized email to use for validation and storage. Perhaps mentioning this in the docs would help developers who run into this design decision?

Maybe it's not the library's job to enforce how people manage emails in their systems, but I think one of the reasons people reach for a library like Vuelidate is to make doing "the right thing" easier. This feels like one of those cases.

**Comment by aethr** [comment]
> Agree that case sensitivity **may** be a concern regarding potential for duplicates, but having it as a toggleable state (perhaps with a default of CI) for developers to apply would allow the best balance between UX and back-end requirements for data formatting.

For the most part, I think Vuelidate has gone with the approach of making custom validators very easy to write instead of trying to accommodate everyone. You could probably make a validator that did this by wrapping a function around the existing email validator and transforming the host to lowercase before passing it through, leaving the source data unchanged.

**Comment by aethr** [comment]
Honestly, I'm not sure about this one. If you want to normalize how you store email domains, it has to be done on the server at the end of the day, it's probably not the job of your validation library.

@shentao or @dobromir-hristov what do you think?

**Comment by dobromir-hristov** [comment]
I also dont think this is Vuelidate's job to do. Closing for now.

**Comment by aethr** [comment]
@dobromir-hristov in that case I think we should fix the email validator to be case-insensitive for domains.

**Comment by Rohan-Jalil** [comment]
@malinushj for your helper function, we don't need to split the capital letters can come even after @ sign, so a better way (imo) would be to have helper function as below
```
export const emailFormatter = (value) => {
  if (!value) return value;
  return value.toLowerCase();
};
```

**Comment by camillekaniecki** [comment]
> For those looking for an intermediary fix, here's my solution using a helper function:
> 
> ```js
> // force the domain of the email to be lowercase and send it to the email validator
> export const emailFormatter = (value) => {
>   if (!value) return value;
>   let parts = value.split('@');
>   parts[1] = parts[1].toLowerCase();
>   return parts.join('@');
> }
> ```
> 
> This is how it would be used:
> 
> ```js
> import { email, required } from 'vuelidate/lib/validators';
> import { emailFormatter } from ...
> 
> // ...
> validations: {
>     form: {
>       email: {
>         required,
>         email: (val) => email(emailFormatter(val)),
>       },
>     },
>   },
> // ...
> ```

You're a lifesaver, thanks for this

**Comment by hn-0** [comment]
Small fix for error produced when vuelidate is auto updating on keystroke

`export const emailFormatter = (value) => {
    if (!value) return value;
    let parts = value.split('@');
    if (parts.length != 2) return value;
    parts[1] = parts[1].toLowerCase();
    return parts.join('@');
}`
