### ISSUE TITLE
v2 alpha 7 compile error with typescript

### ISSUE THREAD

**Issue by gregveres** [vuelidate/vuelidate#755]
I have setup a Vue 2 app w/ composition API and Typescript. 
I just yarn add'd @vuelidate/core and got alpha 7

```
11-18 16:03:35 10> yarn why @vuelidate/core
yarn why v1.22.5
[1/4] Why do we have the module "@vuelidate/core"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "@vuelidate/core@2.0.0-alpha.7"
info Has been hoisted to "@vuelidate/core"
info This module exists because it's specified in "dependencies".
info Disk size without dependencies: "92KB"
info Disk size with unique dependencies: "148KB"
info Disk size with transitive dependencies: "148KB"
info Number of shared dependencies: 1
Done in 1.91s.
```
and when I try to build my project, I get this error in index.d.ts:

```
$ vue-cli-service build --report

\  Building for production...Starting type checking service...
Using 1 worker with 2048MB memory limit
|  Building for production...

 ERROR  Failed to compile with 1 errors                                                                                                                                                                                                     4:03:29 PM
 error  in C:/Users/gregv/source/repos/SquashSpider/SquashSpider/SkyCourt.UI/ui/node_modules/@vuelidate/core/index.d.ts

ERROR in C:/Users/gregv/source/repos/SquashSpider/SquashSpider/SkyCourt.UI/ui/node_modules/@vuelidate/core/index.d.ts(160,37):
160:37 Cannot find name 'App'.
    158 |   registerAs?: string
    159 | ) => Ref<Validation<Vargs>>;
  > 160 | export const VuelidatePlugin: (app: App) => void;
        |                                     ^
    161 | 
    162 | export default useVuelidate;
    163 | 

 ERROR  Build failed with errors.
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

I believe there is an error in the index.d.ts file. The type App is not defined anywhere. I assume this is supposed to be the Vue app, but it needs to be explicit about that. 

I will back up to alpha 6 to see if that fixes it, but  with index.d.ts this way, I can't use alpha 7 at all because my build breaks.

**Comment by aethr** [comment]
Sorry about that. This was fix in #752 and will be in the next release.

**Comment by gregveres** [comment]
Great that you know about it. Any ETA on the next release? 
I really like how v2 works with the composition API.

**Comment by aethr** [comment]
There's no official schedule for alpha releases but they generally happen once a week if there are changes to get out.

In the meantime the fix in #752 is quite small, you could manually make that change to vuelidate in your `node_modules` folder during development.

Please keep in mind v2 is still in alpha and not ready to be used in a production site.

**Comment by dobromir-hristov** [comment]
Will release it in tomorrow morning :)

**Comment by gregveres** [comment]
Thanks for the info everybody. I dropped back to alpha-6 for now. I will update when its available.

**Comment by dobromir-hristov** [comment]
Published
