### ISSUE TITLE
No indication of Vue 3 support in documentation. No information on latest version installation.

### ISSUE THREAD

**Issue by RollingTL** [vuelidate/vuelidate#757]
1.  It is hard to understand for not experienced user wether Vuelidate supports Vue3.

2. Instruction informs that to install one should run npm install vuelidate --save. But no indication that it will install version vuelidate@0.7.6.  
And no indication how to install last version
I tried npm install vuelidate@next --save, npm install vuelidate@2.0.0 --save with no good result. 
Only after long search I had found - npm i @vuelidate/core @vuelidate/validators --save
and npm install --save @types/vuelidate

3 New way of importing to Vue 3 never mentioned in docs:

import { VuelidatePlugin } from '@vuelidate/core'
app.use(VuelidatePlugin)

**Comment by shentao** [comment]
Good point. We should add a mention of the new docs to the old ones :) And to the README.

**Comment by ajdvoynos** [comment]
So does it support it or not? https://vuelidate.js.org/ seems to imply that it doesn't, as the Title says "Model based validation for Vue.js 2.0"

**Comment by shentao** [comment]
@ajdvoynos the docs have not been updated. You can go to https://vuelidate-next.netlify.app/#installation for new docs. If you want, you can introduce links to the new docs in a PR.

**Comment by surajmore98** [comment]
@shentao  I have created one PR as my first contribution to open source  for this one you can check : https://github.com/vuelidate/vuelidate/pull/771

**Comment by dobromir-hristov** [comment]
Added.
