### ISSUE TITLE
Error: Maximum recursive updates exceeded. - with nested useVuelidate usage

### ISSUE THREAD

**Issue by etay2000** [vuelidate/vuelidate#764]
When using nested validation, and a parent that displays validation errors in it's template, any changes to the nested component causing a hot reload trigger a 'Maximum recursive updates exceeded error'. Removing the reference to validation.$errors in the parent template resolves the error. 

```
<!-- Parent -->
<template>
  <span>Parent errors: {{ validation.$errors }}</span> 
  <Nested/>
</template>
<script lang="ts">
export default defineComponent({
  components: {
    Nested
  },
  setup() {
    const rules: any = {};
    const validation: Ref<Validation> = useVuelidate(rules, {});
    console.log('Hot Reload: Parent');
    return {
      validation
    };
  }
})
</script>

<!-- Nested -->
<template>
  <span>Nested</span>
</template>
<script lang="ts">
export default defineComponent({
  setup() {
    const rules: any = {};
    const validation: Ref<Validation> = useVuelidate(rules, {});
    console.log('Hot Reload: Nested:::');
    return {};
  }
})
</script>
```

Update the console log text to trigger a hot-reload which will trigger the maximum recursion error.

**Comment by shentao** [comment]
This is something we are working on. However, you could help us a lot by providing a failing test for that specific case!

**Comment by etay2000** [comment]
I'd love to help, but I've already lost a fair amount of time hunting this down. It should be pretty easy to duplicate using the minimal code above.

**Comment by shentao** [comment]
Sorry to hear that. Understandable.

**Comment by ajdvoynos** [comment]
I'm also facing this `maximum recursive updates` issue, but in a slightly different scenario, using custom validation methods. Have you made any progress on this? I have a stripped down version of my code which shows the problem, if you're interested?

**Comment by dobromir-hristov** [comment]
Could you guys try with the latest Vuelidate version?

**Comment by lamka02sk** [comment]
Still having this problem in 2.0.0-alpha.10 😿

**Comment by lamka02sk** [comment]
For anyone seeking fast although not proper solution, use `$scope` property in `useVuelidate` function: https://vuelidate-next.netlify.app/advanced_usage.html#scope-property
```javascript
useVuelidate(rules, data, { $scope: false })
```

**Comment by darkopetreski** [comment]
I am facing the same problem. Parent component and array of child components with several fields with validators. When hot reload I get recursion. I will try to provide example in the following days.

**Comment by bravik** [comment]
> For anyone seeking fast although not proper solution, use `$scope` property in `useVuelidate` function: https://vuelidate-next.netlify.app/advanced_usage.html#scope-property
> 
> ```js
> useVuelidate(rules, data, { $scope: false })
> ```

I found that `$stopPropagation: true,` is more appropriate instead, because when using `scope: false` your root component is not able to gather errors and `$invalid` state. While this is important if you wish to disable your "Submit" button for example...

**Comment by emanuelradu** [comment]
Do you have any updates on this issue?

**Comment by ascheffeapi** [comment]
This may work. I moved the useVuelidate into an onMount callback and it stopped the reloads in the parent. 
```
let v$ = undefined;
onMounted( async () => {
  v$ = useVuelidate(
    rules,
    state,
    {
      $registerAs: "Child",
      $lazy: true,
   });
});
```

**Comment by abcirta** [comment]
It's been nearly 3 years now, any updates or workarounds ?

**Comment by shentao** [comment]
@arslan-bz could you provide a repo with minimal reproduction steps?

**Comment by clemt35** [comment]
>:(

**Comment by joshuagraber** [comment]
Hi, any updates here? I'm experiencing the same very frustrating issue.

**Comment by nerminjukan** [comment]
Hello, same on my end, very annoying issue, please help. @shentao @dobromir-hristov

**Comment by sawa-ko** [comment]
I have this same problem but using useField.

```ts
  import { useField } from 'vee-validate';

  defineOptions({
    inheritAttrs: false,
  });

  const props = defineProps<{
    autocomplete?:
      | 'current-password'
      | 'email'
      | 'family-name'
      | 'given-name'
      | 'new-password'
      | 'off'
      | 'on'
      | 'username';
    disabled?: boolean;
    hasError?: boolean;
    hasWarning?: boolean;
    hint?: string;
    iconLeft?: `lucide:${string}`;
    iconRight?: `lucide:${string}`;
    label: string;
    name: string;
    placeholder?: string;
    readonly?: boolean;
    type: 'email' | 'password' | 'search' | 'tel' | 'text' | 'url';
  }>();

  const isFocused = ref(false);
  const isShowPassword = ref(false);

  const { errorMessage, errors, handleBlur, handleChange, value } = useField(() => props.name);
```

![image](https://github.com/vuelidate/vuelidate/assets/56084970/5ada340c-e176-41e0-ac23-c720495496f1)

**Comment by hardmagnett** [comment]
@shentao @dobromir-hristov 
Hi.

Bug is still present.

It appears on making changes on child.

Furthermore,
if you'll try pass part of formValue object from parent to child,
you'll lose reactivity on live-reload.

{ $scope: false } not helps.


Removing the reference to v$ in the parent template resolves the error.

Versions:
"@vuelidate/core": "^2.0.3",
"@vuelidate/validators": "^2.0.4",
"vue": "^3.4.27",

Minimalistic working example:

Parent:

```vue
<script setup lang="ts">
import {reactive} from 'vue'
import ChildOne from "@/a-library/views/component-list/ViewExperiments/ChildOne.vue";
import {minLength, required} from "@vuelidate/validators";
import {useVuelidate} from "@vuelidate/core";

let formValues = reactive({
  lastname: "outer",
});
const formRules = {
  lastname: { required, minLength: minLength(3), $autoDirty: true },
}

const v$ = useVuelidate(formRules, formValues)

</script>

<template>
  <div class="view-experiments">
    <ChildOne />
    <input v-model="formValues.lastname">
    <pre>
      <!--Uncomenting any of this strings produses bug-->
      {{v$.lastname.$errors.map(e=>e.$message)}}
      {{v$}}
    </pre>
  </div>
</template>
````

Child:
```vue
<script setup lang="ts">
import {reactive, unref} from 'vue'
import {minLength, required} from "@vuelidate/validators";
import {useVuelidate} from "@vuelidate/core";


const formValues = reactive({
  name: "Inner",
})
const formRules = {
  name: { required, minLength: minLength(3), $autoDirty: true },
}
const v$ = useVuelidate(formRules, formValues)

// Make any changes here to get bug. For example uncomment next string.
// let a = 1;
</script>

<template>
  <div class="child-one">
    <input v-model="formValues.name">
  </div>
</template>

```

**Comment by jcupps** [comment]
A simple workaround is to use a computed prop to access `v$`. e.g.:

```vue
<script setup lang="ts">
import {useVuelidate} from "@vuelidate/core";

const v$ = useVuelidate(...);
const isInvalid = computed(() => v$.value.$invalid);
</script>

<template>
  <div>
      <!-- This works -->
      {{ isInvalid }}
      <!-- This doesn't -->
      {{ v$.$invalid }}
  </div>
</template>
```
