### ISSUE TITLE
$invalid evaluating to true on first check, not on second

### ISSUE THREAD

**Issue by silvaDominic** [vuelidate/vuelidate#766]
This issue is also strangely linked to an async isUnqiue validator.

Issue:
There seems to be an issue with the state of $invalid when the isUnique function is present.

Steps to recreate:
A validation check is performed before a save operation in this way:

```
      if (this.$v.segment.$invalid) {
        this.$v.segment.$touch();
        return false;
      }
      return true;
```

My validators are as follows:

```
    segment: {
      name: {
        required,
        minLength: minLength(3),
        maxLength: maxLength(100),
        async isUnique(name) {
          if (!this.newSegment) return true;

          // Don't perform check if field is empty or not correct length
          if (name === "" || !this.$v.segment.name.minLength) return true;
          return Boolean(await this.segmentsService.isUniqueName(name))
        },
      }
```

Whenever I trigger this validation check (via a button press) the form is evaluated to invalid and blocks the save action. On a consecutive button press, the form is evaluated as valid and saved.

The strange issue is that when I add `this.$v.segment.$invalid` into the template to get visual feedback on the state of the form, the $invalid state always works properly, saving on the first time. Further, I've confirmed that the source of the error has to do with the isUnique function as the core issue does not exist when it's removed. This is even stranger to me because in my test cases, it's not even performing a network call. It's just returning true right away.

When performing console.log checks during the time of the conditional check, the state of $invalid is in fact true. If I additionally print the object and inspect it after. The value has changed to false. There definitely seems to be an issue with the initial check.

I don't understand:
1) How adding `this.$v.segment.$invalid` in the template 'fixes' the issue
    **I discovered that the reason adding this to the template 'fixes' the issue
 is because it runs the validation for the first time.**
I still do not understand why the form is always invalid the first check.

2) Why isUnique is causing issue in the first place when it returns a boolean right away.

Possibly related to this isssue:
https://github.com/vuelidate/vuelidate/issues/296

**Comment by silvaDominic** [comment]
Discovered the issue was a result of wrapping my only validation checks within a template conditional statement (v-if). I had done this naively because the name field only needs to be validated during the creation of a new entity, as it's immutable and read only once it exists. However, that conditional block removed the validators that checked for errors causing the invalid state to never properly evaluate on the first page load.

It's an particular case, but hopefully this helps anyone in the future.

**Comment by shentao** [comment]
Interesting! Thanks for clearing this up!
