### ISSUE TITLE
vue-demi doesn't include Plugin export

### ISSUE THREAD

**Issue by gregveres** [vuelidate/vuelidate#767]
I just upgraded from 2.0 alpha 6 to alpha 8. Now I get a build error
```
ERROR in C:/Users/.../node_modules/@vuelidate/core/index.d.ts(1,32):
1:32 Module '"../../vue-demi/lib"' has no exported member 'Plugin'.
  > 1 | import { Ref, defineComponent, Plugin } from 'vue-demi';
      |                                ^
    2 | type Component = ReturnType<typeof defineComponent>;
    3 | 
    4 | /*
Version: typescript 3.9.7
```
I did a yarn why vue-demi and got this:
```
12-11 08:29:44 8> yarn why vue-demi
yarn why v1.22.5
[1/4] Why do we have the module "vue-demi"...?
[2/4] Initialising dependency graph...
[3/4] Finding dependency...
[4/4] Calculating file sizes...
=> Found "vue-demi@0.4.3"
info Reasons this module exists
   - "@vuelidate#core" depends on it
   - Hoisted from "@vuelidate#core#vue-demi"
   - Hoisted from "@vuelidate#validators#vue-demi"
info Disk size without dependencies: "56KB"
info Disk size with unique dependencies: "56KB"
info Disk size with transitive dependencies: "56KB"
info Number of shared dependencies: 0
Done in 1.85s.
```

I am using Vue 2.6.12 in case that matters.

**Comment by gregveres** [comment]
Ok, I have tracked this down a bit. The issue is that I am using Vue 2 instead of Vue 3. The type Plugin is not defined in Vue 2. Plugins are defined as PluginFunction or PluginObject and those are the types that are exposed in Vue2. 
But in Vue 3, there is a Plugin type that vue 3's index.d.ts file exposes. It seems that vue-demi isn't abstracting that part of vue for you.

**Comment by gregveres** [comment]
I have backed up to alpha-7 for the time being

**Comment by mortir** [comment]
Hi,
Have the same problem, use with TypeScript?
There is some solution?

**Comment by victororlyk** [comment]
I have the same problem with stackblitz when trying to vuelidate with vue3.
https://github.com/vuelidate/vuelidate/issues/772#issue-771599686

**Comment by piscis** [comment]
We're using vue2 + composition api / vue-demi + typescript.  When we use @vuelidate/core alpha-8 we get the same failure when downgrading to alpha-7 we get:

`Can not find name App`:
![Screenshot 2021-01-17 at 18 09 23](https://user-images.githubusercontent.com/326163/104850464-91b63e80-58ef-11eb-979a-7c517c69c125.png)

What worked for us was: @vuelidate/core alpha-6 + @vue/composition-api / vue-demi + typescript

**Comment by dobromir-hristov** [comment]
We removed Plugin from the exports.

**Comment by kostia7alania** [comment]
I faced this issue.
