### ISSUE TITLE
Localizing error messages in Vuelidate-next

### ISSUE THREAD

**Issue by klausXR** [vuelidate/vuelidate#769]
The application that I'm working on receives its localization strings dynamically from a network request. To localize strings, I have created a simple plugin, which receives a string name and refers to its value ( localizations are stored in Vuex ).

In short, its injected from a Nuxt plugin

```js
export default ({ store }, inject) {
  // locales = { homepage_title: "Homepage" }
  const t = path => store.state.locales[path]
  inject("t", t)
}
```

In templates, its used similarly to `$t('homepage_title')`.

How should I go about localizing my error messages with your library? I assume that I need to re-export the validators from your package that I'd like to use, and accustom their error messages to my use-case. 

Assuming I have this localization string for a `maxLength` validator `The maximum length allowed is {{length}}`, I would be able to do this

```js
export const maxLength = max => withMessage(
  vuelidateRule => $t('errors_maxlength', { length: validationRule.params.max }),
  maxLength(max)
)
```

My issue is, the `$t` part is a plugin injected at run-time, which I don't have access to in my example. How would I go about this to reduce the boilerplate for my forms to a minimum?

It feels like my end goal would be to be able to do this

```js
import { maxLength } from "@/utils/validators"

export default {
    ...,
    validations() {
        return {
            form: {
                name: {
                    maxLength: maxLength(35)
                }
            }
        }
    }
}
```

Thanks a lot for this feature, by the way. Now its a complete validator :)

**Comment by dobromir-hristov** [comment]
You should be able to import the localisation instance in your validators?

**Comment by klausXR** [comment]
Well, I can't, because its dynamically injected through a nuxt plugin, as can be seen from the example. But even if using `vue-i18n`, I'm not sure that one allows you to import the localization instance either, it only adds mixins and directives.

**Comment by kibertoad** [comment]
@dobromir-hristov Are there no plans to support localisation within builtin validators, e. g. by accepting optional `messageResolver` function param?

**Comment by dobromir-hristov** [comment]
We never discussed it but that is all option. I will play with some ideas.
