### ISSUE TITLE
How to add condition based url validation in vuelidate

### ISSUE THREAD

**Issue by Jai-Kumaresh** [vuelidate/vuelidate#770]
I used `vuelidate` in my vue.js project form validation. It's works good.

But I need URL validation with a condition based. My requirement below.

My create meeting form have location type field & that based location info field.

Screenshots below:

Type - 1

![image](https://user-images.githubusercontent.com/43090102/102040744-aafd3400-3df3-11eb-911d-07e08ba339d1.png)

Type - 2

![image](https://user-images.githubusercontent.com/43090102/102040775-bf413100-3df3-11eb-8faf-28ac68c0450c.png)

If the user chooses virtual URL validate added. otherwise not to add URL validate.

If anyone has this solution Kindly share me.

**Comment by dobromir-hristov** [comment]
Just return different valuation based on the selection. Validations can be a function that returns an object

**Comment by Jai-Kumaresh** [comment]
> Just return different valuation based on the selection. Validations can be a function that returns an object

@dobromir-hristov Thank you for your comment. But, I didn't understand your solution. Kindly explain that solution brief.

**Comment by dobromir-hristov** [comment]
```js
validations() {
 return {
    link: {
      someRule: this.otherField.checked ? url : otherValidator 
    }
  }
}
```

**Comment by Jai-Kumaresh** [comment]
> ```js
> validations() {
>  return {
>     link: {
>       someRule: this.otherField.checked ? url : otherValidator 
>     }
>   }
> }
> ```

@dobromir-hristov  Thank you. I got it.

My solution is below

```
validations() {
  const self = this;
  return {
    model: {
      location: { required },
      location_info: {
        required,
        condUrlVald: self.model.location == 'V' ? url : required
      }
    }
  }
},
```
