### ISSUE TITLE
Invalid TypeScript declaration for sameAs

### ISSUE THREAD

**Issue by khorsky** [vuelidate/vuelidate#773]
I'm using TypeScript, Vue 3, vuelidate/core 2.0.0-alpha.8, vuelidate/validators 2.0.0-alpha.5.

Code and rules work as expected, but I'm encountering TypeScript error "Expected 2 arguments, but got 1" for sameAs validator. Rule definition: 

```
// ...

controlPassword: {
  sameAs: sameAs(newPassword),
},

// ...
```

When trying to find out where do I have a bug, I found file `node_modules/@vuelidate/validators/index.d.ts`, that exports this:

```
export const sameAs: <E = unknown>(
  equalTo: E,
  otherName: string
) => ValidationRuleWithParams<{ equalTo: E, otherName: string }>; 
```

I believe that's the source of error, but I'm not sure if it's not intended for some reason...

**Comment by dobromir-hristov** [comment]
Please contribute a fix, TS was not first priority at the time of writing the alpha version.
