### ISSUE TITLE
Module '"../../node_modules/@vuelidate/validators"' has no exported member 'helpers'.

### ISSUE THREAD

**Issue by jyork03** [vuelidate/vuelidate#785]
I'm using vue 3 and vuelidate 2 (current latest "@vuelidate/core": "^2.0.0-alpha.8" and "@vuelidate/validators": "^2.0.0-alpha.5") with typescript, and I cannot import the `helpers` object since there is no exported member 'helpers' in `node_modules/@vuelidate/validators/index.d.ts`.   You can verify it yourself here: [index.d.ts](https://github.com/vuelidate/vuelidate/blob/%40vuelidate/validators%402.0.0-alpha.5/packages/validators/index.d.ts)

The [custom error messages](https://vuelidate-next.netlify.app/custom_validators.html#custom-error-messages) section of the documentation provides two examples for importing `helpers` from the library:

`import { required, helpers, minLength } from '@vuelidate/validators'`
and 
`import { helpers } from 'vuelidate/lib/validators'`

In it's current state, the recommended usage in the documentation does not work in typescript.

my usage in my project is nearly identical
`import { required, helpers } from '@vuelidate/validators';`

The import of `required` works just fine, but `helpers` is missing and breaks the typescript compilation with `TS2305: Module '"../../node_modules/@vuelidate/validators"' has no exported member 'helpers'.`

The `helpers` export needs to be added to the `index.d.ts` file for this to work properly.

Let me know if I can provide any additional information that might help.

**Comment by dobromir-hristov** [comment]
If you could contribute a fix to the types, that would be awesome.

**Comment by KVahlin** [comment]
Let me get this straight. that functionality is not work currenlty now?

**Comment by dobromir-hristov** [comment]
Helper's work, the types are probably wonky

**Comment by dobromir-hristov** [comment]
Should be fixed in @vuelidate/validators@2.0.0-alpha.9
