### ISSUE TITLE
help with optional validator

### ISSUE THREAD

**Issue by josejachuf** [vuelidate/vuelidate#786]
Hi,

I have the following situation and I don't know how to solve it.
To simplify I have two fields:
F1. It can take two values: A or B
F2. It is always required, but if F1 is B I must also validate a custom validator: myvalidator

I am sure that myvalidator works fine

i looked at this [1] but i couldn't do what i need.

I would appreciate if someone could help me
Jose

[1] https://vuelidate.js.org/#sub-optional-validator

**Comment by dobromir-hristov** [comment]
Use a function for validations, that returns different validation object based on some condition.
