### ISSUE TITLE
Basic Validate of type, exact value, alternatives etc

### ISSUE THREAD

**Issue by kubaPod** [vuelidate/vuelidate#787]
Hi, the library is great though I got stuck with issues more basic than the 'Basic usage', namely how to validate that a field:

1. is of e.g. `String` / `Object` / `Number` type or,
2. is exactly e.g. `"this string"`
3. has a value from given alternatives: `['opt1', 'opt2', 3]`
4. containsAll / containsAny / containsNone etc of given alternatives ( ? #422)

It seems that 1. can be solved with `fieldName: { required: String }` but I don't see this documented anywhere so I suspect it is not the right way.

All can be solved by writing a set of simple helpers with `==` `is` `indexOf` but I got stuck because I expected they will already be built in.
They are not, are they? Will they be? If not, what is the reason?

Regardless of answers and plans I think it is worth to put a line of explanation somewhere in docs, around Basic usage or Builtin validators sections.

**Comment by dobromir-hristov** [comment]
They are not included, as they are simple enough to create on your own. We did not want to bloat the package with validators.

If you think they make sense to be added, you can contribute to the project, or create your own validations package, that people can use.
