### ISSUE TITLE
how to set $v

### ISSUE THREAD

**Issue by qwentry11** [vuelidate/vuelidate#788]
```
import` { required } from 'vuelidate/lib/validators'

export default {
  data () {
    return {
      middleName: '',
    }
  },
  validations: {
    cusInd: {
        middleName: {reauired}
      },
    }
  }
}
```

When changing the checkbox, the required parameter must change its value so that the check does not work on this field.

`this.$v.cusInd.middleName.required = true;`

error.. TypeError: Cannot set property required of #<Object> which has only a getter

**Comment by dobromir-hristov** [comment]
Vuelidate properties are not mutable. If you need to make it conditional, transform `validations` into a function and do your logic there.
