### ISSUE TITLE
Setting optionMergeStrategies problem

### ISSUE THREAD

**Issue by masoudelahi** [vuelidate/vuelidate#789]
version: 2.0.0-alpha.8
Vue: 3.0.5

When I set the 'optionMergeStrategies' as follows
`app.config.optionMergeStrategies.validations = app.config.optionMergeStrategies.data;`
I get this error:

![Annotation 2021-01-22 203545](https://user-images.githubusercontent.com/22923839/105521665-72555200-5cf1-11eb-889b-742d315d66a0.png)

**Comment by dobromir-hristov** [comment]
Vuelidate does not support merge strategies, sorry.
