### ISSUE TITLE
Vuelidate Types

### ISSUE THREAD

**Issue by louiss0** [vuelidate/vuelidate#793]
### Make sure that you are familiar with documentation before submitting an issue.

  https://vuelidate.netlify.com/

### Please use the following jsfiddle to provide a reproduction of your problem

  https://jsfiddle.net/Frizi/b5v4faqf/

Issues without a working fiddle are generally much harder to solve and usually take much more time to actually do it.

here are the ones i made you can take the files if you want    [the type definitions](https://github.com/louiss0/vuelidate-types)

**Comment by dobromir-hristov** [comment]
As of now, Vuelidate will stay written in JS. Thank you for your time.
