### ISSUE TITLE
"export 'VuelidatePlugin' was not found in '@vuelidate/core'

### ISSUE THREAD

**Issue by ZeusZoe** [vuelidate/vuelidate#797]
### Make sure that you are familiar with documentation before submitting an issue.
Hi,
I've installed the last version for vue-cli for vuejs 3 by npm install @vuelidate/core @vuelidate/validators.

I initialize the plugin by

`import { createApp } from 'vue'
import App from './App.vue'

import {VuelidatePlugin} from '@vuelidate/core';

createApp(App).use(VuelidatePlugin).mount('#app')`

When I build the app, I get this warning:

"export 'VuelidatePlugin' was not found in '@vuelidate/core'

I opened the plugin's files and I do not found the VuelidatePlugin function.

Regards

**Comment by dobromir-hristov** [comment]
There is no plugin anymore. Please read the updated docs. Thank you.

**Comment by FofoDev** [comment]
The vue 3 documentation on the 'next' branch doesn't seem to be updated, as it still says to use the plugin

**Comment by dobromir-hristov** [comment]
@shentao you had one job 😁😁😁

**Comment by dobromir-hristov** [comment]
@FofoDev could you share a link to where you are reading these outdated instructions?

**Comment by ZeusZoe** [comment]
https://github.com/vuelidate/vuelidate/tree/next

**Comment by dobromir-hristov** [comment]
The readme 😂 use the docs website pls. I will update the readme in 15mins

**Comment by ZeusZoe** [comment]
thanks

**Comment by metalsadman** [comment]
> There is no plugin anymore. Please read the updated docs. Thank you.
> 
> Call useVuelidate in your component setup.

why was this removed tho? imo it helps with legacy vue 2 code that relied on the validation options to work, otherwise we are forced to migrate quickly to composition api which is not a work in the park to do.

**Comment by dobromir-hristov** [comment]
It was causing allot of issues, memory problems etc. We also can't use provide inject outside of setup.

**Comment by shentao** [comment]
And `setup` can’t be mixed in through a `mixin`, which limited our options.

Since Vuelidate v2 already requires the composition-API, we decided that requiring the dev to add a 1 online `setup` function is not that terrible.

```js
  setup () {
    return { v$: useVuelidate() }
  },
  validations: {
    person: {
      required,
      minLength: minLength(2),
    }
  }
}
```

**Comment by ZeusZoe** [comment]
@dobromir-hristov can you remove the note on my initial post?

Regards

**Comment by dobromir-hristov** [comment]
I don't get what you mean, sorry.

**Comment by ZeusZoe** [comment]
@dobromir-hristov I'm reading this note: "Make sure that you are familiar with documentation before submitting an issue." on my initial post.

**Comment by ZeusZoe** [comment]
Thank you.

Regards
