### ISSUE TITLE
Vue 2 + Composition API support broken

### ISSUE THREAD

**Issue by stickeegreg** [vuelidate/vuelidate#798]
Pull release #790 makes use of `isProxy`, which not supported by [vuejs/composition-api](https://github.com/vuejs/composition-api).

```
Missing APIs
The following APIs introduced in Vue 3 are not available in this plugin.

 - defineAsyncComponent
 - onRenderTracked
 - onRenderTriggered
 - isProxy
```

This results in the following error:
`Error in callback for immediate watcher "function () { return source.value; }": "TypeError: Object(...) is not a function"`

Using cut-down sample code from the documentation will trigger the error.

```
const name = ref('')
const rules = computed(() => ({name: {required}}))
const v$ = useVuelidate(rules, { name })
```

**Comment by dobromir-hristov** [comment]
Yep, I saw. I will use another helper for that, thanks.

**Comment by dobromir-hristov** [comment]
Should be fixed in latest release.
