### ISSUE TITLE
[Vuelidate 2] [Vue warn]: Error in data(): "TypeError: Cannot read property 'validations' of undefined"

### ISSUE THREAD

**Issue by metalsadman** [vuelidate/vuelidate#799]
### Make sure that you are familiar with documentation before submitting an issue.
following the snippet from https://vuelidate-next.netlify.app/#getting-started-2, using `@vue/composition-api 1.0.0-rc.1`
  https://vuelidate.netlify.com/

### Please use the following jsfiddle to provide a reproduction of your problem

  https://codepen.io/metalsadman/pen/MWbjvJm?editors=1010

Steps:
 1. open provided codepen
 2. un-comment line `// v$: useVuelidate()`
 3. see error logs

**Comment by dobromir-hristov** [comment]
Got a fix in. Will probably release later today :)

**Comment by dobromir-hristov** [comment]
Released in alpha.10
