### ISSUE TITLE
useVuelidate breaks reactivity connection of object returned by a toRef

### ISSUE THREAD

**Issue by IlCallo** [vuelidate/vuelidate#805]
The codesandbox won't compile due to some error with vue-demi, but I hope you can get the gist.
Providing an object obtained via `toRefs` into `useVuelidate` will break the connection between the original state and the generated refs. Was pretty painful to debug.

If the refs object is denstructured, everything works as expected. I tried to look into the source code, but could not understand where the problem lies

https://codesandbox.io/s/brave-raman-fex90?file=/src/App.vue

**Comment by dobromir-hristov** [comment]
Why don't you just pass the state as a reactive?

**Comment by IlCallo** [comment]
Because I didn't know it was possible :D
Docs doesn't mention it's possible, I thought you needed a plain object of refs

**Comment by dobromir-hristov** [comment]
It is documented - https://vuelidate-next.netlify.app/#alternative-syntax-composition-api

**Comment by IlCallo** [comment]
I see, I was reading there instead: https://vuelidate-next.netlify.app/advanced_usage.html#composition-api
But I see you just updated that page too to show the reactive state usage.

The highlighted problem still holds btw, but I guess it's intended behaviour or we're in "won't fix" realm

**Comment by dobromir-hristov** [comment]
Yeah... We have the main ways working, so I think that's good for now
