### ISSUE TITLE
Lazy validation & touch not working properly?

### ISSUE THREAD

**Issue by khorsky** [vuelidate/vuelidate#807]
@vuelidate/core: ^2.0.0-alpha.12,
@vuelidate/validators: ^2.0.0-alpha.11,

After updating to latest Vuelidate I'm unable to use lazy validation and I'm wondering what am I doing wrong. The simplest code I'm able to write:
```
<template>
  <form @click.prevent="test">
    <input v-model="name" type="text"> 
    <button type="button" @click="v$.$touch()">touch</button>
    <button>submit</button>
  </form>

  <pre>{{ name }}</pre>

  <pre>dirty: {{ v$.$dirty }}</pre>
  <pre>error: {{ v$.$error }}</pre>
  <pre>invalid: {{ v$.$invalid }}</pre>
</template>

<script lang="ts">
import { defineComponent, ref } from 'vue'
import useVuelidate from '@vuelidate/core'
import { required } from '@vuelidate/validators'

export default defineComponent({
  name: 'Home',
  setup() {
    const name = ref('')

    const v$ = useVuelidate(
    {
        name: { required },
    },
    { name },
    { $lazy: true },
  )

  const test = () => {
    v$.value.$touch()

    if (!v$.value.$error) {
      console.log('success')
    }
  }

  return {v$, name, test}
  },
})
</script>

```
After submit, I get success regardless to name value. When I click touch first, it works. When remove $lazy, it works.

Is it a bug or intended behavior?

**Comment by dobromir-hristov** [comment]
Validations are no longer lazy by default, as that was a huge breaking change. If you need them to be, set them as `$lazy`.

That ofc means no validations are run, and the state is considered valid.

**Comment by khorsky** [comment]
I'm not sure if I understand your comment. I would say that I've set validation to be lazy - there's `{ $lazy: true }` as third parameter of `useVuelidate` in my example. I believe that according to [documentation](https://vuelidate-next.netlify.app/api.html#validation-configuration) that should be correct.

Can you give a hint where do I have an error?

**Comment by dobromir-hristov** [comment]
I checked your example and I dont see anything wrong. Validators are run only after the state is dirty. You are using the name instead of the `v$.name.$model`, which never makes it dirty, so it never triggers the validators.

All validators are async now, so if you want to check for $error after $touch, you have to `await nextTick()` or better yet `await v$.$validate()`. This will trigger all async valifators, even when lazy, and will resolve only after they are done.

**Comment by khorsky** [comment]
I don't understand "You are using the name instead of the v$.name.$model, which never makes it dirty". When I log `v$.dirty` or `v$.name.dirty` right after the `v$.$touch()`, it's true.

Just to make sure (and for others looking for solution), after your advice, my test method should look like this:

```
const test = async () => {
  v$.value.$touch()

  await nextTick()

  if (!v$.value.$error) {
    console.log('success')
  }
}
```
It seems a bit strange that I've to use Vue's method to use validation library, but I'm still Vue beginner, so I cannot judge.

Your advice to use `await v$.$validate()` is complicated by the fact, that it's type definition is `readonly $validate?: () => Promise<boolean>`, so TypeScript compiler complains about undefined object: `Cannot invoke an object which is possibly 'undefined'`.

It's IMHO a pity that one can't use `v$.$validate` in this way:
```
v$.$validate()
  .then(() => {
    // run on successful validation
  })
  .catch((errors) => {
    // validation fails, let's see all the errors
  })
```
but I guess it has some drawbacks.

**Comment by khorsky** [comment]
Thanks for the tip with nextTick!

**Comment by dobromir-hristov** [comment]
It returns a promise, you can resolve it anyway you want.

The TS type may be off, because the types are added after the fact. I will check on them in a few.

As for your case, if you want to use your state, without touching, you can set $autoDirty to true,  this will run validations the moment you type in the field.

**Comment by dobromir-hristov** [comment]
Released a fix for the types. The `$validate` is no longer optional :)
