### ISSUE TITLE
Issue trying to use the regex validator

### ISSUE THREAD

**Issue by jimparslow** [vuelidate/vuelidate#812]
So I have an issue, using the latest versions of vuelidate core/validators

I am using Vue 3.

 ```
const commaSeparatedRegex = helpers.regex('keyword', /^[a-zA-Z0-9,]*$/);

        const state = reactive({
            keywords: ''
        });

        const rules = {
            keywords: { commaSeparatedRegex } 
        }

        const v$ = useVuelidate(rules, state);
```

This is returning an error stating that expr.test is not a function.

I dug into your code on git and simply copied out this function to make it local: but removed the check for !req(value)

 ```
const regex = (type, expr) =>
        helpers.withParams({ type }, (value) => expr.test(value))

        const commaSeparatedRegex = regex('keyword', /^[a-zA-Z0-9,]*$/);
```
And now it validates properly.

Am I using this wrong or is there a bug somewhere in the latest release?

**Comment by Giwayume** [comment]
@dobromir-hristov 
Just ran into this as well, is it an easy fix?

Here is the reproduction:
https://codesandbox.io/s/billowing-morning-8ody4?file=/package.json

**Comment by dobromir-hristov** [comment]
The regex helper now accepts a single parameter, the regular expression. This is a breaking change that we probably oversaw....

I will look into it.
Please try by just providing the regex to it.

**Comment by dobromir-hristov** [comment]
Yeah... The docs are wrong... I will do a fix tonight, so sorry for the confusion.

**Comment by Giwayume** [comment]
Ok, yeah works without extra param
