### ISSUE TITLE
$scope globalConfig mismatch with documentation

### ISSUE THREAD

**Issue by tochoromero** [vuelidate/vuelidate#813]
[The Documentation](https://vuelidate-next.netlify.app/advanced_usage.html#scope-property) indicates that for the `$scope` globalConfig we can use `true` for collect all, `false` for collect none or `string` for a specific scope.

However, the type definition for `$scope` is `$scope?: string | number | symbol`.

So I'm not sure what the behavior would be. Should I follow the documentation or should I follow the type definition?

**Comment by dobromir-hristov** [comment]
If scope can be a boolean to allow/deny sharing it's state.

Anything else will be used to direct compare with parent and child forms. If you choose string, then all that match will get collected by the parent.

**Comment by dobromir-hristov** [comment]
I am working on docs as we speak

**Comment by tochoromero** [comment]
Great, thank you!

>If scope can be a boolean to allow/deny sharing it's state.

Does this mean the Type definition will be updated to allow `boolean`?

**Comment by dobromir-hristov** [comment]
Yep, I will publish a fix tomorrow.

**Comment by tochoromero** [comment]
Awesome, thank you!

**Comment by dobromir-hristov** [comment]
Should be fixed now.
