### ISSUE TITLE
Vue 2 Composition API: Cannot read property '$options' of undefined

### ISSUE THREAD

**Issue by tochoromero** [vuelidate/vuelidate#814]
I believe [this change](https://github.com/vuelidate/vuelidate/commit/9cb5ec5c73a3d1d20d8c2e3c45b326b8bdd9912d#diff-b56b127d659c4beda82086b284218428d0e784ca336dfd07442cab11017681f4R98) broke Vuelidate for my Vue 2 with composition API project, just by updating I started getting this error:

`"TypeError: Cannot read property '$options' of undefined"`

I created a [Code Sandbox](https://codesandbox.io/s/vuelidate-next-vue-2-error-ytsj7?file=/src/components/Vuelidate.vue). The error I get there is different but I think they are related, something has gone wrong with Vue 2 support.

**Comment by dobromir-hristov** [comment]
Strange, tests are passing...

**Comment by dobromir-hristov** [comment]
Can you give me which versions of Vue and `@vue/composition-api` you are using?

**Comment by tochoromero** [comment]
Yeah, not sure what is going on, I downgraded to `2.0.0-alpha.11` and everything works again

**Comment by tochoromero** [comment]
I'm using `"@vue/composition-api": "^1.0.0-beta.21",`

**Comment by dobromir-hristov** [comment]
Thats probably it. We are using a newer version, `^1.0.0-rc.1`.

**Comment by tochoromero** [comment]
I'm going to upgrade to `rc.1` and give it a try. Thanks

**Comment by tochoromero** [comment]
You were right, upgrading to the latest Release Candidate of Vue Composition API fixed it, thank you!
