### ISSUE TITLE
 Cannot read property 'validations' of undefined

### ISSUE THREAD

**Issue by corsa-dn** [vuelidate/vuelidate#819]
**Describe the bug**
After mirgrate to clear vue-cli for my vue project throws such error

Cannot read property 'validations' of undefined

**To Reproduce**
1. Create new  vue-cli project
2. Install Vuelidate
3. Import it into main.js
4. Vue.use(Vuelidate)

**Expected behavior**
Expected that it works such as on prev project

![image](https://user-images.githubusercontent.com/11840832/110767313-ca72f400-825e-11eb-9e3b-dc38c54fce42.png)

    "vue": "^2.6.11",
    "vuelidate": "^0.7.4"

The problem is that everything works in codesandbox (https://codesandbox.io/s/condescending-hofstadter-d5ly8?file=/src/main.js)

**Comment by dobromir-hristov** [comment]
Hey bud, without a bit more info, we can't help much you know...

**Comment by corsa-dn** [comment]
added more info about error

**Comment by dobromir-hristov** [comment]
What Vue version are you using, which Vuelidate version, give us a minimal reproduction code... 

Such issues like this one are usually closed automatically, help us help you :)
