### ISSUE TITLE
Using vuelidate in a plugin

### ISSUE THREAD

**Issue by rcovell** [vuelidate/vuelidate#820]
We are building a library of reusable components/atoms/molecules (in storybook) that will be consumed via a plugin in several Apps. Once we register the plugin in an App and consume any component (that does validation) we get the following warning:

`[Vue warn]: Error in data(): "TypeError: Cannot read property 'uid' of null"`

In the stack the last item is: `useVuelidate`

Short Backstory: Validation used to be performed in the App and not in the plugin. We initially wanted to keep our plugin components somewhat dumb, have them react to the change in validation, not perform it. This functionality was moved into the plugin due to support of array validation being dropped (our ContactForm can have several PhoneNumbers that need validation). 

Incorrectly asked this on the thread (my mind was thinking $each/array, not specifically on the above warning):

[https://github.com/vuelidate/vuelidate/issues/781](url)

Response there, before moving it over to here, was about Vue being null. Have a suspicion that this might be due to the way we use webpack to build the App as we had to make changes to support `buefy`. Our App had one Vue instance and the plugin had its another, so anything registered in the App (i.e.. buefy) was not seen by the plugin (that used buefy). Might be a red herring, might not. Here is the change we did.

`
  chainWebpack: (config) => {
    if (process.env.NODE_ENV !== "production") {
      config.resolve.modules.prepend(path.resolve(__dirname, "./node_modules"));
    }
  },
`

Side question: Should our plugin even have vuelidate in it? As stated above the goal was to have a set of somewhat dumb reusable components. With vuelidate now in the plugin to validate arrays, they are smart. Are we going about this the wrong way?

Any suggestions would be greatly appreciated...

**Comment by dobromir-hristov** [comment]
I would need to see some example code, something we can debug with. We have a plan to make this possible, but there would be limitations.

**Comment by dobromir-hristov** [comment]
Hey, so you should be able to use Vuelidate outside of components now, worth giving it a shot?

**Comment by rcovell** [comment]
Thank you. Will give it a go and report back...

**Comment by rcovell** [comment]
The previous issue is no longer being seen. But we now see the following:

`[Vue warn]: [vue-composition-api] already installed. Vue.use(VueCompositionAPI) should be called only once.`

After searching around for this I came across an issue with `vue-demi` calling `_vue.use(VueCompositionAPI)`. Our app is also using the `VueCompositionAPI` which looks like the two aren't playing well together. Looked at the latest version of demi and how it uses the composition api is the same. Wouldn't think that we would have to do anything special when we pull it in, could be wrong. Any thoughts?

And also, to make sure, when we reverted our plugin changes to not have validation, the warning went away.

**Comment by rcovell** [comment]
After a bit of research the above warning seems to be an issue that other people are having (in other projects outside of vuelidate). I was able to solve it by putting this in `vue.config.js`:

`  config.configureWebpack = (config) => {
    config.externals = ["@vue/composition-api"];
  };`

Going to do a little more testing. Will report back with my final results.

**Comment by rcovell** [comment]
Everything seems to work as expected, no issues. Was able to validate firstName, lastName, N+ phones from plugin contact component. Thanks Dobromir...
