### ISSUE TITLE
Displaying external validation errors 

### ISSUE THREAD

**Issue by entermix** [vuelidate/vuelidate#824]
**Is your feature request related to a problem? Please describe.**
Vuelidate does a great job with client-side validation, but sometimes we need to implement server-side validation as well. I know it is possible to add custom validations, but what if the only method to find out about errors is to submit a form?

Here's a simple example:
https://codesandbox.io/s/eager-clarke-nmz2q

I would like to be able to nicely display the errors that occurred after the form was submitted. Is it possible? Unfortunately, I was unable to find a solution.

**Describe the solution you'd like**
It would be great to be able to inject temporary error messages that go away as soon as the user interacts with the form.

**Describe alternatives you've considered**
Now we have to use various crutch solutions, for example:
https://blog.philiphendry.me.uk/2020/01/09/integrating-server-side-errors-with-vuelidate
https://stackoverflow.com/questions/55497881/vuelidate-server-side-validation

**Additional context**
https://github.com/vuelidate/vuelidate/issues/277

**Comment by dobromir-hristov** [comment]
I played a but with this concept, but I hit a few blockers. First and foremost, the validation errors were not getting shown in time. They were shown after changing the input...

```js
 data () {
    return {
      password: 'testpassword',
      errors: {}
    }
  },
  methods: {
    async handlelogIn () {
      this.errors = {}
      if (!(await this.v$.$validate())) return
      this.errors = {
        password: 'User is not found'
      }
    }
  },
  validations () {
    const that = this
    return {
      password: {
        serverValidation: {
          $message () {
            // `this` is not yet available in latest release
            return that.errors.password
          },
          $validator () {
            // `this` is not yet available in latest release
            return !that.errors.password
          }
        }
      }
    }
  }
```

For now its best to just create async validators, that are run on input change instead. I am not exactly sure how we could integrate server-side errors, that are not connected to the vuelidate validators..

Anything we think of, would require errors to be saved in specific format and place, causing complications for Composition API users as well. @shentao any thoughts?

**Comment by shentao** [comment]
Interesting issue. I think a way to handle that would be to add an async validator to the top level of the form object. 
```js
const form = reactive({
  email: '',
  password: ''
})
```
Then the rules:
```js
const rules = {
  form: {
    serverValidation,
    email: { email, required },
    password: { required }
  }
}
```

The issue would be that `serverValidation` is run automatically when both `$lazy` and `$autoDirty` is present. So maybe potentially such a validator could have `$manual: true` property? Which would only trigger when using `$validate()` or `$submit`?

Of course, if a `form` object doesn’t exist, we could always make a `computed` that simply gets the content that has to be submitted to the API. Maybe it could be a POST request that is used to send something to the API. Maybe just a method that actually performs the API call that we want to execute anyway with the addition of a `.catch(err => ({ $message: 'User doesn’t exist', $valid: false })` or similar.

Wdyt?

**Comment by dobromir-hristov** [comment]
It might with, but there won't be a way to provide which exact property needs attention, it will be for the entire form.

**Comment by entermix** [comment]
@dobromir-hristov 
> I played a but with this concept, but I hit a few blockers. First and foremost, the validation errors were not getting shown in time. They were shown after changing the input...

Perhaps we need to use `$reset()` and `$touch()`? 

It seems to have worked: 
https://codesandbox.io/s/blissful-hellman-u4bvz

**Comment by zach-mcnulty** [comment]
Really appreciate this feature, but I'm running into an issue with an input whose only possible error might exist in $externalValidators -- i.e. it has no client-side validators to write into my rules object., like required.

I've found that while the property does not exist in the rules object, it makes no difference that the key appears in $externalResults. That's fair, as I can't expect Vuelidate to track errors on something that it doesn't know about. But how can I write a rule for an input like this so Vuelidate knows that said input's only errors could only exist in $externalValidators?

Referring to line 347 on docs page for this feature: `const rules = { foo: { someValidation } }`

What should `someValidation` be if the only validation is that the field doesn't appear in $externalResults?

**Comment by dobromir-hristov** [comment]
Just return a true from the validator and do your thing on the backend. Or create an async validator and call the backend, your choice.

**Comment by zach-mcnulty** [comment]
Thanks for the reply. I had noticed that simply returned true from a validator seemed to work, but I wondered if there was a more appropriate way to go about it.
