### ISSUE TITLE
Export ValidationArgs for Props Type Checking, Document Passing Rules to Child Component Pattern

### ISSUE THREAD

**Issue by shasderias** [vuelidate/vuelidate#826]
**Is your feature request related to a problem? Please describe.**
I'm following the approach outlined in #712 to pass rules down to a child component. I'm using Typescript and am trying to properly type the prop. It seems to me that rules should be typed as `ValidationArgs `but the definition for it is not exported.

**Describe the solution you'd like**
If I'm right, could ValidationArgs be exported? Otherwise, could someone point me in the right direction?

Incidentally the approach in #712 appears to be quite handy for consistently styling/presenting errors. Should it be documented? I'm happy to attempt a PR if so.

**Comment by dobromir-hristov** [comment]
I am not really sure how to do this properly, so if you could make a PR and see how you can approach it.

**Comment by ConnorJBishop** [comment]
I could also do with `ValidationArgs` being exported in order to create a properly typed function which wraps `useVuelidate`.

@shasderias did you begin the process of making a PR?

**Comment by shasderias** [comment]
@ConnorJBishop nope, have plans/would like to but there's quite a bit of work standing in the way before I can attempt one D:

**Comment by dobromir-hristov** [comment]
I have exported `ValidationArgs`, sorry for the stupidly long wait...
