### ISSUE TITLE
Docs - note gotcha due to how vue-demi works

### ISSUE THREAD

**Issue by rebolyte** [vuelidate/vuelidate#827]
I was confused when using latest @vuelidate/core `2.0.0-alpha.14` that this was causing an `Object(...) is not a function` error:

```ts
const state = reactive({
	username: '',
	password: ''
});

const rules = {
	username: {
		required
	},
	password: {
		required
	}
};

const $v = useVuelidate(rules, state);
```

I saw #798, so I dug into vue-demi's `isProxy`, and it looked fine. But in my node_modules, vue-demi had no `isReactive` export. Then I noticed that vue-demi assembles the exports [at install time](https://github.com/vueuse/vue-demi/blob/v0.6.0/scripts/utils.js#L39), not runtime.

Turns out vue-demi's postInstall hook will only run when it's added (as you'd expect), and I had run it while having @vue/composition-api 0.5.0 installed. `isReactive` was not added [until 0.6.0](https://github.com/vuejs/composition-api/blob/master/CHANGELOG.md#060). My issue only went away when I did `yarn remove @vuelidate/core && yarn add @vuelidate/core`.

Can Vuelidate add a note to the docs on how vue-demi works, and point people to the fact that they can re-add the module or try `yarn vue-demi-fix`?

**Comment by dobromir-hristov** [comment]
This is not really a Vuelidate issue, more of a vue-demi thing, that I hope they fix. Feel free to add a PR to the docs, where you see fit and we can reiterate :)
