### ISSUE TITLE
Example with Vuelidate Next (2.x) using Vuex

### ISSUE THREAD

**Issue by JellyM** [vuelidate/vuelidate#830]
I can't seem to find an example that is using Vuex.
Is there anyway to get it working properly using composition API?

**Comment by dobromir-hristov** [comment]
Good question. We added support for using Vuelidate outside of Vue components, so you should be able to just pass a reactive state to `useVuelidate` and save the output to your store.

```
const formState = reactive({})
const rules = {}
const state = {
 someProperty: '',
 validations: useVuelidate(rules, formState)
}
```
