### ISSUE TITLE
RequiredIf with Email not working.

### ISSUE THREAD

**Issue by ricky11** [vuelidate/vuelidate#831]
I am trying to validate a email with requiredIf, this is what i have

senderEmail: {
      requiredIf: requiredIf(function()  {
           return this.sendAs === 'email'
    }),
    email 
      },

Expected :
senderEmail will only be required if this.sendAs === 'email' otherwise it is not required

Outcome  :  email is always required and the input is invalid.

I want to conditionaly render email, i have tried email : function() return this.sendAs === 'email'  which also does not work.

Thanks.

**Comment by dobromir-hristov** [comment]
Hey there. What you are showing should in fact work.

Could you create a codesandbox showcasing the exact issue?

**Comment by ricky11** [comment]
The requiredIF does work if the condition is met within the function, but when i add email as a parameter, if the email filed is not blank, it will require it to be a formatted as a email.  

i will try to reproduce this issue.

**Comment by dobromir-hristov** [comment]
Hey there, sorry for the long wait. Just pushed a PR, we should fix it very soon :)

**Comment by ricky11** [comment]
is this fixed in version 0.7.6?
