### ISSUE TITLE
[Question] How do I use helpers.ref in Typescript?

### ISSUE THREAD

**Issue by MrSuttonmann** [vuelidate/vuelidate#834]
I am trying to write a custom validator in Typescript to check if a field containing a date is after another field's date value.

Here's the code I have written so far:

```typescript
export const isDateAfter: (field: string | ((vm: any, parentVm?: Vue) => any)) => ValidationRule = (field) => {
  return helpers.withParams(
    { type: "isDateAfter", message: "{{fieldName}} must be after {{min}}", min: field },
    (value: Date, vm: any) => {
      const fieldValue = helpers.ref(field, vm, ???);
      return isAfter(fieldValue, value);
    }
  );
};
```

I am not sure what to pass as the third argument to `ref`, and the documentation has zero examples on how to use it.

Any help would be greatly appreciated.

See also: [StackOverflow post](https://stackoverflow.com/questions/66885870/how-to-use-vuelidate-ref-in-custom-validator-using-typescript).

**Comment by dobromir-hristov** [comment]
I am not a TS user, so I can't tell you, maybe someone else can...

**Comment by dobromir-hristov** [comment]
Oh this is Vuelidate 0.x ., Should have started with that probably. Even more so I am not sure :(

**Comment by MrSuttonmann** [comment]
I solved this by creating my own `ref` function outside of Vuelidate:

```ts

const ref: (reference: string | ((vm: any) => any), vm: any) => any = (reference, vm) => {
  return typeof reference === "function" ? reference(vm) : vm[reference];
};
```

This is used inside a custom validation rule as such:

```ts
(value: Date, vm: any) => {
  const fieldValue = ref(field, vm);
  return isAfter(value, fieldValue);
}

```

and used in the form validators object as such:

```ts
isDateAfter: isDateAfter((vm) => vm.startDate)
```
