### ISSUE TITLE
Custom validation with provide/inject reactive objects stopped working. Regression after moving from alpha.8 to alpha.14

### ISSUE THREAD

**Issue by ajdvoynos** [vuelidate/vuelidate#835]
**Describe the bug**
Child component with custom validation that uses injected reactive objects don't work after upgrading to alpha.14.

This used to work in alpha.8. I upgraded today to alpha.14, but I'm now facing this new issue. I can't seem to find a workaround for this one, so I had to roll back to alpha.8.

**Reproduction URL**

https://codesandbox.io/s/tender-gould-zhuwi

**To Reproduce**
1. Go to 'https://codesandbox.io/s/tender-gould-zhuwi'
2. Click on $touch button
3. Change first dropdown from Female to Male

**Expected behavior**
Both rows should be marked as invalid in the screenshot below.

The custom validation function inside the [dropdown component](https://codesandbox.io/s/tender-gould-zhuwi?file=/src/components/SexDropdown.vue) should not allow repeated values.

**Screenshots**
![image](https://user-images.githubusercontent.com/5531373/113225289-8d15eb00-928d-11eb-80b5-5052e28a49d2.png)

**Additional context**
My use case is that deeply nested components need to access variables up the chain for validation purposes, so I use provide/inject to pass the data to the nested components.

**Comment by ajdvoynos** [comment]
So thought I'd share the workaround I'm doing to solve this for now:

I'm adding a watcher to the injected reactive object with `deep: true` and doing a `v.$reset(); v.$touch()` to force the validation to run again.

**Comment by dobromir-hristov** [comment]
I saw your issue but have not had time to investigate.

I will over the weekend.

**Comment by kozmanbalint** [comment]
+1
The case is similar if the custom validator's reactive parameter is a computed value (when using with options api).

**Comment by dobromir-hristov** [comment]
I think I see whats going on. This is not for child validations only.

I implemented a change a few versions back, which transforms all validators to async by default, using `watch` instead of `computed`. This was done because it was not easy to track the difference, between `async` and `sync` validators.

This however has the downside of triggering validators ONLY when on specific watched properties, the `$dirty` and `model`. This means it does not trigger validators, when they depend on the changes of external properties, like what you are doing with the injected properties and iterating over them.

Honestly I was expecting this to happen, but it was a slim chance. I do however see how this might be a big problem, and I will need some time to figure something out. @shentao do you have any ideas?

**Comment by dobromir-hristov** [comment]
I looked into this and I tried a few things:

1. Allowing passing directly a `computed` as a validator. - though it is pretty easy to do so, the function inside `computed` has to return `false` if valid and `true` if invalid, so we can populate the `$invalid` property directly. This will cause more confusion. Wrapping it in another computed, sounds stupid to me, though its possible - `computed(() => !validator.value)
2. Revert the use of `$isAsync` property - This used to tell Vuelidate what the return type of the validator is. 90% of validators are usually sync, so removing it might have been a bad decision on my end.
3. Use `watchEffect` to detect changes in all function dependencies - Even though this is similar to initiating `computed` internally, our tests detect it triggers extra validator calls. I suspect it is detecting `$pending` and `$pendingCounter` changes.
4. We could use the `computed` that the user provides in step 1, to instantiate an internal `watcher` and watch for changes on that. This would give us the most freedom, and would keep the API the same. -  Something like this - https://github.com/vuelidate/vuelidate/pull/846

**Comment by ajdvoynos** [comment]
I'm not really familiar with the insides of vuelidate, but instead of using an $isAsync property, can't you check if the return value of the validator function is a Promise to decide if it's async or not? Sorry if I'm just stating the obvious.

**Comment by dobromir-hristov** [comment]
We can, but we need to create a computed or a watcher before we do that, so they call your validator based on what changes. If the value of the property changes then we can just create a watcher, but that won't trigger for your case.

**Comment by dobromir-hristov** [comment]
We already reverted back to using sync validators by default. This is the default behavior for 90% of cases, so your case should also be fixed. Please let me know.
