### ISSUE TITLE
SameAsPassword always return true

### ISSUE THREAD

**Issue by Logeswaranbca** [vuelidate/vuelidate#841]
`{ "$dirty": true, "$path": "request.confirmPassword", "required": { "$message": "Value is required", "$params": {}, "$pending": false, "$invalid": false, "$response": true }, "sameAsPassword": { "$message": "The value must be equal to the other value", "$params": { "otherName": "other" }, "$pending": false, "$invalid": true, "$response": false }, "$invalid": true, "$pending": false, "$error": true, "$silentErrors": [ { "$propertyPath": "request.confirmPassword", "$property": "confirmPassword", "$validator": "sameAsPassword", "$message": "The value must be equal to the other value", "$params": { "otherName": "other" }, "$response": false, "$pending": false } ], "$errors": [ { "$propertyPath": "request.confirmPassword", "$property": "confirmPassword", "$validator": "sameAsPassword", "$message": "The value must be equal to the other value", "$params": { "otherName": "other" }, "$response": false, "$pending": false } ], "$model": "Test", "$anyDirty": true }`

**Comment by dobromir-hristov** [comment]
This is not a proper bug report.. please follow the guide
