### ISSUE TITLE
Add `id` to error entries for iteration

### ISSUE THREAD

**Issue by kibertoad** [vuelidate/vuelidate#843]
It is considered the best practice in Vue.js to define key for `v-for` iterations for performance and determinism reasons.
And it is not uncommon to use `vuelidate` results this way:

```
  <div class="input-errors" v-for="error of state.v$.classifierId.$errors" v-bind:key="error ">
    <div class="error-msg">{{ error.$message }}</div>
  </div>
```

However, currently there is no unique id exposed on error array that could be used for `v-bind: key`, and generic `error` has to be used, which is against the Vue.js recommendation.

**To Reproduce**
Perform any validation that results in errors.

**Expected behavior**
There is a unique `id` field per entry in `$errors` array.

**Comment by kibertoad** [comment]
I can try working on a PR for this, if it is a desired behaviour.

**Comment by dobromir-hristov** [comment]
You can use the path or validator name?

**Comment by kibertoad** [comment]
@dobromir-hristov Neither of them will work in all cases. `validator` can be non-unique when more than one field is failing it. `path` can be non-unique when it fails more than one validation.

**Comment by dobromir-hristov** [comment]
Right, then we can make a property that combines them both. It will be unique then.

**Comment by kibertoad** [comment]
Yup, that would definitely work!

**Comment by dobromir-hristov** [comment]
PR is up, @shentao will review when he gets some time and we can release it :)
