### ISSUE TITLE
[Composition API] Cannot track $errors flag inside setup() function after first $touch()

### ISSUE THREAD

**Issue by giero** [vuelidate/vuelidate#847]
Hello.
I'm trying to reproduce [lazy form validation](https://vuelidate-next.netlify.app/guide.html#validating-forms-before-submitting), but using Composition API. As far as I know `useVuelidate` returns Ref object, so I tried to use `$touch()` and check `$error` flag via `v$.value` inside `setup()` function ... and this worked some versions ago. After upgrade Vuelidate this method doesn't work anymore as it should.

**Used Dependencies**
```
"@vuelidate/core": "2.0.0-alpha.16",
"@vuelidate/validators": "2.0.0-alpha.13",
"vue": "3.0.11"
```

**Reproduction URL**
https://codesandbox.io/s/frosty-lichterman-ztt3y?file=/src/App.vue

**To Reproduce**
1. Click `Touch` button.
2. Observe that `v$.$error` in template equals true (as it should be), but `v$.value.$error` in `touch` function equals false.
3. Click `Touch` button second time.
4. `v$.value.$error` in `touch` function now equals true (as it should be the first time).

**Expected behavior**
After first `v$.value.$touch()` `v$.value.$error` flag should be equal true.

**Comment by giero** [comment]
I read some other issues/comments and saw this in https://github.com/vuelidate/vuelidate/issues/835#issuecomment-821794255
> I implemented a change a few versions back, which transforms all validators to async by default

An idea struck me: async? lets do this `async` then ;)
```javascript
const submit = async () => {
    await v$.value.$touch();

    // at this point v$.value.$error === true
```
and it works .... so is this still a bug or async / await is a general solution for this?

**Comment by dobromir-hristov** [comment]
Instead of touch you can `await v.$validate()`

**Comment by giero** [comment]
Right .... it's even mentioned in [link](https://vuelidate-next.netlify.app/guide#validating-forms-before-submitting) I provided ...
And this should be better solution in general (with async validators). I will use this - thanks :)
