### ISSUE TITLE
Export TypeScript types related to useVuelidate

### ISSUE THREAD

**Issue by khorsky** [vuelidate/vuelidate#849]
**Is your feature request related to a problem? Please describe.**
I would like to use predefined global configuration in whole project ($lazy = true by default). My own factory function, that would set up global config when needed, seems as a viable solution.

It seems better than specifying `useVuelidate(..., ..., { $lazy: true })` everywhere.

**Additional context**
While I use TypeScript, I miss the opportunity to use argument type and return type definitions to simplify usage (autocompletion etc).

**Comment by khorsky** [comment]
Currently I've repeated definitions for `ValidationArgs`, `ValidationRuleCollection`, `ExtractStateLeaf`, `ChildStateLeafs`, `ExtractState`, `GlobalConfig` in my code and everything seems working fine.

It may be sufficient to export these types and interfaces to fullfill my request.

**Comment by victorgarciaesgi** [comment]
@khorsky I'm in the same problem as you, it would help me a lot to have access to `NestedValidations`

**Comment by dobromir-hristov** [comment]
Hey, sorry for the long wait. I think we can do that, by exposing a `setGlobalVuelidateConfig` method or something similar. We dont really have a default export, that we can attach a `config` to, like `Vue.config` used to have.

```js
// main.js
import { setGlobalVuelidateConfig } from '@vuelidate/core'

setGlobalVuelidateConfig({ $lazy: true })
```

**Comment by dobromir-hristov** [comment]
As for the types, feel free to make a PR and export whatever you feel is needed.
