### ISSUE TITLE
Issue sameAs API with Vue 3 Composition API

### ISSUE THREAD

**Issue by Enoooch** [vuelidate/vuelidate#851]
**Describe the bug**
Using sameAs api with Vue 3 Composition API, validation only triggers when original input changed.

**Reproduction URL**
Here is the code.
[Vuelidate 2 - Composition API + Vue 3](https://codesandbox.io/embed/vigorous-cache-oi8qk?fontsize=14&hidenavigation=1&theme=dark)

**To Reproduce**
1. Click first input, then enter '123456789'
2. Click second input, then enter '123456789'
3. Click first input, then enter '12345678'

**Expected behavior**
When the first input changes, validator will be triggered.

**Screenshots**
See Reproduction URL.

**Additional context**
None.

**Comment by dobromir-hristov** [comment]
Yea that is a known bug that we introduced a while back, accidently. Validators are only watching the property value, but not other dependencies. 

We may need to revert back to using computed for validations, instead of watch. This is a breaking change for async validators thought :(

**Comment by dobromir-hristov** [comment]
ping @shentao

**Comment by shentao** [comment]
Answered in #846.

**Comment by Croosle** [comment]
I found a solution, but yes, it doesn't look good:
```
const rules = computed(() => ({
      password: { 
        required, 
        minLength: minLength(8), 
        repeatPassword: () => {
            if (form.repeatPassword) {
              v$.value.repeatPassword.$reset()
              v$.value.repeatPassword.$touch()
            }

            return true;
        } 
      },
      repeatPassword: { required, sameAs: sameAs(password) },
}));
```

**Comment by dobromir-hristov** [comment]
This should be fixed with latest update.
