### ISSUE TITLE
$touch not updating validation state immediately after model is updated programmatically.

### ISSUE THREAD

**Issue by Giwayume** [vuelidate/vuelidate#853]
### Make sure that you are familiar with documentation before submitting an issue.

  https://vuelidate-next.netlify.com/

**Describe the bug**
In the previous version of Vuelidate, if I update data programmatically then use the $touch() function, the $touch will update the $invalid variable correctly. However, in the new version $touch only works if I wait for nextTick first after making any data changes.

**Reproduction URL**
https://codesandbox.io/s/loving-proskuriakova-xm26s?file=/src/App.vue

**To Reproduce**
Create a app with a basic form with one input.
1. The initial input value should be invalid according to the vuelidate rules.
2. On submit of form, set the input value to something that should be valid.
3. Call `this.v$.$touch()`

**Expected behavior**
`this.v$.$invalid` should be false.

**Relevant Code**
In this example, `this.number` was previously an invalid value. It is set to a valid value then the form is touched.
```
this.number = 6;
this.v$.$touch();
console.log(this.v$.$invalid); // Outputs true
```

If I use nextTick between updating the value and touching, I get expected behavior. However, I should not have to do this.
```
this.number = 6;
await nextTick();
this.v$.$touch();
console.log(this.v$.$invalid); // Outputs false
```

**Comment by dobromir-hristov** [comment]
Please try the new `await this.v.$validate()` method. It is meant to do exactly that.

**Comment by Giwayume** [comment]
In that case at the very least I expect to be able to do something like

```
await this.v$.$touch();
```

The vuelidate library should take care of itself.

**Comment by dobromir-hristov** [comment]
Touch just sets $dirty to true, validators are run after that. We can return nextTick, but that does not guarantee your async validators have completed.

**Comment by Giwayume** [comment]
I see, $touch in this example is a red herring that could be left out. It's automatically validating sync validators after nextTick.

**Comment by thehovdev** [comment]
I get the issue in my case too and solve it, you just need to assign reactive data instead of pure data.
If you assign data like that :
this.order.number = 6
Change it to this: 
this.$set(this.order, 'number', 6)
And anything will work correctly.

More detailed info about reactivity 
https://v2.vuejs.org/v2/guide/reactivity.html
