### ISSUE TITLE
Typescript error with async validator, doesn't expect a promise return?

### ISSUE THREAD

**Issue by Giwayume** [vuelidate/vuelidate#854]
### Make sure that you are familiar with documentation before submitting an issue.

  https://vuelidate-next.netlify.com/

**Describe the bug**

I have a simple withParams validation where the validation function returns a Promise that resolves with a boolean.
```
validations: {
    test: validators.helpers.withParams({ type: 'test' }, function() {
        return new Promise<boolean>((resolve) => {
	    resolve(true);
        });
    })
}
```

This used to work in old vuelidate, but it seems the types indicate it is not supported?

![image](https://user-images.githubusercontent.com/4075314/118019763-5967bf80-b327-11eb-9c8a-82ee6af2d2ed.png)

I can't find in the next documentation how async custom validators are meant to work.

The conflicting type is here:

https://github.com/vuelidate/vuelidate/blob/next/packages/vuelidate/index.d.ts#L43

```
export interface ValidatorResponse {
  $valid: boolean
  [key: string]: any
}

export type ValidatorFn <T = unknown> = (value: T) => boolean | ValidatorResponse;
```

**Comment by dobromir-hristov** [comment]
Sorry about that, types are a weak part of Vuelidate heh.. would you like to try and do a PR to fix it?

**Comment by Giwayume** [comment]
Thanks

**Comment by dobromir-hristov** [comment]
Should be published already
