### ISSUE TITLE
Validators requiredIf and requiredUnless don't react to prop change

### ISSUE THREAD

**Issue by littlejon85** [vuelidate/vuelidate#858]
**Describe the bug**
The **requiredIf** and **requiredUnless** validators take argument. The requiredIf validator should only validate when the argument is true and the requiredUnless validator should only validate when the argument is false. However the validators only respect the initial value and don't respond to argument change.

**Reproduction URL**
https://codesandbox.io/s/vuelidate-requiredif-issue-qmnqs?file=/src/App.vue

**To Reproduce**
Steps for requiredIf(prop):
1. prop = true;
2. validator requires value
3. change prop to false;
4. validator still requires value = error.

**Expected behavior**
Expect requireIf(prop) not to require the value when prop changes from true to false.

**Comment by dobromir-hristov** [comment]
This should be fixed now, with the change back to `sync` validators by default.

**Comment by rjd22** [comment]
@dobromir-hristov I've tested the latest version in de codesandbox and I'm not sure if it's working properly. I can't seem to make it work. Now requiredIf and requiredUnless don't seem to validate at all.

**Comment by dobromir-hristov** [comment]
Give me a link

**Comment by rjd22** [comment]
@dobromir-hristov I've updated the dependencies in the original codesandbox to the latest version on the left.

**Comment by rjd22** [comment]
I've done some testing in the codesandbox with different versions. And the problem with the `requiredIf` validator not responding seems to be introduced after updating to `vuelidate/core 2.0.0-alpha.18` and higher.

**Comment by rjd22** [comment]
After reading the commit log it seems like the documentation might be incorrect for the requiredIf and other async validators. When  I changed the demo to:

```js
validations() {
    const { withAsync } = helpers;

    return {
      text: {
        required: withAsync(requiredIf(() => this.isRequired)),
      },
    };
  },
```

The validation seems to work properly. The question would be. Is this the correct way to use `requiredIf`?

Link to demo:
https://codesandbox.io/s/vuelidate-requiredif-issue-forked-r2zbf

**Comment by dobromir-hristov** [comment]
That is a new way to use it, deff, should work, but we should fix the other way too.

**Comment by dobromir-hristov** [comment]
As I said, we have issues with the Optional API. Composition API seems to work fine

**Comment by rjd22** [comment]
@dobromir-hristov That is really good to know. I use the Composition API mostly so I'm glad it will work correctly there.

**Comment by dobromir-hristov** [comment]
https://github.com/vuelidate/vuelidate/releases/tag/%40vuelidate%2Fvalidators%402.0.0-alpha.17 should fix it all. Let me know if you find any other issues.

**Comment by littlejon85** [comment]
Looks good to me. Thank you.

**Comment by rjd22** [comment]
@dobromir-hristov works awesomely! Do I understand correctly that we don't need to use async for these anymore?

**Comment by dobromir-hristov** [comment]
Yes. It should work, but not needed.
