### ISSUE TITLE
Add $validate for a single field

### ISSUE THREAD

**Issue by Croosle** [vuelidate/vuelidate#861]
**Is your feature request related to a problem? Please describe.**
On my site, when you enter a phone, vuelidate send the request with checking to exist it, then the user clicks the "send validation code" button. And here I have a problem: if I use `$touch`, the user will have to press the button twice, because the request has not yet returned, If I use `$validate`, all fields are validated, although the user has not yet fill them in. I would like to be able to use $validate only for the phone.

**Additional context**
https://codesandbox.io/s/new-lake-or1yx?file=/src/App.vue

**Comment by dobromir-hristov** [comment]
You basically need a way to await the `$pending` status of the `phone` field, right? 
What do you want to do, after you await that? What would happen if the user updates the input after that? 

Once you call `touch` or `validate`, calling them again doesnt really do much. `validate` will just return a promise that will resolve, once any `pending` properties are done.

**Comment by Croosle** [comment]
> What do you want to do, after you await that? What would happen if the user updates the input after that?

I will send the verification code to him and if he update the input, I'll validate field again and send another verification code.

> validate will just return a promise that will resolve, once any pending properties are done.

Yes, It's exactly what I need but only for phone field. I don't want to validate the whole form.

**Comment by dobromir-hristov** [comment]
@shentao any suggestions? We could add it to every property, it's not a big deal, but I fear people will use it wrong.

The problem I see, is that the field will auto validate on every keystroke, so calling $validate,  might not do much. How do you know when to call it? 

To me, this sounds like a custom server validation step, than a Vuelidate validator. Could be wrong.

**Comment by nskazki** [comment]
I would really like every node within the validation state to have the `$validate` method, so I could force validation for two separate forms shown within the same component independently. At this moment, I do this to achieve the desired result:

```js
 function validateNode(node) {
  // based on https://github.com/vuelidate/vuelidate/blob/685b2abdaf0caf1a0398ef6325d0423ae053a802/packages/vuelidate/src/core.js#L673
  return new Promise((resolve) => {
    node.$touch()

    return nextTick().then(() => {
      if (!node.$pending) {
        resolve(!node.$error)
      } else {
        const stop = watch(() => node.$pending, () => {
          stop()
          resolve(!node.$error)
        })
      }
    })
  }) 
}
```

**Comment by dobromir-hristov** [comment]
PR is up, give it a try if you want.
