### ISSUE TITLE
Cannot find module '@vuelidate/core' or its corresponding type declarations. 

### ISSUE THREAD

**Issue by RollingTL** [vuelidate/vuelidate#862]
ERROR TS2307: Cannot find module '@vuelidate/core' or its corresponding type declarations.

TypeScript report this error in IDE but in the runtime all is working as expected. 

```
import { reactive, computed } from 'vue'
import { useVuelidate } from '@vuelidate/core'  - !!! Here is place of TypeScript error
import { customRule } from '@/components/forms/validations/rules'
import { required } from '@vuelidate/validators'
```

I have found npm module /@types/vuelidate at https://www.npmjs.com/package/@types/vuelidate
The question is can I use the module? If yes why it is not mentioned in documentation or included in core?

If I do npm install --save @types/vuelidate
How to use it?
import { ???? } from '@types/vuelidate'

Vuelidate 2 - Composition API + Vue 3

My package.json
```
  "dependencies": {
    "@vuelidate/core": "^2.0.0-alpha.16",
    "@vuelidate/validators": "^2.0.0-alpha.13",
    "axios": "^0.21.1",
    "core-js": "^3.6.5",
    "ol": "^6.5.0",
    "vue": "^3.0.0",
    "vue-i18n": "^9.1.6",
    "vue-router": "^4.0.8",
    "xstate": "^4.19.1"
  },
  "devDependencies": {
    "@typescript-eslint/eslint-plugin": "^4.18.0",
    "@typescript-eslint/parser": "^4.18.0",
    "@vue/cli-plugin-babel": "~4.5.0",
    "@vue/cli-plugin-eslint": "~4.5.0",
    "@vue/cli-plugin-typescript": "~4.5.0",
    "@vue/cli-service": "~4.5.0",
    "@vue/compiler-sfc": "^3.0.0",
    "@vue/eslint-config-prettier": "^6.0.0",
    "@vue/eslint-config-typescript": "^7.0.0",
    "babel-eslint": "^10.1.0",
    "eslint": "^6.7.2",
    "eslint-plugin-prettier": "^3.3.1",
    "eslint-plugin-vue": "^7.0.0",
    "prettier": "^2.2.1",
    "sass": "^1.26.5",
    "sass-loader": "^8.0.2",
    "typescript": "~4.1.5"
  }
```

**Comment by dobromir-hristov** [comment]
`import useVuelidate from "@vuelidate/core"`

**Comment by RollingTL** [comment]
I have this line, it works. Below is all import I use, but the line with useVuelidate generates error.

import { reactive, computed } from 'vue'
import { useVuelidate } from '@vuelidate/core'  - !!! Here is place of TypeScript error
import { customRule } from '@/components/forms/validations/rules'
import { required } from '@vuelidate/validators'

Did you read the message? Or just kidding?

**Comment by dobromir-hristov** [comment]
Vuelidate 2 has it's own types, no need to install them separately.

And yes I read what you said, and import the default export, not a named export, like I showed.

**Comment by RollingTL** [comment]
Thanks, now it is clear. Sorry, I missed the difference.


And one more question - the documentation (https://github.com/vuelidate/vuelidate/tree/next) clearly states that: 
---------
Usage with Options API
To use Vuelidate with the Options API, you just need to return an empty Vuelidate instance from setup.
Your validation state lives in the data and the rules are in validations function.

import { email, required } from '@vuelidate/validators'
import { useVuelidate } from '@vuelidate/core'
---------
Maybe it needs to be fixed.

**Comment by dobromir-hristov** [comment]
Yeah, we changed that sometime back, when we dropped the old mixin.

**Comment by dobromir-hristov** [comment]
By the looks of things `import { useVuelidate } from '@vuelidate/core'` should work, as we are exporting the types as named exports as well.
