### ISSUE TITLE
$error not working

### ISSUE THREAD

**Issue by logustra** [vuelidate/vuelidate#863]
**Describe the bug**
Hello, I found the `$error` not working.

**Reproduction URL**
[https://codesandbox.io/s/vivu-in9p2](https://codesandbox.io/s/vivu-in9p2?file=/src/modules/Home/views/home.vue)

```
// the value always false
<div>
  {{ v$.name.$error }}
</div>
```

**Expected behavior**
update value `$error` to `true` when the validation is error

**Comment by dobromir-hristov** [comment]
Did you use $model or $touch first?

**Comment by logustra** [comment]
@dobromir-hristov
thanks, my bad haha
oh ya, I remember in the previous version default value `$invalid` was `true`, 
why in the newest version to be `false`?
