### ISSUE TITLE
How can I add fields for validation after initialization vuelidate?

### ISSUE THREAD

**Issue by j-tap** [vuelidate/vuelidate#865]
Some fields come to me from the server and I would like to add them to `validations` in order to work with them normally, is it possible to do this after initialization?
For example, there would be a method of some kind or it would be possible to reinitialize the Vuelidate library after updating the variable `validations`.

**Comment by j-tap** [comment]
> If you just change your rules, the library will auto update.
> 
> Make the rules a function and return extra validations based on some conditional.

I started doing this, but then I ran into a problem: `validations()` cannot return promises and cannot be asynchronous

**Comment by dobromir-hristov** [comment]
Eh.. just use some plain boolean somewhere and change it from an external method.

**Comment by j-tap** [comment]
Thanks, the first time I did it differently, this is how it works, is it the right solution?

```
validations() {
    const protectRules = {
      1: {
        required,
        minValue: minValue(0.1),
      },
    }
    const rules = {
      name: {
        required,
      },
      url: {
        required,
        url,
      },
    }
    Object.keys(this.meta.protections)
    .forEach((key) => {
      const field = this.meta.protections[key]
      const rules = protectRules[field.id]
      if (rules) rules[key] = rules
    })
    return rules
  },

**Comment by dobromir-hristov** [comment]
You can do something like that I guess. You can be as creative as you want in the function, as long as it's not async.

**Comment by j-tap** [comment]
Thank you for the answers, although everything was obvious - I could not do it until I asked a question. Good luck
