### ISSUE TITLE
Reactive rules injection to useVuelidate for dynamic i18n switching

### ISSUE THREAD

**Issue by ViXP** [vuelidate/vuelidate#867]
Hello! I'm trying to solve one problem that I didn't find in issues, sorry If I missed the proper implementation suggestion already. 

I am using composable function to setup and use v$ object in component for validations. Here is what I'm doing:

1. Injecting my custom readonly reactive **i18n** object with all of my localizations into composable function. 
2. Creating computed **rules** object that is passing my custom **i18n** object into factory function, that generates rules with proper localizations. And this computed property successfully recalculates itself when i18n is switching locale, so no problems on this stage.
3. Creating reactive **data** object with my initial data
4. Creating **v$** instance with **useVuelidate()** by passing computed **rules** and reactive **data** as an arguments.
5. Returning the **v$** object.

Here is the code example:
```
// Validation rules function
function someRulesFunction(i18n) {
  return {
    sampleProperty: {
      required: helpers.withMessage(i18n.t("errors.required"), required)
    }
  };
}

// Composable function
function useFormValidations(initialData, rulesFunction) {
  const i18n = inject("i18n");

  const rules = computed(() => rulesFunction(i18n));
  const data = reactive({ ...initialData });

  return { v$: useVuelidate(rules, data) };
}

// Sample component
{
  name: "SampleComponent",
  props: {
    initialData: Object
  },
  setup(props) {
    const { v$ } = useFormValidations(
      props.initialData,
      someRulesFunction
    );

    return { v$ };
  }
};
```

**_THE PROBLEM:_** when my i18n object changes (after locale is switched from a default mode), **v$** still doesn't update its rules and all errors texts remain translated to a default language. However, data part of the object remains reactive (so no problems in actual data validations, only with errors texts).
Is it possible to make v$ object to update its rules dynamically? Or maybe you can recommend some different approach to me?

Thank you very much for your time and help!

**Comment by dobromir-hristov** [comment]
Hey there. We will be looking at i18n support in the near future. It's currently a bit shady as you can see.

Try passing a function to withMessage or a computed. That should do the trick.

**Comment by ViXP** [comment]
Ok, thank you! I'll try
