### ISSUE TITLE
Vuelidate Next breaks Typescript-builds

### ISSUE THREAD

**Issue by Nerixyz** [vuelidate/vuelidate#868]
**Describe the bug**
Vuelidate breaks Typescript-builds due to  vueuse/vue-demi#49.

**Reproduction URL**
[CodeSandbox Link](https://codesandbox.io/s/dry-water-xitw2?file=/src/App.vue)

**To Reproduce**
Run `yarn build`.
It should fail with
```
node_modules/vue-demi/lib/index.d.ts:7:17 - error TS7010: 'del', which lacks return-type annotation, implicitly has an 'any' return type.
```

I'm not sure if upgrading `vue-demi` to `0.7.3` breaks anything, but it would be nice if this could be done.

**Comment by dobromir-hristov** [comment]
Done c51f999cdb4a851ce2a931c174a92b4f3fbb8ec0
