### ISSUE TITLE
How to validate a field only if the checkbox is enabled?

### ISSUE THREAD

**Issue by fisherspoon** [vuelidate/vuelidate#870]
Good afternoon, there is a form with two inputs, one is validated by default for an empty value, and the second is validated only if the checkbox is enabled (then the input appears).

With the first input, everything works, but with the second, there is always an error, I will be very grateful for your help.

**Comment by fisherspoon** [comment]
`<form action=""  @submit.prevent="editInfo($event)">
                <p class="sub-text">Information</p>
                <div class="rector-info">
                    <div class="input-group" :class="{ 'form-group--error': $v.forms.rector.$error, 'form-group--success': !$v.forms.rector.$invalid }">
                        <label for="fio-rector">Rector</label>
                        <div class="input-container">
                            <input id="fio-rector" name="manager_fullname_ua" type="text" v-model="$v.forms.rector.$model">
                            <div class="error" v-if="!$v.forms.rector.required && $v.forms.rector.$dirty">Can't be empty</div>
                        </div>
                    </div>
                </div>

                <p class="sub-text">Additional functions</p>
                <div class="additional-functions">
                    <div class="input-group">
                        <input id="additional-checkbox" name="schedule" type="checkbox" v-model="visible">
                        <label for="additional-checkbox" class="custom-checkbox">
                            <span>Additional function</span>
                        </label>
                    </div>

                    <div class="input-group">
                        <input v-if="visible" name="shedule_start_date" type="text" placeholder="Additional function" v-model="$v.forms.additional.$model">
                        <div class="error" v-if="!$v.forms.additional.required && $v.forms.additional.$dirty">Can't be empty</div>
                    </div>
                </div>

                <div class="btn-container">
                    <button type="submit" class="btn-primary edit" @click="editInfo($event)" :disabled="submitStatus === 'PENDING'">Add</button>
                </div>
                   
                </form>




new Vue({
    el: '#App',
    data: {
        visible: false,
        forms: {
            rector: '',
            additional: ''
        }
    },
    validations() {
        return {
            forms: {
                rector: {required},
                // how to write the condition that if visible === true add validation to the additional field?
                additional: {required}
            }
        }
    },
    methods: {
        editInfo: function (e) {

            let target = e.target || e;
            this.$v.$touch()
            if (this.$v.$invalid) {
                console.log('Error');
                this.submitStatus = 'ERROR'
            } else {
                console.log("Done")
            }
        },
    }
})`

**Comment by fisherspoon** [comment]
`<form @submit.prevent="editInfo($event)">
                <div class="rector-info">
                    <div class="input-group" :class="{ 'form-group--error': $v.forms.rector.$error, 'form-group--success': !$v.forms.rector.$invalid }">
                        <label for="fio-rector">Rector</label>
                        <div class="input-container">
                            <input id="fio-rector" name="manager_fullname_ua" type="text" v-model="$v.forms.rector.$model">
                            <div class="error" v-if="!$v.forms.rector.required && $v.forms.rector.$dirty">Can't be empty</div>
                        </div>
                    </div>
                </div>
                <p class="sub-text">Additional functions</p>
                <div class="additional-functions">
                    <div class="input-group">
                        <input id="additional-checkbox" name="schedule" type="checkbox" v-model="visible">
                        <label for="additional-checkbox" class="custom-checkbox">
                            <span>Additional function</span>
                        </label>
                    </div>
                    <div class="input-group">
                        <input v-if="visible" name="shedule_start_date" type="text" placeholder="Additional function" v-model="$v.forms.additional.$model">
                        <div class="error" v-if="!$v.forms.additional.required && $v.forms.additional.$dirty">Can't be empty</div>
                    </div>
                </div>
                <div class="btn-container">
                    <button type="submit" class="btn-primary edit" @click="editInfo($event)" :disabled="submitStatus === 'PENDING'">Add</button>
                </div>
                </form>`

**Comment by dobromir-hristov** [comment]
You can use the `requiredIf` validator.
