### ISSUE TITLE
How to add validation based on state?

### ISSUE THREAD

**Issue by fisherspoons** [vuelidate/vuelidate#871]
Hi, I have an example where I add a certain status based on the data that comes from the backend and, depending on whether the input is filled or not, I add a status based on which I need to add validation.
That is, in fact, the input is visible only if you turn on the checkbox or the field came filled out from the backend, validation is added if the field is visible.
`elems: [
        {
          value: 123,
        },
        {
          value: "",
        },
      ],`
      
      
`elems: {
        0: this.elems[0].state === true ? { required } : {},
        1: this.elems[1].state === true ? { required } : {},
      },`
      
I use this construction, but the validation always succeeds

[https://bit.ly/2S9qd4u](Sandbox)

**Comment by fisherspoons** [comment]
Copy and paste the link into the address bar
[https://bit.ly/2S9qd4u](link)

**Comment by dobromir-hristov** [comment]
This is not how you validate collections. Please read - https://vuelidate-next.netlify.app/advanced_usage.html#validating-collections
