### ISSUE TITLE
CIDR range validator

### ISSUE THREAD

**Issue by perfecto25** [vuelidate/vuelidate#882]
hello, Im using Vuelidate 0.7.6 to validate my form input

it has IP Address validator, but dont see a CIDR validator

how can you validate a CIDR range?

also is it possible to validate a input field that has comma separated list of IP addresses,

192.168.1.1, 192.168.2.3,

**Comment by dobromir-hristov** [comment]
Sorry, you have to write your own validator, for those cases. You can still use the built-in ones, to base your one.
