### ISSUE TITLE
How to use sameAs validator with options API in 2.0?

### ISSUE THREAD

**Issue by Giwayume** [vuelidate/vuelidate#884]
### Documentation

Passing a string to sameAs in 2.0 seems different from 1.0, as it's a raw value instead of a field name.

https://vuelidate-next.netlify.app/validators.html#sameas

### Example

This appears to leave no way for those using the options API to reference the other field

https://codesandbox.io/s/nostalgic-noether-92exr?file=/src/App.vue

**Comment by dobromir-hristov** [comment]
Yeah, that is a mistake in the docs, raw strings are no longer supported by default, you have to pass a reference to the field. 

```
export default {
  validations(){
    return { passwordConfirm: sameAs(this.password)  }
  }
}
```

**Comment by constantinosergiou** [comment]
@dobromir-hristov  i added 
sameAs(this.password) but i get this
```
 Uncaught (in promise) TypeError: Cannot read property 'password' of undefined
```

**Comment by dobromir-hristov** [comment]
Validations must be a normal function.
