### ISSUE TITLE
$model shouldn't be typed readonly

### ISSUE THREAD

**Issue by jods4** [vuelidate/vuelidate#892]
### Make sure that you are familiar with documentation before submitting an issue.

https://vuelidate-next.netlify.com/

From the docs: 
> **When you modify it** [$model], it calls $touch() for that property and then proceeds to update the original value.

**Describe the bug**
The type `BaseValidation` declares `readonly $model: T`.
Hence you get a TS error if you try to modify it.

**To Reproduce**
```ts
let a: Validation;
// Cannot assign to '$model' because it is a read-only property.
a.$model = 4;
```

**Expected behavior**
Compiles without error

**Additional context**
I suppose the fix is as simple as dropping the `readonly` modifier from `BaseValidation.$model`

**Comment by dobromir-hristov** [comment]
Wonder why no one complained up to now... :D care to make a PR?
