### ISSUE TITLE
Cut-down babel transpilation in dist

### ISSUE THREAD

**Issue by jods4** [vuelidate/vuelidate#895]
I noticed Vuelidate 2.x includes some babel helpers in dist.
In terms of space, mostly:
- ES6 classes, supported everywhere Vue 3 runs, except Edge 12, which I don't think is a target at all.
- Iteration, again supported everywhere Vue 3 runs, except Edge 12-13, which again is not a likely target.

So I was thinking you could cut down the dist code a bit by upgrading the babel target to ES6, at least.

**Comment by dobromir-hristov** [comment]
Yep, its on the list :) Thanks for taking time to post the issue.

**Comment by dobromir-hristov** [comment]
Pushed a PR, let me know if you think its enough :)

**Comment by jods4** [comment]
Thanks!

Just want to let you know that in the end we've decided to replace Vuelidate with our own validation code.

It's much inspired by Vuelidate (in particular the `$model` approach) but is specifically tailored to our needs and has a few extra features.

**Comment by dobromir-hristov** [comment]
Makes me sad and happy at the same time 😁
