### ISSUE TITLE
Publish @vuelidate/components package

### ISSUE THREAD

**Issue by darthf1** [vuelidate/vuelidate#898]
In the [docs](https://vuelidate-next.netlify.app/advanced_usage.html#using-the-validateeach-component) a hint is given to use the `ValidateEach` component inside the `@vuelidate/components` package.

The package is not yet published, as I cannot find it on [NPM](https://www.npmjs.com/search?q=%40vuelidate) and I get an error while installing it.

```
yarn add @vuelidate/components

yarn add v1.22.5
[1/4] Resolving packages...
error An unexpected error occurred: "https://registry.yarnpkg.com/@vuelidate%2fcomponents: Not found".
info If you think this is a bug, please open a bug report with the information provided in "/usr/src/client/yarn-error.log".
info Visit https://yarnpkg.com/en/docs/cli/add for documentation about this command.
```

The package is [introduced](https://github.com/vuelidate/vuelidate/pull/880) only 11 days ago, so I'm not sure whether the package is just not published yet, or this is an error since the package is mentioned in the docs (and a [publish](https://github.com/vuelidate/vuelidate/commit/82c8b517c1ae923f72dd74ab96ff1bc710efea97) commit is made).

**Comment by dobromir-hristov** [comment]
@shentao please publish the package when you have time. :)

**Comment by shentao** [comment]
Just published! Sorry!
