### ISSUE TITLE
How to set $externalResults for collections?

### ISSUE THREAD

**Issue by darthf1** [vuelidate/vuelidate#899]
Hi!

I'm using [`$externalResults`](https://vuelidate-next.netlify.app/advanced_usage.html#external-results-with-composition-api) for storing additional validation errors thrown by my external API.

For validating collections; I'm using the [`ValidateEach`](https://vuelidate-next.netlify.app/advanced_usage.html#using-the-validateeach-component) component for displaying the "internal" errors, which already works great. How can I set the `$externalResults` for a record in the collection?

My code is exactly the same as in the [example](https://vuelidate-next.netlify.app/advanced_usage.html#using-the-validateeach-component) with the `ValidateEach` component.

```js
const rules = {
  name: {
    required,
    minLength: minLength(10)
  }
}
const collection = reactive([
  { name: 'foo' },
  { name: 'bar' }
])

const $externalResults = ref({})

// how to set a message for collection[0].name?
$externalResults.value = { collection: .. ?? }

const v = useVuelidate(rules, collection, { $externalResults })
```

How can I set the `$externalResults` for e.g. ` collection[0].name` (in the parent component)?

**Comment by dobromir-hristov** [comment]
Good question!

`ValidateEach` has a `config` prop, which accepts, you guessed it, an `$externalResults` property. 

Maybe try providing a Ref, for each entity? Or a reactive array, for the entire collection.

Let me know what works for you.

**Comment by darthf1** [comment]
Thanks for commenting back.

My usecase: I've created my own `useForm()` composable which does a lot of my "common" form logic. If I provide a state, the validation rules, and a "handleSubmit" click action, it returns a `canSubmit` boolean, it returns the `handleSubmit` action and the `validator` instance.

```html
<button type="button" class="btn btn-primary" :disabled="canSubmit" @click="handleSubmit">Submit</button>
```

```js
const { canSubmit, handleSubmit, validator } = useForm(
  state,
  rules,
  async () => {
     ...handle submit click action...
  }
)
```

Inside this composable, I add a try-catch around the `handleSubmit` click action. When invalid data is passed to the API, I always get a certain HTTP response. So I catch that response and add the errors to the `externalErrors`.

```js
const externalErrors = ref<ServerErrors>({})
const validator = useVuelidate(rules, state, {
  $externalResults: externalErrors,
})

const handleSubmit = async (): Promise<void> => {
  try {
    await submitAction()
  } catch (e) {
    if (e is my api error response) {
      ... some transformations ...
      externalErrors.value = { field: ['bad input'] }
      ... touch each field which has an external error ...
      validator.field.$touch()
    } else {
      throw new Error(e)
    }
  }
}
```

I was hoping it would be possible providing these `$externalResults` for collections inside this composable, keeping the logic inside that composable. 

Now, I'll try to return a `externalCollectionResults` from my composable, and provide that to the `ValidateEach` component as you mentioned. 

```js
const { canSubmit, handleSubmit, validator, externalCollectionResults } = useForm(
  state,
  rules,
  async () => {
     ...handle submit click action...
  }
)
```

Is it also true that the `$touch()` function is not available per field in the collection, but only on the entire collection at once?

Can "setting `$externalResults` for collections in parent validator" be considered as a feature request? I don't know if it fits with how working with collections is currently designed.

**Comment by dobromir-hristov** [comment]
Generally the parent is only a collector, because we don't know how many levels down that child is. So providing those results from a parent may not be possible.

**Comment by darthf1** [comment]
Ok!

I made a small reproduction; I cannot get the `$externalResults` errors to show for the `ValidateEach` component.

https://codesandbox.io/s/dark-paper-crdvv

I added `{{ v.name.$touch() }}` in the template; what would be the best way to `$touch()` the field programatically? Via `$ref`?

**Comment by dobromir-hristov** [comment]
Touching the parent, should touch all children as well.

**Comment by dobromir-hristov** [comment]
I played a bit with the example you linked, here is what works for me locally, but not in codesandbox... for some reason :D 

https://codesandbox.io/s/using-validateeach-with-externalresults-c0thq
