### ISSUE TITLE
Question: how to link PR number to commit after merging?

### ISSUE THREAD

**Issue by nawa** [vuelidate/vuelidate#905]
Sorry, but I didn't find a better place to ask this question, I would appreciate it if someone answers

I see that almost all commits in `next` and `master` branches are with links to corresponding PRs - `fix: email validation with uppercase domain (#888)`.  How to archive that and automatically add the PR number to commit after merging?

**Comment by dobromir-hristov** [comment]
GitHub automatically closes issues that have been linked in a PR, when the keyword `closes #number`.

This should be in the body of the PR, and If in the title, then it's copied to the Change log.

**Comment by nawa** [comment]
@dobromir-hristov Sorry but I meant a link to PR, not an issue. And the question wasn't about a closing issue. The question was "How to add to commit the PR number (link) on which that commit was merged"
