### ISSUE TITLE
Replacing $each with vue-multiselect component

### ISSUE THREAD

**Issue by jskitz** [vuelidate/vuelidate#906]
I've been trying to upgrade my project to Vue3, and as a result of that, I have attempted to move to Vuelidate Next 2.x. Everything has been going quite smoothly except for the removal of `$each`. This was a very good feature for doing validation over collections. I don't quite understand how I would use your nested validation solution using the `vue-multiselect` component. This component takes a collection, and I need to validate that what the users type in are valid email addresses. So, in the previous version of Vuelidate, I had the following validation definition:

```
      recipients: {
        required,
        $each: {
          email: {
            email
          }
        }
```

The recipients data model is just expected to be a required array of email addresses.

The multiselect component definition in my project looks like the following:

```
            <multiselect
              id="multiselect-friends"
              v-model="recipients"
              placeholder="Add email address or search contacts (pick at least one)."
              :class="{ custom: multiselectCustomCSS }"
              :options="options"
              :searchable="true"
              :allow-empty="true"
              :multiple="true"
              :taggable="true"
              :hideSelected="true"
              tagPlaceholder="Add email address to invite friend."
              label="email"
              track-by="email"
              @tag="addNewContact"
              @close="v$.recipients.$touch()">
            </multiselect>
```

My main feedback here, is that `$each` was a very powerful feature that worked very well. I don't really know how I would use  nested validations here. I know that vue-multiselect is also a tool created by your team, so I'm wondering what the suggestion is here to validate this correctly? Any help would be much appreciated as I work through the arduous task of getting on to Vue 3. The answer might be, don't upgrade yet :) Thanks for your hard work here.

**Comment by jskitz** [comment]
I think I found my solution by digging in further. Adding here for anyone else who runs into this and closing:

https://vuelidate-next.netlify.app/advanced_usage.html#using-the-new-foreach-helper

**Comment by dobromir-hristov** [comment]
You can have an array validator, it just won't tell you which exact item is not valid, unless you do some manual checking.

Let me know if you made things working.

**Comment by jskitz** [comment]
@dobromir-hristov thanks for the hint! That's actually all I needed, and was very easy to implement versus using the forEach helper.
