### ISSUE TITLE
Required-validation doesn't change upon input

### ISSUE THREAD

**Issue by zethzeth** [vuelidate/vuelidate#907]
**Describe the bug**

The bug is with the 'required' and 'email' validator together. 
I'm aware that the 'email'-validator makes the 'required'-validator redundant (since an empty-string isn't a valid email). But still. 

And there is no example using the 'email'-validator in the documentation. 

**Reproduction URL**

You can see the bug here: https://codesandbox.io/s/confident-benz-x1lq8?file=/src/App.vue

**To Reproduce**
1. Go to above CodeSandbox
2. As you can see for an empty form, 'required'-validator is `false` and the 'email'-validator is `true`. That's the first bug. Why is an empty string a valid email?
3. The next bug is, that if you insert something in the text-field, then the 'required'-validator doesn't change (it remains `false`). I'm experiencing the same thing on my local environment, with that code (copy/pasted). 

**Expected behavior**
I was expecting the 'required'-validator to become `true`, when I insert content in the text-field. 

**Screenshots**

I've attached how it looks on my local environment. 

![vuelidate-bug-email-and-required-1](https://user-images.githubusercontent.com/5783787/126882133-53471503-bf98-4223-9c32-86d6dd6c02c1.png)
![vuelidate-bug-email-and-required-2](https://user-images.githubusercontent.com/5783787/126882134-737ab0a7-7c63-45f8-85ad-9af3b5fe532e.png)
![vuelidate-bug-email-and-required-3](https://user-images.githubusercontent.com/5783787/126882136-16d34b64-62f6-43b8-87a9-788faa0fd094.png)

**Comment by dobromir-hristov** [comment]
There is no `emailToInvite` in your `data`, so it cannot track the reactivity of it.

Validation state needs to be predefined.
