### ISSUE TITLE
validator when used as a function inside a custom validator fails silently.

### ISSUE THREAD

**Issue by metalsadman** [vuelidate/vuelidate#913]
**Describe the bug**
this use to work in old vuelidate. see snippet:
```js
import { required } from '@vuelidate/validators'
export function rules() {
  return {
     field1: { required }, // works fine
     field2: {
        customValidator: (val, vm) => {
          return vm.someValue.nestedValue === false || required(val) // fails silently and will always return falsy validation even if it's truthy
        }
      }
  }
}
```

**To Reproduce**
1. https://codesandbox.io/s/jolly-ride-ez6ft?file=/src/App.vue
2. Change value of "Input 2" input field
3. Click on 'Toggle All Ouput' button
3. Scroll down to "mehval" object

**Expected behavior**

**Screenshots**

**Additional context**

**Comment by dobromir-hristov** [comment]
Hello!

Can you make a small reproduction on codesandbox so I can see whats going in? At first glance it looks good.

**Comment by metalsadman** [comment]
@dobromir-hristov hi, updated above with sandbox. ty

**Comment by dobromir-hristov** [comment]
Right I see what is going on. Default exported validators are now objects that have metadata, like a validation message, params etc. You can use the raw validators to do what you are aiming, which are just functions.

`import { required } from "@vuelidate/validators/dist/raw.esm"`

**Comment by metalsadman** [comment]
that may result in a clash no? since I also use the validator normally in other fields and imo it's unintuitive to be doing such.

**Comment by metalsadman** [comment]
ok, I guess that would do. ty
