### ISSUE TITLE
Not updated v$

### ISSUE THREAD

**Issue by uskov-dev** [vuelidate/vuelidate#915]
I do everything right here https://vuelidate-next.netlify.app/#getting-started-2
v$ does not change on errors

**Comment by dobromir-hristov** [comment]
Can you show us an example of your code?

**Comment by uskov-dev** [comment]
https://codesandbox.io/s/keen-cache-y5bf6?file=/src/main.js

**Comment by dobromir-hristov** [comment]
Use `v$.name.$model` or set autoDirty to true

**Comment by uskov-dev** [comment]
Thank you very much
