### ISSUE TITLE
Types for custom validator with vm missing in ValidationRule

### ISSUE THREAD

**Issue by ig-onoffice-de** [vuelidate/vuelidate#917]
**Describe the bug**
I wrote a custom validator using the second parameter vm of the Validator Function [like described here](https://vuelidate-next.netlify.app/custom_validators.html#passing-extra-properties-to-validators). 
I also have a withI18nMessage function to pass all validators thru to add messages. This function uses the `helpers.withMessage`-Function. This function requires 2 parameters with the following types `message: string | Function, validator: ValidationRule`. Unfortunately I can't pass my validator with type `(value: T, vm: any) => boolean | ValidatorResponse | Promise<boolean | ValidatorResponse>` to the validator parameter, because the vm option is not included in ValidationRule.

Should I use a different type or could you please just add it?

**Expected behavior**
I should be able to use `helper.withMessage` with custom validators with the vm parameter too.

**Comment by dobromir-hristov** [comment]
Hey there, sorry about the confusion. I am very much not a TS user, so if you want/can a PR would be very much appreciated. A TS rewrite is planned, I just dont have the bandwidth to do it :/

**Comment by ig-onoffice-de** [comment]
this may be fixed with !903
