### ISSUE TITLE
Can't have a ref for external results when Options API is used

### ISSUE THREAD

**Issue by nskazki** [vuelidate/vuelidate#922]
**Describe the bug**

Vuelidate accesses `vuelidateExternalResults` by value which makes it impossible to define external results as a `ref` when the Options API is used. In the example below,  the `fail` won't cause any effect because the `vuelidateExternalResults` will be read by value once and so the following updates to the prop won't be noticed.

```js
export default {
  setup: () => ({
    v$: useVuelidate(),
    vuelidateExternalResults: ref(null)
  }),
  data: () => ({
    myField: null
  }),
  methods: {
    fail() {
      this.vuelidateExternalResults = { myField: 'Server is down' }
    }
  } 
}
```

An obvious fix is to use `toRef` but I saw some complex logic inside `$clearExternalResults`, so it might not work or require the preservation of the `vuelidateExternalResults`'s type. Here is the place where the `vuelidateExternalResults` gets accessed by value and an imaginary fix for the problem:

https://github.com/vuelidate/vuelidate/blob/64892a5ebcdee1ad8c728766d9e693f605e36477/packages/vuelidate/src/index.js#L153

```js
setValidations({
  ...otherOptions,
  externalResults: toRef(instance.proxy, 'vuelidateExternalResults'),
  areExternalResultsReactive: isReactive(instance.proxy.vuelidateExternalResults) // for the later use in `$clearExternalResults`
})
```

**Reproduction URL**

https://codesandbox.io/s/dreamy-spence-plni5?file=/src/App.vue

**To Reproduce**

The demo automatically sets the `vuelidateExternalResults` and makes the `number` dirty on init, so no actions are required.

**Expected behavior**

The `Server is down` is expected to be shown but it's missing because Vuelidate didn't notice the replacement of the `vuelidateExternalResults`. Check the `fail` method for details.

**Comment by dobromir-hristov** [comment]
Can't you just define that property in your data? Or pass it as a config like you normally do for composition API?

**Comment by nskazki** [comment]
Thank you for the very rapid response! 

> Can't you just define that property in your data?

It won't solve it for Vue@3: https://codesandbox.io/s/modern-smoke-wys96?file=/src/App.vue. And for Vue@2, you will have to access it via the `value` which isn't cool:  `this.vuelidateExternalResults.value = { ... }` vs `this.vuelidateExternalResults = { ... }`

> Or pass it as a config like you normally do for composition API?

Vuelidate won't accept the `$externalResults` option unless I pass some `rules` and `state` alongside and for some of my components I just can't do that. Although, always accepting the `$externalResults` could be a solution to my problem.

**Comment by nskazki** [comment]
To clarify, I won't this because I'm still on Vue@2, so defining `vuelidateExternalResults` as a reactive object means listing all my fields once again and yet another place and this's just annoying. A ref would totally solve this.

```js
export {
  data: () => ({
    fieldA: null,
    fieldB: null,
    vuelidateExternalResults: { 
      fieldA: null, // I would like to replace
      fieldB: null  // this with a ref(null)
    }
  }),
  validations: () => ({
    fieldA: [required],
    fieldB: [required]
  })
}
```
