### ISSUE TITLE
Feature Request - $validate for every node

### ISSUE THREAD

**Issue by nskazki** [vuelidate/vuelidate#924]
**Is your feature request related to a problem? Please describe.**

I have two groups of inputs shown within the same component and I would like to have the ability to force validation for these groups separately.

```js
export default { 
  setup: () => ({
    v$: useVuelidate()
  }),
  date: () => ({
    firstForm: {
      firstField: null
    },
    secondForm: { 
      secondField: null
    }
  }),
  validations: () => ({
    firstForm: {
      firstField: { required }
    },
    secondForm: { 
      secondField: { required }
    }
  }),
  methods: {
    async submitFirstForm() {
      if (await this.v$.firstForm.$validate()) { // can't do!
        ...
      }
    },
    async submitSecondForm() {
      if (await this.v$.secondForm.$validate()) { // can't do!
        ...
      }
    }
  }
}
```

**Describe the solution you'd like**

I would like each node in the validation state to have its own `$validate` method but at this moment only the root node has one.

```js
v$.$validate() // can do
v$.firstForm.$validate() // cannot
```

**Describe alternatives you've considered**

It's possible to call `$touch` and wait for `$pending` to turn false.

**Additional context**

I actually have such a component:

![image](https://user-images.githubusercontent.com/6743076/130363328-c111953d-afa2-4904-9329-a1340321bb1d.png)

**Comment by dobromir-hristov** [comment]
Duped of #861.
