### ISSUE TITLE
Vue Plugin: Cannot read property 'config' of null

### ISSUE THREAD

**Issue by rcovell** [vuelidate/vuelidate#929]
We have an app that uses components from a plugin we wrote.

When one of the components (that contains vuelidate) is used we receiving the following error:

`vue.runtime.esm.js?2b0e:1888 TypeError: Cannot read property 'config' of null`

This occurs at:
`const v$ = useVuelidate(rules, buffer);`

```
export default defineComponent<Props, Setup>({
  ...
  setup(props: Props, context): Setup {
    ...
    const v$ = useVuelidate(rules, buffer);
```

We had issues before with vuelidate in our plugin but thought they were resolved. In fact I thought a fix/update was put in place when we brought our plugin use-case issue up.

Setup:
Vuelidate 2
Composition API Plugin
Vue 2

I have seen other issues that seem related:
[https://github.com/vuelidate/vuelidate/issues/815](url)
[https://github.com/vuelidate/vuelidate/issues/922](url)

**Comment by dobromir-hristov** [comment]
Could you give me the entire component? We have tests for both Vue3 and Vue2. But maybe I missed something in the latest refactor.

**Comment by rcovell** [comment]
Here is truncated version. Took out parts to make it easier to see.

[ExampleComp.zip](https://github.com/vuelidate/vuelidate/files/7107402/ExampleComp.zip)

**Comment by rcovell** [comment]
It is dying on:
`
if (!fallbackVM) {
  fallbackVM = defineComponentInstance(getVueConstructor());
}
`

Inside `function getWatcherVM() {`
Not sure where this is in the process.

`const instance = getCurrentInstance();` is also null in the very beginning. Probably telling you stuff you already know or is not relevant to the issue at all.

Could this be related to us using defineComponent?
 
`export default defineComponent<Props, Setup>({`

**Comment by dobromir-hristov** [comment]
I have not yet had time to see it. Will do in an  hour.

**Comment by rcovell** [comment]
Hmm, this might be a me thing. Another guy got it to work from the plugin. Going to do some research. Will report back.

**Comment by rcovell** [comment]
Ok, got it to work. Version was the issue, other guy was on:
`@vuelidate/core": "^2.0.0-alpha.16", "@vuelidate/validators": "^2.0.0-alpha.13",`

I was on the latest. Let me know if there is anything else I can provide. Can also branch off and test something if you find anything out.

**Comment by dobromir-hristov** [comment]
Hey. I am looking at your component now, but I dont see anything wrong with it. It has allot of unnecessary code that I wish you could remove, so I can just reproduce the error.

If you want me to help, create a minimal reproduction, in codesandbox or a new repo with just a single validation and state. No need for all that project specific logic, unless that is the cause of the issue, in which case it may be out of our reach.

**Comment by rcovell** [comment]
Will put something together.
