### ISSUE TITLE
$response.$errors is undefined when using the helpers approach for array of objects

### ISSUE THREAD

**Issue by iamunadike** [vuelidate/vuelidate#931]
I am having issue with this I have giving $response.$errors is undefined
When I call it in the template, for the tthis.v$.tasks.$each.$response.$errors.

```
import { helpers, required } from "@vuelidate/validators";

setup() {
        const rules = { 
            ticket: {
                serial: { required },
            },
            tasks: {
                $each: helpers.forEach({
                    tracker: { required },
                    description: { required },
                    service_ids: { required }
                })
            }
        };
        const state = reactive({
            ticket: {
                serial: "",
                status: "",
                tasks: []
            },
            tasks: [{
                tracker: "",
                description: "",
                rating: 0,
                service_ids: [],
                //workers: []
            }],
            payment: {
                type: "",
                deposit: 0.00,
                total: 0.00
            },
        })
        const v$ = useValidate(rules, state)

        return { v$, state }
```
Browser Console:-
**Tracker {
"$params": {},
"$pending": false,
"$invalid": true,
"$response": "TypeError: can't convert undefined to object"
}**

**Comment by dobromir-hristov** [comment]
OK I found the issue. Its because `rating` has no validator 🤣 I guess the forEach helper tries to go over every single item in the state. I will see how to fix that.

**Comment by dobromir-hristov** [comment]
Cool found a fix. Will do a bit more testing and will try to release it :)

**Comment by iamunadike** [comment]
exactly but in as much that the helper.forEach counts each field I guess , it should remain selective per field rather than compulsory or maybe adding a empty value for the ratings if it must be compulsory , provided no exceptions thrown
