### ISSUE TITLE
Warning validators

### ISSUE THREAD

**Issue by benjamin-t-frost** [vuelidate/vuelidate#934]
## **Is your feature request related to a problem? Please describe.**
When developing a feature, designers sometimes request that we give non-blocking warnings on various form elements.

### Example:
The user has chosen a low resolution image; they are free to do so if they really want to but we want to let them know it won't look the best.

## **Describe the solution you'd like**
If Vuelidate supported `$warn` validators which would not cause any `$error` attributes to be true, it would eliminate a lot of redundant noise in components and speed up development time.

They would function much the same as the existing validators but the resulting `$v...` attributes would be kept separate under `$warn` attributes to avoid convoluting existing logic and introducing breaking changes.

## **Describe alternatives you've considered**
As a workaround, we created redundant custom validators separate from Vuelidate.

## **Additional context**
[Dash Hudson](https://www.dashhudson.com/) is willing to contribute developer time if the Vuelidate maintainers are open to this feature.

**Comment by dobromir-hristov** [comment]
You can return a warning with the validator response, and read it through `v$.name.validator.$response.$warning` for example.

Validator response should be

```
{ $valid: true, $warning: true }
```

**Comment by benjamin-t-frost** [comment]
Thanks @dobromir-hristov!

Is this something which you'd be open to us helping to document? It'd be nice if it weren't destined to be tribal knowledge ~

**Comment by dobromir-hristov** [comment]
Will add some examples over the weekend :) stay tuned

**Comment by dobromir-hristov** [comment]
Closed via - https://github.com/vuelidate/vuelidate/pull/935

https://vuelidate-next.netlify.app/examples.html#returning-metadata-from-validators
