### ISSUE TITLE
useVuelidate script setup Vue 3 example documentation

### ISSUE THREAD

**Issue by thebleucheese** [vuelidate/vuelidate#938]
**Is your feature request related to a problem? Please describe.**
To be fair, I'm very new to Vue 3 so chalk a lot of this up to the learning process. It took me a few hours to get setup with vuelidate and the Composition API with Vue 3 script setup tags. I'm not sure if I'm doing anything right with it. I did some things that contradict the documentation.  

For example: https://vuelidate-next.netlify.app/guide.html#setting-dirty-state-with-autodirty says I can remove the ".$model" from my v-model attribute property.  When I do that, my model bindings break.  My text field shows "`[Object object]`".

Additionally, am I supposed to be calling `await v$.value.$validate()`?  If I don't, nothing seems to work right but I didn't find this in the documentation. 

I was following the PrimeVue documentation https://primefaces.org/primevue/showcase/#/vuelidate and while I'm guessing theirs works as-is, it seems like there are some behavioral differences between script setup sugar and the setup() function composition API (assuming their docs examples are working as-is). 

**Describe the solution you'd like**
Documentation that describes best-practices for using Vuelidate with script setup sfc Vue 3. I read that script setup is the recommended way of starting new projects. 

**Describe alternatives you've considered**
My usual fumbling around like an uncoordinated toddler at the keyboard.

**Additional context**

Here's a sample of my form component. Any commentary on if I'm heading in the right direction is much appreciated, thanks!

```vue
<template>
<form @submit.prevent="handleSubmit">
    <div>
        <label for="name">
            Name
        </label>
        <div>
            <input type="text" v-model="v$.name.$model" name="name" id="name" placeholder="Name" />
        </div>
        <div v-if="v$.name.$error">
            NAME ERROR
            <span id="name-error" v-for="(error, index) of v$.name.$errors" :key="index">
                {{error.$message}}
            </span>
        </div>
    </div>
    <div>
        <label for="custom-select">
            Custom Select
        </label>
        <div>
            <CustomSelect
                name="custom-select"
                placeholder="Select a Value"
                v-model="v$.selectVal.$model"
                />
        </div>
        <div v-if="v$.selectVal.$error">
            Custom Select Error Debug
            <span id="custom-select-error" v-for="(error, index) of v$.selectVal.$errors" :key="index">
                {{error.$message}}
            </span>
        </div>
    </div>
    
    <button type="submit">
        Save
    </button>
</form>
</template>
<script setup>
import { reactive, computed } from 'vue'
import CustomSelect from '@/components/CustomSelect.vue'

import { required } from "@vuelidate/validators";
import { useVuelidate } from "@vuelidate/core";

const formState = reactive({
  selectVal: null,
  name: ''
})

const rules = computed(() => {
  return {
    selectVal: {
      required
    },
    name: {
      required
    }
  }
})

const v$ = useVuelidate(rules, formState, { $autoDirty: true }) 

const handleSubmit = async () => {
  // Do I need this? Without it, my custom select doesn't seem to trigger 
  // $touched or $dirty or something and doesn't show its errors on submit
  await v$.value.$validate()

  // This doesn't work if I don't have the ".value" either
  if (v$.value.$invalid) {
    alert('Form failed validation')
    return
  } else {
    alert('Form successfully submitted.')
    return
  }
}

</script>
```

**Comment by dobromir-hristov** [comment]
Hey there, here are a few things to note:

1. using `autoDirty: true` means you can just change your state, without using `v$.name.$model`, we just create a watcher under the hood and set `$dirty` to `true` for you. Its in the docs - `v-model="name"` vs `v-model="v$.name.$model". https://vuelidate-next.netlify.app/guide.html#setting-dirty-state-with-autodirty
2. Calling `v$.value.validate()` is so that all validators are triggered, and it returns a Promise, which resolves when async validators are done. https://vuelidate-next.netlify.app/guide.html#validating-forms-before-submitting
3. When using the Composition API, `v$` is a computed property, so always access it via `.value`
4. `script setup` and `script` are used the same.
5. Your `rules` dont need to be a computed, unless they are changing their structure.
6. You can check the response of `$validate()` as it is a boolean.

Your code example looks OK to me. Your `CustomSelect` should trigger the dirty state fine. If you use `$model` you dont need the `autoDirty` config.

**Comment by thebleucheese** [comment]
> 1. using `autoDirty: true` means you can just change your state, without using `v$.name.$model`, we just create a watcher under the hood and set `$dirty` to `true` for you. Its in the docs - `v-model="name"` vs `v-model="v$.name.$model". https://vuelidate-next.netlify.app/guide.html#setting-dirty-state-with-autodirty

This is what I thought, but I can't get that working with my codesample.  I see this in the console:

`runtime-core.esm-bundler.js:6871 [Vue warn]: Property "name" was accessed during render but is not defined on instance. 
  at <TestForm> 
  at <TestForm onVnodeUnmounted=fn<onVnodeUnmounted> ref=Ref< undefined > > 
  at <RouterView> 
  at <App>`

If I switch it to `v-model="formState.name"` it seems to work ok but I'll need to do some more testing.  Just following up in case anyone else runs across this.

**Comment by dobromir-hristov** [comment]
Of sorry haha. You absolutely have to keep the same structure as your state. 

Name is inside formState object, so you must access it like that.
