### ISSUE TITLE
Type error with a function for validations

### ISSUE THREAD

**Issue by JohnCampionJr** [vuelidate/vuelidate#940]
**Describe the bug**
Types for validations on useVuelidate does not allow for a function for validations.
Thus, using a function as suggested here #878, while working perfectly, throws a type error.

**Reproduction URL**
https://codesandbox.io/s/infallible-https-f8qgx?file=/src/App.vue

Does not show up well in Code Sandbox, but in VS Code,

**Expected behavior**
No type errors when using a function

**Screenshots**
![Screenshot 2021-09-22 135654](https://user-images.githubusercontent.com/1094820/134396597-587fb964-90cb-42cb-a4e1-413848964ff0.png)

**Comment by JohnCampionJr** [comment]
I can't figure out how to get sameAs working then.  You told the poster here
https://github.com/vuelidate/vuelidate/issues/878
To use a function, as shown here:
https://vuelidate-next.netlify.app/validators.html#sameas

This actually works perfectly, but just get the type error.  If this is not the correct way, can you provide guidance?

**Comment by JohnCampionJr** [comment]
So would this be correct in the sandbox?  It does work and VS code isn't throwing a type error any more.

Maybe an update in the docs?

```js
    const rules = computed(() => {
      return {
        password: {
          required,
        },
        confirm: {
          sameAs: sameAs(state.password),
        },
      };
    });
```

**Comment by dobromir-hristov** [comment]
Update here - https://vuelidate-next.netlify.app/api/rules.html#computed-function-with-composition-api
