### ISSUE TITLE
vue3 script setup, not sameAs

### ISSUE THREAD

**Issue by mrkazu** [vuelidate/vuelidate#942]
Hello, im using vue3 with composition-Api and script setup. When using "not sameAs" the validation dont trigger if i use the value from another input field. However if i hardcode the value as a string the "not sameAs" will work. There seems to be a problem with reactivity.

```
// This is not working
notSameAs: not(sameAs(formState.user2))
```
```
// This is working
notSameAs: not(sameAs('a hardcoded string')
```

If i only use sameAs i can dynamicly use a value from another input field.

```
// This is working
sameAs: sameAs(formState.user2)
```

Here is the entire script file
```
<script setup lang="ts">
import useVuelidate from '@vuelidate/core'
import { required, minLength, not, numeric, sameAs, helpers } from '@vuelidate/validators'

const formState = reactive({
  user1: '',
  pin1: '',
  user2: '',
  pin2: '',
})

const rules = computed(() => {
  return {
    user1: {
      required: helpers.withMessage('Måste anges!', required),
      notSameAs: not(sameAs(formState.user2)),
    },
    pin1: {
      numeric: helpers.withMessage('Endast siffror!', numeric),
      required: helpers.withMessage('Måste anges!', required),
      minLengthValue: helpers.withMessage('Minst 4 siffror!', minLength(4)),
    },
    user2: {
      required: helpers.withMessage('Måste anges!', required),
      notSameAs: not(sameAs(formState.user1)),
    },
    pin2: {
      numeric: helpers.withMessage('Endast siffror!', numeric),
      required: helpers.withMessage('Måste anges!', required),
      minLengthValue: helpers.withMessage('Minst 4 siffror!', minLength(4)),
    },
  }
})

const v$ = useVuelidate(rules, formState, { $autoDirty: true })
</script>
```

**Comment by dobromir-hristov** [comment]
Passing a state from reactive will break reactivity.

Use a ref or computed.

**Comment by mrkazu** [comment]
Hello!
I have tried using refs instead of reactive. However i still get the same results. The reactivity works when using "sameAs". but when using "not(sameAs" reactivity breaks. That is what im confused about since the reactivity works with "sameAs"

Could you show me an example on how to get the "not(sameAs"  to have reactivity from another field?

Thank you in advance.

**Comment by dobromir-hristov** [comment]
Try something that works for me
```js
const social = reactive({ github: '', twitter: '' })
```
then our rules would have something like this. Mind the `toRef` because passing a reactive's property would make it NONE reactive.
```js
        social: {
          github: { sameAs: { required } },
          twitter: { notSameAs: not(sameAs(toRef(social, 'github'))) }
        }
```

**Comment by mrkazu** [comment]
That worked perfectly!
Thank you!
