### ISSUE TITLE
$getResultsForChild usage example

### ISSUE THREAD

**Issue by AnnaYuS** [vuelidate/vuelidate#943]
The description in the docs for [$getResultsForChild](https://vuelidate-next.netlify.app/api/methods.html#getresultsforchild) method sounds like what is needed for my use case but i cannot figure out what should be passed as a `key` into it. Could someone provide an example of how to use it?
Or maybe there is another solution to the problem that we have?
We can access all the errors from child components in the parent, but it's problematic to identify which error belongs to which child component since children are instances of the same component.
```
	  <Editor>
		  <DateTimePicker name="displayFrom"/>
		  <Errors :errors="displayFromErrors">
	  
		  <DateTimePicker name="displayTo"/>
		  <Errors :errors="displayToErrors">
	  </Editor>
```

And the `DateTimePicker` consists of `DatePicker` and `TimePicker`
```
	  <span>
		  <DatePicker />
		  <TimePicker />
	  </span>
```

If we trigger errors in both `DatePicker` fields we are getting the following `$errors` array in the vuelidate instance of the `Editor` component:
```
[
	{
	  "$propertyPath":"germanDateFormat",
	  "$property":"germanDateFormat",
	  "$validator":"inputRegex",
	  "$uid":"germanDateFormat-inputRegex",
	  "$message":"Please enter date in correct format (dd.mm.yyyy)",
	  "$params":{},
	  "$response":false,
	  "$pending":false
	},			
	{
	  "$propertyPath":"germanDateFormat",
	  "$property":"germanDateFormat",
	  "$validator":"inputRegex",
	  "$uid":"germanDateFormat-inputRegex",
	  "$message":"Please enter date in correct format (dd.mm.yyyy)",
	  "$params":{},
	  "$response":false,
	  "$pending":false
	}
]
```

Is there a way to group the errors into `displayFrom` and `displayTo` groups?

**Comment by dobromir-hristov** [comment]
There is a `$regiaterAs` config you can pass to a Vuelidate instance, that is used for this exact thing.
It will return to you that instance, with that name.

**Comment by AnnaYuS** [comment]
@dobromir-hristov Thanks for your reply 🙏  We ended up with something like this: 

https://codesandbox.io/s/vue-3-vuelidate-2-sh945?file=/src/App.vue

Had to use a prop to pass it to `registerAs` and get child errors. Maybe there is a simpler way to do it? 🤔

**Comment by dobromir-hristov** [comment]
That looks good enough.
