### ISSUE TITLE
How should at least one checkbox from the group be selected when the checkbox is enabled?

### ISSUE THREAD

**Issue by fisherspoons** [vuelidate/vuelidate#947]
There is a conditional checkbox (available), if it is enabled, 2 selections must be selected and at least 1 checkbox from the list of roles, I made a dependency for the selections, but I can't think of how to do it for the role selections. 

https://codesandbox.io/s/little-silence-bfjnc?file=/src/App.vue

**Comment by dobromir-hristov** [comment]
Add a rule to the role itself, not each element.

You can loop it's values and see if any are selected
