### ISSUE TITLE
How can you add a rule based on a condition?

### ISSUE THREAD

**Issue by fisherspoons** [vuelidate/vuelidate#948]
Hi, I have a validation object and there may be a rule for a couple of checkboxes, these checkboxes are drawn and added to the data object depending on the route. I found an example of how you can make conditions for adding an object to the validation, but with this approach I will have to completely duplicate the formData object, with the gender object added or not. Perhaps there are some options for how this condition can still be implemented inside formData?

<img width="715" alt="Screenshot at Oct 08 11-36-45" src="https://user-images.githubusercontent.com/54633510/136525357-ce3c6bf5-f009-477c-8ac2-f65a11d944d4.png">

**Comment by dobromir-hristov** [comment]
No, it needs to be a function. How you structure the function body is up to you, it just returns an object. You can create an object, check a condition and just add validations to it. Then return the final object. That will save you some space.
