### ISSUE TITLE
$externalResults not added to child errors

### ISSUE THREAD

**Issue by AnnaYuS** [vuelidate/vuelidate#950]
This is probably a bug. If the child vuelidate instance is registered under the same name as parent model their errors should be merged, including the external results. This doesn't seem to be the case.

Here is an example: https://codesandbox.io/s/vuelidate-external-errors-in-child-errors-oowxc?file=/src/App.vue

**Comment by dobromir-hristov** [comment]
A parent collects the errors of its children in a special "container", but it does not merge them into it's own state. 

What that means, is that it knows its child instances have errors, and it merges them into the `$errors` property for easy display, but if a child has the same name as a state property of it's own, it will not merge those two.

So no, this is not a bug its expected, and it will probably stay that way, sorry.
