### ISSUE TITLE
[Question]: Is there a way to add validation messages with custom validators?

### ISSUE THREAD

**Issue by crotanite** [vuelidate/vuelidate#957]
Adding I18n messages with existing validators is possible but can it be done with a custom validator?

```ts
const sizeValidator = (size: number = 15) => (value: string) => {
	return !helpers.req(value) || value.length === size
}
export const size = withI18nMessage(sizeValidator)
```

Something like the above.

**Comment by dobromir-hristov** [comment]
You probably dont need to specify `$message` if you are applying i18n messages. But yeah, glad you sorted it out. Docs could deff be improved in this regard.

**Comment by ahjam-taoufik** [comment]
very nice solution

**Comment by MURHAF-ELMASRI** [comment]
how can I get i18n object with nuxt in script tag

**Comment by awacode21** [comment]
> It did not, I did manage to get it working with something like the below though. (for future reference for anyone)
> 
> ```ts
> // size.ts
> import { helpers } from '@vuelidate/validators'
> 
> export default function(amount: number) {
> 	return {
> 		$validator: function(value: string) {
> 			return !helpers.req(value) || value.length === amount
> 		},
> 		$message: ({ $params }) => `This field should be exactly ${$params.amount} long.`,
> 		$params: { amount, type: 'size' }
> 	}
> }
> ```
> 
> ```ts
> // validators.ts
> import { createI18nMessage } from '@vuelidate/validators'
> import { createI18n } from 'vue-i18n'
> import sizeValidator from './size'
> 
> const i18n = createI18n({
> 	locale: 'en',
> 	messages: {
> 		en: {
> 			validations: {
> 				size: 'The {property} field must be {amount} characters long.'
> 			}
> 		}
> 	}
> })
> const t = i18n.global.t
> const withI18nMessage = createI18nMessage({ t })
> 
> export const size = withI18nMessage(sizeValidator, { withArguments: true })
> ```

and how do i use this validator, how do i provide the params?
