### ISSUE TITLE
(Vue 2.6 + Composition Api) useVuelidate() stops all returned setup() data from being referenced in the template?

### ISSUE THREAD

**Issue by tleytek** [vuelidate/vuelidate#963]
**Describe the bug**
Once useVuelidate() is instantiated within setup(), all references to setup() return values don't exist in the template.

**Reproduction URL**
[Vuelidate 2 - Composition API + Vue 2.6](https://codesandbox.io/s/competent-framework-27b21?file=/src/components/HelloWorld.vue)

**To Reproduce**
1. Instantiate useVuelidate() within setup()

**Expected behavior**
I should be able to reference v$ or any value's I am returning from setup() in the template

**Comment by dobromir-hristov** [comment]
- I am not sure i understand what the issue is. Your repro link looks alright.

**Comment by dobromir-hristov** [comment]
Vuelidate has issues because of VueDemi in codesandbox.

Can you check this on your local?

**Comment by tleytek** [comment]
Now it seems the instantiation of useVuelidate() causes vue composition api to stop working in other components.

[Github repo](https://github.com/tleytek/vuelidate-test)
[Netlify deployment](https://gracious-fermi-9e092d.netlify.app/)

**Comment by dobromir-hristov** [comment]
This is a problem with the version of Vue-demi we have under the hood.

Changing the import to `@vue/composition-api/dist/vue-composition-api.esm` from `@vue/composition-api` fixes all the issues, but this is not OK.

I will try updating the deps as this might fix things - https://github.com/vueuse/vue-demi/pull/105
