### ISSUE TITLE
Docs website for old docs (https://vuelidate.js.org/) is down

### ISSUE THREAD

**Issue by hugohabicht01** [vuelidate/vuelidate#968]
### Make sure that you are familiar with documentation before submitting an issue.

  https://vuelidate.netlify.com/

**Describe the bug**
The website shows a Netlify not found error

**To Reproduce**
1. Go to https://vuelidate.js.org/

**Expected behavior**
Should show old docs

**Comment by dobromir-hristov** [comment]
Docs are back up. I am investigating what went wrong.
