### ISSUE TITLE
Property '$valid' is missing with Typescript

### ISSUE THREAD

**Issue by fedee13** [vuelidate/vuelidate#972]
I'm trying to implement  i18n with Vuelidate as the example in https://vuelidate-next.netlify.app/advanced_usage.html#i18n-support in a Typescript project

But I got the following error with the minLength validator as well as minValue or sameAs (with the required validator  it's working fine):
```js
export const minLength = withI18nMessage(validators.minLength, { withArguments: true })
```
```
Property '$valid' is missing in type 'ValidationRuleWithParams<{ length: number; }, any>' but required in type 'ValidatorResponse'.
```

Packages version:
@vuelidate/core: "^2.0.0-alpha.32",
@vuelidate/validators: "^2.0.0-alpha.25",
vue-i18n: "^9.2.0-beta.17",

**Comment by dobromir-hristov** [comment]
Honestly I don't know. Since you are using TS, try looking at the types. They are maintained separately so such things do happen.

**Comment by dobromir-hristov** [comment]
This is a bug with the `createI18nMessage` type, but I am not sure whats wrong there. Its probably in the `validator` type.

**Comment by derdem** [comment]
I think I have a similar issue. I am using `withI18nMessage` for my `required` validator. In my `rules` I include my i18nValidator. So far so good, but when I use the `useVulidate` api and hand over my `rules` object as first parameter, typescript starts complaining with following message: 

```
Argument of type 'ComputedRef<{ name: { required: ValidationRuleWithParams<object, unknown> | ((...args: unknown[]) => ValidationRuleWithParams<object, unknown>); }; }>' is not assignable to parameter of type 'ValidationArgs | Ref<ValidationArgs>'.
  Type 'ComputedRef<{ name: { required: ValidationRuleWithParams<object, unknown> | ((...args: unknown[]) => ValidationRuleWithParams<object, unknown>); }; }>' is not assignable to type 'Ref<ValidationArgs>'.ts(2345)
index.d.ts(39, 3): '$valid' is declared here.
``` 

I am still searching for the bug, but what I noticed is that the type for `createI18nMessage` has a return value of `ValidationRuleWithParams | ((...args: unknown[]) => ValidationRuleWithParams)` which doesn't make much sense IMO for a `required` validator.

**Comment by derdem** [comment]
Here an example. If I add a type conversion with `as unknown as ValidationRuleWithoutParams<unknown>;` the error goes away.

```vue
<template>{{ $v.$invalid }}</template>

<script setup lang="ts">
import { reactive, computed } from "vue";
import { required, createI18nMessage } from "@vuelidate/validators";
import { i18n } from "@/plugins/i18n";
import useVuelidate, { ValidationRuleWithoutParams } from "@vuelidate/core";

const { t } = i18n.global;

const withI18nMessage = createI18nMessage({ t });
const requiredI18n = withI18nMessage(
  required
) as unknown as ValidationRuleWithoutParams<unknown>;

const state = reactive({
  name: "",
});

const rules = computed(() => ({
  name: { required: requiredI18n },
}));

const $v = useVuelidate(rules, state);
</script>
```

**Comment by dobromir-hristov** [comment]
Yeah it doesn't. It's because we may have a a function that is wrapped, like the sameAs one.

I did my best with the types, but help is greatly appreciated.

**Comment by derdem** [comment]
I think this might be a solution. Making use of a generic type and enforcing that it is either a ValidationRule or a ValidationWrapper

```typescript
export function createI18nMessage({ t, messagePath, messageParams }: {
  t: typeof TranslationFunction;
  messagePath?: typeof messagePathFactory;
  messageParams?: typeof messageParamsFactory;
}): <T extends (ValidationRule | ValidatorWrapper)>(
  validator: T,
  options?: {
    withArguments?: boolean,
    messagePath?: typeof messagePathFactory,
    messageParams?: typeof messageParamsFactory,
  }) =>
  T
```

**Comment by dobromir-hristov** [comment]
would you like to add a PR? You could test it in your local setup and see if it resolves for both wrapped and unwrapped validators

**Comment by derdem** [comment]
Sure, I already checked it out locally. As this would be my first open source contribution I would ask you for some guidance. I see that I have no rights to push a new branch to the server. What would I have to do to get my local changes to the server?

**Comment by dobromir-hristov** [comment]
You need to fork the project. Then GitHub will auto suggest to you too create a PR once you push your changes to a new branch on your fork.
