### ISSUE TITLE
custom validator using nested field with context

### ISSUE THREAD

**Issue by paulhaem** [vuelidate/vuelidate#974]
Hey there,
first of all thanks for this awesome library and your work!

I am not sure if I am misusing the library but I stumbled upon an issue using following form using vue 3 and vuelidate-next:
```js
data() {
  return {
    fields: {
      startTime: {
        value: null
      },
      endTime: {
        value: null
      }
    }
  }
},
validations() {
  return {
    fields: {
      startTime: {
        value: {
          isAfter
        }
      },
      endTime: {
        value: {
          isAfter: isAfter(this.fields.startTime.value)
        }
      },
    }
  }
}
```
`isAfter` is a custom validator: `(param) => (value) => { ... }`
When I output `param` the value stays at the inital value `null` not being reactive. When I instead of `isAfter(this.fields.startTime.value)` write `isAfter(this.fields.startTime)` I get a `Proxy` object where I am able to view the reactive `value` inside of `isAfter` as part of `param`. Would be great if anyone can explain to me what happens here.

**Comment by dobromir-hristov** [comment]
There are some complexities with validators, depending on other values. Its best to use the `withParams` helper, when you are creating such validators.

```js
import { helpers } from '@vuelidate/validators'

const { withParams } = helpers
const isAfter = (param) => withParams({ param }, (value) => value > param)

export default {
  data(){
    return { ... }
  },
  validations () {
    return {
      fields: {
        startTime: {},
        endTime: {
          isAfter: isAfter(this.fields.startTime)
        }
      }
    }
  }
}
```

**Comment by paulhaem** [comment]
Thanks for the help, works like a charm. But I am still not sure on how my custom validator differs to the built-in `sameAs` validator? They both can use a data field as param.

**Comment by dobromir-hristov** [comment]
Wrapping in withParams does some extra magic behind the scenes.
