### ISSUE TITLE
Built in URL validator should accept valid URLs without "http://" or "https://"

### ISSUE THREAD

**Issue by jedleslie** [vuelidate/vuelidate#975]
**Is your feature request related to a problem? Please describe.**

Not a problem, but I think URLs that do not contain the HTTP prefix should count as valid given this is about user input validation.

**Describe the solution you'd like**

Ideally both URLs with and without https/http should pass the default URL validator.

**Describe alternatives you've considered**

A custom Regex could do it.

**Comment by dobromir-hristov** [comment]
URL validation is very tricky, and the validator is based on a very popular regex for validating URLs - https://gist.github.com/dperini/729294
