### ISSUE TITLE
I need to validate dynamically generated checkboxes and can't find solution

### ISSUE THREAD

**Issue by Marcel-Hartmann** [vuelidate/vuelidate#979]
Hi,

I have a dynamic generated form with agreement types and in the types we have agreements, which has to be selected only if the required field in the same array index is true. See my Code then you see what I want please:

https://codesandbox.io/s/agitated-nobel-d09d6?file=/src/components/CheckboxList.vue

What I'm doing here is fetching the AgreementTypes per axios, here I use array to achive that, and then I add a selected attribute to each agreement, so that I can make my checkbox v-model on it the selected. Later on, if the User will post the form, I want to check, if all selected values have the same value as the required value in the same array index of that agreement.

I have tried this but then I did not know how to get the required attribute in the validator $each: { $each: { *** }}.

```
agreementTypes: {
      $each: {
        agreements: {
          $each: {
            selected: {
              checked: (value) => value === true // this is only validated if it is true but how to check required in the parent?
            }
          }
        }
      }
    }
```
Hopefully you understand me and have a solution or workaround for my problem.

Thanks Marcel

**Comment by dobromir-hristov** [comment]
Hey there. I will assume you are using Vuelidate 0.x with Vue 2.

So if I am understanding correctly, you want each agreement in the `agreements` to have a validator for `selected` be required or not, based on the `required` property on, right?

A validator should have access to the current element's siblings from the second param:

```js
function isChecked (value, siblings) {
  return siblings.required ? value === true : true
}
```

Let me know if this works for you :)

**Comment by Marcel-Hartmann** [comment]
Oh my god, I was 2 days working on this, and the only thing I need i a second parameter in a validater function, to get my result working. A fast check does what I want, thank you very much for this you made my day! :-)
