### ISSUE TITLE
TypeScript errors when binding model to component props.

### ISSUE THREAD

**Issue by RollingTL** [vuelidate/vuelidate#983]
TS Errors in template:

  <boolean-input v-model:**value**="model.agree.$model" />
  <name-input v-model:**value**="model.name.$model" />
  
Type 'unknown' is not assignable to type 'string'.ts(2322)
(JSX attribute) value: string

**To Reproduce**
https://github.com/RollingTL/Testing-Vuelidate-and-TS

See errors in App.vue - line 3, 4

**Expected behavior**
No errors

**Comment by narcisbugeag** [comment]
Possible fix, see https://github.com/vuelidate/vuelidate/issues/925#issuecomment-1008406811

**Comment by RollingTL** [comment]
Pity, but nothing changed. The error still persists after **npm update**.

**Comment by RollingTL** [comment]
After last update the error have gone.
