### ISSUE TITLE
Errors being shown in `$silentErrors` instead of `$errors`

### ISSUE THREAD

**Issue by telisjok** [vuelidate/vuelidate#984]
Recently I migrated my application from Vue2 to Vue3 and I noticed a weird behavior regarding the Vuelidate since I updated it as well from 0.x to Vuelidate Next (2.x).

All of the errors that my input fields produced exist in the `$silentErrors` instead of `$errors` as `Vuelidate 0.x` was doing.

Is there a way to make the errors be part of `$errors` instead of `$silentErrors`?

```
<template>
  <div>
    <FormInput 
      id="task"
      type="text"
      :placeholder="'Start adding tasks'"
      v-model="form.task"
      :isRequired="true"
      :isInvalid="form.task.length >= 1 && v$.task.$silentErrors.length >= 1"
      :hasError="form.task.length >= 0 && v$.task.$silentErrors.length >= 1 ? v$.task.$silentErrors[0].$message : null"
    />
  </div>
</template>

<script lang="ts">
import { defineComponent, reactive, ref } from "vue";

// Libs
import useVuelidate from "@vuelidate/core";
import { required } from "@vuelidate/validators";

// Components
import FormInput from "@/components/form-elements/FormInput.vue";

export default defineComponent({
  name: "Home",
  setup() {
    const form = reactive({
      task: ""
    });
    const validations = {
      task: {
        required
      }
    }
    const v$ = useVuelidate(validations, form);

    return { 
      form,
      v$
    }
  },
  components: {
    FormInput
  },
});
</script>
```
![1](https://user-images.githubusercontent.com/4696628/145690330-5dc67ee1-6dcd-4521-93b2-6437c1087ca8.JPG)

**Comment by dobromir-hristov** [comment]
Use autoDirty option or $model. This is the same as before.

**Comment by telisjok** [comment]
Ahh, I see. I missed that. Thanks a lot.

**Comment by fabokenneth** [comment]
no need to do this, you should just call the `touch` method ((in v$) and the v$ informations will be updated

**Comment by AlanReibel** [comment]
> Use autoDirty option or $model. This is the same as before.

Can you explain a litle bit more or provide an example?

**Comment by gsabater** [comment]
@AlanReibel 
He means using v-model with v$ or $autodirty true as defined in https://vuelidate-next.netlify.app/guide.html#using-the-model-property
