### ISSUE TITLE
Property '$path' is missing in type definition

### ISSUE THREAD

**Issue by BobbieGoede** [vuelidate/vuelidate#985]
Trying to access a fields $path property, tsc outputs this ```Property '$path' does not exist on type '{ $model: unknown; readonly $dirty: boolean; readonly $error: boolean; readonly $errors: ErrorObject[]; readonly $silentErrors: ErrorObject[]; readonly $externalResults: ({ $validator: "$externalResults"; $response: null; $pending: false; $params: {}; } & ErrorObject)[]; ... 6 more ...; readonly $validate: () => Pro...'.```

And looking at the types it is clear that nowhere the property `$path` is defined while it is documented [here](https://vuelidate-next.netlify.app/api/state.html#path).

**Comment by dobromir-hristov** [comment]
closed in #986
