### ISSUE TITLE
Cannot access currently iterated object in forEach helper

### ISSUE THREAD

**Issue by v-dimov** [vuelidate/vuelidate#991]
Hello, I am having trouble accessing the currently iterated object using the forEach helper in a collection. I need that a certain property in the current object is only then required, when another property of the same object returns 'true'. Here's an example:

```
validations() {
  return {
    cinema: {
      name: {},
      location: {},
      movies: {
        $each: helpers.forEach(
          {
            isNew: {},
            title: {
              required
            },
            description: {
              required: requiredIf(function (value, object, vm) {
                return object.isNew
              })
            }
          }
        )
      }
    }
  };
}
```

However, I'm always receiving an error. I tried logging the three different parameters and I receive only the value and the VueComponent. 

In the documentation for the forEach helper it says:
"Each validator function is passed 3 parameters - rule(value, object, vm)

1. The value of the property, for iterated object
2. The current iterated object, aka siblings to property
3. The component instance"

What am I doing wrong here? Any help will be greatly appreciated

**Comment by dobromir-hristov** [comment]
Which versions do you have installed?
Did you try with a custom validator, to see what params are being provided?

I am pretty sure I fixed this recently

**Comment by v-dimov** [comment]
I have the following versions:

```
"@vuelidate/core": "2.0.0-alpha.23",
"@vuelidate/validators": "2.0.0-alpha.20",
```

I also tried with a custom validator and it also returns only the value and the VueComponent.

**Comment by v-dimov** [comment]
Apparently the issue was with the versions of vuelidate and vue/composition-api, which I thought I have updated but didn't. 🤦‍♂️ Thanks for the help!
