### ISSUE TITLE
iife export for @vuelidate/core

### ISSUE THREAD

**Issue by andrei-gheorghiu** [vuelidate/vuelidate#992]
Both Vue 2.x and Vue 3.x work when imported on a webpage from a cdn link (`iife` mode), by creating a Vue entry in global scope. However, the output of this library does not seem to include an export for this mode, which would allow users to register it as a plugin on a standalone Vue browser app. It seems to only support usage on node based apps, relying on node to resolve its dependencies, at compilation.

If I am wrong in saying that, it means I haven't been able to find it and my suggestion would be to extend the Getting Started section with a paragraph on how this could be achieved, without any additional setup or tooling.
___
To overcome this limitation, I have provided an answer for [this question](https://stackoverflow.com/questions/70633687/vuelidate-in-vue-property-v-was-accessed-during-render-but-is-not-defined-on), showing how to create an `iife` export using rollup for any node package. This doesn't seem to be an isolated request, there are others like it: [this](https://stackoverflow.com/questions/66424860/support-vuelidate-with-cdn-for-vue-3#comment124916910_66424860), [this](https://stackoverflow.com/questions/68090546/how-do-i-use-vuelidate-2-in-browser). There might be more, I haven't performed a thorough search.

What I've done is quite basic, but works. 

This is a shout-out to the maintainers of this lib. 

 I'd like to know if: 

 1. you don't care about an `iife` export for this lib, you don't want to support it, as you believe `iife` is a thing of the past/bad practice/dead, etc...
 2.  you want it, it was planned. You just didn't get to it. You'll add this feature in the lib yourself, some time in the future. It's great that , at least for now, there's a workaround.
 3. you want it but it wasn't planned. Which would mean you'd welcome a PR attempting to add this mode to the current export, so the lib supports it out of the box, going forward.
___

Kind regards, A.

**Comment by dobromir-hristov** [comment]
Hey there. I just never got to it hehe. It should be pretty easy to add I think.

**Comment by andrei-gheorghiu** [comment]
Yes, I'd say so. 

So it's 2 above, right? 
Cheers and keep up the good work!
