### ISSUE TITLE
`requiredIf` and `requiredUnless` validators have different definition of requiredness than `required`

### ISSUE THREAD

**Issue by manuscriptmastr** [vuelidate/vuelidate#996]
Hi, I noticed that `requiredIf` and `requiredUnless` treat whitespace as valid, while `required` does not treat it as valid. This is rather confusing when using both validators in the same form.

In my project, we make credit card fields optional when the order total is zero, which is a perfect use case for updating from `required` to `requiredUnless(() => this.total === 0)`. Unfortunately, because `requiredUnless` has a different definition of "required" (where `' '` is valid), it failed our test suite and required a custom solution to pre-trim the value before handing off to a validator.

Given that [`required` has already been updated with pre-trimming](https://github.com/vuelidate/vuelidate/pull/455), would it make sense to update other definitions? Could be for instance:
- Updating `helpers.req()` to pre-trim the value (low effort, probably breaks a lot of tests though)
- Updating `requiredIf()` and `requiredUnless()` to pre-trim value just like `required` (medium effort, breaks some tests, but is consistent with current API docs)
- Add another utility, such as `helpers.reqTrimmed()` or a composable util such as `trim()` (medium effort, breaks no tests, but someone esoteric)
- Document a solution to that handles trimmed behavior (for instance, can one compose a custom `trim()` function with a validator?) (low effort, breaks no tests)

Related issue: https://github.com/vuelidate/vuelidate/issues/454

**Comment by dobromir-hristov** [comment]
Hey there. I think option two sounds good. Care to make a quick PR?

**Comment by manuscriptmastr** [comment]
@dobromir-hristov Have a PR with some extra test cases!

Dumb question 😄 , how do I push up my local branch to this repo?

**Comment by dobromir-hristov** [comment]
Fork ny project, GitHub will suggest you to do a PR across forks.
